(()=>{
  const API=(window.MEDIA_INTELLIGENCE_API||'/api').replace(/\/$/,'');
  const $=s=>document.querySelector(s);
  const toast=(msg,ok=true)=>{const t=$('#toast');t.textContent=msg;t.className=`fixed bottom-5 right-5 glass rounded-xl px-4 py-3 text-xs shadow-2xl ${ok?'text-emerald-300':'text-rose-300'}`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),3200)};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function api(path,options={}){const r=await fetch(API+path,{credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data;}
  async function session(){try{const r=await api('/me');if(r.user?.role!=='admin')throw new Error('ADMIN_REQUIRED');$('#userLabel').textContent=`${r.user.email} · ADMINISTRATOR`;return r.user}catch(e){$('#workspace').classList.add('hidden');$('#gate').classList.remove('hidden');$('#userLabel').textContent='Sesi administrator tidak tersedia';throw e}}

  let opds=[],sources=[];
  function resetOpd(){ $('#opdId').value='';$('#opdName').value='';$('#opdCode').value='';$('#opdActive').checked=true;$('#opdTitle').textContent='Tambah OPD'; }
  function editOpd(x){$('#opdId').value=x.id;$('#opdName').value=x.name;$('#opdCode').value=x.code||'';$('#opdActive').checked=!!x.active;$('#opdTitle').textContent='Edit OPD';window.scrollTo({top:0,behavior:'smooth'});}
  function renderOpds(){ $('#opdCount').textContent=opds.length;$('#opdRows').innerHTML=opds.map(x=>`<tr class="border-t border-slate-800"><td class="p-2 font-mono text-cyan-300">${esc(x.code)}</td><td class="p-2 font-semibold">${esc(x.name)}</td><td class="p-2 text-center"><span class="px-2 py-1 rounded-full text-[10px] ${x.active?'bg-emerald-500/10 text-emerald-300':'bg-slate-800 text-slate-500'}">${x.active?'AKTIF':'NONAKTIF'}</span></td><td class="p-2 text-right whitespace-nowrap"><button data-edit-opd="${x.id}" class="px-2 py-1 rounded bg-slate-800 text-cyan-300 mr-1">Edit</button>${x.active?`<button data-off-opd="${x.id}" class="px-2 py-1 rounded bg-rose-500/10 text-rose-300">Nonaktifkan</button>`:''}</td></tr>`).join('')||`<tr><td colspan="4" class="p-8 text-center text-slate-500">Belum ada OPD.</td></tr>`;}
  async function loadOpds(){opds=(await api('/admin/opd')).data||[];renderOpds();}

  function resetSource(){ $('#sourceId').value='';$('#sourceName').value='';$('#sourceCategory').value='online';$('#sourceTier').value='2';$('#sourceUrl').value='';$('#sourceActive').checked=true;$('#sourceTitle').textContent='Tambah Sumber Berita'; }
  function editSource(x){$('#sourceId').value=x.id;$('#sourceName').value=x.name;$('#sourceCategory').value=x.category;$('#sourceTier').value=x.tier;$('#sourceUrl').value=x.url||'';$('#sourceActive').checked=!!x.active;$('#sourceTitle').textContent='Edit Sumber Berita';window.scrollTo({top:0,behavior:'smooth'});}
  function renderSources(){ $('#sourceCount').textContent=sources.length;$('#sourceRows').innerHTML=sources.map(x=>`<tr class="border-t border-slate-800"><td class="p-2"><div class="font-semibold">${esc(x.name)}</div><div class="text-[10px] text-slate-500 max-w-[300px] truncate">${esc(x.url||'Tanpa URL')}</div></td><td class="p-2 uppercase text-[10px] tracking-wider text-slate-400">${esc(x.category)}</td><td class="p-2 text-center font-black">${esc(x.tier)}</td><td class="p-2 text-center"><span class="px-2 py-1 rounded-full text-[10px] ${x.active?'bg-emerald-500/10 text-emerald-300':'bg-slate-800 text-slate-500'}">${x.active?'AKTIF':'NONAKTIF'}</span></td><td class="p-2 text-right whitespace-nowrap"><button data-edit-source="${x.id}" class="px-2 py-1 rounded bg-slate-800 text-amber-300 mr-1">Edit</button>${x.active?`<button data-off-source="${x.id}" class="px-2 py-1 rounded bg-rose-500/10 text-rose-300">Nonaktifkan</button>`:''}</td></tr>`).join('')||`<tr><td colspan="5" class="p-8 text-center text-slate-500">Belum ada sumber berita.</td></tr>`;}
  async function loadSources(){sources=(await api('/admin/sources')).data||[];renderSources();}

  $('#opdForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#opdId').value;const body={name:$('#opdName').value.trim(),code:$('#opdCode').value.trim().toUpperCase(),active:$('#opdActive').checked};try{await api(id?`/admin/opd/${id}`:'/admin/opd',{method:id?'PATCH':'POST',body:JSON.stringify(body)});toast(id?'OPD diperbarui.':'OPD ditambahkan.');resetOpd();await loadOpds();}catch(err){toast(err.message,false)}});
  $('#sourceForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#sourceId').value;const body={name:$('#sourceName').value.trim(),category:$('#sourceCategory').value,tier:Number($('#sourceTier').value),url:$('#sourceUrl').value.trim(),active:$('#sourceActive').checked};try{await api(id?`/admin/sources/${id}`:'/admin/sources',{method:id?'PATCH':'POST',body:JSON.stringify(body)});toast(id?'Sumber diperbarui.':'Sumber ditambahkan.');resetSource();await loadSources();}catch(err){toast(err.message,false)}});
  $('#opdReset').onclick=resetOpd;$('#sourceReset').onclick=resetSource;
  document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.editOpd){const x=opds.find(v=>String(v.id)===b.dataset.editOpd);if(x)editOpd(x)}if(b.dataset.offOpd&&confirm('Nonaktifkan OPD ini dari monitoring?')){await api(`/admin/opd/${b.dataset.offOpd}`,{method:'DELETE'});toast('OPD dinonaktifkan.');await loadOpds()}if(b.dataset.editSource){const x=sources.find(v=>String(v.id)===b.dataset.editSource);if(x)editSource(x)}if(b.dataset.offSource&&confirm('Nonaktifkan sumber berita ini dari ingestion?')){await api(`/admin/sources/${b.dataset.offSource}`,{method:'DELETE'});toast('Sumber berita dinonaktifkan.');await loadSources()}}catch(err){toast(err.message,false)}});
  document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.className='tab px-4 py-2 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 font-bold text-sm');b.className='tab px-4 py-2 rounded-lg bg-cyan-500 text-slate-950 font-black text-sm';const tab=b.dataset.tab;$('#opdPanel').classList.toggle('hidden',tab!=='opd');$('#sourcesPanel').classList.toggle('hidden',tab!=='sources')});
  $('#logoutBtn').onclick=async()=>{try{await api('/auth/logout',{method:'POST'})}finally{location.href='./index.html'}};
  (async()=>{try{await session();await Promise.all([loadOpds(),loadSources()])}catch{}})();
})();
