(()=>{
'use strict';
const A=(window.MEDIA_INTELLIGENCE_API||'/api').replace(/\/$/,'');
const $=s=>document.querySelector(s);
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
async function api(p,o={}){const r=await fetch(A+p,{credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json',...(o.headers||{})},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||d.error||`HTTP ${r.status}`);return d}
const toast=(m,ok=1)=>{const t=$('#toast');if(!t)return;t.textContent=m;t.className=`fixed bottom-5 right-5 glass rounded-xl px-4 py-3 text-xs shadow-2xl ${ok?'text-emerald-300':'text-rose-300'}`;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3000)};
let rows=[],opds=[];
function reset(){if(!$('#uptdForm'))return;$('#uptdId').value='';if($('#uptdOpdGroup'))$('#uptdOpdGroup').value='';renderOpds();$('#uptdOpd').value='';$('#uptdName').value='';$('#uptdCode').value='';$('#uptdAliases').value='';$('#uptdActive').checked=true;}
function ensureGroup(){if($('#uptdOpdGroup')||!$('#uptdOpd'))return;const s=document.createElement('select');s.id='uptdOpdGroup';s.className=$('#uptdOpd').className;s.innerHTML='<option value="">Pilih jenis OPD</option><option value="DINAS">Dinas</option><option value="BADAN">Badan</option><option value="SETDA">Bagian / Setda</option><option value="LAINNYA">Lainnya</option>';$('#uptdOpd').parentElement.insertBefore(s,$('#uptdOpd'));s.addEventListener('change',()=>renderOpds())}function renderOpds(selected){if(!$('#uptdOpd'))return;ensureGroup();const g=$('#uptdOpdGroup')?.value||'',list=g?opds.filter(x=>x.active&&x.opd_group===g):[];$('#uptdOpd').innerHTML='<option value="">'+(g?'Pilih OPD induk':'Pilih jenis OPD dahulu')+'</option>'+list.map(x=>`<option value="${x.id}">${E(x.code||'-')} — ${E(x.name)}</option>`).join('');if(selected)$('#uptdOpd').value=String(selected);}
function render(){if($('#uptdCount'))$('#uptdCount').textContent=rows.length;if(!$('#uptdRows'))return;$('#uptdRows').innerHTML=rows.map(x=>`<tr class="border-t border-slate-800"><td class="p-2 font-mono text-cyan-300">${E(x.code||'-')}</td><td class="p-2 font-semibold">${E(x.name)}</td><td class="p-2 text-slate-300">${E(x.opd_name||'-')}</td><td class="p-2 text-slate-400">${E((x.aliases||[]).join(', '))}</td><td class="p-2 text-center">${x.active?'AKTIF':'NONAKTIF'}</td><td class="p-2 text-right whitespace-nowrap"><button data-eu="${x.id}" class="px-2 py-1 bg-slate-800 rounded text-cyan-300">Edit</button>${x.active?`<button data-du="${x.id}" class="ml-2 px-2 py-1 rounded bg-rose-500/10 text-rose-300">Nonaktifkan</button>`:''}</td></tr>`).join('');}
async function reload(){const [u,o]=await Promise.all([api('/admin/uptd'),api('/admin/opd')]);rows=u.data||[];opds=o.data||[];renderOpds();render();}
function bind(){const form=$('#uptdForm');if(!form||form.dataset.bound)return;form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();const id=$('#uptdId').value;const body={opdId:Number($('#uptdOpd').value),name:$('#uptdName').value.trim(),code:$('#uptdCode').value.trim().toUpperCase(),aliases:$('#uptdAliases').value.split(/[,;\n]+/).map(v=>v.trim()).filter(Boolean),active:$('#uptdActive').checked};try{await api(id?`/admin/uptd/${id}`:'/admin/uptd',{method:id?'PATCH':'POST',body:JSON.stringify(body)});toast('UPTD disimpan.');await reload();reset();window.adminActivateTab?.('units')}catch(err){toast(err.message,0)}});$('#uptdReset')?.addEventListener('click',reset);document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.eu){const x=rows.find(v=>String(v.id)===b.dataset.eu);if(!x)return;$('#uptdId').value=x.id;if($('#uptdOpdGroup'))$('#uptdOpdGroup').value=opds.find(o=>String(o.id)===String(x.opd_id))?.opd_group||'LAINNYA';renderOpds(x.opd_id);$('#uptdName').value=x.name;$('#uptdCode').value=x.code||'';$('#uptdAliases').value=(x.aliases||[]).join(', ');$('#uptdActive').checked=!!x.active;window.adminActivateTab?.('units');return}if(b.dataset.du){const x=rows.find(v=>String(v.id)===b.dataset.du);if(!x||!confirm(`Nonaktifkan UPTD "${x.name}"? Data historis tetap dipertahankan.`))return;try{b.disabled=true;await api(`/admin/uptd/${x.id}`,{method:'PATCH',body:JSON.stringify({active:false})});toast('UPTD dinonaktifkan.');await reload();reset();window.adminActivateTab?.('units')}catch(err){toast(err.message,0)}finally{b.disabled=false}}});}
async function init(){bind();try{await reload()}catch(err){console.warn('UPTD admin init failed',err)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();