(()=>{
const API=(window.MEDIA_INTELLIGENCE_API||'/api').replace(/\/$/,'');
const $=s=>document.querySelector(s);
const hideSelectors=['header','nav','main','#toast'];
const logo=()=>window.BATAM_LOGO_DATA_URI||'';
function applyBranding(){
 const mark=document.getElementById('headerBrandMark');
 if(mark&&logo()) mark.innerHTML=`<img src="${logo()}" alt="Logo Kota Batam" style="width:44px;height:52px;object-fit:contain;display:block;filter:drop-shadow(0 3px 8px rgba(0,0,0,.35))">`;
}
function loginStyles(){if(document.getElementById('authGateStyles'))return;const s=document.createElement('style');s.id='authGateStyles';s.textContent=`
#authGate{min-height:100vh;background:#020617;color:#f8fafc;font-family:Inter,ui-sans-serif,system-ui,sans-serif}
.mi-login-shell{min-height:100vh;display:grid;grid-template-columns:minmax(0,1.06fr) minmax(430px,.94fr);background:#020617}
.mi-login-hero{position:relative;min-height:100vh;display:flex;align-items:center;justify-content:center;overflow:hidden;background-image:linear-gradient(180deg,rgba(2,6,23,.20),rgba(2,6,23,.90)),linear-gradient(90deg,rgba(2,6,23,.05),rgba(2,6,23,.38)),url('https://commons.wikimedia.org/wiki/Special:Redirect/file/Jembatan%20Barelang.jpg?width=1800');background-size:cover;background-position:center}
.mi-login-hero:after{content:'';position:absolute;inset:0;background:radial-gradient(circle at 50% 35%,rgba(6,182,212,.08),transparent 32%);pointer-events:none}
.mi-hero-content{position:relative;z-index:1;width:min(720px,82%);text-align:center;text-shadow:0 3px 24px rgba(0,0,0,.7)}
.mi-hero-logo{width:170px;height:215px;object-fit:contain;filter:drop-shadow(0 16px 30px rgba(0,0,0,.55));margin:0 auto 24px;display:block}
.mi-hero-title{font-size:clamp(32px,4vw,58px);line-height:1.05;font-weight:950;letter-spacing:-.025em;margin:0;color:#fff}
.mi-hero-gov{margin:14px 0 0;font-size:clamp(13px,1.2vw,19px);letter-spacing:.32em;color:#dbeafe;text-transform:uppercase}
.mi-cyan-line{width:96px;height:3px;background:#22d3ee;border-radius:999px;margin:24px auto}
.mi-hero-tag{font-size:clamp(11px,1vw,15px);letter-spacing:.24em;color:#cbd5e1;text-transform:uppercase}
.mi-cityline{margin-top:19vh;font-size:11px;letter-spacing:.32em;color:#cbd5e1;text-transform:uppercase}
.mi-photo-credit{position:absolute;left:18px;bottom:12px;z-index:2;font-size:9px;color:rgba(226,232,240,.55)}
.mi-login-side{min-height:100vh;display:grid;place-items:center;padding:44px;background:radial-gradient(circle at 40% 30%,rgba(14,165,233,.12),transparent 28%),linear-gradient(145deg,#061526,#020617 70%)}
.mi-login-card{width:min(570px,100%);border:1px solid rgba(56,189,248,.32);border-radius:28px;background:linear-gradient(180deg,rgba(8,31,53,.88),rgba(4,18,33,.94));box-shadow:0 30px 90px rgba(0,0,0,.5);padding:38px 40px;backdrop-filter:blur(18px)}
.mi-card-brand{text-align:center}.mi-card-logo{width:116px;height:146px;object-fit:contain;display:block;margin:0 auto 14px;filter:drop-shadow(0 12px 22px rgba(0,0,0,.45))}
.mi-card-title{margin:0;font-size:clamp(25px,2.3vw,36px);line-height:1.08;font-weight:950;letter-spacing:.015em}.mi-card-gov{margin:9px 0 0;font-size:13px;letter-spacing:.28em;color:#cbd5e1}
.mi-auth-label{text-align:center;color:#22d3ee;font-weight:800;font-size:12px;letter-spacing:.23em;margin:0 0 28px;text-transform:uppercase}
.mi-form{display:grid;gap:17px}.mi-label{display:block;font-size:13px;color:#e2e8f0}.mi-field{position:relative;margin-top:7px}.mi-field i{position:absolute;left:15px;top:50%;transform:translateY(-50%);color:#94a3b8;font-size:16px}.mi-input{box-sizing:border-box;width:100%;border-radius:11px;background:rgba(2,6,23,.78);border:1px solid #3b526f;padding:13px 44px;color:#fff;outline:none;font-size:15px;transition:.2s}.mi-input:focus{border-color:#22d3ee;box-shadow:0 0 0 3px rgba(34,211,238,.10)}
.mi-eye{position:absolute;right:13px;top:50%;transform:translateY(-50%);border:0;background:transparent;color:#94a3b8;cursor:pointer;padding:6px}.mi-row{display:flex;justify-content:space-between;align-items:center;gap:15px;font-size:12px;color:#cbd5e1}.mi-remember{display:flex;align-items:center;gap:9px}.mi-remember input{width:17px;height:17px;accent-color:#06b6d4}.mi-forgot{color:#22d3ee;text-decoration:none;cursor:default}.mi-login-btn{border:0;border-radius:11px;background:linear-gradient(90deg,#0ea5e9,#0284c7);color:#fff;font-weight:900;font-size:18px;padding:14px;cursor:pointer;box-shadow:0 12px 30px rgba(2,132,199,.22)}.mi-login-btn:disabled{opacity:.65;cursor:wait}.mi-note{margin:22px 0 0;padding-top:19px;border-top:1px solid rgba(148,163,184,.25);text-align:center;font-size:11px;color:#64748b}.mi-error{display:none;margin:0;font-size:12px;color:#fda4af;background:rgba(244,63,94,.08);border:1px solid rgba(244,63,94,.2);border-radius:10px;padding:11px}
@media(max-width:900px){.mi-login-shell{grid-template-columns:1fr}.mi-login-hero{min-height:38vh}.mi-hero-content{width:88%;padding:32px 0}.mi-hero-logo{width:92px;height:116px;margin-bottom:10px}.mi-hero-title{font-size:29px}.mi-hero-gov{font-size:11px;letter-spacing:.22em}.mi-cyan-line{margin:14px auto;width:66px}.mi-hero-tag{font-size:9px;letter-spacing:.14em}.mi-cityline{display:none}.mi-photo-credit{font-size:7px}.mi-login-side{min-height:auto;padding:22px 16px 34px}.mi-login-card{padding:26px 20px;border-radius:22px}.mi-card-logo{width:78px;height:96px}.mi-card-title{font-size:25px}.mi-card-gov{font-size:10px;letter-spacing:.20em}.mi-auth-label{font-size:10px;margin-bottom:22px}.mi-row{font-size:11px}}
@media(max-width:520px){.mi-login-hero{min-height:31vh}.mi-hero-title{font-size:24px}.mi-hero-tag{display:none}.mi-cyan-line{margin:10px auto}.mi-login-side{padding-top:14px}.mi-login-card{border-radius:20px}.mi-card-logo{width:70px;height:84px}}
`;document.head.appendChild(s)}
function hideApp(){
 document.body.dataset.auth='required';hideSelectors.forEach(s=>document.querySelectorAll(s).forEach(e=>e.style.display='none'));let box=document.getElementById('authGate');if(box)return box;loginStyles();box=document.createElement('div');box.id='authGate';
 const l=logo();const emblem=l?`<img src="${l}" alt="Logo Kota Batam" class="mi-hero-logo">`:'';const emblemSmall=l?`<img src="${l}" alt="Logo Kota Batam" class="mi-card-logo">`:'';
 box.innerHTML=`<div class="mi-login-shell"><section class="mi-login-hero"><div class="mi-hero-content">${emblem}<h1 class="mi-hero-title">MEDIA INTELLIGENCE<br>COMMAND CENTER</h1><p class="mi-hero-gov">PEMERINTAH KOTA BATAM</p><div class="mi-cyan-line"></div><div class="mi-hero-tag">SCAN · DETECT · UNDERSTAND · HIGHLIGHT · ACT</div><div class="mi-cityline">BATAM MAJU, MASYARAKAT SEJAHTERA</div></div><div class="mi-photo-credit">Foto Barelang: Annayu Maharani / Wikimedia Commons · CC BY-SA 4.0</div></section><section class="mi-login-side"><div class="mi-login-card"><div class="mi-card-brand">${emblemSmall}<h2 class="mi-card-title">MEDIA INTELLIGENCE<br>COMMAND CENTER</h2><p class="mi-card-gov">PEMERINTAH KOTA BATAM</p><div class="mi-cyan-line"></div></div><div class="mi-auth-label">Authentication Required</div><form id="loginForm" class="mi-form"><label class="mi-label">Email<div class="mi-field"><i class="fa-regular fa-user"></i><input id="loginEmail" class="mi-input" type="email" autocomplete="username" required placeholder="nama@pemko.go.id"></div></label><label class="mi-label">Password<div class="mi-field"><i class="fa-solid fa-lock"></i><input id="loginPassword" class="mi-input" type="password" autocomplete="current-password" required minlength="8" placeholder="••••••••"><button id="togglePassword" type="button" class="mi-eye" aria-label="Tampilkan password"><i class="fa-regular fa-eye-slash"></i></button></div></label><div class="mi-row"><label class="mi-remember"><input id="rememberLogin" type="checkbox"> Ingat saya</label><span class="mi-forgot">Lupa password?</span></div><button type="submit" class="mi-login-btn"><i class="fa-solid fa-right-to-bracket" style="margin-right:8px"></i>Masuk</button><p id="loginError" class="mi-error"></p></form><p class="mi-note">Gunakan akun yang terdaftar pada database Media Intelligence.</p></div></section></div>`;
 document.body.appendChild(box);
 const remembered=localStorage.getItem('mi.rememberedEmail');if(remembered){$('#loginEmail').value=remembered;$('#rememberLogin').checked=true}
 $('#togglePassword').addEventListener('click',()=>{const p=$('#loginPassword'),show=p.type==='password';p.type=show?'text':'password';$('#togglePassword').innerHTML=`<i class="fa-regular fa-eye${show?'':'-slash'}"></i>`});
 $('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const err=$('#loginError');err.style.display='none';const btn=e.currentTarget.querySelector('button[type="submit"]');btn.disabled=true;const old=btn.innerHTML;btn.innerHTML='<i class="fa-solid fa-spinner fa-spin" style="margin-right:8px"></i>Masuk...';try{const email=$('#loginEmail').value.trim();const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({email,password:$('#loginPassword').value})});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);if($('#rememberLogin').checked)localStorage.setItem('mi.rememberedEmail',email);else localStorage.removeItem('mi.rememberedEmail');history.replaceState(null,'',location.pathname);location.reload();}catch(e){err.textContent=e.message==='INVALID_CREDENTIALS'?'Email atau password salah.':`Login gagal: ${e.message}`;err.style.display='block';}finally{btn.disabled=false;btn.innerHTML=old}});return box;
}
async function doLogout(button){if(button){button.disabled=true;button.innerHTML='<i class="fa-solid fa-spinner fa-spin mr-1"></i> Keluar...';}try{await fetch(API+'/auth/logout',{method:'POST',credentials:'include',cache:'no-store',headers:{'Content-Type':'application/json'}})}catch(e){console.warn('Logout request failed; continuing to login gate.',e)}finally{window.location.replace('./index.html?auth=login')}}
function ensureLogoutButton(){const report=document.getElementById('reportBtn');if(!report)return null;document.querySelectorAll('#logoutNavBtn').forEach((el,i)=>{if(i>0)el.remove()});let b=document.getElementById('logoutNavBtn');if(!b){b=document.createElement('button');b.id='logoutNavBtn';b.dataset.action='logout';b.type='button';b.className='px-3 py-2 rounded-lg bg-rose-500/10 border border-rose-500/30 text-rose-300 text-xs font-black';b.innerHTML='<i class="fa-solid fa-right-from-bracket mr-1"></i> Keluar';b.addEventListener('click',()=>doLogout(b));}return b;}
function placeHeaderActions(canAdmin){const report=document.getElementById('reportBtn');const host=report?.parentElement;if(!report||!host)return;const logout=ensureLogoutButton();if(canAdmin){let admin=document.getElementById('adminNavBtn');if(!admin){admin=document.createElement('a');admin.id='adminNavBtn';admin.href='./admin.html';admin.className='px-3 py-2 rounded-lg bg-amber-400 text-slate-950 text-xs font-black';admin.innerHTML='<i class="fa-solid fa-screwdriver-wrench mr-1"></i> Administrasi';}report.insertAdjacentElement('afterend',admin);admin.insertAdjacentElement('afterend',logout);}else{document.getElementById('adminNavBtn')?.remove();report.insertAdjacentElement('afterend',logout);}host.querySelectorAll('button,a').forEach(el=>{if(el===logout||el.id==='adminNavBtn')return;const text=(el.textContent||'').trim().toLowerCase(),action=(el.dataset?.action||'').toLowerCase(),id=(el.id||'').toLowerCase();if(text==='keluar'||action==='logout'||id.includes('logout'))el.remove();});}
async function init(){applyBranding();hideApp();const forceLogin=new URLSearchParams(location.search).get('auth')==='login';if(forceLogin)return;try{const base=await fetch(API+'/me',{credentials:'include',cache:'no-store'});if(!base.ok)throw new Error('unauthenticated');const baseData=await base.json();let user=baseData.user;try{const rbac=await fetch(API+'/rbac/me',{credentials:'include',cache:'no-store'});if(rbac.ok){const ctx=await rbac.json();user={...user,...ctx.user};}}catch{}window.MEDIA_CURRENT_USER=user;window.MEDIA_PERMISSIONS=new Set(user.permissions||[]);window.MEDIA_ROLES=new Set(user.roles||[]);document.body.dataset.auth='ok';document.getElementById('authGate')?.remove();hideSelectors.forEach(s=>document.querySelectorAll(s).forEach(e=>e.style.display=''));applyBranding();const canAdmin=(user.roles||[]).includes('super_admin')||(user.permissions||[]).some(p=>['platform.admin','users.manage','opd.manage','sources.manage','keywords.manage'].includes(p));placeHeaderActions(canAdmin);window.dispatchEvent(new CustomEvent('media:authenticated',{detail:user}));}catch(e){document.body.dataset.auth='required';}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();