(()=>{'use strict';
const API=(window.MEDIA_INTELLIGENCE_API||'/api').replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const api=async p=>{const r=await fetch(API+p,{credentials:'include',cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||j.message||('HTTP '+r.status));return j};
const n=v=>Number(v||0), risk=x=>String(x||'low').toLowerCase(), roles=()=>new Set(window.MEDIA_CURRENT_USER?.roles||[]);
const roleLabel=()=>roles().has('super_admin')?'Super Admin':roles().has('humas')?'Humas':roles().has('opd')?'OPD':roles().has('district')?'Kecamatan':'Pengguna';
const badge=l=>{const x=risk(l),m={critical:'bg-rose-500/15 text-rose-300 border-rose-500/30',high:'bg-orange-500/15 text-orange-300 border-orange-500/30',medium:'bg-amber-500/15 text-amber-300 border-amber-500/30',low:'bg-emerald-500/10 text-emerald-300 border-emerald-500/20'};return '<span class="px-2 py-1 rounded-lg border text-[10px] font-black uppercase '+(m[x]||m.low)+'">'+esc(x)+'</span>'};
const kpi=(label,value,sub,icon,accent='text-cyan-300')=>'<div class="glass rounded-xl p-4"><div class="flex justify-between gap-3"><div><div class="text-[10px] font-black tracking-wider text-slate-500">'+label+'</div><div class="text-2xl font-black mt-1 '+accent+'">'+esc(value)+'</div></div><i class="fa-solid fa-'+icon+' text-slate-500"></i></div><div class="text-[10px] text-slate-500 mt-2">'+sub+'</div></div>';
function qs(){const q=new URLSearchParams(),opd=document.getElementById('opdSelect')?.value,dist=document.getElementById('districtSelect')?.value;if(opd&&opd!=='all')q.set('opdId',opd);if(dist&&dist!=='all')q.set('districtId',dist);return q}
function derive(rows,alerts){const sorted=[...rows].sort((a,b)=>n(b.risk_score)-n(a.risk_score)||n(b.impact_score)-n(a.impact_score));const neg=rows.filter(x=>String(x.sentiment||'').toLowerCase()==='negative');const high=rows.filter(x=>['high','critical'].includes(risk(x.risk_level)));return{sorted,neg,high,top:sorted[0],alerts:alerts||[]}}
let activeFilter='all';function render(data){const root=document.getElementById('dashboard');if(!root)return;const {metrics,rows,alerts,ownedOwnerCount}=data,d=derive(rows,alerts),top=d.top;
 root.innerHTML='<section id="command-center-main" class="space-y-5">'+
 '<div class="glass rounded-2xl p-5 border border-cyan-500/20"><div class="flex flex-wrap items-start justify-between gap-4"><div><div class="text-[10px] text-cyan-400 font-black tracking-[.22em]">COMMAND CENTER · '+esc(roleLabel()).toUpperCase()+'</div><h2 class="text-2xl font-black mt-1">Situasi Media & Komunikasi</h2><p class="text-xs text-slate-400 mt-2">Satu tampilan untuk melihat sinyal, memahami prioritas, memantau pekerjaan komunikasi, dan membuka intelligence lanjutan.</p></div><button id="ccRefresh" class="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-xs font-bold"><i class="fa-solid fa-rotate mr-1"></i>Refresh</button></div></div>'+
 '<div class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-6 gap-3">'+
 kpi('BERITA TERPANTAU',metrics.total_articles??rows.length,'Sesuai scope aktif','newspaper')+
 '<button data-cc-filter="negative" class="text-left rounded-xl '+(activeFilter==='negative'?'ring-2 ring-cyan-400':'')+'">'+kpi('NEGATIF',d.neg.length,'Klik untuk filter','face-frown','text-rose-300')+'</button>'+
 '<button data-cc-filter="high" class="text-left rounded-xl '+(activeFilter==='high'?'ring-2 ring-cyan-400':'')+'">'+kpi('HIGH / CRITICAL',d.high.length,'Klik untuk filter','triangle-exclamation','text-orange-300')+'</button>'+
 '<button data-cc-filter="alert" class="text-left rounded-xl '+(activeFilter==='alert'?'ring-2 ring-cyan-400':'')+'">'+kpi('OPEN ALERT',alerts.length,'Klik untuk filter','bell','text-amber-300')+'</button>'+
 kpi('SUMBER MEDIA',metrics.sources??0,'Sumber pada ringkasan','tower-broadcast')+
 kpi('OWNED CHANNEL',ownedOwnerCount,'Pemilik kanal owned aktif','building')+'</div>'+
 '<div class="grid lg:grid-cols-3 gap-4"><div class="lg:col-span-2 glass rounded-2xl p-5"><div class="flex justify-between gap-3"><div><div class="text-[10px] text-amber-400 font-black tracking-wider">SITUASI UTAMA</div><h3 class="font-black text-lg mt-1">'+esc(top?.title||'Belum ada sinyal utama')+'</h3></div>'+(top?badge(top.risk_level):'')+'</div>'+(top?'<div class="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4 text-xs"><div><span class="text-slate-500">Risk</span><b class="block mt-1">'+n(top.risk_score)+'/100</b></div><div><span class="text-slate-500">Impact</span><b class="block mt-1">'+n(top.impact_score)+'/100</b></div><div><span class="text-slate-500">Sentimen</span><b class="block mt-1 capitalize">'+esc(top.sentiment||'-')+'</b></div><div><span class="text-slate-500">Sumber</span><b class="block mt-1">'+esc(top.source_name||'-')+'</b></div></div><p class="text-xs text-slate-400 leading-5 mt-4">'+esc(top.summary||'Ringkasan belum tersedia.')+'</p>':'<p class="text-xs text-slate-500 mt-4">Belum ada evidence pada scope ini.</p>')+'</div>'+
 '<div class="glass rounded-2xl p-5"><div class="text-[10px] text-rose-400 font-black tracking-wider">PERLU PERHATIAN</div><div class="space-y-3 mt-3">'+(d.high.slice(0,4).map(x=>'<div class="border-b border-slate-800 pb-3"><div class="flex justify-between gap-2"><p class="text-xs font-semibold">'+esc(x.title)+'</p>'+badge(x.risk_level)+'</div></div>').join('')||'<p class="text-xs text-slate-500">Tidak ada high/critical pada data yang tampil.</p>')+'</div></div></div>'+
 '<div class="grid lg:grid-cols-2 gap-4"><section class="glass rounded-2xl p-5"><div class="flex items-center justify-between gap-3"><div><div class="text-[10px] text-cyan-400 font-black tracking-wider">BRIEFING HARIAN</div><h3 class="font-black mt-1">Ringkasan cepat</h3></div><span class="text-[10px] text-slate-500">READ-ONLY BASELINE</span></div><p class="text-sm text-slate-300 leading-6 mt-3">'+(top?('Sinyal teratas saat ini adalah <b>'+esc(top.title)+'</b>. Terdapat <b>'+d.neg.length+'</b> sinyal negatif dan <b>'+d.high.length+'</b> high/critical pada kumpulan data aktif.'):'Belum ada data yang cukup untuk briefing.')+'</p><div class="mt-4 text-[11px] text-slate-500">Generator Daily Intelligence lama belum dipanggil otomatis karena proses tersebut memiliki side effect penyimpanan. Integrasi briefing final akan dipisahkan menjadi read-only.</div></section>'+
 '<section class="glass rounded-2xl p-5"><div class="text-[10px] text-violet-400 font-black tracking-wider">ASK INTELLIGENCE</div><h3 class="font-black mt-1">Tanya dari Command Center</h3><p class="text-xs text-slate-500 mt-1">Baseline saat ini memakai mesin Ask yang sudah ada; konteks Issue/Gap/Strakom akan diperluas pada tahap berikutnya.</p><div class="flex gap-2 mt-4"><input id="ccAskInput" class="min-w-0 flex-1 bg-slate-950 border border-slate-700 rounded-lg px-3 py-2 text-xs" placeholder="Contoh: Apa isu paling berisiko hari ini?"><button id="ccAskBtn" class="px-3 py-2 rounded-lg bg-violet-500 text-white text-xs font-black">Tanya</button></div><div id="ccAskAnswer" class="hidden mt-3 rounded-xl bg-slate-950/60 border border-slate-800 p-3 text-xs text-slate-300 leading-5"></div></section></div>'+
 '<div class="glass rounded-2xl p-5"><div class="text-[10px] text-emerald-400 font-black tracking-wider">ALUR KERJA KOMUNIKASI</div><div class="grid grid-cols-2 md:grid-cols-5 gap-2 mt-3">'+[['Manajemen Isu','issues','diagram-project'],['Analisa Gap','commgap','magnifying-glass-chart'],['Strategi Komunikasi','strategy','bullseye'],['AI Content Studio','contentstudio','wand-magic-sparkles'],['Pemantauan Media','mediamonitoring','satellite-dish']].map(x=>'<button data-cc-go="'+x[1]+'" class="rounded-xl bg-slate-950/60 border border-slate-800 p-3 text-left hover:border-cyan-500/40"><i class="fa-solid fa-'+x[2]+' text-cyan-400"></i><div class="text-xs font-bold mt-2">'+x[0]+'</div></button>').join('')+'</div></div></section>';
 root.querySelector('#ccRefresh')?.addEventListener('click',load);root.querySelectorAll('[data-cc-filter]').forEach(b=>b.onclick=()=>{const next=b.dataset.ccFilter;activeFilter=activeFilter===next?'all':next;const list=activeFilter==='negative'?d.neg:activeFilter==='high'?d.high:rows;const alertList=activeFilter==='alert'?alerts:[];const title=activeFilter==='negative'?'Filter aktif: Berita Negatif':activeFilter==='high'?'Filter aktif: High / Critical':activeFilter==='alert'?'Filter aktif: Open Alert':'';render({...data,rows:list,alerts:activeFilter==='alert'?alertList:alerts});if(title)window.toast?.(title)});root.querySelectorAll('[data-cc-go]').forEach(b=>b.onclick=()=>window.showTab?.(b.dataset.ccGo));
 const ask=root.querySelector('#ccAskBtn');if(ask)ask.onclick=async()=>{const input=root.querySelector('#ccAskInput'),box=root.querySelector('#ccAskAnswer'),question=String(input?.value||'').trim();if(!question)return;ask.disabled=true;box.classList.remove('hidden');box.textContent='Menganalisis...';try{const q=qs(),body={question};if(q.get('opdId'))body.opdId=q.get('opdId');const r=await fetch(API+'/ask',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||('HTTP '+r.status));box.textContent=j.answer||j.data?.answer||'Jawaban belum tersedia.'}catch(e){box.textContent='Ask Intelligence gagal: '+e.message}finally{ask.disabled=false}};
}
async function load(){if(window.__ccLoading)return;window.__ccLoading=true;try{const q=qs(),suffix=q.toString()?'?'+q.toString():'';const articleQ=new URLSearchParams(q);articleQ.set('limit','50');const [dash,arts,als,owned]=await Promise.all([api('/dashboard'+suffix),api('/articles?'+articleQ.toString()),api('/alerts'+suffix),api('/admin/owned-social-accounts').catch(()=>({data:[]}))]);const ownedOwnerCount=new Set((owned.data||[]).filter(x=>x.active).map(x=>x.ownership_level==='opd'&&x.opd_id!=null?'opd:'+x.opd_id:x.ownership_level==='district'&&x.district_id!=null?'district:'+x.district_id:'pemko')).size;render({metrics:dash.metrics||{},rows:arts.data||[],alerts:als.data||[],ownedOwnerCount});}catch(e){const root=document.getElementById('dashboard');if(root)root.innerHTML='<div class="glass rounded-2xl p-5 text-sm text-rose-300">Command Center gagal dimuat: '+esc(e.message)+'</div>'}finally{window.__ccLoading=false}}
window.renderCommandCenter=load;
window.addEventListener('media:authenticated',()=>{if((window.state?.tab||'dashboard')==='dashboard')load()});
window.addEventListener('media-intelligence-tab',e=>{if(e.detail==='dashboard')load()});
document.getElementById('opdSelect')?.addEventListener('change',()=>setTimeout(load,120));
document.getElementById('districtSelect')?.addEventListener('change',()=>setTimeout(load,120));
setTimeout(()=>{if(document.body.dataset.auth==='ok')load()},1600);
})();