(()=>{
 const districtSelect=document.getElementById('districtSelect'),opdSelect=document.getElementById('opdSelect');
 if(!districtSelect||!opdSelect||typeof api!=='function'||typeof state==='undefined')return;
 state.district=state.district||'all';state.districtList=state.districtList||[];
 async function options(){const [o,d]=await Promise.all([api('/opd'),api('/districts')]);state.opdList=o.data||[];state.districtList=d.data||[];opdSelect.innerHTML='<option value="all">Semua OPD / Pemko Batam</option>'+state.opdList.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');districtSelect.innerHTML='<option value="all">Semua Kecamatan / Kota Batam</option>'+state.districtList.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('');opdSelect.value=state.opd;districtSelect.value=state.district}
 async function refresh(){
  const q=new URLSearchParams();if(state.opd!=='all')q.set('opdId',String(state.opd));if(state.district!=='all')q.set('districtId',String(state.district));
  try{const r=await api('/command-center/scope'+(q.toString()?`?${q}`:''));state.metrics=r.metrics||{};state.articles=r.articles||[];state.highlights=r.highlights||[];state.alerts=r.alerts||[];renderHighlights();renderSoWhat();renderSources();renderAsk();if(state.tab==='dashboard'&&typeof window.renderPhase2gDashboard==='function')await window.renderPhase2gDashboard();else if(state.tab==='printarchive')window.renderPrintArchive?.();const on=state.opd==='all'?'Seluruh OPD':state.opdList.find(x=>String(x.id)===String(state.opd))?.name||'OPD terpilih',dn=state.district==='all'?'Seluruh Kecamatan':state.districtList.find(x=>String(x.id)===String(state.district))?.name||'Kecamatan terpilih';const t=document.getElementById('alertText');if(t)t.textContent=`Scope: ${on} · ${dn} · ${state.articles.length} artikel · ${state.highlights.length} highlight · ${state.alerts.length} open alert.`}catch(err){console.warn('Scope refresh failed',err);window.toast?.('Filter gagal dimuat: '+err.message)}
 }
 opdSelect.onchange=async e=>{state.opd=e.target.value;await refresh()};districtSelect.onchange=async e=>{state.district=e.target.value;await refresh()};
 options().then(refresh).catch(e=>console.warn('Scope init failed',e));
})();