(() => {
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const stop=new Set(['yang','dan','dengan','untuk','dari','pada','dalam','akan','ini','itu','oleh','sebagai','karena','lebih','telah','dapat','agar','atau','juga','para','berita','batam','pemko','kota']);
  const state={rows:[],loading:false};
  const toks=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(x=>x.length>=5&&!stop.has(x));
  function cluster(rows){
    const m=new Map();
    rows.forEach(a=>{const words=[...new Set(toks(`${a.title} ${a.summary||''}`))];words.forEach(w=>{if(!m.has(w))m.set(w,{word:w,articles:[],sources:new Set(),opds:new Set(),neg:0,risk:0,impact:0});const g=m.get(w);g.articles.push(a);if(a.source_name)g.sources.add(a.source_name);if(a.opd_name)g.opds.add(a.opd_name);if(a.sentiment==='negative')g.neg++;g.risk+=+a.risk_score||0;g.impact+=+a.impact_score||0;});});
    return [...m.values()].filter(g=>g.articles.length>=2).map(g=>{const n=g.articles.length;const times=g.articles.map(a=>new Date(a.published_at||0).getTime()).filter(Number.isFinite);const hours=times.length>1?Math.max(1,(Math.max(...times)-Math.min(...times))/3600000):24;const velocity=Math.min(100,Math.round(n*16+g.neg*10+g.sources.size*7+(hours<12?15:0)));const risk=Math.min(100,Math.round(g.risk/n));const spread=Math.min(100,g.sources.size*22);const escalation=Math.min(100,Math.round(velocity*.35+risk*.4+spread*.25));let level=escalation>=80?'CRITICAL':escalation>=60?'ESCALATING':escalation>=40?'WATCH':'LOW';return {...g,count:n,risk,spread,velocity,escalation,level,latest:g.articles.sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0))[0]};}).sort((a,b)=>b.escalation-a.escalation).slice(0,10);
  }
  const action=x=>x.level==='CRITICAL'?'Aktifkan koordinasi lintas-OPD, siapkan holding statement, dan pantau eskalasi secara real-time.':x.level==='ESCALATING'?'Validasi fakta, siapkan key message, dan lakukan monitoring intensif terhadap sumber utama.':'Pantau perkembangan dan siapkan respons faktual bila volume atau sentimen meningkat.';
  function render(){const host=document.getElementById('dashboard');if(!host)return;let p=document.getElementById('narrativeClusterPanel');if(!p){p=document.createElement('section');p.id='narrativeClusterPanel';p.className='glass rounded-2xl p-5';host.appendChild(p);}if(state.loading){p.innerHTML='<div class="text-xs text-slate-400">Membangun cluster narasi dan menghitung propagation risk…</div>';return;}const cs=cluster(state.rows),x=cs[0];p.innerHTML=`<div class="flex flex-wrap justify-between gap-3"><div><div class="text-[10px] tracking-[.25em] font-black text-fuchsia-300">NARRATIVE CLUSTER INTELLIGENCE</div><h2 class="text-xl font-black mt-1">${x?`Early warning: “${esc(x.word)}”`:'Belum ada cluster yang cukup kuat'}</h2><p class="text-xs text-slate-400 mt-1">Cluster berbasis kemunculan istilah lintas artikel; propagation dan escalation dipakai sebagai indikator, bukan bukti kausalitas.</p></div><button id="clusterRefresh" class="px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-xs font-bold">↻ ANALYZE</button></div>${x?`<div class="grid md:grid-cols-5 gap-3 mt-5"><div class="rounded-xl bg-slate-950/70 p-3"><div class="text-[10px] text-slate-500">ESCALATION</div><b class="text-2xl">${x.escalation}</b>/100</div><div class="rounded-xl bg-slate-950/70 p-3"><div class="text-[10px] text-slate-500">VELOCITY</div><b class="text-2xl">${x.velocity}</b>/100</div><div class="rounded-xl bg-slate-950/70 p-3"><div class="text-[10px] text-slate-500">MEDIA SPREAD</div><b class="text-2xl">${x.sources.size}</b></div><div class="rounded-xl bg-slate-950/70 p-3"><div class="text-[10px] text-slate-500">OPD EXPOSURE</div><b class="text-2xl">${x.opds.size}</b></div><div class="rounded-xl bg-slate-950/70 p-3"><div class="text-[10px] text-slate-500">STATUS</div><b class="text-lg">${x.level}</b></div></div><div class="mt-4 p-4 rounded-xl border border-fuchsia-400/20 bg-fuchsia-400/5"><div class="text-[10px] text-fuchsia-300 font-black tracking-widest">RECOMMENDED RESPONSE</div><div class="text-sm font-semibold mt-1">${action(x)}</div><div class="text-[11px] text-slate-400 mt-2">Latest signal: ${esc(x.latest?.title||'—')}</div></div>`:''}<div class="overflow-x-auto mt-5"><table class="w-full text-xs"><thead><tr class="text-left text-slate-500"><th class="pb-2">CLUSTER</th><th>ARTIKEL</th><th>MEDIA</th><th>RISK</th><th>ESCALATION</th><th>STATUS</th></tr></thead><tbody>${cs.map(c=>`<tr class="border-t border-slate-800"><td class="py-3 font-bold text-fuchsia-200">${esc(c.word)}</td><td>${c.count}</td><td>${c.sources.size}</td><td>${c.risk}</td><td class="font-black">${c.escalation}</td><td>${c.level}</td></tr>`).join('')||'<tr><td colspan="6" class="py-5 text-slate-500">Data belum mencukupi.</td></tr>'}</tbody></table></div>`;document.getElementById('clusterRefresh')?.addEventListener('click',load);}
  async function load(){state.loading=true;render();try{const o=document.getElementById('opdSelect')?.value;const p=new URLSearchParams({limit:'100'});if(o&&o!=='all')p.set('opdId',o);const r=await fetch('/api/articles?'+p,{credentials:'include'});const j=await r.json();state.rows=j.data||[];}catch{state.rows=[];}finally{state.loading=false;render();}}
  addEventListener('DOMContentLoaded',()=>{load();document.getElementById('opdSelect')?.addEventListener('change',load);setInterval(load,60000);});
})();