-- Media Intelligence v2 schema (PostgreSQL)
CREATE TABLE IF NOT EXISTS opd (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, code TEXT UNIQUE, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS media_sources (id BIGSERIAL PRIMARY KEY, name TEXT NOT NULL UNIQUE, category TEXT NOT NULL CHECK(category IN ('online','print','social')), tier SMALLINT NOT NULL DEFAULT 2, url TEXT, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS keywords (id BIGSERIAL PRIMARY KEY, opd_id BIGINT REFERENCES opd(id) ON DELETE CASCADE, keyword TEXT NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE(opd_id, keyword));
CREATE TABLE IF NOT EXISTS articles (id BIGSERIAL PRIMARY KEY, source_id BIGINT REFERENCES media_sources(id) ON DELETE SET NULL, opd_id BIGINT REFERENCES opd(id) ON DELETE SET NULL, title TEXT NOT NULL, url TEXT, published_at TIMESTAMPTZ, author TEXT, content TEXT, summary TEXT, sentiment TEXT CHECK(sentiment IN ('positive','neutral','negative')), importance_score NUMERIC(5,2) NOT NULL DEFAULT 0, impact_score NUMERIC(5,2) NOT NULL DEFAULT 0, velocity_score NUMERIC(5,2) NOT NULL DEFAULT 0, is_highlight BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(url));
CREATE INDEX IF NOT EXISTS idx_articles_published ON articles(published_at DESC); CREATE INDEX IF NOT EXISTS idx_articles_opd ON articles(opd_id); CREATE INDEX IF NOT EXISTS idx_articles_sentiment ON articles(sentiment); CREATE INDEX IF NOT EXISTS idx_articles_highlight ON articles(is_highlight,published_at DESC);
CREATE TABLE IF NOT EXISTS article_entities (id BIGSERIAL PRIMARY KEY, article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE, entity_type TEXT NOT NULL, entity_name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS media_scans (id BIGSERIAL PRIMARY KEY, source_id BIGINT REFERENCES media_sources(id) ON DELETE SET NULL, opd_id BIGINT REFERENCES opd(id) ON DELETE SET NULL, file_name TEXT NOT NULL, storage_key TEXT, ocr_text TEXT, status TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','processing','completed','failed')), error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), processed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'viewer', active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check; ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('admin','operator','viewer'));
CREATE TABLE IF NOT EXISTS refresh_tokens (id BIGSERIAL PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS audit_logs (id BIGSERIAL PRIMARY KEY, user_id BIGINT REFERENCES users(id) ON DELETE SET NULL, action TEXT NOT NULL, metadata JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO opd(name,code) VALUES ('Dinas Komunikasi dan Informatika','DISKOMINFO'),('Dinas Bina Marga dan Sumber Daya Air','DBMSDA'),('DPMPTSP','DPMPTSP'),('Dinas Perhubungan','DISHUB'),('Dinas Kesehatan','DINKES'),('Dinas Pendidikan','DISDIK') ON CONFLICT DO NOTHING;
