import { FastifyInstance, FastifyRequest } from 'fastify';
import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import argon2 from 'argon2';
import { z } from 'zod';
import { hasPermission, loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { adminAuthz?: AuthorizationContext } }
export async function registerAdminRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const guard=(permission:string,allowedRoles:string[]=[])=>async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const c=await loadAuthorizationContext(pool,d.sub);if(!c||!c.active)return reply.code(401).send({error:'USER_INACTIVE_OR_MISSING'});const roleAllowed=allowedRoles.some(role=>(c.roles as readonly string[]).includes(role));if(!hasPermission(c,permission)&&!hasPermission(c,'platform.admin')&&!roleAllowed)return reply.code(403).send({error:'FORBIDDEN',permission});request.adminAuthz=c;}catch(e:any){if(reply.sent)return;return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const sourceGuard=guard('sources.manage',['humas']);
 const keywordGuard=guard('keywords.manage',['humas']);
 const opdReadGuard=guard('opd.manage',['humas']);
 const audit=async(r:FastifyRequest,a:string,m:any)=>{try{await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,$2,$3::jsonb)`,[r.adminAuthz!.id,a,JSON.stringify(m??{})]);}catch(e:any){r.log.warn({err:e,action:a},'Audit log write failed');}};
 const resolveOrganizationId=async(r:FastifyRequest)=>{if(r.adminAuthz?.opdId){const row=(await pool.query(`SELECT organization_id FROM opd WHERE id=$1`,[r.adminAuthz.opdId])).rows[0];if(row?.organization_id!=null)return String(row.organization_id);}const rows=(await pool.query(`SELECT id FROM organizations WHERE active=true ORDER BY id LIMIT 2`)).rows;if(rows.length===1)return String(rows[0].id);return null;};
 const id=z.object({id:z.string().regex(/^\d+$/)});
 const opd=z.object({name:z.string().trim().min(2).max(200),code:z.string().trim().min(2).max(50),active:z.boolean().default(true)});
 const uptd=z.object({opdId:z.coerce.number().int().positive(),name:z.string().trim().min(2).max(200),code:z.string().trim().max(50).optional().default(''),aliases:z.array(z.string().trim().min(1).max(200)).max(50).optional().default([]),active:z.boolean().default(true)});
 const source=z.object({name:z.string().trim().min(2).max(200),category:z.enum(['online','print','social']),tier:z.coerce.number().int().min(1).max(3).default(2),url:z.string().trim().max(1000).optional().or(z.literal('')),active:z.boolean().default(true)});
 const branding=z.object({governmentName:z.string().trim().min(2).max(160),shortName:z.string().trim().max(80).optional().default(''),cityName:z.string().trim().max(100).optional().default(''),logoUrl:z.string().max(1500000).optional().default(''),loginBackgroundUrl:z.string().max(4000000).optional().default(''),tagline:z.string().trim().max(255).optional().default('')});
 app.get('/api/branding/active',async()=>({data:(await pool.query(`SELECT id,government_name,short_name,city_name,logo_url,login_background_url,tagline FROM government_branding WHERE is_active=true ORDER BY id DESC LIMIT 1`)).rows[0]||null}));
 app.get('/api/admin/branding',{preHandler:guard('platform.admin')},async()=>({data:(await pool.query(`SELECT id,government_name,short_name,city_name,logo_url,login_background_url,tagline,is_active,updated_at FROM government_branding WHERE is_active=true ORDER BY id DESC LIMIT 1`)).rows[0]||null}));
 app.put('/api/admin/branding',{preHandler:guard('platform.admin')},async(r,p)=>{const x=branding.safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_BRANDING',detail:x.error.issues[0]?.message});try{const c=(await pool.query(`SELECT id FROM government_branding WHERE is_active=true ORDER BY id DESC LIMIT 1`)).rows[0];let q;if(c){q=await pool.query(`UPDATE government_branding SET government_name=$1,short_name=$2,city_name=$3,logo_url=$4,login_background_url=$5,tagline=$6,updated_at=NOW(),updated_by=$7 WHERE id=$8 RETURNING *`,[x.data.governmentName,x.data.shortName||null,x.data.cityName||null,x.data.logoUrl||null,x.data.loginBackgroundUrl||null,x.data.tagline||null,r.adminAuthz!.id,c.id]);}else{q=await pool.query(`INSERT INTO government_branding(government_name,short_name,city_name,logo_url,login_background_url,tagline,is_active,updated_by) VALUES($1,$2,$3,$4,$5,$6,true,$7) RETURNING *`,[x.data.governmentName,x.data.shortName||null,x.data.cityName||null,x.data.logoUrl||null,x.data.loginBackgroundUrl||null,x.data.tagline||null,r.adminAuthz!.id]);}await audit(r,'GOVERNMENT_BRANDING_UPDATED',{brandingId:String(q.rows[0].id),governmentName:x.data.governmentName,loginBackground:Boolean(x.data.loginBackgroundUrl)});return{data:q.rows[0]};}catch(e:any){r.log.error({err:e,code:e?.code},'Government branding save failed');return p.code(500).send({error:'BRANDING_SAVE_FAILED',code:String(e?.code||''),detail:String(e?.message||'Database save failed')});}});
 app.get('/api/admin/opd',{preHandler:opdReadGuard},async()=>({data:(await pool.query(`SELECT id,code,name,active,organization_id,created_at FROM opd ORDER BY active DESC,name`)).rows}));
 app.post('/api/admin/opd',{preHandler:guard('opd.manage')},async(r,p)=>{const x=opd.safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_OPD'});try{const organizationId=await resolveOrganizationId(r);if(!organizationId)return p.code(409).send({error:'ORGANIZATION_SCOPE_REQUIRED',detail:'Tidak dapat menentukan organization_id untuk OPD baru.'});const q=await pool.query(`INSERT INTO opd(name,code,active,organization_id) VALUES($1,$2,$3,$4) RETURNING id,code,name,active,organization_id,created_at`,[x.data.name,x.data.code.toUpperCase(),x.data.active,organizationId]);await audit(r,'OPD_CREATED',{opdId:q.rows[0].id,organizationId});return p.code(201).send({data:q.rows[0]});}catch(e:any){if(e.code==='23505')return p.code(409).send({error:'OPD_ALREADY_EXISTS'});throw e;}});
 app.patch('/api/admin/opd/:id',{preHandler:guard('opd.manage')},async(r,p)=>{const i=id.safeParse(r.params),x=opd.partial().safeParse(r.body);if(!i.success||!x.success)return p.code(400).send({error:'INVALID_OPD'});const c=(await pool.query(`SELECT * FROM opd WHERE id=$1`,[i.data.id])).rows[0];if(!c)return p.code(404).send({error:'OPD_NOT_FOUND'});const n={name:x.data.name??c.name,code:(x.data.code??c.code).toUpperCase(),active:x.data.active??c.active};const q=await pool.query(`UPDATE opd SET name=$1,code=$2,active=$3 WHERE id=$4 RETURNING id,code,name,active,organization_id,created_at`,[n.name,n.code,n.active,i.data.id]);await audit(r,'OPD_UPDATED',{opdId:i.data.id,changes:n});return{data:q.rows[0]};});
 app.delete('/api/admin/opd/:id',{preHandler:guard('opd.manage')},async(r,p)=>{const i=id.safeParse(r.params);if(!i.success)return p.code(400).send({error:'INVALID_OPD'});try{const q=await pool.query(`UPDATE opd SET active=false WHERE id=$1 RETURNING id,code,name,active`,[i.data.id]);if(!q.rows[0])return p.code(404).send({error:'OPD_NOT_FOUND'});await audit(r,'OPD_DEACTIVATED',{opdId:i.data.id});return{data:q.rows[0]};}catch(e:any){r.log.error({err:e,code:e?.code,opdId:i.data.id},'OPD deactivate failed');return p.code(500).send({error:'OPD_DEACTIVATE_FAILED',code:String(e?.code||''),detail:String(e?.message||'Database update failed')});}});
 app.get('/api/admin/uptd',{preHandler:opdReadGuard},async()=>({data:(await pool.query(`SELECT u.id,u.organization_id,u.opd_id,u.code,u.name,u.aliases,u.active,u.created_at,u.updated_at,o.name opd_name,o.code opd_code FROM uptd u JOIN opd o ON o.id=u.opd_id ORDER BY u.active DESC,o.name,u.name`)).rows}));
 app.post('/api/admin/uptd',{preHandler:guard('opd.manage')},async(r,p)=>{const x=uptd.safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_UPTD',detail:x.error.issues[0]?.message});try{const parent=(await pool.query(`SELECT id,organization_id,active FROM opd WHERE id=$1`,[x.data.opdId])).rows[0];if(!parent||!parent.active)return p.code(404).send({error:'OPD_NOT_FOUND_OR_INACTIVE'});if(parent.organization_id==null)return p.code(409).send({error:'OPD_ORGANIZATION_REQUIRED'});const q=await pool.query(`INSERT INTO uptd(organization_id,opd_id,code,name,aliases,active) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[parent.organization_id,x.data.opdId,x.data.code?x.data.code.toUpperCase():null,x.data.name,x.data.aliases,x.data.active]);await audit(r,'UPTD_CREATED',{uptdId:q.rows[0].id,opdId:x.data.opdId,organizationId:parent.organization_id});return p.code(201).send({data:q.rows[0]});}catch(e:any){if(e.code==='23505')return p.code(409).send({error:'UPTD_ALREADY_EXISTS'});r.log.error({err:e,code:e?.code},'UPTD create failed');return p.code(500).send({error:'UPTD_CREATE_FAILED',detail:String(e?.message||'Database insert failed')});}});
 app.patch('/api/admin/uptd/:id',{preHandler:guard('opd.manage')},async(r,p)=>{const i=id.safeParse(r.params),x=uptd.partial().safeParse(r.body);if(!i.success||!x.success)return p.code(400).send({error:'INVALID_UPTD'});const c=(await pool.query(`SELECT * FROM uptd WHERE id=$1`,[i.data.id])).rows[0];if(!c)return p.code(404).send({error:'UPTD_NOT_FOUND'});const opdId=x.data.opdId??Number(c.opd_id);const parent=(await pool.query(`SELECT id,organization_id,active FROM opd WHERE id=$1`,[opdId])).rows[0];if(!parent||!parent.active)return p.code(404).send({error:'OPD_NOT_FOUND_OR_INACTIVE'});if(parent.organization_id==null)return p.code(409).send({error:'OPD_ORGANIZATION_REQUIRED'});const n={name:x.data.name??c.name,code:x.data.code===undefined?c.code:(x.data.code?x.data.code.toUpperCase():null),aliases:x.data.aliases??c.aliases,active:x.data.active??c.active};try{const q=await pool.query(`UPDATE uptd SET organization_id=$1,opd_id=$2,code=$3,name=$4,aliases=$5,active=$6,updated_at=NOW() WHERE id=$7 RETURNING *`,[parent.organization_id,opdId,n.code,n.name,n.aliases,n.active,i.data.id]);await audit(r,'UPTD_UPDATED',{uptdId:i.data.id,opdId,changes:n});return{data:q.rows[0]};}catch(e:any){if(e.code==='23505')return p.code(409).send({error:'UPTD_ALREADY_EXISTS'});r.log.error({err:e,code:e?.code,uptdId:i.data.id},'UPTD update failed');return p.code(500).send({error:'UPTD_UPDATE_FAILED',detail:String(e?.message||'Database update failed')});}});
 app.delete('/api/admin/uptd/:id',{preHandler:guard('opd.manage')},async(r,p)=>{const i=id.safeParse(r.params);if(!i.success)return p.code(400).send({error:'INVALID_UPTD'});const q=await pool.query(`UPDATE uptd SET active=false,updated_at=NOW() WHERE id=$1 RETURNING id,name,active`,[i.data.id]);if(!q.rows[0])return p.code(404).send({error:'UPTD_NOT_FOUND'});await audit(r,'UPTD_DEACTIVATED',{uptdId:i.data.id});return{data:q.rows[0]};});
 app.get('/api/admin/sources',{preHandler:sourceGuard},async()=>({data:(await pool.query(`SELECT id,name,category,tier,url,active,created_at,last_checked_at,last_success_at,last_error,last_fetched_count,last_inserted_count FROM media_sources ORDER BY active DESC,tier,name`)).rows}));
 app.post('/api/admin/sources',{preHandler:sourceGuard},async(r,p)=>{const x=source.safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_SOURCE'});try{const q=await pool.query(`INSERT INTO media_sources(name,category,tier,url,active) VALUES($1,$2,$3,$4,$5) RETURNING *`,[x.data.name,x.data.category,x.data.tier,x.data.url||null,x.data.active]);await audit(r,'SOURCE_CREATED',{sourceId:q.rows[0].id});return p.code(201).send({data:q.rows[0]});}catch(e:any){if(e.code==='23505')return p.code(409).send({error:'SOURCE_ALREADY_EXISTS'});throw e;}});
 app.patch('/api/admin/sources/:id',{preHandler:sourceGuard},async(r,p)=>{const i=id.safeParse(r.params),x=source.partial().safeParse(r.body);if(!i.success||!x.success)return p.code(400).send({error:'INVALID_SOURCE'});const c=(await pool.query(`SELECT * FROM media_sources WHERE id=$1`,[i.data.id])).rows[0];if(!c)return p.code(404).send({error:'SOURCE_NOT_FOUND'});const n={name:x.data.name??c.name,category:x.data.category??c.category,tier:x.data.tier??c.tier,url:x.data.url===''?null:(x.data.url??c.url),active:x.data.active??c.active};const q=await pool.query(`UPDATE media_sources SET name=$1,category=$2,tier=$3,url=$4,active=$5 WHERE id=$6 RETURNING *`,[n.name,n.category,n.tier,n.url,n.active,i.data.id]);await audit(r,'SOURCE_UPDATED',{sourceId:i.data.id});return{data:q.rows[0]};});
 app.delete('/api/admin/sources/:id',{preHandler:sourceGuard},async(r,p)=>{const i=id.safeParse(r.params);if(!i.success)return p.code(400).send({error:'INVALID_SOURCE'});const q=await pool.query(`UPDATE media_sources SET active=false WHERE id=$1 RETURNING id,name,active`,[i.data.id]);if(!q.rows[0])return p.code(404).send({error:'SOURCE_NOT_FOUND'});await audit(r,'SOURCE_DEACTIVATED',{sourceId:i.data.id});return{data:q.rows[0]};});
 app.get('/api/admin/keywords',{preHandler:keywordGuard},async()=>({data:(await pool.query(`SELECT k.id,k.opd_id,k.district_id,k.keyword,k.active,o.name opd_name,d.name district_name,CASE WHEN k.opd_id IS NOT NULL THEN 'opd' WHEN k.district_id IS NOT NULL THEN 'district' ELSE 'unknown' END target_type FROM keywords k LEFT JOIN opd o ON o.id=k.opd_id LEFT JOIN districts d ON d.id=k.district_id ORDER BY COALESCE(o.name,d.name),k.keyword`)).rows}));
 app.post('/api/admin/keywords',{preHandler:keywordGuard},async(r,p)=>{const x=z.object({targetType:z.enum(['opd','district']).optional(),opdId:z.coerce.number().int().positive().optional(),districtId:z.coerce.number().int().positive().optional(),keyword:z.string().trim().min(2).max(1000),active:z.boolean().default(true)}).safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_KEYWORD',detail:x.error.issues[0]?.message});const targetType=x.data.targetType??(x.data.districtId?'district':'opd');const opdId=targetType==='opd'?x.data.opdId:null;const districtId=targetType==='district'?x.data.districtId:null;if((targetType==='opd'&&!opdId)||(targetType==='district'&&!districtId))return p.code(400).send({error:'INVALID_KEYWORD_TARGET'});try{if(targetType==='district'){const exists=(await pool.query(`SELECT 1 FROM districts WHERE id=$1 AND active=true`,[districtId])).rowCount;if(!exists)return p.code(404).send({error:'DISTRICT_NOT_FOUND_OR_INACTIVE'});}else{const exists=(await pool.query(`SELECT 1 FROM opd WHERE id=$1 AND active=true`,[opdId])).rowCount;if(!exists)return p.code(404).send({error:'OPD_NOT_FOUND_OR_INACTIVE'});}const q=await pool.query(`INSERT INTO keywords(opd_id,district_id,keyword,active) VALUES($1,$2,$3,$4) RETURNING *`,[opdId??null,districtId??null,x.data.keyword,x.data.active]);await audit(r,'KEYWORD_CREATED',{keywordId:q.rows[0].id,targetType,opdId:opdId??null,districtId:districtId??null});return p.code(201).send({data:q.rows[0]});}catch(e:any){if(e.code==='23505')return p.code(409).send({error:'KEYWORD_ALREADY_EXISTS'});r.log.error({err:e,code:e?.code,targetType,opdId,districtId},'Keyword create failed');return p.code(500).send({error:'KEYWORD_CREATE_FAILED',code:String(e?.code||''),detail:String(e?.message||'Database insert failed')});}});
 app.patch('/api/admin/keywords/:id',{preHandler:keywordGuard},async(r,p)=>{const i=id.safeParse(r.params),x=z.object({keyword:z.string().trim().min(2).max(1000).optional(),active:z.boolean().optional()}).safeParse(r.body);if(!i.success||!x.success)return p.code(400).send({error:'INVALID_KEYWORD'});const c=(await pool.query(`SELECT * FROM keywords WHERE id=$1`,[i.data.id])).rows[0];if(!c)return p.code(404).send({error:'KEYWORD_NOT_FOUND'});const q=await pool.query(`UPDATE keywords SET keyword=$1,active=$2 WHERE id=$3 RETURNING *`,[x.data.keyword??c.keyword,x.data.active??c.active,i.data.id]);await audit(r,'KEYWORD_UPDATED',{keywordId:i.data.id});return{data:q.rows[0]};});
 app.delete('/api/admin/keywords/:id',{preHandler:keywordGuard},async(r,p)=>{const i=id.safeParse(r.params);if(!i.success)return p.code(400).send({error:'INVALID_KEYWORD'});const q=await pool.query(`DELETE FROM keywords WHERE id=$1 RETURNING id`,[i.data.id]);if(!q.rows[0])return p.code(404).send({error:'KEYWORD_NOT_FOUND'});await audit(r,'KEYWORD_DELETED',{keywordId:i.data.id});return{data:q.rows[0]};});
 app.get('/api/admin/users',{preHandler:guard('users.manage')},async()=>({data:(await pool.query(`SELECT id,email,role,active,opd_id,created_at FROM users ORDER BY email`)).rows}));
 app.post('/api/admin/users',{preHandler:guard('users.manage')},async(r,p)=>{const x=z.object({email:z.string().email(),password:z.string().min(8),role:z.enum(['admin','operator','viewer']),opdId:z.coerce.number().int().positive().nullable().optional(),active:z.boolean().default(true)}).safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_USER'});const h=await argon2.hash(x.data.password);const q=await pool.query(`INSERT INTO users(email,password_hash,role,active,opd_id) VALUES($1,$2,$3,$4,$5) RETURNING id,email,role,active,opd_id,created_at`,[x.data.email.toLowerCase(),h,x.data.role,x.data.active,x.data.opdId??null]);await audit(r,'USER_CREATED',{userId:q.rows[0].id});return p.code(201).send({data:q.rows[0]});});
}
