import { Pool } from 'pg';
import { analyzeArticle as analyzeCoreArticle, parseKeywordQuery } from './media-intelligence-core.js';
import { applyRisk } from './risk.js';

function normalize(value:string){return value.toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim();}
function containsPhrase(text:string,phrase:string){const t=` ${normalize(text)} `,p=normalize(phrase);return p.length>=2&&t.includes(` ${p} `);}
function meaningfulTokens(value:string){const stop=new Set(['dan','atau','yang','dengan','untuk','dalam','serta','pemerintah','daerah','masyarakat','kota','kabupaten']);return normalize(value).split(/\s+/).filter(v=>v.length>=4&&!stop.has(v));}
function dynamicOpdTerms(row:{name?:string;code?:string}){const terms=new Set<string>();const code=normalize(String(row.code||'')),name=normalize(String(row.name||''));if(code.length>=3)terms.add(code);if(name.length>=4)terms.add(name);for(const prefix of ['dinas ','badan ']){const v=name.replace(new RegExp(`^${prefix}`),'').trim();if(v.length>=5)terms.add(v);}return [...terms];}
function taxonomyTerms(row:{name?:string;description?:string}){const generic=new Set(['dan','atau','yang','dengan','untuk','dalam','serta','pemerintah','daerah','masyarakat']);const terms=new Set<string>();for(const raw of [row.name,row.description])for(const part of String(raw||'').split(/[,;&/]+/)){const term=normalize(part);if(term.length>=4&&!generic.has(term))terms.add(term);}return [...terms];}
function uptdTerms(row:{name?:string;code?:string;aliases?:unknown}){const terms=new Set<string>();for(const raw of [row.name,row.code]){const term=normalize(String(raw||''));if(term.length>=3)terms.add(term);}const aliases=Array.isArray(row.aliases)?row.aliases:[];for(const raw of aliases){const term=normalize(String(raw||''));if(term.length>=3)terms.add(term);}return [...terms];}
function cleanSummary(value:string){const text=String(value||'').trim();if(!text)return'';const cut=text.search(/\b(?:baca juga|pewarta\s*:|editor\s*:|copyright\b)/i);const cleaned=cut>=0?text.slice(0,cut):text;return cleaned.length<=700?cleaned:cleaned.slice(0,700);}

async function mapHeadlineToExistingIssue(pool:Pool,articleId:string,title:string,taxonomyId:string|null){
 const headline=normalize(title);if(!headline)return null;
 const rows=(await pool.query(`SELECT i.id,i.title,i.taxonomy_category_id,t.name taxonomy_name,t.description taxonomy_description FROM issues i LEFT JOIN taxonomy_categories t ON t.id=i.taxonomy_category_id WHERE i.status IN ('active','watch') ORDER BY CASE WHEN i.status='active' THEN 0 ELSE 1 END,i.id`)).rows;
 let best:{id:string;score:number}|null=null;
 for(const row of rows){let score=0;if(taxonomyId&&String(row.taxonomy_category_id||'')===taxonomyId)score+=45;if(containsPhrase(headline,String(row.title||'')))score+=100;if(containsPhrase(headline,String(row.taxonomy_name||'')))score+=80;for(const token of meaningfulTokens(String(row.title||'')))if(containsPhrase(headline,token))score+=35;for(const term of taxonomyTerms({name:row.taxonomy_name,description:row.taxonomy_description})){if(containsPhrase(headline,term))score+=25;else for(const token of meaningfulTokens(term))if(containsPhrase(headline,token))score+=15;}if(score>(best?.score??0))best={id:String(row.id),score};}
 if(!best||best.score<35)return null;await pool.query(`INSERT INTO issue_articles(issue_id,article_id,relevance_score) VALUES($1,$2,$3) ON CONFLICT (issue_id,article_id) DO UPDATE SET relevance_score=EXCLUDED.relevance_score`,[best.id,articleId,Math.min(100,best.score)]);return best;
}

export async function routeArticleHeadline(pool:Pool,articleId:string){
 const article=(await pool.query(`SELECT id,title,summary,content FROM articles WHERE id=$1`,[articleId])).rows[0];if(!article)return null;
 const title=String(article.title||''),summary=cleanSummary(String(article.summary||'')),content=String(article.content||'');
 const titleText=normalize(title),summaryText=normalize(summary),contentText=normalize(content),fullNormalized=normalize(`${title} ${summary} ${content}`);
 const masterRows=(await pool.query(`SELECT k.id,k.keyword,kt.category_id,kt.weight,ko.opd_id,ko.weight opd_weight,ko.routing_role,kd.district_id,kd.weight district_weight FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true JOIN classification_sectors cs ON cs.id=tc.sector_id AND cs.active=true LEFT JOIN keyword_opd ko ON ko.keyword_id=k.id AND ko.active=true LEFT JOIN keyword_district kd ON kd.keyword_id=k.id AND kd.active=true WHERE k.active=true AND k.organization_id IS NOT NULL AND k.opd_id IS NULL AND k.district_id IS NULL AND tc.organization_id=k.organization_id AND cs.organization_id=k.organization_id ORDER BY k.id`)).rows;
 const allMatches=masterRows.filter(k=>containsPhrase(fullNormalized,String(k.keyword||'')));
 const contextualMatches=allMatches.filter(k=>containsPhrase(titleText,String(k.keyword||''))||containsPhrase(summaryText,String(k.keyword||'')));
 const taxonomyScores=new Map<string,{score:number;contextual:boolean;supporting:Set<string>;keywords:Set<string>}>(),opdScores=new Map<string,number>(),districtScores=new Map<string,number>();
 const opdEvidence=new Map<string,{title:Set<string>;summary:Set<string>;directHeadline:boolean}>();
 const seenTaxonomy=new Set<string>(),seenOpd=new Set<string>(),seenDistrict=new Set<string>();
 for(const m of contextualMatches){
  const keyword=String(m.keyword||''),base=Number(m.weight||0),inTitle=containsPhrase(titleText,keyword),inSummary=containsPhrase(summaryText,keyword),position=inTitle?1.5:inSummary?1:0;
  if(m.category_id!=null&&base>0&&position>0){const id=String(m.category_id),dedupe=`${m.id}:${id}`,cur=taxonomyScores.get(id)??{score:0,contextual:false,supporting:new Set<string>(),keywords:new Set<string>()};if(!seenTaxonomy.has(dedupe)){cur.score+=base*position;seenTaxonomy.add(dedupe);}if(base>=5)cur.contextual=true;else cur.supporting.add(keyword);cur.keywords.add(keyword);taxonomyScores.set(id,cur);}
  if(m.opd_id!=null&&position>0){const id=String(m.opd_id),dedupe=`${m.id}:${id}`,ev=opdEvidence.get(id)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};if(inTitle)ev.title.add(keyword);else if(inSummary)ev.summary.add(keyword);opdEvidence.set(id,ev);if(!seenOpd.has(dedupe)){const role=String(m.routing_role||'SUPPORTING').toUpperCase(),roleFactor=role==='PRIMARY'?4:1;opdScores.set(id,(opdScores.get(id)??0)+Number(m.opd_weight||1)*position*roleFactor);seenOpd.add(dedupe);}}
  if(m.district_id!=null&&position>0){const id=String(m.district_id),dedupe=`${m.id}:${id}`;if(!seenDistrict.has(dedupe)){districtScores.set(id,(districtScores.get(id)??0)+Number(m.district_weight||2)*position);seenDistrict.add(dedupe);}}
 }
 const eligible=[...taxonomyScores.entries()].filter(([,v])=>v.contextual||v.supporting.size>=2).sort((a,b)=>b[1].score-a[1].score),taxonomyId=eligible[0]?.[0]??null,taxonomyScore=eligible[0]?.[1].score??0;
 const uptdRows=(await pool.query(`SELECT u.id,u.opd_id,u.name,u.code,u.aliases FROM uptd u JOIN opd o ON o.id=u.opd_id AND o.active=true WHERE u.active=true ORDER BY u.id`)).rows,uptdMatches:{id:string;opdId:string;name:string;score:number;evidence:string[]}[]=[];
 for(const unit of uptdRows){let score=0;const evidence:string[]=[];for(const term of uptdTerms(unit)){let points=0;if(containsPhrase(titleText,term))points=24;else if(containsPhrase(summaryText,term))points=16;if(points){score+=points;evidence.push(term);}}if(score>=16){const opdId=String(unit.opd_id);uptdMatches.push({id:String(unit.id),opdId,name:String(unit.name||''),score,evidence});opdScores.set(opdId,(opdScores.get(opdId)??0)+score);const ev=opdEvidence.get(opdId)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};if(evidence.some(term=>containsPhrase(titleText,term)))ev.directHeadline=true;opdEvidence.set(opdId,ev);}}
 uptdMatches.sort((a,b)=>b.score-a.score||Number(a.id)-Number(b.id));
 const opdRows=(await pool.query(`SELECT id,name,code FROM opd WHERE active=true ORDER BY id`)).rows;for(const opd of opdRows){const id=String(opd.id);let score=opdScores.get(id)??0;let direct=false;for(const term of dynamicOpdTerms(opd))if(containsPhrase(titleText,term)){score+=20;direct=true;}if(direct){const ev=opdEvidence.get(id)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};ev.directHeadline=true;opdEvidence.set(id,ev);}if(score>0)opdScores.set(id,score);}
 const districtRows=(await pool.query(`SELECT id,name,code FROM districts WHERE active=true ORDER BY id`)).rows;for(const district of districtRows){const id=String(district.id);let score=districtScores.get(id)??0;for(const raw of [district.name,district.code]){const term=normalize(String(raw||''));if(term.length>=3&&containsPhrase(titleText,term))score+=12;}if(score>0)districtScores.set(id,score);}
 const confidentOpdScores=[...opdScores.entries()].filter(([id])=>{const ev=opdEvidence.get(id);return !!ev&&(ev.directHeadline||ev.title.size>=1||ev.summary.size>=2);});
 const opdId=confidentOpdScores.sort((a,b)=>b[1]-a[1])[0]?.[0]??null,districtId=[...districtScores.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??null;await pool.query(`UPDATE articles SET opd_id=$2,district_id=$3 WHERE id=$1`,[articleId,opdId,districtId]);
 await pool.query(`DELETE FROM article_uptd WHERE article_id=$1`,[articleId]);for(let i=0;i<uptdMatches.length;i++){const unit=uptdMatches[i];await pool.query(`INSERT INTO article_uptd(article_id,uptd_id,relevance_score,evidence,is_primary,updated_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT (article_id,uptd_id) DO UPDATE SET relevance_score=EXCLUDED.relevance_score,evidence=EXCLUDED.evidence,is_primary=EXCLUDED.is_primary,updated_at=NOW()`,[articleId,unit.id,unit.score,unit.evidence,i===0]);}
 await pool.query(`DELETE FROM article_entities WHERE article_id=$1 AND entity_type IN ('keyword','taxonomy','uptd')`,[articleId]);const matchedNames=[...new Set(contextualMatches.map(k=>String(k.keyword)))].slice(0,40);for(const name of matchedNames)await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'keyword',$2) ON CONFLICT DO NOTHING`,[articleId,name]);for(const unit of uptdMatches.slice(0,20))await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'uptd',$2) ON CONFLICT DO NOTHING`,[articleId,unit.name]);
 let taxonomyName:string|null=null;if(taxonomyId){const t=(await pool.query(`SELECT name FROM taxonomy_categories WHERE id=$1`,[taxonomyId])).rows[0];taxonomyName=t?.name??null;if(taxonomyName)await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'taxonomy',$2) ON CONFLICT DO NOTHING`,[articleId,taxonomyName]);}
 if(String(articleId)==='542')await pool.query(`INSERT INTO audit_logs(action,metadata) VALUES('CLASSIFICATION_RUNTIME_DIAGNOSTIC',$1)`,[{build:'headline-confidence-v4-20260915',articleId:String(articleId),title,masterRowsLoaded:masterRows.length,asnRows:masterRows.filter(r=>normalize(String(r.keyword||''))==='asn').map(r=>({keywordId:String(r.id),weight:Number(r.weight||0),opdId:r.opd_id==null?null:String(r.opd_id),routingRole:r.routing_role??null,titleHit:containsPhrase(titleText,String(r.keyword||'')),summaryHit:containsPhrase(summaryText,String(r.keyword||'')),fullHit:containsPhrase(fullNormalized,String(r.keyword||''))})),matchedKeywords:matchedNames,bodyOnlyKeywords:[...new Set(allMatches.filter(k=>!contextualMatches.includes(k)).map(k=>String(k.keyword)))].slice(0,40),selectedTaxonomyId:taxonomyId,selectedOpdId:opdId}]).catch(()=>undefined);
 const issueMatch=await mapHeadlineToExistingIssue(pool,String(articleId),title,taxonomyId),primaryUptd=uptdMatches[0]??null;return{articleId:String(articleId),opdId,districtId,uptdId:primaryUptd?.id??null,uptdName:primaryUptd?.name??null,uptdMatches:uptdMatches.length,taxonomyId,taxonomyName,taxonomyScore:Number(taxonomyScore.toFixed(2)),issueId:issueMatch?.id??null,issueMatchScore:issueMatch?.score??0,keywordMatches:matchedNames.length,matchedKeywords:matchedNames};
}

export async function analyzeArticle(pool:Pool,articleId:string){
 const article=(await pool.query(`SELECT a.id,a.title,a.content,a.summary,a.published_at,ms.name source_name,ms.tier,ms.category media_kind FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE a.id=$1`,[articleId])).rows[0];if(!article)return null;
 const routing=await routeArticleHeadline(pool,articleId),opdId=routing?.opdId??null,matchedNames=routing?.matchedKeywords??[],query=parseKeywordQuery(matchedNames.join(' | '));const peerResult=await pool.query(`SELECT COUNT(*)::int count FROM articles WHERE id<>$1 AND (title ILIKE $2 OR summary ILIKE $2)`,[articleId,`%${String(article.title).slice(0,80)}%`]);const peerCount=Number(peerResult.rows[0]?.count??1)+1;
 const analysis=analyzeCoreArticle({id:article.id,title:article.title,summary:article.summary,content:article.content,sourceName:article.source_name,sourceTier:Number(article.tier??2),mediaKind:article.media_kind==='print'?'print':article.media_kind==='social'?'social':'online',opdId,publishedAt:article.published_at},query,peerCount);
 await pool.query(`UPDATE articles SET opd_id=$2,sentiment=$3,importance_score=$4,impact_score=$5,velocity_score=$6,risk_score=$7,risk_level=$8,is_highlight=$9,summary=COALESCE(NULLIF(summary,''),$10) WHERE id=$1`,[articleId,opdId,analysis.sentiment,analysis.importanceScore,analysis.impactScore,analysis.velocityScore,analysis.riskScore,analysis.riskLevel,analysis.importanceScore>=65||analysis.riskLevel==='high'||analysis.riskLevel==='critical',String(article.content??article.title).slice(0,300)]);await pool.query(`DELETE FROM article_entities WHERE article_id=$1 AND entity_type='entity'`,[articleId]);for(const entity of analysis.entities.slice(0,20))await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'entity',$2) ON CONFLICT DO NOTHING`,[articleId,entity]);const risk=await applyRisk(pool,articleId);return{articleId,opdId,districtId:routing?.districtId??null,uptdId:routing?.uptdId??null,uptdName:routing?.uptdName??null,uptdMatches:routing?.uptdMatches??0,taxonomyId:routing?.taxonomyId??null,taxonomyName:routing?.taxonomyName??null,taxonomyScore:routing?.taxonomyScore??0,issueId:routing?.issueId??null,issueMatchScore:routing?.issueMatchScore??0,sentiment:analysis.sentiment,importance:analysis.importanceScore,impact:analysis.impactScore,velocity:analysis.velocityScore,highlight:analysis.importanceScore>=65||analysis.riskLevel==='high'||analysis.riskLevel==='critical',keywordMatches:matchedNames.length,matchedKeywords:matchedNames,entities:analysis.entities,duplicateFingerprint:analysis.duplicateFingerprint,risk};
}
