import { Pool } from 'pg';
import { analyzeArticle as analyzeCoreArticle, parseKeywordQuery } from './media-intelligence-core.js';
import { applyRisk } from './risk.js';

export const CLASSIFICATION_VERSION='article-opd-v12-20260916';
function normalize(value:string){return value.toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim();}
function containsPhrase(text:string,phrase:string){const t=` ${normalize(text)} `,p=normalize(phrase);return p.length>=2&&t.includes(` ${p} `);}
function isWeakStandaloneKeyword(value:string){return new Set(['viral']).has(normalize(value));}
function meaningfulTokens(value:string){const stop=new Set(['dan','atau','yang','dengan','untuk','dalam','serta','pemerintah','daerah','masyarakat','kota','kabupaten']);return normalize(value).split(/\s+/).filter(v=>v.length>=4&&!stop.has(v));}
function dynamicOpdTerms(row:{name?:string;code?:string}){const terms=new Set<string>();const code=normalize(String(row.code||'')),name=normalize(String(row.name||''));if(code.length>=3)terms.add(code);if(name.length>=4)terms.add(name);for(const prefix of ['dinas ','badan ']){const v=name.replace(new RegExp(`^${prefix}`),'').trim();if(v.length>=5)terms.add(v);}return [...terms];}
function taxonomyTerms(row:{name?:string;description?:string}){const generic=new Set(['dan','atau','yang','dengan','untuk','dalam','serta','pemerintah','daerah','masyarakat']);const terms=new Set<string>();for(const raw of [row.name,row.description])for(const part of String(raw||'').split(/[,;&/]+/)){const term=normalize(part);if(term.length>=4&&!generic.has(term))terms.add(term);}return [...terms];}
function uptdTerms(row:{name?:string;code?:string;aliases?:unknown}){const terms=new Set<string>();for(const raw of [row.name,row.code]){const term=normalize(String(raw||''));if(term.length>=3)terms.add(term);}const aliases=Array.isArray(row.aliases)?row.aliases:[];for(const raw of aliases){const term=normalize(String(raw||''));if(term.length>=3)terms.add(term);}return [...terms];}
function cleanSummary(value:string){const text=String(value||'').trim();if(!text)return'';const cut=text.search(/\b(?:baca juga|pewarta\s*:|editor\s*:|copyright\b)/i);const cleaned=cut>=0?text.slice(0,cut):text;return cleaned.length<=700?cleaned:cleaned.slice(0,700);}

async function mapHeadlineToExistingIssue(pool:Pool,articleId:string,title:string,taxonomyId:string|null){
 const manual=(await pool.query(`SELECT ia.issue_id,ia.relevance_score FROM issue_articles ia JOIN issues i ON i.id=ia.issue_id WHERE ia.article_id=$1 AND ia.assignment_source='MANUAL' AND i.status IN ('active','watch') ORDER BY ia.relevance_score DESC,ia.created_at DESC LIMIT 1`,[articleId])).rows[0];
 await pool.query(`DELETE FROM issue_articles WHERE article_id=$1 AND assignment_source='AUTO'`,[articleId]);
 if(manual)return{id:String(manual.issue_id),score:Number(manual.relevance_score||100),source:'MANUAL'};
 const headline=normalize(title);if(!headline||!taxonomyId)return null;
 const rows=(await pool.query(`SELECT i.id,i.title,i.taxonomy_category_id,t.name taxonomy_name,t.description taxonomy_description FROM issues i JOIN taxonomy_categories t ON t.id=i.taxonomy_category_id AND t.active=true WHERE i.status IN ('active','watch') AND i.taxonomy_category_id=$1 ORDER BY CASE WHEN i.status='active' THEN 0 ELSE 1 END,i.id`,[taxonomyId])).rows;
 let best:{id:string;score:number}|null=null;
 for(const row of rows){let score=45,headlineEvidence=0;if(containsPhrase(headline,String(row.title||'')))headlineEvidence+=100;for(const token of meaningfulTokens(String(row.title||'')))if(containsPhrase(headline,token))headlineEvidence+=35;for(const term of taxonomyTerms({name:row.taxonomy_name,description:row.taxonomy_description})){if(containsPhrase(headline,term))headlineEvidence+=25;else for(const token of meaningfulTokens(term))if(containsPhrase(headline,token))headlineEvidence+=15;}if(headlineEvidence<=0)continue;score+=headlineEvidence;if(score>(best?.score??0))best={id:String(row.id),score};}
 if(!best||best.score<60)return null;await pool.query(`INSERT INTO issue_articles(issue_id,article_id,relevance_score,assignment_source) VALUES($1,$2,$3,'AUTO') ON CONFLICT (issue_id,article_id) DO UPDATE SET relevance_score=EXCLUDED.relevance_score,assignment_source=CASE WHEN issue_articles.assignment_source='MANUAL' THEN 'MANUAL' ELSE 'AUTO' END`,[best.id,articleId,Math.min(100,best.score)]);return{...best,source:'AUTO'};
}

export async function routeArticleHeadline(pool:Pool,articleId:string){
 const article=(await pool.query(`SELECT id,title,summary,content FROM articles WHERE id=$1`,[articleId])).rows[0];if(!article)return null;
 const title=String(article.title||''),summary=cleanSummary(String(article.summary||'')),content=String(article.content||'');
 const titleText=normalize(title),summaryText=normalize(summary),fullNormalized=normalize(`${title} ${summary} ${content}`);
 const masterRows=(await pool.query(`SELECT k.id,k.keyword,kt.category_id,kt.weight,ko.opd_id,ko.weight opd_weight,ko.routing_role,kd.district_id,kd.weight district_weight FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true JOIN classification_sectors cs ON cs.id=tc.sector_id AND cs.active=true LEFT JOIN keyword_opd ko ON ko.keyword_id=k.id AND ko.active=true LEFT JOIN keyword_district kd ON kd.keyword_id=k.id AND kd.active=true WHERE k.active=true AND k.organization_id IS NOT NULL AND k.opd_id IS NULL AND k.district_id IS NULL AND tc.organization_id=k.organization_id AND cs.organization_id=k.organization_id ORDER BY k.id`)).rows;
 const manualIds=new Set((await pool.query(`SELECT keyword_id FROM article_manual_keywords WHERE article_id=$1 AND active=true ORDER BY updated_at DESC,keyword_id`,[articleId])).rows.map((r:any)=>String(r.keyword_id))),hasManual=manualIds.size>0;
 const allMatches=masterRows.filter(k=>containsPhrase(fullNormalized,String(k.keyword||'')));
 const rawContextualMatches=hasManual?masterRows.filter(k=>manualIds.has(String(k.id))):allMatches.filter(k=>containsPhrase(titleText,String(k.keyword||''))||containsPhrase(summaryText,String(k.keyword||'')));
 const hasStrongContextualMatch=rawContextualMatches.some(k=>!isWeakStandaloneKeyword(String(k.keyword||'')));
 const contextualMatches=hasManual?rawContextualMatches:rawContextualMatches.filter(k=>!isWeakStandaloneKeyword(String(k.keyword||''))||hasStrongContextualMatch);
 const taxonomyScores=new Map<string,{score:number;title:Set<string>;summary:Set<string>;supporting:Set<string>;keywords:Set<string>}>(),opdScores=new Map<string,number>(),districtScores=new Map<string,number>();
 const opdEvidence=new Map<string,{title:Set<string>;summary:Set<string>;directHeadline:boolean}>();
 const opdRoles=new Map<string,Set<string>>();
 const opdTaxonomies=new Map<string,Set<string>>();
 const seenTaxonomy=new Set<string>(),seenOpd=new Set<string>(),seenDistrict=new Set<string>();
 for(const m of contextualMatches){
  const keyword=String(m.keyword||''),base=Number(m.weight||0),inTitle=containsPhrase(titleText,keyword),inSummary=containsPhrase(summaryText,keyword),position=hasManual?10:inTitle?1.5:inSummary?1:0;
  if(m.category_id!=null&&base>0&&position>0){const id=String(m.category_id),dedupe=`${m.id}:${id}`,cur=taxonomyScores.get(id)??{score:0,title:new Set<string>(),summary:new Set<string>(),supporting:new Set<string>(),keywords:new Set<string>()};if(!seenTaxonomy.has(dedupe)){cur.score+=base*position;seenTaxonomy.add(dedupe);}if(hasManual||inTitle)cur.title.add(keyword);else if(inSummary)cur.summary.add(keyword);if(base<5)cur.supporting.add(keyword);cur.keywords.add(keyword);taxonomyScores.set(id,cur);}
  if(m.opd_id!=null&&position>0){const id=String(m.opd_id),dedupe=`${m.id}:${id}`,ev=opdEvidence.get(id)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};if(hasManual||inTitle)ev.title.add(keyword);else if(inSummary)ev.summary.add(keyword);opdEvidence.set(id,ev);const role=String(m.routing_role||'SUPPORTING').toUpperCase();const roles=opdRoles.get(id)??new Set<string>();roles.add(role);opdRoles.set(id,roles);if(m.category_id!=null){const tax=opdTaxonomies.get(id)??new Set<string>();tax.add(String(m.category_id));opdTaxonomies.set(id,tax);}if(!seenOpd.has(dedupe)){const roleFactor=hasManual?(role==='PRIMARY'?10:2):(role==='PRIMARY'?4:1);opdScores.set(id,(opdScores.get(id)??0)+Number(m.opd_weight||1)*position*roleFactor);seenOpd.add(dedupe);}}
  if(m.district_id!=null&&position>0){const id=String(m.district_id),dedupe=`${m.id}:${id}`;if(!seenDistrict.has(dedupe)){districtScores.set(id,(districtScores.get(id)??0)+Number(m.district_weight||2)*position);seenDistrict.add(dedupe);}}
 }
 const eligible=[...taxonomyScores.entries()].filter(([,v])=>hasManual||v.title.size>=1||v.summary.size>=2).sort((a,b)=>b[1].score-a[1].score),taxonomyId=eligible[0]?.[0]??null,taxonomyScore=eligible[0]?.[1].score??0;
 const secondaryTaxonomyIds=new Set(eligible.slice(1).filter(([,v])=>{if(hasManual)return true;const ratio=taxonomyScore>0?v.score/taxonomyScore:0;return v.title.size>=1&&v.score>=5&&ratio>=0.45;}).map(([id])=>id));
 const uptdRows=(await pool.query(`SELECT u.id,u.opd_id,u.name,u.code,u.aliases FROM uptd u JOIN opd o ON o.id=u.opd_id AND o.active=true WHERE u.active=true ORDER BY u.id`)).rows,uptdMatches:{id:string;opdId:string;name:string;score:number;evidence:string[]}[]=[];
 for(const unit of uptdRows){let score=0;const evidence:string[]=[];for(const term of uptdTerms(unit)){let points=0;if(containsPhrase(titleText,term))points=24;else if(containsPhrase(summaryText,term))points=16;if(points){score+=points;evidence.push(term);}}if(score>=16){const opdId=String(unit.opd_id);uptdMatches.push({id:String(unit.id),opdId,name:String(unit.name||''),score,evidence});if(!hasManual)opdScores.set(opdId,(opdScores.get(opdId)??0)+score);const ev=opdEvidence.get(opdId)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};if(evidence.some(term=>containsPhrase(titleText,term)))ev.directHeadline=true;opdEvidence.set(opdId,ev);}}
 uptdMatches.sort((a,b)=>b.score-a.score||Number(a.id)-Number(b.id));
 const opdRows=(await pool.query(`SELECT id,name,code FROM opd WHERE active=true ORDER BY id`)).rows;for(const opd of opdRows){const id=String(opd.id);let score=opdScores.get(id)??0;let direct=false;for(const term of dynamicOpdTerms(opd))if(containsPhrase(titleText,term)){if(!hasManual)score+=20;direct=true;}if(direct){const ev=opdEvidence.get(id)??{title:new Set<string>(),summary:new Set<string>(),directHeadline:false};ev.directHeadline=true;opdEvidence.set(id,ev);}if(score>0)opdScores.set(id,score);}
 const districtRows=(await pool.query(`SELECT id,name,code FROM districts WHERE active=true ORDER BY id`)).rows;for(const district of districtRows){const id=String(district.id);let score=districtScores.get(id)??0;for(const raw of [district.name,district.code]){const term=normalize(String(raw||''));if(term.length>=3&&containsPhrase(titleText,term))score+=12;}if(score>0)districtScores.set(id,score);}
 const confidentOpdScores=[...opdScores.entries()].filter(([id])=>hasManual||(()=>{const ev=opdEvidence.get(id);return !!ev&&(ev.directHeadline||ev.title.size>=1||ev.summary.size>=2);})()).sort((a,b)=>b[1]-a[1]);
 const opdId=confidentOpdScores[0]?.[0]??null,districtId=[...districtScores.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0]??null;
 await pool.query(`UPDATE articles SET opd_id=$2,district_id=$3 WHERE id=$1`,[articleId,opdId,districtId]);
 await pool.query(`DELETE FROM article_opd WHERE article_id=$1 AND assignment_source='AUTO'`,[articleId]);
 if(opdId){const ev=opdEvidence.get(opdId);await pool.query(`INSERT INTO article_opd(article_id,opd_id,routing_role,relevance_score,evidence,assignment_source,updated_at) VALUES($1,$2,'PRIMARY',$3,$4,'AUTO',NOW()) ON CONFLICT(article_id,opd_id) DO UPDATE SET routing_role='PRIMARY',relevance_score=EXCLUDED.relevance_score,evidence=EXCLUDED.evidence,assignment_source=CASE WHEN article_opd.assignment_source='MANUAL' THEN 'MANUAL' ELSE 'AUTO' END,updated_at=NOW()`,[articleId,opdId,opdScores.get(opdId)??0,JSON.stringify({title:[...(ev?.title??[])],summary:[...(ev?.summary??[])],directHeadline:ev?.directHeadline??false})]);}
 const supporting=confidentOpdScores.filter(([id])=>{if(id===opdId)return false;if(opdRoles.get(id)?.has('SUPPORTING'))return true;const ev=opdEvidence.get(id),taxonomies=opdTaxonomies.get(id)??new Set<string>();return !!ev&&ev.title.size>=1&&opdRoles.get(id)?.has('PRIMARY')&&[...taxonomies].some(t=>secondaryTaxonomyIds.has(t));}).slice(0,3);for(const [id,score] of supporting){const ev=opdEvidence.get(id);await pool.query(`INSERT INTO article_opd(article_id,opd_id,routing_role,relevance_score,evidence,assignment_source,updated_at) VALUES($1,$2,'SUPPORTING',$3,$4,'AUTO',NOW()) ON CONFLICT(article_id,opd_id) DO UPDATE SET routing_role=CASE WHEN article_opd.assignment_source='MANUAL' THEN article_opd.routing_role ELSE 'SUPPORTING' END,relevance_score=EXCLUDED.relevance_score,evidence=EXCLUDED.evidence,updated_at=NOW()`,[articleId,id,score,JSON.stringify({title:[...(ev?.title??[])],summary:[...(ev?.summary??[])],directHeadline:ev?.directHeadline??false})]);}
 const routedOpdIds=new Set([opdId,...supporting.map(([id])=>id)].filter(Boolean) as string[]);
 const primaryUptd=uptdMatches.find(u=>u.opdId===opdId)??null;
 await pool.query(`DELETE FROM article_uptd WHERE article_id=$1`,[articleId]);for(const unit of uptdMatches){if(!routedOpdIds.has(unit.opdId))continue;await pool.query(`INSERT INTO article_uptd(article_id,uptd_id,relevance_score,evidence,is_primary,updated_at) VALUES($1,$2,$3,$4,$5,NOW()) ON CONFLICT (article_id,uptd_id) DO UPDATE SET relevance_score=EXCLUDED.relevance_score,evidence=EXCLUDED.evidence,is_primary=EXCLUDED.is_primary,updated_at=NOW()`,[articleId,unit.id,unit.score,unit.evidence,primaryUptd?.id===unit.id]);}
 await pool.query(`DELETE FROM article_entities WHERE article_id=$1 AND entity_type IN ('keyword','taxonomy','uptd')`,[articleId]);const matchedNames=[...new Set(contextualMatches.map(k=>String(k.keyword)))].slice(0,40);for(const name of matchedNames)await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'keyword',$2) ON CONFLICT DO NOTHING`,[articleId,name]);for(const unit of uptdMatches.filter(u=>routedOpdIds.has(u.opdId)).slice(0,20))await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'uptd',$2) ON CONFLICT DO NOTHING`,[articleId,unit.name]);
 let taxonomyName:string|null=null;if(taxonomyId){const t=(await pool.query(`SELECT name FROM taxonomy_categories WHERE id=$1`,[taxonomyId])).rows[0];taxonomyName=t?.name??null;if(taxonomyName)await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'taxonomy',$2) ON CONFLICT DO NOTHING`,[articleId,taxonomyName]);}
 if(String(articleId)==='542')await pool.query(`INSERT INTO audit_logs(action,metadata) VALUES('CLASSIFICATION_RUNTIME_DIAGNOSTIC',$1)`,[{build:CLASSIFICATION_VERSION,articleId:String(articleId),classificationSource:hasManual?'MANUAL_KEYWORD':'AUTO',manualKeywordIds:[...manualIds],title,masterRowsLoaded:masterRows.length,matchedKeywords:matchedNames,selectedTaxonomyId:taxonomyId,selectedOpdId:opdId,supportingOpdIds:supporting.map(([id])=>id)}]).catch(()=>undefined);
 const issueMatch=await mapHeadlineToExistingIssue(pool,String(articleId),title,taxonomyId);return{articleId:String(articleId),classificationSource:hasManual?'MANUAL_KEYWORD':'AUTO',opdId,supportingOpdIds:supporting.map(([id])=>id),districtId,uptdId:primaryUptd?.id??null,uptdName:primaryUptd?.name??null,uptdMatches:uptdMatches.filter(u=>routedOpdIds.has(u.opdId)).length,taxonomyId,taxonomyName,taxonomyScore:Number(taxonomyScore.toFixed(2)),issueId:issueMatch?.id??null,issueMatchScore:issueMatch?.score??0,issueAssignmentSource:issueMatch?.source??null,keywordMatches:matchedNames.length,matchedKeywords:matchedNames};
}

export async function analyzeArticle(pool:Pool,articleId:string){
 const article=(await pool.query(`SELECT a.id,a.title,a.content,a.summary,a.published_at,ms.name source_name,ms.tier,ms.category media_kind FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE a.id=$1`,[articleId])).rows[0];if(!article)return null;
 const routing=await routeArticleHeadline(pool,articleId),opdId=routing?.opdId??null,matchedNames=routing?.matchedKeywords??[],query=parseKeywordQuery(matchedNames.join(' | '));const peerResult=await pool.query(`SELECT COUNT(*)::int count FROM articles WHERE id<>$1 AND (title ILIKE $2 OR summary ILIKE $2)`,[articleId,`%${String(article.title).slice(0,80)}%`]);const peerCount=Number(peerResult.rows[0]?.count??1)+1;
 const analysis=analyzeCoreArticle({id:article.id,title:article.title,summary:article.summary,content:article.content,sourceName:article.source_name,sourceTier:Number(article.tier??2),mediaKind:article.media_kind==='print'?'print':article.media_kind==='social'?'social':'online',opdId,publishedAt:article.published_at},query,peerCount);
 await pool.query(`UPDATE articles SET opd_id=$2,sentiment=$3,importance_score=$4,impact_score=$5,velocity_score=$6,risk_score=$7,risk_level=$8,is_highlight=$9,summary=COALESCE(NULLIF(summary,''),$10) WHERE id=$1`,[articleId,opdId,analysis.sentiment,analysis.importanceScore,analysis.impactScore,analysis.velocityScore,analysis.riskScore,analysis.riskLevel,analysis.importanceScore>=65||analysis.riskLevel==='high'||analysis.riskLevel==='critical',String(article.content??article.title).slice(0,300)]);await pool.query(`DELETE FROM article_entities WHERE article_id=$1 AND entity_type='entity'`,[articleId]);for(const entity of analysis.entities.slice(0,20))await pool.query(`INSERT INTO article_entities(article_id,entity_type,entity_name) VALUES($1,'entity',$2) ON CONFLICT DO NOTHING`,[articleId,entity]);const risk=await applyRisk(pool,articleId);await pool.query(`UPDATE articles SET classified_at=NOW(),classification_version=$2 WHERE id=$1`,[articleId,CLASSIFICATION_VERSION]);return{articleId,classificationSource:routing?.classificationSource??'AUTO',classificationVersion:CLASSIFICATION_VERSION,opdId,supportingOpdIds:routing?.supportingOpdIds??[],districtId:routing?.districtId??null,uptdId:routing?.uptdId??null,uptdName:routing?.uptdName??null,uptdMatches:routing?.uptdMatches??0,taxonomyId:routing?.taxonomyId??null,taxonomyName:routing?.taxonomyName??null,taxonomyScore:routing?.taxonomyScore??0,issueId:routing?.issueId??null,issueMatchScore:routing?.issueMatchScore??0,issueAssignmentSource:routing?.issueAssignmentSource??null,sentiment:analysis.sentiment,importance:analysis.importanceScore,impact:analysis.impactScore,velocity:analysis.velocityScore,highlight:analysis.importanceScore>=65||analysis.riskLevel==='high'||analysis.riskLevel==='critical',keywordMatches:matchedNames.length,matchedKeywords:matchedNames,entities:analysis.entities,duplicateFingerprint:analysis.duplicateFingerprint,risk};
}