import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import { generateDailyIntelligence } from './daily-intelligence.js';
import { registerAdminRoutes } from './admin-routes.js';
import { registerRbacRoutes } from './rbac-routes.js';
import { registerDistrictRoutes } from './district-routes.js';
import { registerOwnedSocialRoutes } from './owned-social-routes.js';
import { registerSocialIntelligenceRoutes } from './social-intelligence-routes.js';
import { registerSocialIngestionRoutes } from './social-ingestion-routes.js';
import { registerCommandCenterScopeRoutes } from './command-center-scope-routes.js';
import { registerPrintMediaRoutes } from './print-media-routes.js';
import { registerPrintReviewRoutes } from './print-review-routes.js';
import { registerPrintIssueLinkageRoutes } from './print-issue-linkage.js';
import { registerPrintWarningSignalRoutes } from './print-warning-signal.js';
import { registerPhase2fCandidateAlertRoutes } from './phase2f-candidate-alerts.js';
import { registerPhase2fCandidateIssueRoutes } from './phase2f-candidate-issues.js';
import { registerPhase2gMediaSummaryRoutes } from './phase2g-media-summary.js';
import { registerPrintAnalysisRecoveryRoutes } from './print-analysis-recovery-routes.js';
import { registerPrintEvidenceRecoveryRoutes } from './print-evidence-recovery-routes.js';
import { registerPrintCreateStableRoutes } from './print-create-stable-routes.js';
import { loadAuthorizationContext, hasPermission, type AuthorizationContext } from './rbac.js';

type Row = { title:string; summary:string|null; source_name:string|null; published_at:string|null; sentiment:string|null; risk_level:string; risk_score:number; impact_score:number; importance_score:number; velocity_score:number; opd_name:string|null };
declare module 'fastify' { interface FastifyRequest { intelligenceAuth?: AuthorizationContext } }
function fallback(question:string, rows:Row[], alertCount:number){const q=question.toLowerCase();if(!rows.length)return{mode:'deterministic-fallback',answer:'Belum ada data media yang cukup untuk menjawab pertanyaan ini. Jalankan monitoring dan pastikan feed aktif.',evidence:[],actions:['Jalankan monitoring sekarang.','Periksa Source Health bila data tetap kosong.'],priority:'WATCH'};const negative=rows.filter(r=>String(r.sentiment).toLowerCase()==='negative'),critical=rows.filter(r=>['critical','high'].includes(String(r.risk_level).toLowerCase())),top=rows[0];let answer=`Sinyal tertinggi saat ini adalah “${top.title}” dari ${top.source_name||'media'} dengan risk ${Number(top.risk_score)||0}/100 dan impact ${Number(top.impact_score)||0}/100.`;if(q.includes('negatif'))answer=`Terdapat ${negative.length} sinyal negatif dalam kumpulan data yang dianalisis. Sinyal dengan prioritas tertinggi adalah “${top.title}”.`;else if(q.includes('opd'))answer=`Sinyal teratas berasal dari konteks OPD ${top.opd_name||'belum terpetakan'}.`;return{mode:'deterministic-fallback',answer,evidence:rows.slice(0,5),actions:critical.length?['Validasi fakta lintas OPD.','Tetapkan juru bicara.','Siapkan holding statement dan Q&A.']:['Monitor perkembangan.'],priority:critical.length?'HIGH':negative.length?'MEDIUM':'WATCH',active_alerts:alertCount};}
async function ai(question:string,rows:Row[]){const key=process.env.OPENAI_API_KEY;if(!key)return null;const model=process.env.OPENAI_MODEL||'gpt-5-mini';const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,input:`Jawab berdasarkan data ini saja: ${JSON.stringify({question,signals:rows.slice(0,15)})}`,max_output_tokens:1000})});if(!response.ok)throw new Error(`AI provider HTTP ${response.status}`);const payload=await response.json() as any;return payload.output_text?{mode:'ai',answer:payload.output_text,evidence:rows.slice(0,5)}:null;}
export async function registerAskIntelligence(app:FastifyInstance,pool:Pool,jwtSecret:string){const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.intelligenceAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};await registerAdminRoutes(app,pool,jwtSecret);await registerRbacRoutes(app,pool,jwtSecret);await registerDistrictRoutes(app,pool,jwtSecret);await registerOwnedSocialRoutes(app,pool,jwtSecret);await registerSocialIntelligenceRoutes(app,pool,jwtSecret);await registerSocialIngestionRoutes(app,pool,jwtSecret);await registerCommandCenterScopeRoutes(app,pool,jwtSecret);await registerPrintMediaRoutes(app,pool,jwtSecret);await registerPrintReviewRoutes(app,pool,jwtSecret);await registerPrintIssueLinkageRoutes(app,pool,jwtSecret);await registerPrintWarningSignalRoutes(app,pool,jwtSecret);await registerPhase2fCandidateAlertRoutes(app,pool,jwtSecret);await registerPhase2fCandidateIssueRoutes(app,pool,jwtSecret);await registerPhase2gMediaSummaryRoutes(app,pool,jwtSecret);await registerPrintAnalysisRecoveryRoutes(app,pool,jwtSecret);await registerPrintEvidenceRecoveryRoutes(app,pool,jwtSecret);await registerPrintCreateStableRoutes(app,pool,jwtSecret);const scopedOpd=(u:AuthorizationContext,requested?:string)=>hasPermission(u,'platform.admin')||hasPermission(u,'intelligence.read.all')?requested:(u.opdId??null);
app.post('/api/ask',{preHandler:auth},async(request,reply)=>{const parsed=z.object({question:z.string().trim().min(3).max(1000),opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const opdId=scopedOpd(request.intelligenceAuth!,parsed.data.opdId),params:unknown[]=[],where:string[]=[];if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`)}params.push(30);const {rows}=await pool.query(`SELECT a.title,a.summary,a.published_at,a.sentiment,a.risk_level,a.risk_score,a.impact_score,a.importance_score,a.velocity_score,o.name opd_name,ms.name source_name FROM articles a LEFT JOIN opd o ON o.id=a.opd_id LEFT JOIN media_sources ms ON ms.id=a.source_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY a.risk_score DESC,a.impact_score DESC LIMIT $${params.length}`,params);const data=rows as Row[];try{return await ai(parsed.data.question,data)??fallback(parsed.data.question,data,0)}catch{return fallback(parsed.data.question,data,0)}});
app.get('/api/intelligence/daily',{preHandler:auth},async(request,reply)=>{const p=z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!p.success)return reply.code(400).send({error:'INVALID_QUERY'});return{data:await generateDailyIntelligence(pool,p.data.date??new Date().toISOString().slice(0,10),scopedOpd(request.intelligenceAuth!,p.data.opdId))}});
app.get('/api/intelligence/daily/history',{preHandler:auth},async(request,reply)=>{const p=z.object({limit:z.coerce.number().int().min(1).max(30).default(7),opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!p.success)return reply.code(400).send({error:'INVALID_QUERY'});const opdId=scopedOpd(request.intelligenceAuth!,p.data.opdId),params:unknown[]=[],where:string[]=[];if(opdId){params.push(opdId);where.push(`opd_id=$${params.length}`)}params.push(p.data.limit);return{data:(await pool.query(`SELECT id,run_date,opd_id,status,payload,created_at FROM daily_intelligence_runs ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY run_date DESC LIMIT $${params.length}`,params)).rows}});
}
