import type { FastifyInstance,FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { hasPermission,loadAuthorizationContext,type AuthorizationContext } from './rbac.js';
import { getCollectionConfig,runCollection,type CollectionSource } from './collection-scheduler.js';

declare module 'fastify'{interface FastifyRequest{collectionAdmin?:AuthorizationContext}}
export async function registerCollectionSchedulerRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(r:FastifyRequest,p:any)=>{const token=r.cookies.access_token;if(!token)return p.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const c=await loadAuthorizationContext(pool,d.sub);if(!c?.active||!hasPermission(c,'platform.admin'))return p.code(403).send({error:'FORBIDDEN'});r.collectionAdmin=c}catch{return p.code(401).send({error:'INVALID_ACCESS_TOKEN'})}};
 app.get('/api/admin/collection-scheduler',{preHandler:auth},async()=>{const config=await getCollectionConfig(pool);const history=(await pool.query(`SELECT id,trigger_type,status,started_at,finished_at,sources,result,error_message FROM collection_scheduler_runs ORDER BY started_at DESC LIMIT 10`)).rows;return{data:{config,history,socialReady:false}}});
 app.put('/api/admin/collection-scheduler',{preHandler:auth},async(r,p)=>{const x=z.object({enabled:z.boolean(),runTime:z.literal('08:00'),onlineEnabled:z.boolean(),ownedEnabled:z.boolean(),socialEnabled:z.boolean().default(false)}).safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_SCHEDULER_CONFIG',detail:'Pada Vercel Hobby, jadwal otomatis dikunci ke 08:00 WIB.'});if(x.data.socialEnabled)return p.code(409).send({error:'SOCIAL_COLLECTOR_NOT_READY'});const q=await pool.query(`UPDATE collection_scheduler_config SET enabled=$1,run_time=$2::time,timezone='Asia/Jakarta',online_enabled=$3,owned_enabled=$4,social_enabled=false,updated_by=$5,updated_at=now() WHERE id=1 RETURNING *`,[x.data.enabled,x.data.runTime,x.data.onlineEnabled,x.data.ownedEnabled,r.collectionAdmin!.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'COLLECTION_SCHEDULER_UPDATED',$2::jsonb)`,[r.collectionAdmin!.id,JSON.stringify(x.data)]);return{data:q.rows[0]}});
 app.post('/api/admin/collection-scheduler/run',{preHandler:auth},async(r,p)=>{const x=z.object({sources:z.array(z.enum(['online','owned','social'])).min(1)}).safeParse(r.body);if(!x.success)return p.code(400).send({error:'INVALID_COLLECTION_SOURCES'});if(x.data.sources.includes('social'))return p.code(409).send({error:'SOCIAL_COLLECTOR_NOT_READY'});return{data:await runCollection(pool,'MANUAL',String(r.collectionAdmin!.id),x.data.sources as CollectionSource[])}});
}
