import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, hasPermission, type AuthorizationContext } from './rbac.js';
declare module 'fastify' { interface FastifyRequest { dailyReportAuth?: AuthorizationContext } }
export async function registerDailyReportRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.dailyReportAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 app.get('/api/command-center/daily-report',{preHandler:auth},async(request,reply)=>{
  const q=z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),opdId:z.string().regex(/^\d+$/).optional(),districtId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});
  const ctx=request.dailyReportAuth!,global=ctx.legacyRole==='admin'||ctx.roles.some(r=>['super_admin','humas','executive'].includes(r))||hasPermission(ctx,'platform.admin');
  const opdId=global?(q.data.opdId||null):(ctx.roles.includes('opd')?ctx.opdId:null),districtId=global?(q.data.districtId||null):(ctx.roles.includes('district')?ctx.districtId:null);if(!global&&!opdId&&!districtId)return reply.code(403).send({error:'REPORT_SCOPE_UNRESOLVED'});
  const day=q.data.date||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),params:any[]=[day],bind=(v:any)=>{params.push(v);return '$'+params.length},op=opdId?bind(opdId):null,dist=districtId?bind(districtId):null;
  const mediaScope=(a:string)=>[op?a+'.opd_id='+op:'',dist?a+'.district_id='+dist:''].filter(Boolean).map(x=>' AND '+x).join('');
  const workflowScope=(w='w',i='i')=>op?' AND ('+w+'.lead_opd_id='+op+" OR EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id="+w+".id AND c.contributor_type='OPD' AND c.opd_id="+op+'))':dist?' AND (EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id='+w+".id AND c.contributor_type='DISTRICT' AND c.district_id="+dist+') OR '+i+".geographic_scope='CITYWIDE' OR EXISTS(SELECT 1 FROM issue_districts d WHERE d.issue_id="+i+'.id AND d.district_id='+dist+'))':'';
  const issueScope=op?' AND (EXISTS(SELECT 1 FROM issue_opd io WHERE io.issue_id=i.id AND io.opd_id='+op+') OR EXISTS(SELECT 1 FROM issue_workflows w WHERE w.issue_id=i.id AND (w.lead_opd_id='+op+" OR EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id=w.id AND c.contributor_type='OPD' AND c.opd_id="+op+'))))':dist?" AND (i.geographic_scope='CITYWIDE' OR EXISTS(SELECT 1 FROM issue_districts d WHERE d.issue_id=i.id AND d.district_id="+dist+") OR EXISTS(SELECT 1 FROM issue_workflows w JOIN issue_workflow_contributors c ON c.workflow_id=w.id WHERE w.issue_id=i.id AND c.contributor_type='DISTRICT' AND c.district_id="+dist+'))':'';
  const queries=[
   pool.query("SELECT COUNT(*)::int n FROM articles a WHERE a.news_classification='UTAMA' AND (a.published_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('a'),params),
   pool.query("SELECT COUNT(*)::int n FROM print_articles pa JOIN print_editions pe ON pe.id=pa.edition_id WHERE lower(pa.status)='analyzed' AND pe.edition_date=$1::date"+mediaScope('pa'),params),
   pool.query("SELECT COUNT(*)::int n FROM social_mentions sm WHERE sm.source_kind='external' AND (COALESCE(sm.published_at,sm.captured_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('sm'),params),
   pool.query("SELECT COUNT(*)::int n FROM social_mentions sm WHERE sm.source_kind='owned' AND (COALESCE(sm.published_at,sm.captured_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('sm'),params),
   pool.query("SELECT COUNT(*)::int n,COUNT(*) FILTER(WHERE lower(i.status)='watch')::int watch,COUNT(*) FILTER(WHERE lower(i.status)='active')::int active,COUNT(*) FILTER(WHERE lower(i.status)='resolved')::int resolved FROM issues i WHERE (i.created_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+issueScope,params),
   pool.query("SELECT COUNT(*)::int n FROM issue_communication_gap_snapshots g JOIN issue_workflows w ON w.id=g.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (g.analyzed_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n,COUNT(*) FILTER(WHERE s.status='APPROVED')::int approved FROM communication_strategies s JOIN issue_workflows w ON w.id=s.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (COALESCE(s.approved_at,s.reviewed_at,s.generated_at,s.updated_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n FROM issue_workflows w JOIN issues i ON i.id=w.issue_id WHERE w.published_at IS NOT NULL AND (w.published_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n FROM issue_monitoring_analysis_snapshots m JOIN issue_workflows w ON w.id=m.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (m.analyzed_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params)
  ];
  const [online,print,social,owned,issues,gaps,strategies,published,monitoring]=await Promise.all(queries),scopeName=opdId?(await pool.query('SELECT name FROM opd WHERE id=$1',[opdId])).rows[0]?.name:districtId?(await pool.query('SELECT name FROM districts WHERE id=$1',[districtId])).rows[0]?.name:'Seluruh Pemko Batam';
  return{data:{date:day,timeZone:'Asia/Jakarta',scope:{type:opdId?'OPD':districtId?'DISTRICT':'GLOBAL',id:opdId||districtId||null,name:scopeName||'Scope Akun'},media:{online:Number(online.rows[0]?.n||0),print:Number(print.rows[0]?.n||0),social:Number(social.rows[0]?.n||0),owned:Number(owned.rows[0]?.n||0)},issues:{total:Number(issues.rows[0]?.n||0),watch:Number(issues.rows[0]?.watch||0),active:Number(issues.rows[0]?.active||0),resolved:Number(issues.rows[0]?.resolved||0)},workflow:{gap:Number(gaps.rows[0]?.n||0),strategy:Number(strategies.rows[0]?.n||0),strategyApproved:Number(strategies.rows[0]?.approved||0),publication:Number(published.rows[0]?.n||0),monitoring:Number(monitoring.rows[0]?.n||0)}}};
 });
}