import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, hasPermission, type AuthorizationContext } from './rbac.js';
declare module 'fastify' { interface FastifyRequest { dailyReportAuth?: AuthorizationContext } }
export async function registerDailyReportRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.dailyReportAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 app.get('/api/command-center/daily-report',{preHandler:auth},async(request,reply)=>{
  const q=z.object({date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),opdId:z.string().regex(/^\d+$/).optional(),districtId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});
  const ctx=request.dailyReportAuth!,global=ctx.legacyRole==='admin'||ctx.roles.some(r=>['super_admin','humas','executive'].includes(r))||hasPermission(ctx,'platform.admin');
  const opdId=global?(q.data.opdId||null):(ctx.roles.includes('opd')?ctx.opdId:null),districtId=global?(q.data.districtId||null):(ctx.roles.includes('district')?ctx.districtId:null);if(!global&&!opdId&&!districtId)return reply.code(403).send({error:'REPORT_SCOPE_UNRESOLVED'});
  const day=q.data.date||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),params:any[]=[day],bind=(v:any)=>{params.push(v);return '$'+params.length},op=opdId?bind(opdId):null,dist=districtId?bind(districtId):null;
  const mediaScope=(a:string)=>[op?a+'.opd_id='+op:'',dist?a+'.district_id='+dist:''].filter(Boolean).map(x=>' AND '+x).join('');
  const workflowScope=(w='w',i='i')=>op?' AND ('+w+'.lead_opd_id='+op+" OR EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id="+w+".id AND c.contributor_type='OPD' AND c.opd_id="+op+'))':dist?' AND (EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id='+w+".id AND c.contributor_type='DISTRICT' AND c.district_id="+dist+') OR '+i+".geographic_scope='CITYWIDE' OR EXISTS(SELECT 1 FROM issue_districts d WHERE d.issue_id="+i+'.id AND d.district_id='+dist+'))':'';
  const issueScope=op?' AND (EXISTS(SELECT 1 FROM issue_opd io WHERE io.issue_id=i.id AND io.opd_id='+op+') OR EXISTS(SELECT 1 FROM issue_workflows w WHERE w.issue_id=i.id AND (w.lead_opd_id='+op+" OR EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id=w.id AND c.contributor_type='OPD' AND c.opd_id="+op+'))))':dist?" AND (i.geographic_scope='CITYWIDE' OR EXISTS(SELECT 1 FROM issue_districts d WHERE d.issue_id=i.id AND d.district_id="+dist+") OR EXISTS(SELECT 1 FROM issue_workflows w JOIN issue_workflow_contributors c ON c.workflow_id=w.id WHERE w.issue_id=i.id AND c.contributor_type='DISTRICT' AND c.district_id="+dist+'))':'';
  const queries=[
   pool.query("SELECT COUNT(*)::int n FROM articles a WHERE a.news_classification='UTAMA' AND (a.published_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('a'),params),
   pool.query("SELECT COUNT(*)::int n FROM print_articles pa JOIN print_editions pe ON pe.id=pa.edition_id WHERE lower(pa.status)='analyzed' AND pe.edition_date=$1::date"+mediaScope('pa'),params),
   pool.query("SELECT COUNT(*)::int n FROM social_mentions sm WHERE sm.source_kind='external' AND (COALESCE(sm.published_at,sm.captured_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('sm'),params),
   pool.query("SELECT COUNT(*)::int n FROM social_mentions sm WHERE sm.source_kind='owned' AND (COALESCE(sm.published_at,sm.captured_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('sm'),params),
   pool.query("SELECT COUNT(*)::int n,COUNT(*) FILTER(WHERE lower(i.status)='watch')::int watch,COUNT(*) FILTER(WHERE lower(i.status)='active')::int active,COUNT(*) FILTER(WHERE lower(i.status)='resolved')::int resolved FROM issues i WHERE (i.created_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+issueScope,params),
   pool.query("SELECT COUNT(*)::int n FROM issue_communication_gap_snapshots g JOIN issue_workflows w ON w.id=g.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (g.analyzed_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n,COUNT(*) FILTER(WHERE s.status='APPROVED')::int approved FROM communication_strategies s JOIN issue_workflows w ON w.id=s.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (COALESCE(s.approved_at,s.reviewed_at,s.generated_at,s.updated_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n FROM issue_workflows w JOIN issues i ON i.id=w.issue_id WHERE w.published_at IS NOT NULL AND (w.published_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params),
   pool.query("SELECT COUNT(*)::int n FROM issue_monitoring_analysis_snapshots m JOIN issue_workflows w ON w.id=m.workflow_id JOIN issues i ON i.id=w.issue_id WHERE (m.analyzed_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+workflowScope(),params)
  ];
  const [online,print,social,owned,issues,gaps,strategies,published,monitoring]=await Promise.all(queries),scopeName=opdId?(await pool.query('SELECT name FROM opd WHERE id=$1',[opdId])).rows[0]?.name:districtId?(await pool.query('SELECT name FROM districts WHERE id=$1',[districtId])).rows[0]?.name:'Seluruh Pemko Batam';
  const importantSql=[
   "SELECT 'Online'::text media,a.title,COALESCE(ms.name,'Media Online')::text source,a.sentiment,a.risk_level::text risk_level,COALESCE(a.risk_score,0)::float risk_score,a.published_at::timestamptz happened_at FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE a.news_classification='UTAMA' AND (a.published_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('a'),
   "SELECT 'Cetak'::text media,pa.title,COALESCE(ms.name,'Media Cetak')::text source,pa.sentiment,COALESCE(NULLIF(pa.ai_metadata->'intelligence'->>'riskLevel',''),CASE WHEN pa.risk_score>=80 THEN 'critical' WHEN pa.risk_score>=60 THEN 'high' WHEN pa.risk_score>=35 THEN 'medium' ELSE 'low' END)::text risk_level,COALESCE(pa.risk_score,0)::float risk_score,pe.edition_date::timestamptz happened_at FROM print_articles pa JOIN print_editions pe ON pe.id=pa.edition_id LEFT JOIN media_sources ms ON ms.id=pe.source_id WHERE lower(pa.status)='analyzed' AND pe.edition_date=$1::date"+mediaScope('pa'),
   "SELECT 'Sosial'::text media,COALESCE(sm.title,left(sm.content,180)) title,COALESCE(sm.author_name,sm.platform,'Media Sosial')::text source,sm.sentiment,sm.risk_level::text risk_level,COALESCE(sm.risk_score,0)::float risk_score,COALESCE(sm.published_at,sm.captured_at)::timestamptz happened_at FROM social_mentions sm WHERE sm.source_kind='external' AND (COALESCE(sm.published_at,sm.captured_at) AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+mediaScope('sm')
  ].join(' UNION ALL ');
  const [important,issueRows,attentionRows]=await Promise.all([
   pool.query("SELECT * FROM ("+importantSql+") x ORDER BY CASE WHEN lower(COALESCE(risk_level,''))='critical' THEN 4 WHEN lower(COALESCE(risk_level,''))='high' THEN 3 WHEN lower(COALESCE(risk_level,''))='medium' THEN 2 ELSE 1 END DESC,risk_score DESC,happened_at DESC LIMIT 10",params),
   pool.query("SELECT i.id,i.title,i.status,i.risk_level,w.workflow_status,o.name lead_opd_name FROM issues i LEFT JOIN LATERAL(SELECT x.* FROM issue_workflows x WHERE x.issue_id=i.id ORDER BY x.cycle_number DESC,x.id DESC LIMIT 1) w ON true LEFT JOIN opd o ON o.id=w.lead_opd_id WHERE (i.created_at AT TIME ZONE 'Asia/Jakarta')::date=$1::date"+issueScope+" ORDER BY CASE lower(COALESCE(i.risk_level,'')) WHEN 'critical' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END DESC,i.created_at DESC LIMIT 10",params),
   pool.query("SELECT i.id,i.title,i.risk_level,w.workflow_status,o.name lead_opd_name,(SELECT COUNT(*) FROM communication_strategies s WHERE s.workflow_id=w.id AND s.status='APPROVED')::int approved_strategy FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id WHERE i.status='active' AND w.workflow_status<>'CLOSED'"+workflowScope()+" ORDER BY CASE lower(COALESCE(i.risk_level,'')) WHEN 'critical' THEN 4 WHEN 'high' THEN 3 WHEN 'medium' THEN 2 ELSE 1 END DESC,w.updated_at DESC LIMIT 10",params)
  ]);
  const mediaNumbers={online:Number(online.rows[0]?.n||0),print:Number(print.rows[0]?.n||0),social:Number(social.rows[0]?.n||0),owned:Number(owned.rows[0]?.n||0)},issueNumbers={total:Number(issues.rows[0]?.n||0),watch:Number(issues.rows[0]?.watch||0),active:Number(issues.rows[0]?.active||0),resolved:Number(issues.rows[0]?.resolved||0)},workflowNumbers={gap:Number(gaps.rows[0]?.n||0),strategy:Number(strategies.rows[0]?.n||0),strategyApproved:Number(strategies.rows[0]?.approved||0),publication:Number(published.rows[0]?.n||0),monitoring:Number(monitoring.rows[0]?.n||0)};
  const negative=important.rows.filter((x:any)=>String(x.sentiment||'').toLowerCase()==='negative').length,high=important.rows.filter((x:any)=>['high','critical'].includes(String(x.risk_level||'').toLowerCase())).length,totalExternal=mediaNumbers.online+mediaNumbers.print+mediaNumbers.social;
  const attention:any[]=[];if(negative)attention.push({type:'MEDIA_NEGATIVE',label:negative+' berita penting bersentimen negatif hari ini'});if(high)attention.push({type:'MEDIA_HIGH_RISK',label:high+' berita penting berisiko tinggi/kritis hari ini'});for(const x of attentionRows.rows){if(Number(x.approved_strategy||0)===0)attention.push({type:'STRATEGY_PENDING',label:'Issue aktif belum memiliki Strakom disetujui',issueTitle:x.title,leadOpd:x.lead_opd_name||null});else if(!['PUBLISHED','MONITORING','CLOSED'].includes(String(x.workflow_status)))attention.push({type:'PUBLICATION_PENDING',label:'Strakom sudah tersedia, publikasi belum tercatat',issueTitle:x.title,leadOpd:x.lead_opd_name||null});if(attention.length>=8)break}
  const executiveSummary=totalExternal===0&&issueNumbers.total===0&&workflowNumbers.gap===0&&workflowNumbers.strategy===0&&workflowNumbers.publication===0&&workflowNumbers.monitoring===0?'Belum ada aktivitas Media Intelligence yang tercatat pada scope ini untuk tanggal laporan.':'Hari ini tercatat '+totalExternal+' pemberitaan eksternal, '+mediaNumbers.owned+' item Media Internal, '+issueNumbers.total+' issue baru, '+workflowNumbers.strategy+' aktivitas Strakom, '+workflowNumbers.publication+' publikasi, dan '+workflowNumbers.monitoring+' analisa monitoring pada scope laporan.';
  return{data:{date:day,timeZone:'Asia/Jakarta',scope:{type:opdId?'OPD':districtId?'DISTRICT':'GLOBAL',id:opdId||districtId||null,name:scopeName||'Scope Akun'},executiveSummary,media:mediaNumbers,issues:issueNumbers,workflow:workflowNumbers,importantNews:important.rows,issueDetails:issueRows.rows,attention}};
 });
}