import type {Pool} from 'pg';import {checkIssueEvidenceEligibility,type IssueEvidenceSource} from './issue-evidence-eligibility.js';
export type IssueMonitorSource='online'|'print'|'social'|'owned';export type IssueMonitorInput={sourceType:IssueMonitorSource;evidenceId:number;publishedAt?:Date|string|null;title?:string|null;content?:string|null;taxonomyId?:number|null};
export type IssueMonitorMatch={monitorId:number;issueId:number;monitorName:string;matchedTerms:string[];relevanceScore:number};
const norm=(v:string)=>v.toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim();
const has=(h:string,t:string)=>{const x=norm(t);return !!x&&(' '+norm(h)+' ').includes(' '+x+' ')};
const gateSource=(s:IssueMonitorSource):IssueEvidenceSource=>s==='print'?'PRINT':s==='owned'?'OWNED':s==='online'?'ONLINE':'SOCIAL';
export async function matchEligibleIssueMonitors(pool:Pool,input:IssueMonitorInput):Promise<IssueMonitorMatch[]>{
 const gate=await checkIssueEvidenceEligibility(pool,gateSource(input.sourceType),input.evidenceId);if(!gate.eligible)return[];
 if(!input.publishedAt)return[];const published=new Date(input.publishedAt);if(Number.isNaN(published.getTime()))return[];
 const {rows}=await pool.query(`SELECT m.id monitor_id,m.issue_id,m.name,i.taxonomy_category_id,jsonb_agg(jsonb_build_object('term',t.term,'matchType',t.match_type) ORDER BY t.id) FILTER(WHERE t.active=true) terms FROM issue_monitors m JOIN issues i ON i.id=m.issue_id JOIN issue_monitor_sources s ON s.monitor_id=m.id AND s.source_type=$1 JOIN issue_monitor_terms t ON t.monitor_id=m.id AND t.active=true WHERE m.status='watching' AND $2::timestamptz BETWEEN m.starts_at AND m.ends_at GROUP BY m.id,m.issue_id,m.name,i.taxonomy_category_id`,[input.sourceType,published]);
 const title=String(input.title||''),body=String(input.content||''),all=title+' '+body,out:IssueMonitorMatch[]=[];
 for(const row of rows){if(row.taxonomy_category_id!=null&&(input.taxonomyId==null||Number(row.taxonomy_category_id)!==Number(input.taxonomyId)))continue;
  const terms=(row.terms||[]) as Array<{term:string;matchType:'DIRECT'|'CONTEXT'}>;const matched=terms.filter(x=>x.matchType==='DIRECT'?has(title,x.term):has(all,x.term));if(!matched.length)continue;
  const titleHits=matched.filter(x=>has(title,x.term)).length;out.push({monitorId:Number(row.monitor_id),issueId:Number(row.issue_id),monitorName:String(row.name),matchedTerms:matched.map(x=>x.term),relevanceScore:Math.min(100,60+titleHits*20+Math.max(0,matched.length-titleHits)*10)});
 }return out;
}
export async function linkEligibleOnline(pool:Pool,args:Omit<IssueMonitorInput,'sourceType'|'evidenceId'>&{articleId:number}){const matches=await matchEligibleIssueMonitors(pool,{...args,evidenceId:args.articleId,sourceType:'online'});for(const m of matches)await pool.query(`INSERT INTO issue_articles(issue_id,article_id,relevance_score,assignment_source) VALUES($1,$2,$3,'ISSUE_MONITOR') ON CONFLICT(issue_id,article_id) DO UPDATE SET relevance_score=CASE WHEN issue_articles.assignment_source='MANUAL' THEN issue_articles.relevance_score ELSE GREATEST(issue_articles.relevance_score,EXCLUDED.relevance_score) END,assignment_source=CASE WHEN issue_articles.assignment_source='MANUAL' THEN 'MANUAL' ELSE 'ISSUE_MONITOR' END`,[m.issueId,args.articleId,m.relevanceScore]);return matches}
export async function linkEligibleSocial(pool:Pool,args:Omit<IssueMonitorInput,'sourceType'|'evidenceId'>&{mentionId:number;sourceKind:'external'|'owned'}){const sourceType=args.sourceKind==='owned'?'owned':'social';const matches=await matchEligibleIssueMonitors(pool,{...args,evidenceId:args.mentionId,sourceType});for(const m of matches)await pool.query(`INSERT INTO social_mention_issues(mention_id,issue_id,relevance_score,linkage_source) VALUES($1,$2,$3,'ISSUE_MONITOR') ON CONFLICT(mention_id,issue_id) DO UPDATE SET relevance_score=CASE WHEN lower(social_mention_issues.linkage_source)='manual' THEN social_mention_issues.relevance_score ELSE GREATEST(social_mention_issues.relevance_score,EXCLUDED.relevance_score) END,linkage_source=CASE WHEN lower(social_mention_issues.linkage_source)='manual' THEN social_mention_issues.linkage_source ELSE 'ISSUE_MONITOR' END`,[args.mentionId,m.issueId,m.relevanceScore]);return matches}
export async function findEligiblePrintCandidates(pool:Pool,args:Omit<IssueMonitorInput,'sourceType'|'evidenceId'>&{printArticleId:number}){const matches=await matchEligibleIssueMonitors(pool,{...args,evidenceId:args.printArticleId,sourceType:'print'});for(const m of matches)await pool.query(`INSERT INTO issue_print_articles(issue_id,print_article_id,relevance_score,linkage_status,evidence) VALUES($1,$2,$3,'linked',$4::jsonb) ON CONFLICT(issue_id,print_article_id) DO UPDATE SET relevance_score=CASE WHEN issue_print_articles.decided_by IS NULL AND issue_print_articles.linkage_status NOT IN ('rejected','linked') THEN GREATEST(issue_print_articles.relevance_score,EXCLUDED.relevance_score) ELSE issue_print_articles.relevance_score END,linkage_status=CASE WHEN issue_print_articles.decided_by IS NULL AND issue_print_articles.linkage_status NOT IN ('rejected','linked') THEN 'linked' ELSE issue_print_articles.linkage_status END,evidence=CASE WHEN issue_print_articles.decided_by IS NULL AND issue_print_articles.linkage_status NOT IN ('rejected','linked') THEN EXCLUDED.evidence ELSE issue_print_articles.evidence END,updated_at=CASE WHEN issue_print_articles.decided_by IS NULL AND issue_print_articles.linkage_status NOT IN ('rejected','linked') THEN now() ELSE issue_print_articles.updated_at END`,[m.issueId,args.printArticleId,m.relevanceScore,JSON.stringify({engine:'ISSUE_MONITOR_V2',linkageSource:'ISSUE_MONITOR',monitorId:m.monitorId,monitorName:m.monitorName,matchedTerms:m.matchedTerms})]);return matches}
