import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { issueTaxonomyAuth?: AuthorizationContext } }
const canManage=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');
async function resolveOrganizationId(pool:Pool,ctx:AuthorizationContext){if(ctx.opdId){const r=await pool.query('SELECT organization_id FROM opd WHERE id=$1',[ctx.opdId]);if(r.rows[0]?.organization_id)return Number(r.rows[0].organization_id);}const r=await pool.query('SELECT id FROM organizations ORDER BY id LIMIT 2');return r.rowCount===1?Number(r.rows[0].id):0;}

export async function registerIssueTaxonomyManagementRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.issueTaxonomyAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const manager=async(request:FastifyRequest,reply:any)=>{await auth(request,reply);if(reply.sent)return;const ctx=request.issueTaxonomyAuth!;if(!canManage(ctx))return reply.code(403).send({error:'HUMAS_OR_SUPER_ADMIN_REQUIRED'});};

 app.get('/api/admin/issue-taxonomy/taxonomies',{preHandler:auth},async()=>({data:(await pool.query(`SELECT t.id,t.code,t.name,t.description,t.active,t.created_at,t.updated_at,COUNT(i.id)::int issue_count FROM taxonomy_categories t LEFT JOIN issues i ON i.taxonomy_category_id=t.id GROUP BY t.id ORDER BY t.active DESC,t.name ASC`)).rows}));
 app.post('/api/admin/issue-taxonomy/taxonomies',{preHandler:manager},async(request,reply)=>{const p=z.object({code:z.string().trim().min(2).max(60).regex(/^[A-Z0-9_]+$/),name:z.string().trim().min(3).max(120),description:z.string().trim().max(500).optional().default('')}).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});try{return{ok:true,data:(await pool.query(`INSERT INTO taxonomy_categories(code,name,description,active) VALUES($1,$2,$3,true) RETURNING *`,[p.data.code,p.data.name,p.data.description||null])).rows[0]}}catch(e:any){if(e?.code==='23505')return reply.code(409).send({error:'TAXONOMY_ALREADY_EXISTS'});throw e;}});
 app.patch('/api/admin/issue-taxonomy/taxonomies/:id',{preHandler:manager},async(request,reply)=>{const id=Number((request.params as any).id);if(!Number.isInteger(id)||id<=0)return reply.code(400).send({error:'INVALID_ID'});const p=z.object({name:z.string().trim().min(3).max(120).optional(),description:z.string().trim().max(500).nullable().optional(),active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query('SELECT * FROM taxonomy_categories WHERE id=$1',[id])).rows[0];if(!current)return reply.code(404).send({error:'TAXONOMY_NOT_FOUND'});return{ok:true,data:(await pool.query(`UPDATE taxonomy_categories SET name=$2,description=$3,active=$4,updated_at=now() WHERE id=$1 RETURNING *`,[id,p.data.name??current.name,p.data.description===undefined?current.description:p.data.description,p.data.active??current.active])).rows[0]}});

 app.get('/api/admin/issue-taxonomy/issues',{preHandler:auth},async(request,reply)=>{const ctx=request.issueTaxonomyAuth!;const organizationId=await resolveOrganizationId(pool,ctx);if(!organizationId)return reply.code(409).send({error:'ORGANIZATION_UNRESOLVED'});return{data:(await pool.query(`SELECT i.id,i.issue_key,i.title,i.description,i.status,i.risk_level,i.momentum,i.taxonomy_category_id,t.name taxonomy_name,t.code taxonomy_code,iw.workflow_status,COALESCE((SELECT COUNT(*) FROM issue_print_articles x WHERE x.issue_id=i.id),0)::int print_count,COALESCE((SELECT COUNT(*) FROM issue_articles x WHERE x.issue_id=i.id),0)::int online_count,COALESCE((SELECT COUNT(*) FROM social_mention_issues x WHERE x.issue_id=i.id),0)::int social_count,i.created_at,i.updated_at FROM issues i LEFT JOIN taxonomy_categories t ON t.id=i.taxonomy_category_id LEFT JOIN issue_workflows iw ON iw.issue_id=i.id WHERE i.organization_id=$1 ORDER BY CASE WHEN i.status IN ('active','watch') THEN 0 ELSE 1 END,i.updated_at DESC,i.id DESC`,[organizationId])).rows}});
 app.patch('/api/admin/issue-taxonomy/issues/:id',{preHandler:manager},async(request,reply)=>{const ctx=request.issueTaxonomyAuth!;const organizationId=await resolveOrganizationId(pool,ctx);if(!organizationId)return reply.code(409).send({error:'ORGANIZATION_UNRESOLVED'});const id=Number((request.params as any).id);if(!Number.isInteger(id)||id<=0)return reply.code(400).send({error:'INVALID_ID'});const p=z.object({title:z.string().trim().min(3).max(250).optional(),description:z.string().trim().max(1500).nullable().optional(),taxonomyCategoryId:z.number().int().positive().nullable().optional(),status:z.enum(['active','watch','resolved','archived']).optional(),riskLevel:z.enum(['low','medium','high','critical']).optional(),momentum:z.enum(['low','medium','high','critical']).optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query('SELECT * FROM issues WHERE id=$1 AND organization_id=$2',[id,organizationId])).rows[0];if(!current)return reply.code(404).send({error:'ISSUE_NOT_FOUND'});if(p.data.taxonomyCategoryId){const t=(await pool.query('SELECT id FROM taxonomy_categories WHERE id=$1',[p.data.taxonomyCategoryId])).rows[0];if(!t)return reply.code(400).send({error:'TAXONOMY_NOT_FOUND'});}const row=(await pool.query(`UPDATE issues SET title=$3,description=$4,taxonomy_category_id=$5,status=$6,risk_level=$7,momentum=$8,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *`,[id,organizationId,p.data.title??current.title,p.data.description===undefined?current.description:p.data.description,p.data.taxonomyCategoryId===undefined?current.taxonomy_category_id:p.data.taxonomyCategoryId,p.data.status??current.status,p.data.riskLevel??current.risk_level,p.data.momentum??current.momentum])).rows[0];await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ISSUE_MANAGEMENT_UPDATED',$2)`,[ctx.id,{issueId:id,organizationId,changes:p.data}]);return{ok:true,data:row};});
}
