import type { FastifyInstance,FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { put,del } from '@vercel/blob';
import { loadAuthorizationContext,type AuthorizationContext } from './rbac.js';

declare module 'fastify'{interface FastifyRequest{mapBoundaryAuth?:AuthorizationContext}}
const canManage=(c:AuthorizationContext)=>c.legacyRole==='admin'||c.roles.includes('super_admin')||c.roles.includes('humas');
const norm=(v:any)=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
const sq=(a:number[],b:number[],p:number[])=>{let x=a[0],y=a[1],dx=b[0]-x,dy=b[1]-y;if(dx||dy){const t=((p[0]-x)*dx+(p[1]-y)*dy)/(dx*dx+dy*dy);if(t>1){x=b[0];y=b[1]}else if(t>0){x+=dx*t;y+=dy*t}}dx=p[0]-x;dy=p[1]-y;return dx*dx+dy*dy};
function dp(points:number[][],tol=.0002){if(points.length<=4)return points;const closed=points[0][0]===points.at(-1)?.[0]&&points[0][1]===points.at(-1)?.[1],src=closed?points.slice(0,-1):points;if(src.length<=3)return points;const keep=new Uint8Array(src.length);keep[0]=keep[src.length-1]=1;const stack:[[number,number]]|any=[[0,src.length-1]],t2=tol*tol;while(stack.length){const [s,e]=stack.pop();let best=t2,idx=-1;for(let i=s+1;i<e;i++){const d=sq(src[s],src[e],src[i]);if(d>best){best=d;idx=i}}if(idx>0){keep[idx]=1;stack.push([s,idx],[idx,e])}}let out=src.filter((_,i)=>keep[i]);if(out.length<3)out=src.slice(0,3);if(closed)out=[...out,out[0]];return out}
function simplifyGeom(g:any){if(!g||!['Polygon','MultiPolygon'].includes(g.type))throw new Error('UNSUPPORTED_GEOMETRY');const poly=(p:any)=>p.map((r:any)=>dp(r));return{type:g.type,coordinates:g.type==='Polygon'?poly(g.coordinates):g.coordinates.map(poly)}}
function prop(p:any,names:string[]){for(const n of names)if(p?.[n]!=null&&String(p[n]).trim())return String(p[n]).trim();return''}
async function orgId(pool:Pool,c:AuthorizationContext){if(c.opdId){const r=await pool.query('SELECT organization_id FROM opd WHERE id=$1',[c.opdId]);if(r.rows[0]?.organization_id)return Number(r.rows[0].organization_id)}const r=await pool.query('SELECT id FROM organizations WHERE active=true ORDER BY id LIMIT 2');return r.rowCount===1?Number(r.rows[0].id):0}

export async function registerMapBoundaryRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(r:FastifyRequest,reply:any)=>{const token=r.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw 0;const c=await loadAuthorizationContext(pool,d.sub);if(!c?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});r.mapBoundaryAuth=c}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'})}};
 app.post('/api/admin/map-boundaries/upload',{preHandler:auth,bodyLimit:20_000_000},async(r,reply)=>{
  const ctx=r.mapBoundaryAuth!;if(!canManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  const oid=await orgId(pool,ctx);if(!oid)return reply.code(409).send({error:'ACTIVE_ORGANIZATION_UNRESOLVED'});
  let geo:any;try{geo=Buffer.isBuffer(r.body)?JSON.parse(r.body.toString('utf8')):r.body}catch{return reply.code(400).send({error:'INVALID_GEOJSON'})}
  if(geo?.type!=='FeatureCollection'||!Array.isArray(geo.features)||!geo.features.length||geo.features.length>500)return reply.code(400).send({error:'INVALID_FEATURE_COLLECTION'});
  const districts=(await pool.query('SELECT id,code,name FROM districts WHERE active=true ORDER BY name')).rows;
  const byCode=new Map(districts.filter((d:any)=>d.code).map((d:any)=>[norm(d.code),d])),byName=new Map(districts.map((d:any)=>[norm(d.name),d]));
  const mapped:any[]=[],features:any[]=[];
  try{for(let i=0;i<geo.features.length;i++){const f=geo.features[i],p=f?.properties||{},name=prop(p,['WADMKC','wadmkc','KECAMATAN','kecamatan','name','NAME']);if(!name)throw new Error('FEATURE_NAME_MISSING');const official=prop(p,['KDCPUM','kdcpum','KODE','kode','code','CODE']);const d=(official&&byCode.get(norm(official)))||byName.get(norm(name))||null,method=d?(official&&byCode.get(norm(official))?'OFFICIAL_CODE':'NORMALIZED_NAME'):'UNMATCHED';features.push({type:'Feature',properties:{featureKey:String(f.id??official??i+1),name,officialCode:official||null},geometry:simplifyGeom(f.geometry)});mapped.push({key:String(f.id??official??i+1),name,officialCode:official||null,districtId:d?.id||null,matchMethod:method})}}catch(e:any){return reply.code(400).send({error:e?.message||'INVALID_GEOJSON_FEATURE'})}
  const original=Buffer.from(JSON.stringify(geo)),optimized=Buffer.from(JSON.stringify({type:'FeatureCollection',features}));
  let a:any,b:any;try{const base='map-boundaries/'+oid+'/'+Date.now();a=await put(base+'/original.geojson',original,{access:'private',contentType:'application/geo+json',addRandomSuffix:false});b=await put(base+'/optimized.geojson',optimized,{access:'private',contentType:'application/geo+json',addRandomSuffix:false})}catch(e:any){if(a?.pathname)try{await del(a.pathname)}catch{}return reply.code(503).send({error:'BOUNDARY_STORAGE_UNAVAILABLE',message:e?.message||'Blob unavailable'})}
  const c=await pool.connect();try{await c.query('BEGIN');const br=(await c.query(`INSERT INTO organization_map_boundaries(organization_id,name,source_name,source_year,original_storage_key,optimized_storage_key,original_size_bytes,optimized_size_bytes,feature_count,status,metadata,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'DRAFT',$10::jsonb,$11) RETURNING id,status,created_at`,[oid,prop(geo,['name'])||'Boundary wilayah','BIG',new Date().getFullYear(),a.pathname,b.pathname,original.length,optimized.length,features.length,JSON.stringify({optimization:{method:'douglas-peucker',tolerance:0.0002}}),ctx.id])).rows[0];for(const x of mapped)await c.query(`INSERT INTO organization_map_boundary_features(boundary_id,feature_key,feature_name,official_code,district_id,match_method) VALUES($1,$2,$3,$4,$5,$6)`,[br.id,x.key,x.name,x.officialCode,x.districtId,x.matchMethod]);await c.query('COMMIT');return{data:{...br,featureCount:features.length,originalSizeBytes:original.length,optimizedSizeBytes:optimized.length,matched:mapped.filter(x=>x.districtId).length,unmatched:mapped.filter(x=>!x.districtId).length,features:mapped}}}catch(e){await c.query('ROLLBACK');try{await Promise.all([del(a.pathname),del(b.pathname)])}catch{}throw e}finally{c.release()}
 });
 app.get('/api/admin/map-boundaries',{preHandler:auth},async(r,reply)=>{const ctx=r.mapBoundaryAuth!;if(!canManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const oid=await orgId(pool,ctx);const rows=(await pool.query(`SELECT b.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',f.id,'featureKey',f.feature_key,'featureName',f.feature_name,'officialCode',f.official_code,'districtId',f.district_id,'districtName',d.name,'matchMethod',f.match_method) ORDER BY f.feature_name) FROM organization_map_boundary_features f LEFT JOIN districts d ON d.id=f.district_id WHERE f.boundary_id=b.id),'[]'::jsonb) features FROM organization_map_boundaries b WHERE b.organization_id=$1 ORDER BY b.created_at DESC`,[oid])).rows;return{data:rows}});
}
