import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { masterBulkRoutingAuth?: AuthorizationContext } }
const canManage=(c:AuthorizationContext)=>c.legacyRole==='admin'||c.roles.includes('super_admin')||c.roles.includes('humas');
async function organizationId(pool:Pool,c:AuthorizationContext){if(c.opdId){const r=await pool.query('SELECT organization_id FROM opd WHERE id=$1',[c.opdId]);if(r.rows[0]?.organization_id)return Number(r.rows[0].organization_id)}const r=await pool.query('SELECT id FROM organizations WHERE active=true ORDER BY id LIMIT 2');return r.rowCount===1?Number(r.rows[0].id):0}
const input=z.object({scopeType:z.enum(['SECTOR','TAXONOMY']),scopeId:z.number().int().positive(),primaryOpdId:z.number().int().positive().nullable(),supportingOpdIds:z.array(z.number().int().positive()).max(3).default([]),overwrite:z.boolean().default(false),dryRun:z.boolean().default(true)});
export async function registerMasterClassificationBulkRoutingRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(req:FastifyRequest,reply:any)=>{const token=req.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw Error();const c=await loadAuthorizationContext(pool,d.sub);if(!c?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});if(!canManage(c))return reply.code(403).send({error:'HUMAS_OR_SUPER_ADMIN_REQUIRED'});req.masterBulkRoutingAuth=c}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'})}};
 app.post('/api/admin/master-classification/bulk-routing',{preHandler:auth},async(req,reply)=>{const p=input.safeParse(req.body);if(!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const org=await organizationId(pool,req.masterBulkRoutingAuth!);if(!org)return reply.code(409).send({error:'ORGANIZATION_UNRESOLVED'});const support=[...new Set(p.data.supportingOpdIds)];if(support.length!==p.data.supportingOpdIds.length||p.data.primaryOpdId!==null&&support.includes(p.data.primaryOpdId))return reply.code(400).send({error:'INVALID_ROUTING_SELECTION'});const opdIds=[...(p.data.primaryOpdId?[p.data.primaryOpdId]:[]),...support];if(opdIds.length){const valid=(await pool.query('SELECT id FROM opd WHERE organization_id=$1 AND active=true AND id=ANY($2::bigint[])',[org,opdIds])).rowCount;if(valid!==opdIds.length)return reply.code(400).send({error:'INVALID_OR_INACTIVE_OPD'})}
 const scope=p.data.scopeType==='SECTOR'?'t.sector_id=$2':'t.id=$2';const rows=(await pool.query(`SELECT DISTINCT k.id,k.keyword,EXISTS(SELECT 1 FROM keyword_opd ko WHERE ko.keyword_id=k.id AND ko.active=true) routed FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories t ON t.id=kt.category_id AND t.active=true JOIN classification_sectors s ON s.id=t.sector_id AND s.active=true WHERE k.organization_id=$1 AND k.active=true AND t.organization_id=$1 AND ${scope} ORDER BY k.keyword`,[org,p.data.scopeId])).rows;if(!rows.length)return reply.code(404).send({error:'NO_ACTIVE_MASTER_KEYWORDS_IN_SCOPE'});const target=rows.filter((r:any)=>p.data.overwrite||!r.routed),skipped=rows.length-target.length;const preview={scopeType:p.data.scopeType,scopeId:p.data.scopeId,totalKeywords:rows.length,affectedKeywords:target.length,skippedExistingRouting:skipped,overwrite:p.data.overwrite,primaryOpdId:p.data.primaryOpdId,supportingOpdIds:support};if(p.data.dryRun)return{ok:true,dryRun:true,data:preview};
 const client=await pool.connect();try{await client.query('BEGIN');for(const k of target){await client.query('UPDATE keyword_opd SET active=false,updated_at=now() WHERE keyword_id=$1 AND active=true',[k.id]);if(p.data.primaryOpdId)await client.query(`INSERT INTO keyword_opd(keyword_id,opd_id,weight,active,routing_role) VALUES($1,$2,1,true,'PRIMARY') ON CONFLICT(keyword_id,opd_id) DO UPDATE SET active=true,routing_role='PRIMARY',updated_at=now()`,[k.id,p.data.primaryOpdId]);for(const oid of support)await client.query(`INSERT INTO keyword_opd(keyword_id,opd_id,weight,active,routing_role) VALUES($1,$2,1,true,'SUPPORTING') ON CONFLICT(keyword_id,opd_id) DO UPDATE SET active=true,routing_role='SUPPORTING',updated_at=now()`,[k.id,oid])}await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'MASTER_BULK_ROUTING_UPDATED',$2)`,[req.masterBulkRoutingAuth!.id,{organizationId:org,...preview}]);await client.query('COMMIT');return{ok:true,dryRun:false,data:preview}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 })
}
