import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool, PoolClient } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { masterClassificationAuth?: AuthorizationContext } }

const canManage=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');
async function resolveOrganizationId(pool:Pool,ctx:AuthorizationContext){if(ctx.opdId){const r=await pool.query('SELECT organization_id FROM opd WHERE id=$1',[ctx.opdId]);if(r.rows[0]?.organization_id)return Number(r.rows[0].organization_id);}const r=await pool.query('SELECT id FROM organizations WHERE active=true ORDER BY id LIMIT 2');return r.rowCount===1?Number(r.rows[0].id):0;}
async function audit(client:Pool|PoolClient,userId:string,action:string,metadata:any){await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,$2,$3)`,[userId,action,metadata]);}

export async function registerMasterClassificationEditorRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.masterClassificationAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const manager=async(request:FastifyRequest,reply:any)=>{await auth(request,reply);if(reply.sent)return;const ctx=request.masterClassificationAuth!;if(!canManage(ctx))return reply.code(403).send({error:'HUMAS_OR_SUPER_ADMIN_REQUIRED'});};
 const org=async(request:FastifyRequest,reply:any)=>{const id=await resolveOrganizationId(pool,request.masterClassificationAuth!);if(!id){reply.code(409).send({error:'ORGANIZATION_UNRESOLVED'});return 0;}return id;};

 app.get('/api/admin/master-classification/options',{preHandler:auth},async(request,reply)=>{const organizationId=await org(request,reply);if(!organizationId)return;const opds=(await pool.query(`SELECT id,code,name,opd_group,active FROM opd WHERE organization_id=$1 ORDER BY active DESC,opd_group,name`,[organizationId])).rows;return{data:{opds,opdGroups:['DINAS','BADAN','SETDA','LAINNYA']}};});

 app.patch('/api/admin/master-classification/sectors/:id',{preHandler:manager},async(request,reply)=>{const organizationId=await org(request,reply);if(!organizationId)return;const id=Number((request.params as any).id);const p=z.object({name:z.string().trim().min(3).max(160).optional(),description:z.string().trim().max(1000).nullable().optional(),sortOrder:z.number().int().min(0).max(9999).optional(),active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!Number.isInteger(id)||id<=0||!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query(`SELECT * FROM classification_sectors WHERE id=$1 AND organization_id=$2`,[id,organizationId])).rows[0];if(!current)return reply.code(404).send({error:'SECTOR_NOT_FOUND'});const row=(await pool.query(`UPDATE classification_sectors SET name=$3,description=$4,sort_order=$5,active=$6,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *`,[id,organizationId,p.data.name??current.name,p.data.description===undefined?current.description:p.data.description,p.data.sortOrder??current.sort_order,p.data.active??current.active])).rows[0];await audit(pool,request.masterClassificationAuth!.id,'MASTER_SECTOR_UPDATED',{organizationId,sectorId:id,changes:p.data});return{ok:true,data:row};});

 app.patch('/api/admin/master-classification/taxonomies/:id',{preHandler:manager},async(request,reply)=>{const organizationId=await org(request,reply);if(!organizationId)return;const id=Number((request.params as any).id);const p=z.object({name:z.string().trim().min(3).max(160).optional(),description:z.string().trim().max(1000).nullable().optional(),sortOrder:z.number().int().min(0).max(9999).optional(),active:z.boolean().optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!Number.isInteger(id)||id<=0||!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query(`SELECT * FROM taxonomy_categories WHERE id=$1 AND organization_id=$2 AND sector_id IS NOT NULL`,[id,organizationId])).rows[0];if(!current)return reply.code(404).send({error:'MASTER_TAXONOMY_NOT_FOUND'});const row=(await pool.query(`UPDATE taxonomy_categories SET name=$3,description=$4,sort_order=$5,active=$6,updated_at=now() WHERE id=$1 AND organization_id=$2 RETURNING *`,[id,organizationId,p.data.name??current.name,p.data.description===undefined?current.description:p.data.description,p.data.sortOrder??current.sort_order,p.data.active??current.active])).rows[0];await audit(pool,request.masterClassificationAuth!.id,'MASTER_TAXONOMY_UPDATED',{organizationId,taxonomyId:id,changes:p.data});return{ok:true,data:row};});

 app.patch('/api/admin/master-classification/keywords/:id',{preHandler:manager},async(request,reply)=>{const organizationId=await org(request,reply);if(!organizationId)return;const id=Number((request.params as any).id);const p=z.object({keyword:z.string().trim().min(2).max(500).optional(),active:z.boolean().optional(),weight:z.number().min(0.01).max(10).optional()}).refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!Number.isInteger(id)||id<=0||!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query(`SELECT k.*,kt.category_id,kt.weight FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id WHERE k.id=$1 AND k.organization_id=$2 AND kt.active=true LIMIT 1`,[id,organizationId])).rows[0];if(!current)return reply.code(404).send({error:'MASTER_KEYWORD_NOT_FOUND'});const client=await pool.connect();try{await client.query('BEGIN');if(p.data.keyword!==undefined)await client.query(`UPDATE keywords SET keyword=$2,normalized_keyword=lower(regexp_replace(trim($2),'\\s+',' ','g')),updated_at=now() WHERE id=$1`,[id,p.data.keyword]);if(p.data.active!==undefined)await client.query(`UPDATE keywords SET active=$2,updated_at=now() WHERE id=$1`,[id,p.data.active]);if(p.data.weight!==undefined)await client.query(`UPDATE keyword_taxonomy SET weight=$3,updated_at=now() WHERE keyword_id=$1 AND category_id=$2`,[id,current.category_id,p.data.weight]);await audit(client,request.masterClassificationAuth!.id,'MASTER_KEYWORD_UPDATED',{organizationId,keywordId:id,changes:p.data});await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}return{ok:true};});

 app.put('/api/admin/master-classification/keywords/:id/routing',{preHandler:manager},async(request,reply)=>{const organizationId=await org(request,reply);if(!organizationId)return;const keywordId=Number((request.params as any).id);const p=z.object({primaryOpdId:z.number().int().positive().nullable(),supportingOpdIds:z.array(z.number().int().positive()).max(3).default([])}).safeParse(request.body);if(!Number.isInteger(keywordId)||keywordId<=0||!p.success)return reply.code(400).send({error:'INVALID_REQUEST'});const supporting=[...new Set(p.data.supportingOpdIds)];if(supporting.length!==p.data.supportingOpdIds.length||supporting.length>3||p.data.primaryOpdId!==null&&supporting.includes(p.data.primaryOpdId))return reply.code(400).send({error:'INVALID_ROUTING_SELECTION'});const keyword=(await pool.query(`SELECT k.id FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id JOIN taxonomy_categories t ON t.id=kt.category_id WHERE k.id=$1 AND k.organization_id=$2 AND t.organization_id=$2 AND t.sector_id IS NOT NULL LIMIT 1`,[keywordId,organizationId])).rows[0];if(!keyword)return reply.code(404).send({error:'MASTER_KEYWORD_NOT_FOUND'});const ids=[...(p.data.primaryOpdId?[p.data.primaryOpdId]:[]),...supporting];if(ids.length){const valid=(await pool.query(`SELECT id FROM opd WHERE organization_id=$1 AND active=true AND id=ANY($2::bigint[])`,[organizationId,ids])).rows.map((r:any)=>Number(r.id));if(valid.length!==ids.length)return reply.code(400).send({error:'INVALID_OR_INACTIVE_OPD'});}const client=await pool.connect();try{await client.query('BEGIN');await client.query(`UPDATE keyword_opd SET active=false,updated_at=now() WHERE keyword_id=$1 AND active=true`,[keywordId]);if(p.data.primaryOpdId)await client.query(`INSERT INTO keyword_opd(keyword_id,opd_id,weight,active,routing_role) VALUES($1,$2,1,true,'PRIMARY') ON CONFLICT(keyword_id,opd_id) DO UPDATE SET active=true,routing_role='PRIMARY',updated_at=now()`,[keywordId,p.data.primaryOpdId]);for(const opdId of supporting)await client.query(`INSERT INTO keyword_opd(keyword_id,opd_id,weight,active,routing_role) VALUES($1,$2,1,true,'SUPPORTING') ON CONFLICT(keyword_id,opd_id) DO UPDATE SET active=true,routing_role='SUPPORTING',updated_at=now()`,[keywordId,opdId]);await audit(client,request.masterClassificationAuth!.id,'MASTER_KEYWORD_ROUTING_UPDATED',{organizationId,keywordId,primaryOpdId:p.data.primaryOpdId,supportingOpdIds:supporting});await client.query('COMMIT');}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}return{ok:true,data:{keywordId,primaryOpdId:p.data.primaryOpdId,supportingOpdIds:supporting}};});
}
