import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import nodemailer from 'nodemailer';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { decryptIntegrationCredential, encryptIntegrationCredential, integrationCredentialHint } from './integration-credentials.js';

declare module 'fastify' { interface FastifyRequest { notificationAdminAuth?: AuthorizationContext } }

const channelCode=z.enum(['EMAIL','TELEGRAM','WHATSAPP']);
const statusInput=z.object({status:z.enum(['INACTIVE','ACTIVE'])});
const templateInput=z.object({titleTemplate:z.string().trim().min(3).max(250),bodyTemplate:z.string().trim().min(3).max(4000),enabled:z.boolean()});
const emailConfig=z.object({host:z.string().trim().min(1).max(255),port:z.coerce.number().int().min(1).max(65535),username:z.string().trim().max(255).default(''),password:z.string().min(1).max(1000).optional(),fromName:z.string().trim().min(1).max(200),fromEmail:z.string().email().max(255),secure:z.boolean().default(true)});
const telegramConfig=z.object({botUsername:z.string().trim().min(3).max(100),botToken:z.string().min(10).max(1000).optional(),webhookSecret:z.string().min(8).max(1000).optional()});

export async function registerNotificationAdminRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active||!(ctx.roles.includes('super_admin')||ctx.legacyRole==='admin'))return reply.code(403).send({error:'ADMIN_REQUIRED'});request.notificationAdminAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 app.get('/api/admin/notifications/channels',{preHandler:auth},async()=>({data:(await pool.query(`SELECT id,code,name,status,settings,credential_hint,last_test_at,last_test_status,last_error,updated_at FROM notification_channels ORDER BY CASE code WHEN 'EMAIL' THEN 1 WHEN 'TELEGRAM' THEN 2 ELSE 3 END`)).rows}));
 app.get('/api/admin/notifications/templates',{preHandler:auth},async()=>({data:(await pool.query('SELECT id,event_type,title_template,body_template,enabled,channel_overrides,updated_at FROM notification_templates ORDER BY id')).rows}));
 app.get('/api/admin/notifications/deliveries',{preHandler:auth},async()=>({data:(await pool.query(`SELECT d.id,d.event_type,d.channel,d.status,d.destination_hint,d.attempt_count,d.last_error,d.sent_at,d.created_at,u.email FROM notification_deliveries d LEFT JOIN users u ON u.id=d.user_id ORDER BY d.created_at DESC LIMIT 100`)).rows}));
 app.put('/api/admin/notifications/channels/EMAIL/config',{preHandler:auth},async(request,reply)=>{const p=emailConfig.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'INVALID_EMAIL_CONFIG'});const ctx=request.notificationAdminAuth!,current=(await pool.query(`SELECT credential_ciphertext FROM notification_channels WHERE code='EMAIL'`)).rows[0];if(!p.data.password&&!current?.credential_ciphertext)return reply.code(400).send({error:'SMTP_PASSWORD_REQUIRED'});const secret=p.data.password?encryptIntegrationCredential(JSON.stringify({password:p.data.password})):current.credential_ciphertext;const hint=p.data.password?integrationCredentialHint(p.data.password):undefined;await pool.query(`UPDATE notification_channels SET settings=$1::jsonb,credential_ciphertext=$2,credential_hint=COALESCE($3,credential_hint),status='INACTIVE',last_test_status=NULL,last_error=NULL,updated_by=$4,updated_at=NOW() WHERE code='EMAIL'`,[JSON.stringify({host:p.data.host,port:p.data.port,username:p.data.username,fromName:p.data.fromName,fromEmail:p.data.fromEmail,secure:p.data.secure}),secret,hint,ctx.id]);return{ok:true};});
 app.put('/api/admin/notifications/channels/TELEGRAM/config',{preHandler:auth},async(request,reply)=>{const p=telegramConfig.safeParse(request.body);if(!p.success)return reply.code(400).send({error:'INVALID_TELEGRAM_CONFIG'});const ctx=request.notificationAdminAuth!,current=(await pool.query(`SELECT credential_ciphertext FROM notification_channels WHERE code='TELEGRAM'`)).rows[0];if(!p.data.botToken&&!current?.credential_ciphertext)return reply.code(400).send({error:'BOT_TOKEN_REQUIRED'});const secret=p.data.botToken?encryptIntegrationCredential(JSON.stringify({botToken:p.data.botToken,webhookSecret:p.data.webhookSecret||''})):current.credential_ciphertext;const hint=p.data.botToken?integrationCredentialHint(p.data.botToken):undefined;await pool.query(`UPDATE notification_channels SET settings=$1::jsonb,credential_ciphertext=$2,credential_hint=COALESCE($3,credential_hint),status='INACTIVE',last_test_status=NULL,last_error=NULL,updated_by=$4,updated_at=NOW() WHERE code='TELEGRAM'`,[JSON.stringify({botUsername:p.data.botUsername}),secret,hint,ctx.id]);return{ok:true};});
 app.post('/api/admin/notifications/channels/EMAIL/test',{preHandler:auth},async(_request,reply)=>{const row=(await pool.query(`SELECT credential_ciphertext,settings FROM notification_channels WHERE code='EMAIL' LIMIT 1`)).rows[0];if(!row?.credential_ciphertext)return reply.code(409).send({error:'EMAIL_NOT_CONFIGURED'});let password='';try{const parsed=JSON.parse(decryptIntegrationCredential(row.credential_ciphertext));password=String(parsed.password||'');}catch{await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error='Credential SMTP tidak dapat dibaca.',updated_at=NOW() WHERE code='EMAIL'`);return reply.code(500).send({error:'EMAIL_CREDENTIAL_INVALID'});}const s=row.settings||{};if(!s.host||!s.port||!password)return reply.code(409).send({error:'EMAIL_NOT_CONFIGURED'});try{const transport=nodemailer.createTransport({host:String(s.host),port:Number(s.port),secure:Boolean(s.secure),auth:s.username?{user:String(s.username),pass:password}:undefined,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:10000});await transport.verify();transport.close();await pool.query(`UPDATE notification_channels SET status='READY',last_test_at=NOW(),last_test_status='SUCCESS',last_error=NULL,updated_at=NOW() WHERE code='EMAIL'`);return{ok:true,data:{host:String(s.host),port:Number(s.port)}};}catch(error:any){const raw=String(error?.message||error?.code||'SMTP connection failed'),detail=raw.replace(/(pass(word)?|auth)=?[^ ]*/gi,'credential').slice(0,300);await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error=$1,updated_at=NOW() WHERE code='EMAIL'`,[detail]);return reply.code(502).send({error:'EMAIL_CONNECTION_FAILED',detail});}});
 app.post('/api/admin/notifications/channels/EMAIL/send-test',{preHandler:auth},async(request,reply)=>{const input=z.object({to:z.string().trim().email().max(255)}).safeParse(request.body);if(!input.success)return reply.code(400).send({error:'INVALID_TEST_EMAIL'});const row=(await pool.query(`SELECT credential_ciphertext,settings,last_test_status FROM notification_channels WHERE code='EMAIL' LIMIT 1`)).rows[0];if(!row?.credential_ciphertext)return reply.code(409).send({error:'EMAIL_NOT_CONFIGURED'});if(row.last_test_status!=='SUCCESS')return reply.code(409).send({error:'EMAIL_CONNECTION_TEST_REQUIRED'});let password='';try{password=String(JSON.parse(decryptIntegrationCredential(row.credential_ciphertext)).password||'');}catch{return reply.code(500).send({error:'EMAIL_CREDENTIAL_INVALID'});}const s=row.settings||{};if(!s.host||!s.port||!s.fromEmail||!password)return reply.code(409).send({error:'EMAIL_NOT_CONFIGURED'});try{const transport=nodemailer.createTransport({host:String(s.host),port:Number(s.port),secure:Boolean(s.secure),auth:s.username?{user:String(s.username),pass:password}:undefined,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000});const info=await transport.sendMail({from:{name:String(s.fromName||'Media Intelligence Pemko Batam'),address:String(s.fromEmail)},to:input.data.to,subject:'Pengujian Email — Media Intelligence Pemko Batam',text:'Ini adalah email pengujian Notification Gateway Media Intelligence Pemko Batam. Jika email ini diterima, konfigurasi SMTP berhasil mengirim pesan.',html:'<p>Ini adalah <strong>email pengujian</strong> Notification Gateway Media Intelligence Pemko Batam.</p><p>Jika email ini diterima, konfigurasi SMTP berhasil mengirim pesan.</p>'});transport.close();return{ok:true,data:{accepted:Array.isArray(info.accepted)?info.accepted.map(String):[],rejected:Array.isArray(info.rejected)?info.rejected.map(String):[],messageId:info.messageId||null}};}catch(error:any){const detail=String(error?.message||error?.code||'SMTP send failed').replace(/(pass(word)?|auth)=?[^ ]*/gi,'credential').slice(0,300);return reply.code(502).send({error:'EMAIL_TEST_SEND_FAILED',detail});}});
 app.post('/api/admin/notifications/channels/TELEGRAM/test',{preHandler:auth},async(_request,reply)=>{const row=(await pool.query(`SELECT credential_ciphertext,settings FROM notification_channels WHERE code='TELEGRAM' LIMIT 1`)).rows[0];if(!row?.credential_ciphertext)return reply.code(409).send({error:'TELEGRAM_NOT_CONFIGURED'});let botToken='';try{const parsed=JSON.parse(decryptIntegrationCredential(row.credential_ciphertext));botToken=String(parsed.botToken||'');}catch{await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error='Credential Telegram tidak dapat dibaca.',updated_at=NOW() WHERE code='TELEGRAM'`);return reply.code(500).send({error:'TELEGRAM_CREDENTIAL_INVALID'});}if(!botToken)return reply.code(409).send({error:'BOT_TOKEN_REQUIRED'});try{const response=await fetch('https://api.telegram.org/bot'+encodeURIComponent(botToken)+'/getMe',{signal:AbortSignal.timeout(10000)});const data:any=await response.json().catch(()=>null);if(!response.ok||!data?.ok){const detail=String(data?.description||('HTTP '+response.status)).slice(0,300);await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error=$1,updated_at=NOW() WHERE code='TELEGRAM'`,[detail]);return reply.code(502).send({error:'TELEGRAM_CONNECTION_FAILED',detail});}const configured=String(row.settings?.botUsername||'').replace(/^@/,'').toLowerCase(),actual=String(data.result?.username||'').toLowerCase();if(configured&&actual&&configured!==actual){const detail='Bot username tidak cocok dengan token Telegram.';await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error=$1,updated_at=NOW() WHERE code='TELEGRAM'`,[detail]);return reply.code(409).send({error:'TELEGRAM_BOT_USERNAME_MISMATCH',detail});}await pool.query(`UPDATE notification_channels SET status='READY',last_test_at=NOW(),last_test_status='SUCCESS',last_error=NULL,settings=jsonb_set(COALESCE(settings,'{}'::jsonb),'{botDisplayName}',to_jsonb($1::text),true),updated_at=NOW() WHERE code='TELEGRAM'`,[String(data.result?.first_name||data.result?.username||'Telegram Bot')]);return{ok:true,data:{username:data.result?.username||null,displayName:data.result?.first_name||null}};}catch(error:any){const detail=String(error?.message||'Telegram connection failed').slice(0,300);await pool.query(`UPDATE notification_channels SET status='INACTIVE',last_test_at=NOW(),last_test_status='FAILED',last_error=$1,updated_at=NOW() WHERE code='TELEGRAM'`,[detail]);return reply.code(502).send({error:'TELEGRAM_CONNECTION_FAILED',detail});}});
 app.post('/api/admin/notifications/channels/TELEGRAM/webhook',{preHandler:auth},async(request,reply)=>{const row=(await pool.query(`SELECT credential_ciphertext,settings,last_test_status FROM notification_channels WHERE code='TELEGRAM' LIMIT 1`)).rows[0];if(!row?.credential_ciphertext)return reply.code(409).send({error:'TELEGRAM_NOT_CONFIGURED'});if(row.last_test_status!=='SUCCESS')return reply.code(409).send({error:'TELEGRAM_CONNECTION_TEST_REQUIRED'});let botToken='',webhookSecret='';try{const parsed=JSON.parse(decryptIntegrationCredential(row.credential_ciphertext));botToken=String(parsed.botToken||'');webhookSecret=String(parsed.webhookSecret||'');}catch{return reply.code(500).send({error:'TELEGRAM_CREDENTIAL_INVALID'});}if(!botToken||!webhookSecret)return reply.code(409).send({error:'TELEGRAM_WEBHOOK_SECRET_REQUIRED'});const forwarded=String(request.headers['x-forwarded-proto']||'').split(',')[0].trim(),protocol=forwarded||request.protocol||'https',host=String(request.headers['x-forwarded-host']||request.headers.host||'').split(',')[0].trim();if(!host)return reply.code(400).send({error:'WEBHOOK_HOST_UNAVAILABLE'});const webhookUrl=protocol+'://'+host+'/api/notifications/telegram/webhook';try{const response=await fetch('https://api.telegram.org/bot'+encodeURIComponent(botToken)+'/setWebhook',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:webhookUrl,secret_token:webhookSecret,allowed_updates:['message'],drop_pending_updates:false}),signal:AbortSignal.timeout(10000)});const data:any=await response.json().catch(()=>null);if(!response.ok||!data?.ok)return reply.code(502).send({error:'TELEGRAM_WEBHOOK_FAILED',detail:String(data?.description||('HTTP '+response.status)).slice(0,300)});await pool.query(`UPDATE notification_channels SET settings=jsonb_set(jsonb_set(COALESCE(settings,'{}'::jsonb),'{webhookConfigured}', 'true'::jsonb,true),'{webhookUrl}',to_jsonb($1::text),true),updated_by=$2,updated_at=NOW() WHERE code='TELEGRAM'`,[webhookUrl,request.notificationAdminAuth!.id]);return{ok:true,data:{webhookUrl,description:data.description||null}};}catch(error:any){return reply.code(502).send({error:'TELEGRAM_WEBHOOK_FAILED',detail:String(error?.message||'Telegram webhook failed').slice(0,300)});}});
 app.patch('/api/admin/notifications/channels/:code/status',{preHandler:auth},async(request,reply)=>{const code=channelCode.safeParse((request.params as any).code),body=statusInput.safeParse(request.body);if(!code.success||!body.success)return reply.code(400).send({error:'INVALID_CHANNEL_STATUS'});const row=(await pool.query('SELECT last_test_status FROM notification_channels WHERE code=$1',[code.data])).rows[0];if(!row)return reply.code(404).send({error:'CHANNEL_NOT_FOUND'});if(body.data.status==='ACTIVE'&&row.last_test_status!=='SUCCESS')return reply.code(409).send({error:'CHANNEL_TEST_REQUIRED'});await pool.query('UPDATE notification_channels SET status=$1,updated_by=$2,updated_at=NOW() WHERE code=$3',[body.data.status,request.notificationAdminAuth!.id,code.data]);return{ok:true};});
 app.patch('/api/admin/notifications/templates/:id',{preHandler:auth},async(request,reply)=>{const id=Number((request.params as any).id),p=templateInput.safeParse(request.body);if(!Number.isInteger(id)||id<=0||!p.success)return reply.code(400).send({error:'INVALID_TEMPLATE'});const row=(await pool.query('UPDATE notification_templates SET title_template=$1,body_template=$2,enabled=$3,updated_at=NOW() WHERE id=$4 RETURNING id',[p.data.titleTemplate,p.data.bodyTemplate,p.data.enabled,id])).rows[0];if(!row)return reply.code(404).send({error:'TEMPLATE_NOT_FOUND'});return{ok:true};});
}
