import type { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { rebuildOnlineStoryClusters, clusterNewOnlineArticles } from './online-story-clustering.js';
import { detectUnifiedIssueCandidates } from './unified-candidate-issues.js';

declare module 'fastify' { interface FastifyRequest { onlineStoryAuth?: AuthorizationContext } }
const canRebuild=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');

export async function registerOnlineStoryClusterRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
  const auth=async(request:FastifyRequest,reply:FastifyReply)=>{
    const token=request.cookies.access_token;
    if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});
    try{
      const decoded=jwt.verify(token,jwtSecret) as jwt.JwtPayload;
      if(typeof decoded.sub!=='string')throw new Error('invalid');
      const ctx=await loadAuthorizationContext(pool,decoded.sub);
      if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});
      request.onlineStoryAuth=ctx;
    }catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}
  };

  app.get('/api/online/story-clusters',{preHandler:auth},async(request,reply)=>{
    const q=z.object({days:z.coerce.number().int().min(1).max(30).default(7),limit:z.coerce.number().int().min(1).max(300).default(100),multiSource:z.enum(['all','yes']).default('all')}).safeParse(request.query);
    if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});
    const params:unknown[]=[q.data.days,q.data.limit];
    const multi=q.data.multiSource==='yes'?'AND c.source_count>1':'';
    const {rows}=await pool.query(`SELECT c.id,c.canonical_title,c.representative_article_id,c.member_count,c.source_count,c.first_published_at,c.last_published_at,c.engine_version,c.origin_mode,COALESCE(json_agg(json_build_object('article_id',a.id,'title',a.title,'url',a.url,'published_at',a.published_at,'source_id',a.source_id,'source_name',ms.name,'news_classification',a.news_classification,'opd_id',a.opd_id,'opd_name',o.name,'sentiment',a.sentiment,'risk_score',a.risk_score,'risk_level',a.risk_level,'similarity_score',m.similarity_score,'similarity_type',m.similarity_type,'assignment_mode',m.assignment_mode) ORDER BY a.published_at ASC NULLS LAST,a.id ASC) FILTER(WHERE a.id IS NOT NULL),'[]'::json) publications FROM online_story_clusters c LEFT JOIN online_story_cluster_members m ON m.cluster_id=c.id LEFT JOIN articles a ON a.id=m.article_id LEFT JOIN media_sources ms ON ms.id=a.source_id LEFT JOIN opd o ON o.id=a.opd_id WHERE COALESCE(c.last_published_at,c.created_at)>=NOW()-($1::int*INTERVAL '1 day') ${multi} GROUP BY c.id ORDER BY c.last_published_at DESC NULLS LAST,c.id DESC LIMIT $2`,params);
    return{data:rows,totalCount:rows.length};
  });

  app.get('/api/online/articles/:articleId/issue-linkage',{preHandler:auth},async(request,reply)=>{
    const id=z.coerce.number().int().positive().safeParse((request.params as any).articleId);if(!id.success)return reply.code(400).send({error:'INVALID_ARTICLE_ID'});
    const article=(await pool.query(`SELECT a.id,a.title,a.summary,a.news_classification,a.opd_id,(SELECT al.action FROM audit_logs al WHERE al.action IN ('ARTICLE_CLASSIFICATION_VERIFIED','ARTICLE_CLASSIFICATION_REOPENED') AND al.metadata->>'articleId'=a.id::text ORDER BY al.created_at DESC,al.id DESC LIMIT 1) verification_action FROM articles a WHERE a.id=$1`,[id.data])).rows[0];if(!article)return reply.code(404).send({error:'ARTICLE_NOT_FOUND'});
    const links=(await pool.query(`SELECT ia.issue_id,i.title,i.status,ia.relevance_score FROM issue_articles ia JOIN issues i ON i.id=ia.issue_id WHERE ia.article_id=$1 ORDER BY ia.relevance_score DESC NULLS LAST,i.updated_at DESC`,[id.data])).rows;
    const issues=(await pool.query(`SELECT i.id,i.title,i.status,i.description,COALESCE(array_agg(DISTINCT io.opd_id) FILTER(WHERE io.opd_id IS NOT NULL),'{}') opd_ids FROM issues i LEFT JOIN issue_opd io ON io.issue_id=i.id WHERE i.status IN ('active','watch') GROUP BY i.id ORDER BY i.updated_at DESC LIMIT 100`)).rows;
    const eligible=article.news_classification==='UTAMA'&&article.verification_action==='ARTICLE_CLASSIFICATION_VERIFIED';
    const words=(v:any)=>new Set(String(v||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').split(/\\s+/).filter((x:string)=>x.length>=4));const aw=words(article.title+' '+(article.summary||''));
    const orgRow=article.opd_id?(await pool.query('SELECT organization_id FROM opd WHERE id=$1',[article.opd_id])).rows[0]:null;const organizationId=Number(orgRow?.organization_id||0);let unifiedCandidate:any=null;if(eligible&&organizationId){const unified=await detectUnifiedIssueCandidates(pool,organizationId);unifiedCandidate=unified.find((candidate:any)=>candidate.evidence?.some((e:any)=>e.sourceType==='online'&&Number(e.id)===Number(article.id)))||null;}const recommended=(unifiedCandidate?.existingIssueMatches||[]).map((m:any)=>({id:m.issueId,title:m.title,category:m.category,score:m.score,reasons:unifiedCandidate.reasons||[]}));
    const cluster=(await pool.query(`SELECT c.id,c.canonical_title,c.member_count,c.source_count FROM online_story_cluster_members m JOIN online_story_clusters c ON c.id=m.cluster_id WHERE m.article_id=$1 AND c.status='ACTIVE' ORDER BY c.updated_at DESC LIMIT 1`,[id.data])).rows[0]||null;
    return{data:{articleId:Number(article.id),eligible,eligibilityReason:eligible?'ONLINE_PRIMARY_VERIFIED':article.news_classification!=='UTAMA'?'ONLINE_REQUIRES_PRIMARY':'ONLINE_REQUIRES_VERIFICATION',links,recommended,cluster:cluster?{id:Number(cluster.id),title:cluster.canonical_title,memberCount:Number(cluster.member_count||0),sourceCount:Number(cluster.source_count||0)}:null,newCandidate:eligible&&!links.length&&!recommended.length&&unifiedCandidate?{candidateKey:unifiedCandidate.candidateKey,suggestedTitle:unifiedCandidate.suggestedTitle||cluster?.canonical_title||article.title,source:'UNIFIED_CANDIDATE_DETECTION',sourceTypes:unifiedCandidate.sourceTypes||['online'],evidenceCount:unifiedCandidate.evidenceCount||1,reason:unifiedCandidate.crossSource?`Kandidat lintas-media (${(unifiedCandidate.sourceTypes||[]).join(', ')}) dengan ${unifiedCandidate.evidenceCount||1} evidence.`:cluster?`Belum ada Issue existing yang cukup cocok. Story Cluster #${cluster.id} dapat ditinjau sebagai Kandidat Issue Baru.`:'Belum ada Issue existing yang cukup cocok. Evidence ini dapat ditinjau sebagai Kandidat Issue Baru.'}:null,availableIssues:issues.map((i:any)=>({issueId:Number(i.id),title:i.title,status:i.status}))}};
  });

  app.post('/api/online/articles/:articleId/issue-linkage',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'ISSUE_LINKAGE_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const id=z.coerce.number().int().positive().safeParse((request.params as any).articleId),body=z.object({issueId:z.coerce.number().int().positive(),reason:z.string().trim().max(1000).optional().default('')}).safeParse(request.body??{});if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const article=(await pool.query(`SELECT a.id,a.news_classification,(SELECT al.action FROM audit_logs al WHERE al.action IN ('ARTICLE_CLASSIFICATION_VERIFIED','ARTICLE_CLASSIFICATION_REOPENED') AND al.metadata->>'articleId'=a.id::text ORDER BY al.created_at DESC,al.id DESC LIMIT 1) verification_action FROM articles a WHERE a.id=$1`,[id.data])).rows[0];if(!article)return reply.code(404).send({error:'ARTICLE_NOT_FOUND'});if(article.news_classification!=='UTAMA'||article.verification_action!=='ARTICLE_CLASSIFICATION_VERIFIED')return reply.code(409).send({error:'ARTICLE_NOT_ELIGIBLE_FOR_ISSUE',reason:article.news_classification!=='UTAMA'?'ONLINE_REQUIRES_PRIMARY':'ONLINE_REQUIRES_VERIFICATION'});
    const issue=(await pool.query(`SELECT id,title FROM issues WHERE id=$1 AND status IN ('active','watch')`,[body.data.issueId])).rows[0];if(!issue)return reply.code(404).send({error:'TARGET_ISSUE_NOT_FOUND'});
    const client=await pool.connect();try{await client.query('BEGIN');await client.query(`DELETE FROM issue_articles WHERE article_id=$1 AND issue_id<>$2`,[id.data,body.data.issueId]);await client.query(`INSERT INTO issue_articles(issue_id,article_id,relevance_score) VALUES($1,$2,100) ON CONFLICT(issue_id,article_id) DO UPDATE SET relevance_score=EXCLUDED.relevance_score`,[body.data.issueId,id.data]);await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ONLINE_ISSUE_LINK_DECISION',$2)`,[(ctx as any).id??(ctx as any).userId??null,{articleId:id.data,issueId:body.data.issueId,reason:body.data.reason,decision:'LINK_EXISTING',source:'ONLINE_ARTICLE_HUMAN_GATE'}]);await client.query('COMMIT');return{ok:true,articleId:id.data,issueId:Number(issue.id),issueTitle:issue.title};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
  });

  app.get('/api/online/story-clusters/:clusterId/issue-linkage',{preHandler:auth},async(request,reply)=>{
    const id=z.coerce.number().int().positive().safeParse((request.params as any).clusterId);if(!id.success)return reply.code(400).send({error:'INVALID_CLUSTER_ID'});
    const cluster=(await pool.query(`SELECT id,canonical_title,member_count FROM online_story_clusters WHERE id=$1`,[id.data])).rows[0];if(!cluster)return reply.code(404).send({error:'CLUSTER_NOT_FOUND'});
    const members=(await pool.query(`SELECT a.id,a.title,a.news_classification,a.opd_id,(SELECT al.action FROM audit_logs al WHERE al.action IN ('ARTICLE_CLASSIFICATION_VERIFIED','ARTICLE_CLASSIFICATION_REOPENED') AND al.metadata->>'articleId'=a.id::text ORDER BY al.created_at DESC,al.id DESC LIMIT 1) verification_action FROM online_story_cluster_members m JOIN articles a ON a.id=m.article_id WHERE m.cluster_id=$1 ORDER BY a.published_at DESC NULLS LAST`,[id.data])).rows;
    const articleIds=members.map((m:any)=>Number(m.id));let links:any[]=[];if(articleIds.length)links=(await pool.query(`SELECT ia.article_id,ia.issue_id,i.title issue_title FROM issue_articles ia JOIN issues i ON i.id=ia.issue_id WHERE ia.article_id=ANY($1::bigint[])`,[articleIds])).rows;
    const eligible=members.filter((m:any)=>m.news_classification==='UTAMA'&&m.verification_action==='ARTICLE_CLASSIFICATION_VERIFIED');const eligibleIds=new Set(eligible.map((m:any)=>Number(m.id)));const counts=new Map<number,{issueId:number,title:string,count:number}>();for(const l of links){if(!eligibleIds.has(Number(l.article_id)))continue;const k=Number(l.issue_id),v=counts.get(k)||{issueId:k,title:l.issue_title,count:0};v.count++;counts.set(k,v);}const current=[...counts.values()].sort((a,b)=>b.count-a.count)[0]||null;
    const issues=(await pool.query(`SELECT id,title,status FROM issues WHERE status IN ('active','watch') ORDER BY updated_at DESC LIMIT 100`)).rows;let unifiedCandidate:any=null;if(eligible.length){const orgIds=(await pool.query(`SELECT DISTINCT o.organization_id FROM articles a JOIN opd o ON o.id=a.opd_id WHERE a.id=ANY($1::bigint[]) AND o.organization_id IS NOT NULL`,[eligible.map((m:any)=>Number(m.id))])).rows.map((r:any)=>Number(r.organization_id)).filter(Boolean);if(orgIds.length===1){const unified=await detectUnifiedIssueCandidates(pool,orgIds[0]);const eligibleSet=new Set(eligible.map((m:any)=>Number(m.id)));unifiedCandidate=unified.find((candidate:any)=>(candidate.evidence||[]).some((e:any)=>e.sourceType==='online'&&eligibleSet.has(Number(e.id))))||null;}}const recommended=(unifiedCandidate?.existingIssueMatches||[]).map((m:any)=>({id:m.issueId,title:m.title,category:m.category,score:m.score}));const newCandidate=!current&&!recommended.length&&unifiedCandidate?{candidateKey:unifiedCandidate.candidateKey,suggestedTitle:unifiedCandidate.suggestedTitle||cluster.canonical_title,sourceTypes:unifiedCandidate.sourceTypes||['online'],evidenceCount:unifiedCandidate.evidenceCount||eligible.length,reason:unifiedCandidate.crossSource?`Kandidat lintas-media (${(unifiedCandidate.sourceTypes||[]).join(', ')}) dengan ${unifiedCandidate.evidenceCount||eligible.length} evidence.`:`${eligible.length} evidence eligible dari Story Cluster ini terdeteksi pada Candidate Issue yang sama.`}:null;
    return{data:{clusterId:Number(cluster.id),title:cluster.canonical_title,total:members.length,eligible:eligible.length,ineligible:members.length-eligible.length,currentIssue:current,recommended,newCandidate,availableIssues:issues.map((i:any)=>({issueId:Number(i.id),title:i.title,status:i.status})),members:members.map((m:any)=>({articleId:Number(m.id),title:m.title,eligible:m.news_classification==='UTAMA'&&m.verification_action==='ARTICLE_CLASSIFICATION_VERIFIED',reason:m.news_classification!=='UTAMA'?'ONLINE_REQUIRES_PRIMARY':m.verification_action!=='ARTICLE_CLASSIFICATION_VERIFIED'?'ONLINE_REQUIRES_VERIFICATION':'ELIGIBLE'}))}};
  });

  app.post('/api/online/story-clusters/:clusterId/issue-linkage',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'ISSUE_LINKAGE_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).clusterId),body=z.object({issueId:z.coerce.number().int().positive(),reason:z.string().trim().max(1000).optional().default('')}).safeParse(request.body??{});if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const issue=(await pool.query(`SELECT id,title FROM issues WHERE id=$1 AND status IN ('active','watch')`,[body.data.issueId])).rows[0];if(!issue)return reply.code(404).send({error:'TARGET_ISSUE_NOT_FOUND'});
    const members=(await pool.query(`SELECT a.id FROM online_story_cluster_members m JOIN articles a ON a.id=m.article_id WHERE m.cluster_id=$1 AND a.news_classification='UTAMA' AND (SELECT al.action FROM audit_logs al WHERE al.action IN ('ARTICLE_CLASSIFICATION_VERIFIED','ARTICLE_CLASSIFICATION_REOPENED') AND al.metadata->>'articleId'=a.id::text ORDER BY al.created_at DESC,al.id DESC LIMIT 1)='ARTICLE_CLASSIFICATION_VERIFIED'`,[id.data])).rows.map((x:any)=>Number(x.id));if(!members.length)return reply.code(409).send({error:'CLUSTER_HAS_NO_ELIGIBLE_EVIDENCE'});
    const client=await pool.connect();try{await client.query('BEGIN');let linked=0;for(const articleId of members){const existing=await client.query(`SELECT issue_id FROM issue_articles WHERE article_id=$1`,[articleId]);if(existing.rows.length)continue;await client.query(`INSERT INTO issue_articles(issue_id,article_id,relevance_score) VALUES($1,$2,100) ON CONFLICT(issue_id,article_id) DO NOTHING`,[body.data.issueId,articleId]);linked++;}await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ONLINE_CLUSTER_ISSUE_LINK_DECISION',$2)`,[(ctx as any).id??(ctx as any).userId??null,{clusterId:id.data,issueId:body.data.issueId,eligibleCount:members.length,linkedCount:linked,reason:body.data.reason,decision:'LINK_EXISTING',source:'ONLINE_STORY_CLUSTER_HUMAN_GATE'}]);await client.query('COMMIT');return{ok:true,clusterId:id.data,issueId:Number(issue.id),issueTitle:issue.title,eligibleCount:members.length,linkedCount:linked,preservedExisting:members.length-linked};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
  });

  app.get('/api/online/story-clusters/regression/:articleId',{preHandler:auth},async(request,reply)=>{
    const id=z.coerce.number().int().positive().safeParse((request.params as any).articleId);
    if(!id.success)return reply.code(400).send({error:'INVALID_ARTICLE_ID'});
    const row=(await pool.query(`SELECT c.id cluster_id,c.canonical_title,c.member_count,c.source_count,c.engine_version,json_agg(json_build_object('article_id',a.id,'title',a.title,'source_name',ms.name,'published_at',a.published_at,'similarity_score',m.similarity_score,'similarity_type',m.similarity_type) ORDER BY a.published_at,a.id) members FROM online_story_cluster_members x JOIN online_story_clusters c ON c.id=x.cluster_id JOIN online_story_cluster_members m ON m.cluster_id=c.id JOIN articles a ON a.id=m.article_id LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE x.article_id=$1 GROUP BY c.id`,[id.data])).rows[0];
    if(!row)return reply.code(404).send({error:'ARTICLE_NOT_CLUSTERED'});
    return{data:row};
  });

  app.post('/api/online/story-clusters/manual/move',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'STORY_CLUSTER_MANUAL_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const body=z.object({articleId:z.coerce.number().int().positive(),clusterId:z.coerce.number().int().positive()}).safeParse(request.body??{});if(!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const client=await pool.connect();try{await client.query('BEGIN');const cluster=(await client.query('SELECT id FROM online_story_clusters WHERE id=$1',[body.data.clusterId])).rows[0];if(!cluster){await client.query('ROLLBACK');return reply.code(404).send({error:'CLUSTER_NOT_FOUND'});}await client.query('DELETE FROM online_story_cluster_members WHERE article_id=$1',[body.data.articleId]);await client.query(`INSERT INTO online_story_cluster_members(cluster_id,article_id,similarity_score,similarity_type,matched_by,assignment_mode) VALUES($1,$2,1,'similar','manual','MANUAL')`,[body.data.clusterId,body.data.articleId]);await client.query('UPDATE articles SET story_cluster_manual_excluded=false WHERE id=$1',[body.data.articleId]);await client.query(`UPDATE online_story_clusters c SET member_count=x.member_count,source_count=x.source_count,first_published_at=x.first_published_at,last_published_at=x.last_published_at,updated_at=NOW() FROM (SELECT m.cluster_id,COUNT(*)::int member_count,COUNT(DISTINCT a.source_id)::int source_count,MIN(COALESCE(a.published_at,a.created_at)) first_published_at,MAX(COALESCE(a.published_at,a.created_at)) last_published_at FROM online_story_cluster_members m JOIN articles a ON a.id=m.article_id WHERE m.cluster_id=$1 GROUP BY m.cluster_id)x WHERE c.id=x.cluster_id`,[body.data.clusterId]);await client.query('COMMIT');return{ok:true};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
  });

  app.post('/api/online/story-clusters/manual/remove',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'STORY_CLUSTER_MANUAL_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const body=z.object({articleId:z.coerce.number().int().positive()}).safeParse(request.body??{});if(!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const old=(await pool.query('SELECT cluster_id FROM online_story_cluster_members WHERE article_id=$1',[body.data.articleId])).rows[0];await pool.query('DELETE FROM online_story_cluster_members WHERE article_id=$1',[body.data.articleId]);await pool.query('UPDATE articles SET story_cluster_manual_excluded=true WHERE id=$1',[body.data.articleId]);if(old?.cluster_id){await pool.query(`UPDATE online_story_clusters c SET member_count=x.member_count,source_count=x.source_count,representative_article_id=x.representative_article_id,first_published_at=x.first_published_at,last_published_at=x.last_published_at,updated_at=NOW() FROM (SELECT m.cluster_id,COUNT(*)::int member_count,COUNT(DISTINCT a.source_id)::int source_count,(ARRAY_AGG(a.id ORDER BY COALESCE(a.published_at,a.created_at),a.id))[1] representative_article_id,MIN(COALESCE(a.published_at,a.created_at)) first_published_at,MAX(COALESCE(a.published_at,a.created_at)) last_published_at FROM online_story_cluster_members m JOIN articles a ON a.id=m.article_id WHERE m.cluster_id=$1 GROUP BY m.cluster_id)x WHERE c.id=x.cluster_id`,[old.cluster_id]);await pool.query(`DELETE FROM online_story_clusters c WHERE c.id=$1 AND c.origin_mode='SYSTEM' AND NOT EXISTS(SELECT 1 FROM online_story_cluster_members m WHERE m.cluster_id=c.id)`,[old.cluster_id]);await pool.query(`UPDATE online_story_clusters c SET status='ARCHIVED',updated_at=NOW() WHERE c.id=$1 AND c.origin_mode='MANUAL' AND NOT EXISTS(SELECT 1 FROM online_story_cluster_members m WHERE m.cluster_id=c.id)`,[old.cluster_id]);}return{ok:true};
  });

  app.post('/api/online/story-clusters/manual/create',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'STORY_CLUSTER_MANUAL_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const body=z.object({name:z.string().trim().min(2).max(120),articleId:z.coerce.number().int().positive()}).safeParse(request.body??{});if(!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const client=await pool.connect();try{await client.query('BEGIN');const a=(await client.query('SELECT id,source_id,COALESCE(published_at,created_at) published_at FROM articles WHERE id=$1',[body.data.articleId])).rows[0];if(!a){await client.query('ROLLBACK');return reply.code(404).send({error:'ARTICLE_NOT_FOUND'});}await client.query('DELETE FROM online_story_cluster_members WHERE article_id=$1',[body.data.articleId]);const ins=await client.query(`INSERT INTO online_story_clusters(canonical_title,representative_article_id,member_count,source_count,first_published_at,last_published_at,engine_version,origin_mode,updated_at) VALUES($1,$2,1,1,$3,$3,'manual','MANUAL',NOW()) RETURNING id`,[body.data.name,body.data.articleId,a.published_at]);await client.query(`INSERT INTO online_story_cluster_members(cluster_id,article_id,similarity_score,similarity_type,matched_by,assignment_mode) VALUES($1,$2,1,'representative','manual','MANUAL')`,[ins.rows[0].id,body.data.articleId]);await client.query('UPDATE articles SET story_cluster_manual_excluded=false WHERE id=$1',[body.data.articleId]);await client.query('COMMIT');return{ok:true,clusterId:ins.rows[0].id};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
  });

  app.post('/api/online/story-clusters/incremental',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;if(!canRebuild(ctx))return reply.code(403).send({error:'STORY_CLUSTER_UPDATE_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const body=z.object({days:z.coerce.number().int().min(1).max(30).default(7),limit:z.coerce.number().int().min(1).max(500).default(200)}).safeParse(request.body??{});if(!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const result=await clusterNewOnlineArticles(pool,body.data.days,body.data.limit);return{ok:true,result};
  });

  app.post('/api/online/story-clusters/rebuild',{preHandler:auth},async(request,reply)=>{
    const ctx=request.onlineStoryAuth!;
    if(!canRebuild(ctx))return reply.code(403).send({error:'STORY_CLUSTER_REBUILD_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const body=z.object({days:z.coerce.number().int().min(1).max(30).default(7),limit:z.coerce.number().int().min(2).max(2000).default(1000)}).safeParse(request.body??{});
    if(!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});
    const result=await rebuildOnlineStoryClusters(pool,body.data.days,body.data.limit);
    await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ONLINE_STORY_CLUSTERS_REBUILT',$2)`,[(ctx as any).userId??null,{...result,days:body.data.days,limit:body.data.limit}]).catch(()=>undefined);
    return{ok:true,result};
  });
}
