import type { Pool, PoolClient } from 'pg';

type Mention={id:string;owned_account_id:string|null;account_name:string|null;ownership_level:'pemko'|'opd'|null;is_primary_source:boolean|null;source_priority:number|null;title:string|null;content:string|null;published_at:string|null;captured_at:string|null};
type MemberType='identical'|'adapted'|'unique';type WorkingMember={mention:Mention;score:number;type:MemberType};type WorkingCluster={representative:Mention;members:WorkingMember[]};
const STOPWORDS=new Set(['dan','yang','di','ke','dari','untuk','pada','dengan','atau','ini','itu','dalam','atas','sebagai','oleh','kota','batam','pemko','pemerintah']);
function normalize(v:string|null|undefined){return String(v??'').toLowerCase().replace(/https?:\/\/\S+/g,' ').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function tokens(v:string|null|undefined,max=420){return normalize(v).split(' ').filter(x=>x.length>2&&!STOPWORDS.has(x)).slice(0,max)}
function jaccard(a:string[],b:string[]){const A=new Set(a),B=new Set(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/(A.size+B.size-n)}
function containment(a:string[],b:string[]){const A=new Set(a),B=new Set(b);if(!A.size||!B.size)return 0;let n=0;for(const x of A)if(B.has(x))n++;return n/Math.min(A.size,B.size)}
function shingles(v:string|null|undefined,size=5,max=650){const t=tokens(v,max),out:string[]=[];for(let i=0;i<=t.length-size;i++)out.push(t.slice(i,i+size).join(' '));return out}
function dateMs(m:Mention){const n=new Date(m.published_at||m.captured_at||'').getTime();return Number.isFinite(n)?n:Number.MAX_SAFE_INTEGER}
function signals(a:Mention,b:Mention){const at=tokens(a.title,60),bt=tokens(b.title,60),ab=tokens(a.content,420),bb=tokens(b.content,420),title=jaccard(at,bt),body=jaccard(ab,bb),bodyContain=containment(ab,bb),phrase=jaccard(shingles(a.content),shingles(b.content)),phraseContain=containment(shingles(a.content),shingles(b.content));const score=Math.max(title,body*.92,bodyContain*.84,phrase,phraseContain*.90,.25*title+.75*body);return{title,body,bodyContain,phrase,phraseContain,score:Math.max(0,Math.min(1,score))}}
function classify(s:ReturnType<typeof signals>):MemberType{if(s.title>=.88||(s.body>=.88&&s.phrase>=.68)||(s.bodyContain>=.94&&s.phraseContain>=.82))return'identical';if(s.score>=.54||s.body>=.56||s.bodyContain>=.66||s.phrase>=.27||s.phraseContain>=.42)return'adapted';return'unique'}
function sourceRank(m:Mention){if(m.is_primary_source)return 0;if(m.ownership_level==='pemko')return 1;return 2}
function chooseOriginal(ms:WorkingMember[]){return ms.slice().sort((a,b)=>sourceRank(a.mention)-sourceRank(b.mention)||(Number(b.mention.source_priority)||0)-(Number(a.mention.source_priority)||0)||dateMs(a.mention)-dateMs(b.mention)||Number(a.mention.id)-Number(b.mention.id))[0].mention}
function bestSignals(m:Mention,c:WorkingCluster){let best=signals(m,c.representative);for(const x of c.members){const s=signals(m,x.mention);if(s.score>best.score)best=s}return best}
function finalize(c:WorkingCluster){const original=chooseOriginal(c.members);c.representative=original;c.members=c.members.map(m=>{if(m.mention.id===original.id)return{...m,score:1,type:'unique'};const s=bestSignals(m.mention,{representative:original,members:c.members.filter(x=>x.mention.id!==m.mention.id)});return{...m,score:s.score,type:classify(s)}})}
function mergeClusters(clusters:WorkingCluster[]){let changed=true;while(changed){changed=false;outer:for(let i=0;i<clusters.length;i++)for(let j=i+1;j<clusters.length;j++){let best=0,kind:MemberType='unique';for(const a of clusters[i].members)for(const b of clusters[j].members){const s=signals(a.mention,b.mention),k=classify(s);if(s.score>best){best=s.score;kind=k}}if(kind!=='unique'){clusters[i].members.push(...clusters[j].members);clusters.splice(j,1);changed=true;break outer}}}return clusters}
async function persist(client:PoolClient,clusters:WorkingCluster[]){await client.query('DELETE FROM owned_content_cluster_members');await client.query('DELETE FROM owned_content_clusters');for(const c of clusters){finalize(c);const times=c.members.map(x=>x.mention.published_at).filter(Boolean).map(String).map(x=>new Date(x)).filter(x=>!Number.isNaN(x.getTime())).sort((a,b)=>a.getTime()-b.getTime()),accounts=new Set(c.members.map(x=>x.mention.owned_account_id).filter(Boolean));const{rows}=await client.query(`INSERT INTO owned_content_clusters(canonical_title,representative_mention_id,member_count,channel_count,first_published_at,last_published_at) VALUES($1,$2,$3,$4,$5,$6) RETURNING id`,[c.representative.title,c.representative.id,c.members.length,accounts.size,times[0]?.toISOString()||null,times.at(-1)?.toISOString()||null]);for(const m of c.members)await client.query(`INSERT INTO owned_content_cluster_members(cluster_id,mention_id,similarity_score,similarity_type,matched_by) VALUES($1,$2,$3,$4,'rule-v1')`,[rows[0].id,m.mention.id,m.score,m.type])}}
export async function rebuildOwnedContentClusters(pool:Pool){const{rows}=await pool.query<Mention>(`SELECT sm.id,sm.owned_account_id,osa.account_name,osa.ownership_level,osa.is_primary_source,osa.source_priority,sm.title,sm.content,sm.published_at,sm.captured_at FROM social_mentions sm LEFT JOIN owned_social_accounts osa ON osa.id=sm.owned_account_id WHERE sm.source_kind='owned' ORDER BY sm.published_at ASC NULLS LAST,sm.captured_at ASC,sm.id ASC LIMIT 1000`);let clusters:WorkingCluster[]=[];for(const m of rows){let best:WorkingCluster|null=null,bs:ReturnType<typeof signals>|null=null;for(const c of clusters){const s=bestSignals(m,c);if(!bs||s.score>bs.score){best=c;bs=s}}const kind=bs?classify(bs):'unique';if(best&&bs&&kind!=='unique')best.members.push({mention:m,score:bs.score,type:kind});else clusters.push({representative:m,members:[{mention:m,score:1,type:'unique'}]})}clusters=mergeClusters(clusters);const client=await pool.connect();try{await client.query('BEGIN');await persist(client,clusters);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}return{mentions:rows.length,clusters:clusters.length,republished:clusters.filter(c=>c.members.length>1).length,maxChannels:clusters.reduce((n,c)=>Math.max(n,new Set(c.members.map(x=>x.mention.owned_account_id).filter(Boolean)).size),0),engine:'owned-content-rule-v1.3-source-hierarchy'}}
