import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { hasPermission, loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { rebuildOwnedContentClusters } from './owned-content-clustering.js';
import { collectOwnedWebsiteAccount } from './website-collector.js';
import { analyzeOwnedRoutingV16, lockOwnedRoutingV16, reopenOwnedRoutingV16 } from './owned-v16-adapter.js';
import { linkEligibleSocial } from './issue-monitor-matcher.js';
import { analyzeArticle as analyzeCoreArticle, parseKeywordQuery } from './media-intelligence-core.js';
import { calculateRisk } from './risk.js';

declare module 'fastify' { interface FastifyRequest { ownedClusterAuth?: AuthorizationContext } }

export async function registerOwnedContentClusteringRoutes(app: FastifyInstance, pool: Pool, jwtSecret: string) {
  const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const decoded=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof decoded.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,decoded.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.ownedClusterAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
  const requireWrite=async(request:FastifyRequest,reply:any)=>{const ctx=request.ownedClusterAuth!;if(!hasPermission(ctx,'intelligence.write')&&!hasPermission(ctx,'platform.admin'))return reply.code(403).send({error:'FORBIDDEN'});};
  const canReadAll=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas')||ctx.roles.includes('executive')||hasPermission(ctx,'platform.admin')||hasPermission(ctx,'intelligence.read.all');
  const canCurate=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');
  const requireCurator=async(request:FastifyRequest,reply:any)=>{if(!canCurate(request.ownedClusterAuth!))return reply.code(403).send({error:'CURATION_FORBIDDEN'});};

  app.post('/api/social/owned-clusters/rebuild',{preHandler:[auth,requireWrite]},async(request)=>{const ctx=request.ownedClusterAuth!,params:unknown[]=[];let scope='';if(!canReadAll(ctx)){if(!ctx.opdId)scope=' AND 1=0';else{params.push(ctx.opdId);scope=` AND opd_id=$${params.length}`;}}const accounts=(await pool.query(`SELECT id,account_name FROM owned_social_accounts WHERE active=true AND platform='website'${scope} ORDER BY is_primary_source DESC,source_priority DESC,id ASC`,params)).rows;const settled=await Promise.allSettled(accounts.map(async account=>({ok:true as const,...await collectOwnedWebsiteAccount(pool,Number(account.id))})));const websiteSync=settled.map((entry,index)=>entry.status==='fulfilled'?entry.value:{accountId:Number(accounts[index].id),accountName:accounts[index].account_name,ok:false as const,error:entry.reason instanceof Error?entry.reason.message:String(entry.reason)});websiteSync.forEach(x=>{if(!x.ok&&'error' in x)app.log.warn({accountId:x.accountId,error:x.error},'Owned website refresh failed')});const result=await rebuildOwnedContentClusters(pool),payload={...result,websiteSync};await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_CONTENT_CLUSTER_REBUILD',$2::jsonb)`,[ctx.id,JSON.stringify(payload)]);return{data:payload};});

  app.get('/api/social/owned-curation',{preHandler:[auth,requireCurator]},async(request)=>{const q=request.query as Record<string,unknown>;const stale=(await pool.query(`SELECT id,title,content,published_at,author_name,platform,opd_id,metadata FROM social_mentions WHERE source_kind='owned' AND curation_status IN ('candidate','approved') AND COALESCE(risk_score,0)=0 LIMIT 200`)).rows;for(const item of stale){const intelligence=analyzeCoreArticle({id:item.id,title:item.title,summary:String(item.content||'').slice(0,900),content:item.content,sourceName:item.author_name||item.platform,mediaKind:'social',opdId:item.opd_id,publishedAt:item.published_at},parseKeywordQuery(''),1);const risk=calculateRisk({importance:intelligence.importanceScore,impact:intelligence.impactScore,velocity:intelligence.velocityScore,sentiment:intelligence.sentiment,sentimentScore:intelligence.sentimentScore});const locked=item.metadata?.v16Routing?.verificationStatus==='LOCKED';await pool.query(`UPDATE social_mentions SET sentiment=$2,sentiment_score=$3,importance_score=$4,influence_score=$5,risk_score=$6,risk_level=$7,metadata=jsonb_set(COALESCE(metadata,'{}'::jsonb),'{intelligence}',$8::jsonb,true),updated_at=now() WHERE id=$1 AND source_kind='owned' AND COALESCE(risk_score,0)=0`,[item.id,intelligence.sentiment,intelligence.sentimentScore,intelligence.importanceScore,intelligence.impactScore,risk.score,risk.level,JSON.stringify({...intelligence,riskLevel:risk.level,riskReasons:risk.reasons,riskStatus:locked?'FINAL':'PROVISIONAL',...(locked?{riskFinalizedAt:item.metadata?.intelligence?.riskFinalizedAt||new Date().toISOString()}: {})})]);}const status=['candidate','approved','ignored'].includes(String(q.status))?String(q.status):'candidate';const limit=Math.max(1,Math.min(200,Number(q.limit)||100));const{rows}=await pool.query(`SELECT sm.id,sm.title,sm.content,sm.canonical_url,sm.platform,sm.published_at,sm.captured_at,sm.curation_status,sm.curation_reason,sm.curated_at,sm.curated_by,sm.opd_id,sm.sentiment,sm.sentiment_score,sm.importance_score,sm.influence_score,sm.risk_score,sm.risk_level,sm.metadata->'intelligence' intelligence,sm.metadata->'v16Routing' v16_routing,o.name opd_name,osa.account_name owned_account_name FROM social_mentions sm LEFT JOIN opd o ON o.id=sm.opd_id LEFT JOIN owned_social_accounts osa ON osa.id=sm.owned_account_id WHERE sm.source_kind='owned' AND sm.curation_status=$1 ORDER BY COALESCE(sm.published_at,sm.captured_at,sm.created_at) DESC NULLS LAST,sm.id DESC LIMIT $2`,[status,limit]);return{data:rows,status};});
  app.post('/api/social/owned-curation/:id',{preHandler:[auth,requireCurator]},async(request,reply)=>{const id=z.coerce.number().int().positive().safeParse((request.params as any).id),body=z.object({status:z.enum(['candidate','approved','ignored']),reason:z.string().trim().max(1000).optional().nullable()}).safeParse(request.body);if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_REQUEST'});const ctx=request.ownedClusterAuth!;const{rows}=await pool.query(`UPDATE social_mentions SET curation_status=$2,curated_by=$3,curated_at=now(),curation_reason=$4,updated_at=now() WHERE id=$1 AND source_kind='owned' RETURNING id,title,canonical_url,curation_status,curation_reason,curated_at`,[id.data,body.data.status,ctx.id,body.data.reason??null]);if(!rows[0])return reply.code(404).send({error:'OWNED_PUBLICATION_NOT_FOUND'});const clustering=await rebuildOwnedContentClusters(pool);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_PUBLICATION_CURATED',$2::jsonb)`,[ctx.id,JSON.stringify({mentionId:id.data,status:body.data.status,reason:body.data.reason??null})]);return{data:rows[0],clustering};});

  app.post('/api/social/owned-curation-bulk',{preHandler:[auth,requireCurator]},async(request,reply)=>{const body=z.object({ids:z.array(z.coerce.number().int().positive()).min(1).max(200),status:z.enum(['candidate','approved','ignored']),reason:z.string().trim().max(1000).optional().nullable()}).safeParse(request.body);if(!body.success)return reply.code(400).send({error:'INVALID_BULK_CURATION_REQUEST',details:body.error.flatten()});const ctx=request.ownedClusterAuth!,ids=[...new Set(body.data.ids)],sourceStatuses=body.data.status==='candidate'?['approved','ignored']:['candidate'];const client=await pool.connect();let updated:any[]=[];try{await client.query('BEGIN');const result=await client.query(`UPDATE social_mentions SET curation_status=$2,curated_by=$3,curated_at=now(),curation_reason=$4,updated_at=now() WHERE id=ANY($1::bigint[]) AND source_kind='owned' AND curation_status=ANY($5::text[]) RETURNING id,title,canonical_url,curation_status,curation_reason,curated_at`,[ids,body.data.status,ctx.id,body.data.reason??null,sourceStatuses]);updated=result.rows;await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_PUBLICATION_BULK_CURATED',$2::jsonb)`,[ctx.id,JSON.stringify({requested:ids.length,updated:updated.length,mentionIds:updated.map(r=>Number(r.id)),status:body.data.status,reason:body.data.reason??null})]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}let clustering=null;try{clustering=await rebuildOwnedContentClusters(pool)}catch(clusterError){app.log.warn({err:clusterError},'Owned content clustering refresh failed after bulk curation')}return{data:{requested:ids.length,updated:updated.length,skipped:ids.length-updated.length,items:updated},clustering};});

  app.get('/api/social/owned-v16-keywords',{preHandler:[auth,requireCurator]},async(request,reply)=>{const parsed=z.object({q:z.string().trim().max(200).optional().default(''),limit:z.coerce.number().int().min(1).max(50).default(20)}).safeParse(request.query);if(!parsed.success)return reply.code(400).send({error:'INVALID_QUERY'});const term=parsed.data.q;const params:any[]=[];let filter='';if(term){params.push(`%${term}%`);filter=` AND (k.keyword ILIKE $1 OR tc.name ILIKE $1 OR o.name ILIKE $1)`;}params.push(parsed.data.limit);const{rows}=await pool.query(`SELECT DISTINCT ON(k.id) k.id,k.keyword,tc.id taxonomy_id,tc.name taxonomy_name,o.id primary_opd_id,o.name primary_opd_name,o.code primary_opd_code FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true AND tc.sector_id IS NOT NULL JOIN keyword_opd ko ON ko.keyword_id=k.id AND ko.active=true AND ko.routing_role='PRIMARY' JOIN opd o ON o.id=ko.opd_id AND o.active=true WHERE k.active=true AND k.opd_id IS NULL AND k.district_id IS NULL${filter} ORDER BY k.id,k.keyword ASC LIMIT $${params.length}`,params);return{data:rows};});

  app.post('/api/social/owned-publications/:id/v16-preview',{preHandler:[auth,requireCurator]},async(request,reply)=>{const id=z.coerce.number().int().positive().safeParse((request.params as any).id),body=z.object({manualKeywordId:z.coerce.number().int().positive().optional().nullable()}).safeParse(request.body??{});if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_OWNED_PUBLICATION_REQUEST'});const{rows}=await pool.query(`SELECT sm.id,sm.title,sm.content,sm.canonical_url,sm.curation_status,sm.owned_account_id,sm.metadata->'v16Routing' v16_routing,osa.account_name,osa.ownership_level,osa.opd_id publisher_opd_id,osa.district_id publisher_district_id FROM social_mentions sm LEFT JOIN owned_social_accounts osa ON osa.id=sm.owned_account_id WHERE sm.id=$1 AND sm.source_kind='owned' AND COALESCE(sm.curation_status,'approved')='approved' LIMIT 1`,[id.data]);const publication=rows[0];if(!publication)return reply.code(404).send({error:'APPROVED_OWNED_PUBLICATION_NOT_FOUND'});const routing=await analyzeOwnedRoutingV16(pool,{title:publication.title,content:publication.content,manualKeywordId:body.data.manualKeywordId??null});return{data:{mentionId:Number(publication.id),title:publication.title,canonicalUrl:publication.canonical_url,lockedRouting:publication.v16_routing??null,publisher:{accountId:publication.owned_account_id==null?null:Number(publication.owned_account_id),accountName:publication.account_name??null,ownershipLevel:publication.ownership_level??null,opdId:publication.publisher_opd_id==null?null:Number(publication.publisher_opd_id),districtId:publication.publisher_district_id==null?null:Number(publication.publisher_district_id)},routing}};});

  app.post('/api/social/owned-publications/:id/v16-lock',{preHandler:[auth,requireCurator]},async(request,reply)=>{const id=z.coerce.number().int().positive().safeParse((request.params as any).id),body=z.object({manualKeywordId:z.coerce.number().int().positive().optional().nullable()}).safeParse(request.body??{});if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_OWNED_PUBLICATION_REQUEST'});const publication=(await pool.query(`SELECT id,title,content,metadata->'v16Routing' v16_routing FROM social_mentions WHERE id=$1 AND source_kind='owned' AND curation_status='approved' LIMIT 1`,[id.data])).rows[0];if(!publication)return reply.code(404).send({error:'APPROVED_OWNED_PUBLICATION_NOT_FOUND'});if(publication.v16_routing?.verificationStatus==='LOCKED')return reply.code(409).send({error:'OWNED_V16_ALREADY_LOCKED'});const routing=await analyzeOwnedRoutingV16(pool,{title:publication.title,content:publication.content,manualKeywordId:body.data.manualKeywordId??null});if(routing.routingStatus!=='ROUTED'||!routing.primaryOpdId||!routing.keywordId)return reply.code(409).send({error:'OWNED_V16_ROUTING_NOT_READY_TO_LOCK',data:routing});const ctx=request.ownedClusterAuth!,client=await pool.connect();try{await client.query('BEGIN');const locked=await lockOwnedRoutingV16(client,id.data,routing,ctx.id);await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_V16_ROUTING_LOCKED',$2::jsonb)`,[ctx.id,JSON.stringify({mentionId:id.data,primaryOpdId:locked.primaryOpdId,keywordId:locked.keywordId,keywordSource:locked.keywordSource,engine:locked.engine})]);await client.query('COMMIT');let issueMonitorMatches=0;try{const evidence=(await pool.query(`SELECT published_at,title,content FROM social_mentions WHERE id=$1`,[id.data])).rows[0];if(evidence)issueMonitorMatches=(await linkEligibleSocial(pool,{mentionId:id.data,sourceKind:'owned',publishedAt:evidence.published_at,title:evidence.title,content:evidence.content,taxonomyId:locked.taxonomyId?Number(locked.taxonomyId):null})).length;}catch(e){request.log.warn({err:e,mentionId:id.data},'Issue Monitor owned linkage skipped');}return{data:{mentionId:id.data,routing:locked,issueMonitorMatches}};}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}});

  app.post('/api/social/owned-publications/:id/v16-reopen',{preHandler:[auth,requireCurator]},async(request,reply)=>{const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_OWNED_PUBLICATION_ID'});const ctx=request.ownedClusterAuth!,client=await pool.connect();try{await client.query('BEGIN');await reopenOwnedRoutingV16(client,id.data);await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_V16_ROUTING_REOPENED',$2::jsonb)`,[ctx.id,JSON.stringify({mentionId:id.data})]);await client.query('COMMIT');return{data:{mentionId:id.data,verificationStatus:'REOPENED'}};}catch(error:any){await client.query('ROLLBACK');if(String(error?.message)==='LOCKED_OWNED_V16_ROUTING_NOT_FOUND')return reply.code(409).send({error:'LOCKED_OWNED_V16_ROUTING_NOT_FOUND'});throw error}finally{client.release()}});

  app.post('/api/social/owned-amplification/:mentionId/review',{preHandler:[auth,requireCurator]},async(request,reply)=>{const mentionId=z.coerce.number().int().positive().safeParse((request.params as any).mentionId),body=z.object({decision:z.enum(['confirmed','rejected']),reason:z.string().trim().max(1000).optional().nullable()}).safeParse(request.body);if(!mentionId.success||!body.success)return reply.code(400).send({error:'INVALID_AMPLIFICATION_REVIEW'});const ctx=request.ownedClusterAuth!;const{rows}=await pool.query(`UPDATE owned_content_cluster_members ocm SET review_status=$2,reviewed_by=$3,reviewed_at=now(),review_reason=$4 FROM social_mentions sm WHERE ocm.mention_id=$1 AND sm.id=ocm.mention_id AND sm.source_kind='owned' AND COALESCE(sm.curation_status,'approved')='approved' RETURNING ocm.mention_id,ocm.review_status,ocm.review_reason,ocm.reviewed_at`,[mentionId.data,body.data.decision,ctx.id,body.data.reason??null]);if(!rows[0])return reply.code(404).send({error:'OWNED_AMPLIFICATION_MEMBER_NOT_FOUND'});await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'OWNED_AMPLIFICATION_REVIEWED',$2::jsonb)`,[ctx.id,JSON.stringify({mentionId:mentionId.data,decision:body.data.decision,reason:body.data.reason??null})]);const clustering=await rebuildOwnedContentClusters(pool);return{data:{mentionId:mentionId.data,decision:body.data.decision,reason:body.data.reason??null,reviewedBy:ctx.id},clustering};});

  app.get('/api/social/owned-publications',{preHandler:auth},async(request)=>{const ctx=request.ownedClusterAuth!,query=request.query as Record<string,unknown>;const stale=(await pool.query(`SELECT id,title,content,published_at,author_name,platform,opd_id,metadata FROM social_mentions WHERE source_kind='owned' AND COALESCE(curation_status,'approved')='approved' AND COALESCE(risk_score,0)=0 LIMIT 200`)).rows;for(const item of stale){const intelligence=analyzeCoreArticle({id:item.id,title:item.title,summary:String(item.content||'').slice(0,900),content:item.content,sourceName:item.author_name||item.platform,mediaKind:'social',opdId:item.opd_id,publishedAt:item.published_at},parseKeywordQuery(''),1);const risk=calculateRisk({importance:intelligence.importanceScore,impact:intelligence.impactScore,velocity:intelligence.velocityScore,sentiment:intelligence.sentiment,sentimentScore:intelligence.sentimentScore});const locked=item.metadata?.v16Routing?.verificationStatus==='LOCKED';await pool.query(`UPDATE social_mentions SET sentiment=$2,sentiment_score=$3,importance_score=$4,influence_score=$5,risk_score=$6,risk_level=$7,metadata=jsonb_set(COALESCE(metadata,'{}'::jsonb),'{intelligence}',$8::jsonb,true),updated_at=now() WHERE id=$1 AND source_kind='owned' AND COALESCE(risk_score,0)=0`,[item.id,intelligence.sentiment,intelligence.sentimentScore,intelligence.importanceScore,intelligence.impactScore,risk.score,risk.level,JSON.stringify({...intelligence,riskLevel:risk.level,riskReasons:risk.reasons,riskStatus:locked?'FINAL':'PROVISIONAL',...(locked?{riskFinalizedAt:item.metadata?.intelligence?.riskFinalizedAt||new Date().toISOString()}: {})})]);}const limit=Math.max(1,Math.min(200,Number(query?.limit)||100));const requestedOpd=typeof query?.opdId==='string'&&/^\d+$/.test(query.opdId)?query.opdId:null;const params:unknown[]=[],where=[`sm.source_kind='owned'`,`COALESCE(sm.curation_status,'approved')='approved'`];if(canReadAll(ctx)){if(requestedOpd){params.push(requestedOpd);where.push(`sm.opd_id=$${params.length}`);}}else if(ctx.opdId){params.push(ctx.opdId);where.push(`sm.opd_id=$${params.length}`);}else where.push('1=0');params.push(limit);const{rows}=await pool.query(`SELECT sm.*,o.name opd_name,osa.account_name owned_account_name,osa.handle owned_account_handle FROM social_mentions sm LEFT JOIN opd o ON o.id=sm.opd_id LEFT JOIN owned_social_accounts osa ON osa.id=sm.owned_account_id WHERE ${where.join(' AND ')} ORDER BY COALESCE(sm.published_at,sm.captured_at,sm.created_at) DESC NULLS LAST,sm.id DESC LIMIT $${params.length}`,params);return{data:rows};});

  app.get('/api/social/owned-clusters',{preHandler:auth},async()=>{const{rows}=await pool.query(`SELECT occ.id,occ.canonical_title,occ.representative_mention_id,occ.member_count,occ.channel_count,occ.first_published_at,occ.last_published_at,COALESCE(json_agg(json_build_object('mentionId',sm.id,'title',sm.title,'url',sm.canonical_url,'platform',sm.platform,'accountId',sm.owned_account_id,'accountName',osa.account_name,'ownershipLevel',osa.ownership_level,'ownerOpdId',osa.opd_id,'ownerOpdName',owner_opd.name,'ownerOpdCode',owner_opd.code,'ownerDistrictId',osa.district_id,'ownerDistrictName',d.name,'publishedAt',sm.published_at,'similarityScore',ocm.similarity_score,'similarityType',ocm.similarity_type,'memberRole',CASE WHEN sm.id=occ.representative_mention_id THEN 'original' WHEN ocm.similarity_type='identical' THEN 'republication' WHEN ocm.similarity_type='adapted' THEN 'adaptation' ELSE 'member' END,'reviewDecision',ocm.review_status,'reviewReason',ocm.review_reason,'reviewedAt',ocm.reviewed_at,'confidenceBand',CASE WHEN sm.id=occ.representative_mention_id THEN 'source' WHEN ocm.similarity_score>=0.85 THEN 'high' WHEN ocm.similarity_score>=0.65 THEN 'medium' ELSE 'low' END,'needsReview',CASE WHEN sm.id=occ.representative_mention_id THEN false WHEN ocm.review_status IS NOT NULL THEN false WHEN ocm.similarity_score<0.85 THEN true ELSE false END) ORDER BY sm.published_at DESC NULLS LAST,sm.id DESC),'[]'::json) members FROM owned_content_clusters occ LEFT JOIN owned_content_cluster_members ocm ON ocm.cluster_id=occ.id LEFT JOIN social_mentions sm ON sm.id=ocm.mention_id LEFT JOIN owned_social_accounts osa ON osa.id=sm.owned_account_id LEFT JOIN opd owner_opd ON owner_opd.id=osa.opd_id LEFT JOIN districts d ON d.id=osa.district_id GROUP BY occ.id ORDER BY occ.last_published_at DESC NULLS LAST,occ.first_published_at DESC NULLS LAST,occ.id DESC`);const reviewCount=rows.reduce((n:any,c:any)=>n+(c.members||[]).filter((m:any)=>m.needsReview).length,0);return{data:rows,review:{needsVerification:reviewCount}};});
}
