import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { hasPermission, loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { phase5Auth?: AuthorizationContext } }

const paramsSchema=z.object({issueId:z.string().regex(/^\d+$/),workflowId:z.string().regex(/^\d+$/)});
const strategyFields=z.object({
 executiveSummary:z.string().trim().max(12000).nullable().optional(),
 communicationObjectives:z.array(z.any()).default([]),
 targetAudiences:z.array(z.any()).default([]),
 keyMessages:z.array(z.any()).default([]),
 talkingPoints:z.array(z.any()).default([]),
 channelStrategy:z.array(z.any()).default([]),
 timingStrategy:z.record(z.string(),z.any()).default({}),
 spokespersonStrategy:z.array(z.any()).default([]),
 contentFormats:z.array(z.any()).default([]),
 communicationRisks:z.array(z.any()).default([]),
 coordinationRequirements:z.array(z.any()).default([]),
 expectedCommunicationOutcomes:z.array(z.any()).default([]),
 successKpis:z.array(z.any()).default([])
});
const reviewSchema=z.object({note:z.string().trim().max(4000).nullable().optional()});
const districtFields=z.object({
 evidenceContext:z.record(z.string(),z.any()).default({}),localAudiences:z.array(z.any()).default([]),communicationFocus:z.array(z.any()).default([]),localMessages:z.array(z.any()).default([]),talkingPoints:z.array(z.any()).default([]),localChannels:z.array(z.any()).default([]),coordinationOpds:z.array(z.any()).default([]),timingStrategy:z.record(z.string(),z.any()).default({}),successKpis:z.array(z.any()).default([]),fieldUpdateRequirements:z.array(z.any()).default([])
});
async function generateStrategyWithGemini(input:any){
 const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('GEMINI_API_KEY_MISSING');
 const model=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite';
 const prompt=`Anda adalah mesin strategi komunikasi Pemerintah Kota Batam. Susun DRAFT strategi komunikasi berbasis data yang diberikan. Jangan mengarang fakta. Bedakan pesan induk Pemko dan arahan kewilayahan. Arahan kecamatan hanya untuk kecamatan yang tercantum dalam input. Pesan lokal harus konsisten dengan pesan induk. Historical learning adalah pembelajaran, bukan fakta kondisi saat ini.

Strakom harus menjawab bukan hanya bagaimana Pemko berkomunikasi, tetapi juga substansi apa yang perlu tersedia agar komunikasi kredibel, koordinasi komunikasi apa yang diperlukan, dan hasil komunikasi apa yang diharapkan pada masyarakat.
coordinationRequirements adalah KEBUTUHAN KOORDINASI/SUBSTANSI KOMUNIKASI, bukan perintah kebijakan operasional dan bukan tuduhan bahwa OPD/kecamatan belum bekerja. Gunakan hanya OPD/kecamatan yang tersedia dalam input/routing. Untuk setiap kebutuhan, jelaskan purpose, informationNeeded, parties, dan publicationUse.
expectedCommunicationOutcomes adalah TARGET setelah komunikasi: apa yang diharapkan masyarakat tahu, pahami, atau lakukan. Jangan menyatakan target itu sudah tercapai; dampak aktual baru dinilai pada Monitoring.
KPI adalah indikator pengukuran, berbeda dari expectedCommunicationOutcomes.

Agar hasil Strakom siap dipakai Content Studio, gunakan kosakata produksi yang TERBATAS dan konsisten. Jangan membuat nama kategori baru.
Target audiens yang boleh dipakai: MASYARAKAT_UMUM, ANAK_PELAJAR, REMAJA_GEN_Z, LANSIA_KELOMPOK_RENTAN, PELAKU_USAHA_UMKM_INVESTOR, INTERNAL_ASN, MEDIA_JURNALIS.
Tone yang boleh dipakai: INFORMATIF_KLARITATIF, RESMI_FORMAL, EDUKATIF_PERSUASIF, EMPATIS_MENENANGKAN, TEGAS_PENGAYOM, SEMANGAT_INSPIRATIF.
Tujuan komunikasi yang boleh dipakai: EDUKASI_SOSIALISASI, PENGUMUMAN_IMBAUAN, KLARIFIKASI_ANTI_HOAKS, LAPORAN_CAPAIAN_TRANSPARANSI, UNDANGAN_PERINGATAN_ACARA, MANAJEMEN_KRISIS.
Format materi yang boleh dipakai: PRESS_RELEASE, CAPTION_MEDIA_SOSIAL, NASKAH_SAMBUTAN_PIDATO, BERITA_WEB, VIDEO_AUDIO_SCRIPT, INFOGRAFIS, PENGUMUMAN_RESMI.
Kanal yang boleh dipakai: WEBSITE_RESMI, INSTAGRAM, FACEBOOK, TIKTOK, YOUTUBE, MEDIA_PERS.
spokespersonStrategy adalah rekomendasi PERAN juru bicara, bukan nama orang. Gunakan hanya kode OPD_UTAMA, HUMAS_PEMKO, atau PIMPINAN_DAERAH. Jangan mengarang nama/jabatan personal. Pilih hanya jika memang diperlukan oleh strategi; bila tidak perlu boleh kosong. OPD_UTAMA berarti pejabat berwenang dari OPD utama yang sudah ada di routing, bukan penetapan nama pejabat baru.
productionRecommendations harus berupa rekomendasi produksi, bukan fakta baru. Setiap rekomendasi wajib memilih tepat satu audience, purpose, tone, format, satu atau lebih channel, priority UTAMA atau PENDUKUNG, serta reason yang singkat dan berbasis Strakom. Maksimal 5 rekomendasi dan hindari kombinasi yang tidak relevan.
Issue, primary/supporting keyword, OPD, kecamatan/wilayah, risk, momentum, fakta/evidence dan data routing dari input adalah CONTEXT TERKUNCI: jangan mengubah, mengganti, menyimpulkan ulang identitasnya, atau membuat nilai baru. Content Studio kelak membacanya sebagai read-only.
Jangan memasukkan kutipan, angka/statistik, dasar hukum, URL, nama pejabat, tanggal, atau fakta spesifik yang tidak tersedia pada input. Jika materi membutuhkannya tetapi input tidak memuatnya, nyatakan sebagai kebutuhan bahan pendukung, bukan mengarangnya.

Output JSON:
{"executiveSummary":"...","communicationObjectives":[],"targetAudiences":[],"keyMessages":[],"talkingPoints":[],"coordinationRequirements":[{"purpose":"...","informationNeeded":["..."],"parties":["..."],"publicationUse":"..."}],"expectedCommunicationOutcomes":[{"audience":"...","expectedUnderstanding":"...","expectedAction":"..."}],"channelStrategy":[],"timingStrategy":{},"spokespersonStrategy":[],"contentFormats":[],"communicationRisks":[],"successKpis":[],"productionRecommendations":[{"audience":"MASYARAKAT_UMUM","purpose":"EDUKASI_SOSIALISASI","tone":"INFORMATIF_KLARITATIF","format":"INFOGRAFIS","channels":["INSTAGRAM","FACEBOOK"],"priority":"UTAMA","reason":"..."}],"districtStrategies":[{"districtId":1,"evidenceContext":{},"localAudiences":[],"communicationFocus":[],"localMessages":[],"talkingPoints":[],"localChannels":[],"coordinationOpds":[],"timingStrategy":{},"successKpis":[],"fieldUpdateRequirements":[]}]}

DATA:
${JSON.stringify(input).slice(0,50000)}`;
 const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});
 if(!r.ok)throw new Error(`Gemini HTTP ${r.status}`);const payload=await r.json() as any,raw=payload.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||'').join('');if(!raw)throw new Error('GEMINI_EMPTY_RESPONSE');return JSON.parse(raw);
}

export async function registerPhase5StrategyRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(401).send({error:'USER_INACTIVE_OR_MISSING'});request.phase5Auth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const workflow=async(issueId:string,workflowId:string)=>(await pool.query(`SELECT w.*,i.title,i.description,i.risk_level,i.momentum,i.geographic_scope,o.name lead_opd_name FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id WHERE w.id=$1 AND w.issue_id=$2`,[workflowId,issueId])).rows[0]||null;
 const snapshot=async(w:any)=>{
  const [gap,response,publication,monitoring,keywords,districts,metrics]=await Promise.all([
   pool.query('SELECT * FROM issue_communication_gap_snapshots WHERE workflow_id=$1',[w.id]),
   pool.query("SELECT response_text,facts_data,key_message,supporting_links,version,reviewed_at AS approved_at FROM issue_response_submissions WHERE workflow_id=$1 AND status='APPROVED' ORDER BY version DESC LIMIT 1",[w.id]),
   pool.query('SELECT result,gap_analyzed_at,analyzed_at FROM issue_publication_analysis_snapshots WHERE workflow_id=$1',[w.id]),
   pool.query('SELECT period_number,result,evidence_summary,period_started_at,period_ended_at,analyzed_at FROM issue_monitoring_analysis_snapshots WHERE workflow_id=$1 ORDER BY period_number',[w.id]),
   pool.query("SELECT k.id,k.keyword,ik.keyword_role FROM issue_keywords ik JOIN keywords k ON k.id=ik.keyword_id WHERE ik.issue_id=$1 ORDER BY CASE WHEN ik.keyword_role='PRIMARY' THEN 0 ELSE 1 END,k.keyword",[w.issue_id]),
   pool.query(`SELECT d.id,d.name FROM issue_districts x JOIN districts d ON d.id=x.district_id WHERE x.issue_id=$1 UNION SELECT d.id,d.name FROM issue_workflow_contributors c JOIN districts d ON d.id=c.district_id WHERE c.workflow_id=$2 AND c.contributor_type='DISTRICT' ORDER BY name`,[w.issue_id,w.id]),
   pool.query('SELECT * FROM issue_metrics WHERE issue_id=$1 ORDER BY measured_at DESC LIMIT 1',[w.issue_id])
  ]);
  const previous=(await pool.query(`SELECT pw.id workflow_id,pw.cycle_number,cs.id strategy_id,cs.version strategy_version,cs.executive_summary,pa.result publication_analysis,ma.result final_monitoring_analysis FROM issue_workflows pw LEFT JOIN LATERAL (SELECT s.* FROM communication_strategies s WHERE s.workflow_id=pw.id AND s.status IN ('APPROVED','SUPERSEDED') ORDER BY s.version DESC LIMIT 1) cs ON true LEFT JOIN issue_publication_analysis_snapshots pa ON pa.workflow_id=pw.id LEFT JOIN LATERAL (SELECT m.result FROM issue_monitoring_analysis_snapshots m WHERE m.workflow_id=pw.id ORDER BY m.period_number DESC LIMIT 1) ma ON true WHERE pw.issue_id=$1 AND pw.cycle_number<$2 AND pw.workflow_status='CLOSED' ORDER BY pw.cycle_number DESC LIMIT 1`,[w.issue_id,w.cycle_number])).rows[0]||null;
  return {capturedAt:new Date().toISOString(),previousCycleLearning:previous,issue:{id:w.issue_id,title:w.title,description:w.description,riskLevel:w.risk_level,momentum:w.momentum,geographicScope:w.geographic_scope},workflow:{id:w.id,cycleNumber:w.cycle_number,status:w.workflow_status,leadOpdId:w.lead_opd_id,leadOpdName:w.lead_opd_name},keywords:keywords.rows,districts:districts.rows,metrics:metrics.rows[0]||null,gap:gap.rows[0]||null,approvedResponse:response.rows[0]||null,publicationAnalysis:publication.rows[0]||null,monitoringAnalysis:monitoring.rows};
 };
 const requireRead=(ctx:AuthorizationContext)=>hasPermission(ctx,'strategy.read')||hasPermission(ctx,'strategy.manage');
 const requireManage=(ctx:AuthorizationContext)=>hasPermission(ctx,'strategy.manage');

 app.get('/api/phase5/strategies',{preHandler:auth},async(request,reply)=>{
  const ctx=request.phase5Auth!;if(!requireRead(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  if(ctx.roles.includes('district')&&ctx.districtId){const rows=(await pool.query(`SELECT w.id workflow_id,w.issue_id,w.cycle_number,w.workflow_status,i.title issue_title,i.risk_level,i.momentum,
COALESCE(o.name,(SELECT ro.name FROM issue_keywords ik JOIN keyword_opd ko ON ko.keyword_id=ik.keyword_id AND ko.active=TRUE AND ko.routing_role='PRIMARY' JOIN opd ro ON ro.id=ko.opd_id WHERE ik.issue_id=w.issue_id AND ik.keyword_role='PRIMARY' ORDER BY ko.weight DESC LIMIT 1)) lead_opd_name,
(SELECT k.keyword FROM issue_keywords ik JOIN keywords k ON k.id=ik.keyword_id WHERE ik.issue_id=w.issue_id AND ik.keyword_role='PRIMARY' LIMIT 1) primary_keyword,
(SELECT im.risk_score FROM issue_metrics im WHERE im.issue_id=w.issue_id ORDER BY im.measured_at DESC LIMIT 1) risk_score,
(SELECT im.metadata->'sentiment' FROM issue_metrics im WHERE im.issue_id=w.issue_id ORDER BY im.measured_at DESC LIMIT 1) sentiment,
s.id strategy_id,s.version strategy_version,s.status strategy_status,s.is_current,s.updated_at strategy_updated_at,TRUE gap_ready,jsonb_build_array(jsonb_build_object('id',d.id,'name',d.name)) districts FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id JOIN communication_strategies s ON s.workflow_id=w.id AND s.status='APPROVED' AND s.is_current=TRUE JOIN communication_strategy_districts sd ON sd.strategy_id=s.id AND sd.district_id=$1 JOIN districts d ON d.id=sd.district_id WHERE EXISTS(SELECT 1 FROM issue_workflow_contributors c WHERE c.workflow_id=w.id AND c.contributor_type='DISTRICT' AND c.district_id=$1 UNION SELECT 1 FROM issue_districts x WHERE x.issue_id=w.issue_id AND x.district_id=$1) ORDER BY s.updated_at DESC LIMIT 200`,[ctx.districtId])).rows;return{data:rows};}
  if(!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});
  const rows=(await pool.query(`SELECT w.id workflow_id,w.issue_id,w.cycle_number,w.workflow_status,i.title issue_title,i.risk_level,i.momentum,
COALESCE(o.name,(SELECT ro.name FROM issue_keywords ik JOIN keyword_opd ko ON ko.keyword_id=ik.keyword_id AND ko.active=TRUE AND ko.routing_role='PRIMARY' JOIN opd ro ON ro.id=ko.opd_id WHERE ik.issue_id=w.issue_id AND ik.keyword_role='PRIMARY' ORDER BY ko.weight DESC LIMIT 1)) lead_opd_name,
(SELECT k.keyword FROM issue_keywords ik JOIN keywords k ON k.id=ik.keyword_id WHERE ik.issue_id=w.issue_id AND ik.keyword_role='PRIMARY' LIMIT 1) primary_keyword,
(SELECT im.risk_score FROM issue_metrics im WHERE im.issue_id=w.issue_id ORDER BY im.measured_at DESC LIMIT 1) risk_score,
(SELECT im.metadata->'sentiment' FROM issue_metrics im WHERE im.issue_id=w.issue_id ORDER BY im.measured_at DESC LIMIT 1) sentiment,
s.id strategy_id,s.version strategy_version,s.status strategy_status,s.is_current,s.updated_at strategy_updated_at,EXISTS(SELECT 1 FROM issue_communication_gap_snapshots g WHERE g.workflow_id=w.id) gap_ready,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',q.id,'name',q.name) ORDER BY q.name) FROM (SELECT d.id,d.name FROM issue_districts x JOIN districts d ON d.id=x.district_id WHERE x.issue_id=w.issue_id UNION SELECT d.id,d.name FROM issue_workflow_contributors c JOIN districts d ON d.id=c.district_id WHERE c.workflow_id=w.id AND c.contributor_type='DISTRICT') q),'[]'::jsonb) districts FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id LEFT JOIN LATERAL (SELECT cs.* FROM communication_strategies cs WHERE cs.workflow_id=w.id ORDER BY CASE WHEN cs.status IN ('DRAFT','IN_REVIEW') THEN 0 WHEN cs.is_current THEN 1 ELSE 2 END,cs.version DESC LIMIT 1) s ON true WHERE (w.workflow_status IN ('APPROVED','STRATEGY') OR s.id IS NOT NULL) ORDER BY COALESCE(s.updated_at,w.updated_at) DESC LIMIT 200`)).rows;
  return{data:rows};
 });

 app.get('/api/phase6/content-projects',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireRead(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const rows=(await pool.query("SELECT id,workflow_id,issue_id,strategy_id,status,production_parameters,created_at,updated_at FROM content_projects ORDER BY updated_at DESC")).rows;return{data:rows};});
 app.post('/api/phase6/content-projects',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const b=z.object({workflowId:z.coerce.number().int().positive(),issueId:z.coerce.number().int().positive(),strategyId:z.coerce.number().int().positive(),productionParameters:z.record(z.string(),z.any()).default({})}).safeParse(request.body);if(!b.success)return reply.code(400).send({error:'INVALID_CONTENT_PROJECT'});const s=(await pool.query("SELECT * FROM communication_strategies WHERE id=$1 AND workflow_id=$2 AND issue_id=$3 AND status='APPROVED' AND is_current=TRUE",[b.data.strategyId,b.data.workflowId,b.data.issueId])).rows[0];if(!s)return reply.code(409).send({error:'APPROVED_STRATEGY_REQUIRED'});const context={strategyVersion:s.version,strategyApprovedAt:s.approved_at,inputSnapshot:s.input_snapshot,executiveSummary:s.executive_summary,keyMessages:s.key_messages};const row=(await pool.query("INSERT INTO content_projects(workflow_id,issue_id,strategy_id,status,context_snapshot,production_parameters,created_by,updated_by) VALUES($1,$2,$3,'DRAFT',$4::jsonb,$5::jsonb,$6,$6) ON CONFLICT(workflow_id,strategy_id) DO UPDATE SET production_parameters=EXCLUDED.production_parameters,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING *",[b.data.workflowId,b.data.issueId,b.data.strategyId,JSON.stringify(context),JSON.stringify(b.data.productionParameters),ctx.id])).rows[0];return reply.code(201).send({data:row});});
 app.put('/api/phase6/content-projects/:id',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({id:z.coerce.number().int().positive()}).safeParse(request.params),b=z.object({status:z.enum(['DRAFT','READY','COMPLETED']).optional(),productionParameters:z.record(z.string(),z.any()).optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_CONTENT_PROJECT'});const current=(await pool.query("SELECT * FROM content_projects WHERE id=$1",[p.data.id])).rows[0];if(!current)return reply.code(404).send({error:'CONTENT_PROJECT_NOT_FOUND'});if(current.status==='COMPLETED')return reply.code(409).send({error:'CONTENT_PROJECT_LOCKED'});const next=b.data.status||current.status;if((current.status==='DRAFT'&&!['DRAFT','READY'].includes(next))||(current.status==='READY'&&!['READY','COMPLETED'].includes(next)))return reply.code(409).send({error:'INVALID_CONTENT_PROJECT_TRANSITION'});const row=(await pool.query("UPDATE content_projects SET status=$1,production_parameters=COALESCE($2::jsonb,production_parameters),updated_by=$3,updated_at=NOW() WHERE id=$4 RETURNING *",[next,b.data.productionParameters?JSON.stringify(b.data.productionParameters):null,ctx.id,p.data.id])).rows[0];return{data:row};});


 app.get('/api/phase6/content-projects/:id/items',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireRead(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({id:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_CONTENT_PROJECT'});const rows=(await pool.query("SELECT * FROM content_project_items WHERE project_id=$1 ORDER BY created_at,id",[p.data.id])).rows;return{data:rows};});
 app.post('/api/phase6/content-projects/:id/items',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({id:z.coerce.number().int().positive()}).safeParse(request.params),b=z.object({title:z.string().trim().min(1).max(200),format:z.string().trim().min(1).max(50),audience:z.string().trim().min(1).max(50),purpose:z.string().trim().min(1).max(50),tone:z.string().trim().min(1).max(50),channels:z.array(z.string()).default([])}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_CONTENT_ITEM'});const project=(await pool.query("SELECT status FROM content_projects WHERE id=$1",[p.data.id])).rows[0];if(!project)return reply.code(404).send({error:'CONTENT_PROJECT_NOT_FOUND'});if(project.status!=='DRAFT')return reply.code(409).send({error:'CONTENT_ITEM_LIST_LOCKED'});const x=b.data;const row=(await pool.query("INSERT INTO content_project_items(project_id,title,format,audience,purpose,tone,channels,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$8) RETURNING *",[p.data.id,x.title,x.format,x.audience,x.purpose,x.tone,JSON.stringify(x.channels),ctx.id])).rows[0];return reply.code(201).send({data:row});});
 app.delete('/api/phase6/content-projects/:projectId/items/:itemId',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({projectId:z.coerce.number().int().positive(),itemId:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_CONTENT_ITEM'});const project=(await pool.query("SELECT status FROM content_projects WHERE id=$1",[p.data.projectId])).rows[0];if(!project)return reply.code(404).send({error:'CONTENT_PROJECT_NOT_FOUND'});if(project.status!=='DRAFT')return reply.code(409).send({error:'CONTENT_ITEM_LIST_LOCKED'});const r=await pool.query("DELETE FROM content_project_items WHERE id=$1 AND project_id=$2",[p.data.itemId,p.data.projectId]);if(!r.rowCount)return reply.code(404).send({error:'CONTENT_ITEM_NOT_FOUND'});return{ok:true};});
 app.get('/api/phase6/content-projects/:id/sources',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireRead(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({id:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_CONTENT_PROJECT'});const rows=(await pool.query("SELECT * FROM content_project_sources WHERE project_id=$1 ORDER BY created_at,id",[p.data.id])).rows;return{data:rows};});
 app.post('/api/phase6/content-projects/:id/sources',{preHandler:auth},async(request,reply)=>{const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const p=z.object({id:z.coerce.number().int().positive()}).safeParse(request.params),b=z.object({itemId:z.coerce.number().int().positive().nullable().optional(),category:z.enum(['OFFICIAL_STATEMENT','DATA_STATISTICS','LEGAL_REGULATION','PROGRAM_SERVICE','ADDITIONAL_REFERENCE']),sourceUrl:z.string().url(),sourceTitle:z.string().trim().max(500).optional()}).safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_CONTENT_SOURCE'});const project=(await pool.query("SELECT status FROM content_projects WHERE id=$1",[p.data.id])).rows[0];if(!project)return reply.code(404).send({error:'CONTENT_PROJECT_NOT_FOUND'});if(project.status!=='DRAFT')return reply.code(409).send({error:'CONTENT_SOURCES_LOCKED'});if(b.data.itemId){const item=(await pool.query("SELECT 1 FROM content_project_items WHERE id=$1 AND project_id=$2",[b.data.itemId,p.data.id])).rows[0];if(!item)return reply.code(409).send({error:'CONTENT_ITEM_PROJECT_MISMATCH'});}const row=(await pool.query("INSERT INTO content_project_sources(project_id,item_id,category,source_url,source_title,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[p.data.id,b.data.itemId||null,b.data.category,b.data.sourceUrl,b.data.sourceTitle||null,ctx.id])).rows[0];return reply.code(201).send({data:row});});

 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireRead(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});
  const rows=(await pool.query(`SELECT cs.*,COALESCE(cs.input_snapshot->'productionRecommendations','[]'::jsonb) production_recommendations FROM communication_strategies cs WHERE cs.workflow_id=$1 ORDER BY cs.version DESC`,[w.id])).rows;return{data:{workflow:w,strategies:rows}};
 });
 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/districts',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_STRATEGY'});const ctx=request.phase5Auth!;if(!requireRead(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});
  const rows=(await pool.query(`SELECT d.*,x.name district_name FROM communication_strategy_districts d JOIN communication_strategies s ON s.id=d.strategy_id JOIN districts x ON x.id=d.district_id WHERE s.workflow_id=$1 AND s.issue_id=$2 AND s.version=$3 ORDER BY x.name`,[p.data.workflowId,p.data.issueId,p.data.version])).rows;return{data:rows};
 });

 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/district',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!ctx.roles.includes('district')||!ctx.districtId)return reply.code(403).send({error:'DISTRICT_ACCOUNT_REQUIRED'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});
  const involved=(await pool.query("SELECT 1 FROM issue_workflow_contributors WHERE workflow_id=$1 AND contributor_type='DISTRICT' AND district_id=$2 UNION SELECT 1 FROM issue_districts WHERE issue_id=$3 AND district_id=$2 LIMIT 1",[w.id,ctx.districtId,w.issue_id])).rows[0];if(!involved)return reply.code(403).send({error:'DISTRICT_NOT_INVOLVED'});
  const row=(await pool.query(`SELECT s.id strategy_id,s.version,s.status,s.approved_at,s.executive_summary,d.id district_strategy_id,d.district_id,d.evidence_context,d.local_audiences,d.communication_focus,d.local_messages,d.talking_points,d.local_channels,d.coordination_opds,d.timing_strategy,d.success_kpis,d.field_update_requirements FROM communication_strategies s JOIN communication_strategy_districts d ON d.strategy_id=s.id WHERE s.workflow_id=$1 AND d.district_id=$2 AND s.status='APPROVED' AND s.is_current=TRUE LIMIT 1`,[w.id,ctx.districtId])).rows[0];if(!row)return reply.code(404).send({error:'APPROVED_DISTRICT_STRATEGY_NOT_FOUND'});return{data:row};
 });

 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/draft',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});if(!['APPROVED','STRATEGY'].includes(String(w.workflow_status)))return reply.code(409).send({error:'STRATEGY_STAGE_NOT_AVAILABLE',status:w.workflow_status});const gap=(await pool.query('SELECT 1 FROM issue_communication_gap_snapshots WHERE workflow_id=$1',[w.id])).rows[0];if(!gap)return reply.code(409).send({error:'COMMUNICATION_GAP_REQUIRED'});const open=(await pool.query("SELECT * FROM communication_strategies WHERE workflow_id=$1 AND status IN ('DRAFT','IN_REVIEW') ORDER BY version DESC LIMIT 1",[w.id])).rows[0];if(open)return reply.code(409).send({error:'OPEN_STRATEGY_EXISTS',data:open});
  const version=Number((await pool.query('SELECT COALESCE(MAX(version),0)+1 v FROM communication_strategies WHERE workflow_id=$1',[w.id])).rows[0].v),input=await snapshot(w);
  const generated=await generateStrategyWithGemini(input);
  const client=await pool.connect();try{await client.query('BEGIN');if(w.workflow_status==='APPROVED')await client.query("UPDATE issue_workflows SET workflow_status='STRATEGY',updated_by=$1,updated_at=NOW() WHERE id=$2",[ctx.id,w.id]);const row=(await client.query("INSERT INTO communication_strategies(workflow_id,issue_id,version,status,input_snapshot,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,coordination_requirements,expected_communication_outcomes,success_kpis,generated_by,generated_at,created_by,updated_by) VALUES($1,$2,$3,'DRAFT',$4::jsonb,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb,$16::jsonb,$17::jsonb,$18,NOW(),$18,$18) RETURNING *",[w.id,w.issue_id,version,JSON.stringify(input),generated.executiveSummary||null,JSON.stringify(generated.communicationObjectives||[]),JSON.stringify(generated.targetAudiences||[]),JSON.stringify(generated.keyMessages||[]),JSON.stringify(generated.talkingPoints||[]),JSON.stringify(generated.channelStrategy||[]),JSON.stringify(generated.timingStrategy||{}),JSON.stringify(generated.spokespersonStrategy||[]),JSON.stringify(generated.contentFormats||[]),JSON.stringify(generated.communicationRisks||[]),JSON.stringify(generated.coordinationRequirements||[]),JSON.stringify(generated.expectedCommunicationOutcomes||[]),JSON.stringify(generated.successKpis||[]),ctx.id])).rows[0];
  // Production recommendations are intentionally stored inside input_snapshot metadata for now.
  // This avoids a schema migration while making newly generated Strakom Content-Studio-ready.
  if(Array.isArray(generated.productionRecommendations)){const enriched={...input,productionRecommendations:generated.productionRecommendations};await client.query('UPDATE communication_strategies SET input_snapshot=$1::jsonb WHERE id=$2',[JSON.stringify(enriched),row.id]);row.input_snapshot=enriched;}
  const allowed=new Set((input.districts||[]).map((d:any)=>Number(d.id)));for(const ds of (generated.districtStrategies||[])){const districtId=Number(ds.districtId);if(!allowed.has(districtId))continue;await client.query(`INSERT INTO communication_strategy_districts(strategy_id,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb)`,[row.id,w.id,districtId,JSON.stringify(ds.evidenceContext||{}),JSON.stringify(ds.localAudiences||[]),JSON.stringify(ds.communicationFocus||[]),JSON.stringify(ds.localMessages||[]),JSON.stringify(ds.talkingPoints||[]),JSON.stringify(ds.localChannels||[]),JSON.stringify(ds.coordinationOpds||[]),JSON.stringify(ds.timingStrategy||{}),JSON.stringify(ds.successKpis||[]),JSON.stringify(ds.fieldUpdateRequirements||[])]);}await client.query('COMMIT');return reply.code(201).send({data:row});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/regenerate',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_STRATEGY'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});const current=(await pool.query("SELECT id,status FROM communication_strategies WHERE workflow_id=$1 AND issue_id=$2 AND version=$3",[p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!current||current.status!=='DRAFT')return reply.code(409).send({error:'ONLY_DRAFT_STRATEGY_CAN_BE_REGENERATED'});
  const input=await snapshot(w),generated=await generateStrategyWithGemini(input),enriched={...input,productionRecommendations:Array.isArray(generated.productionRecommendations)?generated.productionRecommendations:[]};
  const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`UPDATE communication_strategies SET input_snapshot=$1::jsonb,executive_summary=$2,communication_objectives=$3::jsonb,target_audiences=$4::jsonb,key_messages=$5::jsonb,talking_points=$6::jsonb,channel_strategy=$7::jsonb,timing_strategy=$8::jsonb,spokesperson_strategy=$9::jsonb,content_formats=$10::jsonb,communication_risks=$11::jsonb,coordination_requirements=$12::jsonb,expected_communication_outcomes=$13::jsonb,success_kpis=$14::jsonb,generated_by=$15,generated_at=NOW(),updated_by=$15,updated_at=NOW() WHERE id=$16 AND status='DRAFT' RETURNING *`,[JSON.stringify(enriched),generated.executiveSummary||null,JSON.stringify(generated.communicationObjectives||[]),JSON.stringify(generated.targetAudiences||[]),JSON.stringify(generated.keyMessages||[]),JSON.stringify(generated.talkingPoints||[]),JSON.stringify(generated.channelStrategy||[]),JSON.stringify(generated.timingStrategy||{}),JSON.stringify(generated.spokespersonStrategy||[]),JSON.stringify(generated.contentFormats||[]),JSON.stringify(generated.communicationRisks||[]),JSON.stringify(generated.coordinationRequirements||[]),JSON.stringify(generated.expectedCommunicationOutcomes||[]),JSON.stringify(generated.successKpis||[]),ctx.id,current.id])).rows[0];
  await client.query('DELETE FROM communication_strategy_districts WHERE strategy_id=$1',[current.id]);const allowed=new Set((input.districts||[]).map((d:any)=>Number(d.id)));for(const ds of (generated.districtStrategies||[])){const districtId=Number(ds.districtId);if(!allowed.has(districtId))continue;await client.query(`INSERT INTO communication_strategy_districts(strategy_id,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb)`,[current.id,w.id,districtId,JSON.stringify(ds.evidenceContext||{}),JSON.stringify(ds.localAudiences||[]),JSON.stringify(ds.communicationFocus||[]),JSON.stringify(ds.localMessages||[]),JSON.stringify(ds.talkingPoints||[]),JSON.stringify(ds.localChannels||[]),JSON.stringify(ds.coordinationOpds||[]),JSON.stringify(ds.timingStrategy||{}),JSON.stringify(ds.successKpis||[]),JSON.stringify(ds.fieldUpdateRequirements||[])]);}await client.query('COMMIT');return{data:row};}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
 app.put('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params),b=strategyFields.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_STRATEGY'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  const v=b.data;const row=(await pool.query(`UPDATE communication_strategies SET executive_summary=$1,communication_objectives=$2::jsonb,target_audiences=$3::jsonb,key_messages=$4::jsonb,talking_points=$5::jsonb,channel_strategy=$6::jsonb,timing_strategy=$7::jsonb,spokesperson_strategy=$8::jsonb,content_formats=$9::jsonb,communication_risks=$10::jsonb,coordination_requirements=$11::jsonb,expected_communication_outcomes=$12::jsonb,success_kpis=$13::jsonb,updated_by=$14,updated_at=NOW() WHERE workflow_id=$15 AND issue_id=$16 AND version=$17 AND status='DRAFT' RETURNING *`,[v.executiveSummary||null,JSON.stringify(v.communicationObjectives),JSON.stringify(v.targetAudiences),JSON.stringify(v.keyMessages),JSON.stringify(v.talkingPoints),JSON.stringify(v.channelStrategy),JSON.stringify(v.timingStrategy),JSON.stringify(v.spokespersonStrategy),JSON.stringify(v.contentFormats),JSON.stringify(v.communicationRisks),JSON.stringify(v.coordinationRequirements),JSON.stringify(v.expectedCommunicationOutcomes),JSON.stringify(v.successKpis),ctx.id,p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!row)return reply.code(409).send({error:'STRATEGY_NOT_EDITABLE'});return{data:row};
 });
 app.put('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/district/:districtId',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive(),districtId:z.coerce.number().int().positive()}).safeParse(request.params),b=districtFields.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_DISTRICT_STRATEGY'});const ctx=request.phase5Auth!;if(!requireManage(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const v=b.data;
  const row=(await pool.query(`UPDATE communication_strategy_districts d SET evidence_context=$1::jsonb,local_audiences=$2::jsonb,communication_focus=$3::jsonb,local_messages=$4::jsonb,talking_points=$5::jsonb,local_channels=$6::jsonb,coordination_opds=$7::jsonb,timing_strategy=$8::jsonb,success_kpis=$9::jsonb,field_update_requirements=$10::jsonb,updated_at=NOW() FROM communication_strategies s WHERE d.strategy_id=s.id AND s.workflow_id=$11 AND s.issue_id=$12 AND s.version=$13 AND s.status='DRAFT' AND d.district_id=$14 RETURNING d.*`,[JSON.stringify(v.evidenceContext),JSON.stringify(v.localAudiences),JSON.stringify(v.communicationFocus),JSON.stringify(v.localMessages),JSON.stringify(v.talkingPoints),JSON.stringify(v.localChannels),JSON.stringify(v.coordinationOpds),JSON.stringify(v.timingStrategy),JSON.stringify(v.successKpis),JSON.stringify(v.fieldUpdateRequirements),p.data.workflowId,p.data.issueId,p.data.version,p.data.districtId])).rows[0];if(!row)return reply.code(409).send({error:'DISTRICT_STRATEGY_NOT_EDITABLE'});return{data:row};
 });

 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/review',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params),b=reviewSchema.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_REVIEW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const row=(await pool.query("UPDATE communication_strategies SET status='IN_REVIEW',review_note=$1,reviewed_by=$2,reviewed_at=NOW(),updated_by=$2,updated_at=NOW() WHERE workflow_id=$3 AND issue_id=$4 AND version=$5 AND status='DRAFT' RETURNING *",[b.data.note||null,ctx.id,p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!row)return reply.code(409).send({error:'STRATEGY_NOT_DRAFT'});return{data:row};
 });
 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/approve',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_APPROVAL'});const ctx=request.phase5Auth!;if(!requireManage(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const client=await pool.connect();try{await client.query('BEGIN');const target=(await client.query("SELECT id FROM communication_strategies WHERE workflow_id=$1 AND issue_id=$2 AND version=$3 AND status IN ('DRAFT','IN_REVIEW') FOR UPDATE",[p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!target){await client.query('ROLLBACK');return reply.code(409).send({error:'STRATEGY_NOT_APPROVABLE'});}await client.query("UPDATE communication_strategies SET status='SUPERSEDED',is_current=FALSE,updated_by=$1,updated_at=NOW() WHERE workflow_id=$2 AND status='APPROVED' AND is_current=TRUE",[ctx.id,p.data.workflowId]);const row=(await client.query("UPDATE communication_strategies SET status='APPROVED',is_current=TRUE,approved_by=$1,approved_at=NOW(),updated_by=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[ctx.id,target.id])).rows[0];await client.query('COMMIT');return{data:row};}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/revise',{preHandler:auth},async(request,reply)=>{
  return reply.code(409).send({error:'STRATEGY_REVISION_DISABLED_AFTER_APPROVAL'});
  /* Legacy revision implementation retained below for audit history.

  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const approved=(await pool.query("SELECT * FROM communication_strategies WHERE workflow_id=$1 AND issue_id=$2 AND status='APPROVED' ORDER BY version DESC LIMIT 1",[p.data.workflowId,p.data.issueId])).rows[0];if(!approved)return reply.code(409).send({error:'APPROVED_STRATEGY_REQUIRED'});const open=(await pool.query("SELECT 1 FROM communication_strategies WHERE workflow_id=$1 AND status IN ('DRAFT','IN_REVIEW') LIMIT 1",[p.data.workflowId])).rows[0];if(open)return reply.code(409).send({error:'OPEN_STRATEGY_EXISTS'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});const input=await snapshot(w),version=Number(approved.version)+1;
  const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`INSERT INTO communication_strategies(workflow_id,issue_id,version,status,input_snapshot,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,success_kpis,generated_by,generated_at,created_by,updated_by) SELECT workflow_id,issue_id,$1,'DRAFT',$2::jsonb,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,success_kpis,$3,NOW(),$3,$3 FROM communication_strategies WHERE id=$4 RETURNING *`,[version,JSON.stringify(input),ctx.id,approved.id])).rows[0];await client.query(`INSERT INTO communication_strategy_districts(strategy_id,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements) SELECT $1,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements FROM communication_strategy_districts WHERE strategy_id=$2`,[row.id,approved.id]);await client.query('COMMIT');return reply.code(201).send({data:row});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
  */
 });
}
