import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { canAssignPhase3, canReviewPhase3, canTransitionPhase3, type Phase3ActorRole, type Phase3WorkflowStatus } from './phase3-workflow-policy.js';

declare module 'fastify' { interface FastifyRequest { phase3Auth?: AuthorizationContext } }

const idParam=z.object({id:z.string().regex(/^\d+$/)});
const assignmentInput=z.object({leadOpdId:z.coerce.number().int().positive(),supportingOpdIds:z.array(z.coerce.number().int().positive()).default([]),dueAt:z.string().datetime().nullable().optional()});
const submissionInput=z.object({responseText:z.string().trim().min(10).max(20000),factsData:z.string().trim().max(20000).nullable().optional(),keyMessage:z.string().trim().max(5000).nullable().optional(),supportingLinks:z.array(z.string().url().max(2000)).max(20).default([])});
const reviewInput=z.object({decision:z.enum(['REVISION_REQUIRED','APPROVED']),reason:z.string().trim().max(4000).nullable().optional()});

export async function registerPhase3WorkflowRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(401).send({error:'USER_INACTIVE_OR_MISSING'});request.phase3Auth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const actorRole=(ctx:AuthorizationContext):Phase3ActorRole=>(ctx.roles[0]||'viewer') as Phase3ActorRole;
 const event=async(issueId:string|number,ctx:AuthorizationContext,type:string,fromStatus:string|null,toStatus:string|null,note?:string|null,metadata:any={})=>pool.query(`INSERT INTO issue_workflow_events(issue_id,actor_user_id,actor_role,event_type,from_status,to_status,note,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb)`,[issueId,ctx.id,actorRole(ctx),type,fromStatus,toStatus,note||null,JSON.stringify(metadata||{})]);
 const workflow=async(issueId:string)=>{const {rows}=await pool.query(`SELECT w.*,i.title,i.description,i.status analytical_status,i.risk_level,i.momentum,lo.name lead_opd_name FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd lo ON lo.id=w.lead_opd_id WHERE w.issue_id=$1`,[issueId]);return rows[0]||null;};
 const canSee=(ctx:AuthorizationContext,w:any)=>ctx.roles.some(r=>['super_admin','humas','executive','viewer'].includes(r))||(ctx.roles.includes('opd')&&ctx.opdId&&(String(w.lead_opd_id)===String(ctx.opdId)));

 app.get('/api/phase3/issues',{preHandler:auth},async(request)=>{const ctx=request.phase3Auth!;const global=ctx.roles.some(r=>['super_admin','humas','executive','viewer'].includes(r));const params:any[]=[];let scope='';if(!global&&ctx.roles.includes('opd')){params.push(ctx.opdId);scope=`WHERE w.lead_opd_id=$1 OR EXISTS(SELECT 1 FROM issue_workflow_supporting_opd s WHERE s.issue_id=w.issue_id AND s.opd_id=$1)`}const {rows}=await pool.query(`SELECT w.issue_id,w.workflow_status,w.lead_opd_id,w.assigned_at,w.due_at,w.approved_at,w.published_at,w.closed_at,w.updated_at,i.title,i.description,i.status analytical_status,i.risk_level,i.momentum,o.name lead_opd_name,(SELECT COALESCE(json_agg(json_build_object('id',so.id,'name',so.name) ORDER BY so.name),'[]'::json) FROM issue_workflow_supporting_opd s JOIN opd so ON so.id=s.opd_id WHERE s.issue_id=w.issue_id) supporting_opds FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id ${scope} ORDER BY w.updated_at DESC,i.last_seen_at DESC`,params);return{data:rows};});

 app.get('/api/phase3/issues/:id',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_ISSUE_ID'});const w=await workflow(p.data.id);if(!w)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!canSee(request.phase3Auth!,w))return reply.code(403).send({error:'FORBIDDEN'});const supporting=(await pool.query(`SELECT o.id,o.name,o.code FROM issue_workflow_supporting_opd s JOIN opd o ON o.id=s.opd_id WHERE s.issue_id=$1 ORDER BY o.name`,[p.data.id])).rows;const submissions=(await pool.query(`SELECT s.*,o.name opd_name,u.email submitted_by_email,ru.email reviewed_by_email FROM issue_response_submissions s JOIN opd o ON o.id=s.opd_id JOIN users u ON u.id=s.submitted_by LEFT JOIN users ru ON ru.id=s.reviewed_by WHERE s.issue_id=$1 ORDER BY s.version DESC,s.created_at DESC`,[p.data.id])).rows;return{data:{...w,supportingOpds:supporting,submissions}};});

 app.post('/api/phase3/issues/:id/assign',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params),b=assignmentInput.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_ASSIGNMENT'});const ctx=request.phase3Auth!,role=actorRole(ctx);if(!canAssignPhase3(role))return reply.code(403).send({error:'FORBIDDEN'});const current=await workflow(p.data.id);if(!current)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!canTransitionPhase3(current.workflow_status as Phase3WorkflowStatus,'ASSIGNED',role)&&current.workflow_status!=='ASSIGNED')return reply.code(409).send({error:'INVALID_WORKFLOW_TRANSITION',from:current.workflow_status,to:'ASSIGNED'});const ids=[b.data.leadOpdId,...b.data.supportingOpdIds];const valid=await pool.query(`SELECT id FROM opd WHERE active=true AND id=ANY($1::bigint[])`,[ids]);if(valid.rows.length!==new Set(ids).size)return reply.code(400).send({error:'INVALID_OR_INACTIVE_OPD'});const client=await pool.connect();try{await client.query('BEGIN');await client.query(`UPDATE issue_workflows SET workflow_status='ASSIGNED',lead_opd_id=$1,assigned_by=$2,assigned_at=NOW(),due_at=$3,updated_by=$2,updated_at=NOW() WHERE issue_id=$4`,[b.data.leadOpdId,ctx.id,b.data.dueAt??null,p.data.id]);await client.query(`DELETE FROM issue_workflow_supporting_opd WHERE issue_id=$1`,[p.data.id]);for(const opdId of [...new Set(b.data.supportingOpdIds)].filter(x=>x!==b.data.leadOpdId)){await client.query(`INSERT INTO issue_workflow_supporting_opd(issue_id,opd_id,assigned_by) VALUES($1,$2,$3)`,[p.data.id,opdId,ctx.id]);}await client.query('COMMIT');await event(p.data.id,ctx,'ISSUE_ASSIGNED',current.workflow_status,'ASSIGNED',null,{leadOpdId:b.data.leadOpdId,supportingOpdIds:b.data.supportingOpdIds,dueAt:b.data.dueAt??null});return{data:await workflow(p.data.id)}}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}});

 app.post('/api/phase3/issues/:id/start',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_ISSUE_ID'});const ctx=request.phase3Auth!,w=await workflow(p.data.id);if(!w)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!ctx.roles.includes('opd')||!ctx.opdId||String(w.lead_opd_id)!==String(ctx.opdId))return reply.code(403).send({error:'ONLY_LEAD_OPD_CAN_START'});const role=actorRole(ctx);if(!canTransitionPhase3(w.workflow_status,'IN_PROGRESS',role))return reply.code(409).send({error:'INVALID_WORKFLOW_TRANSITION',from:w.workflow_status,to:'IN_PROGRESS'});await pool.query(`UPDATE issue_workflows SET workflow_status='IN_PROGRESS',updated_by=$1,updated_at=NOW() WHERE issue_id=$2`,[ctx.id,p.data.id]);await event(p.data.id,ctx,'WORK_STARTED',w.workflow_status,'IN_PROGRESS');return{data:await workflow(p.data.id)};});

 app.post('/api/phase3/issues/:id/submit',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params),b=submissionInput.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_SUBMISSION'});const ctx=request.phase3Auth!,w=await workflow(p.data.id);if(!w)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!ctx.roles.includes('opd')||!ctx.opdId||String(w.lead_opd_id)!==String(ctx.opdId))return reply.code(403).send({error:'ONLY_LEAD_OPD_CAN_SUBMIT'});const role=actorRole(ctx);if(!canTransitionPhase3(w.workflow_status,'SUBMITTED',role))return reply.code(409).send({error:'INVALID_WORKFLOW_TRANSITION',from:w.workflow_status,to:'SUBMITTED'});const next=Number((await pool.query(`SELECT COALESCE(MAX(version),0)+1 v FROM issue_response_submissions WHERE issue_id=$1 AND opd_id=$2`,[p.data.id,ctx.opdId])).rows[0].v);const {rows}=await pool.query(`INSERT INTO issue_response_submissions(issue_id,opd_id,submitted_by,version,response_text,facts_data,key_message,supporting_links,status,submitted_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,'SUBMITTED',NOW()) RETURNING *`,[p.data.id,ctx.opdId,ctx.id,next,b.data.responseText,b.data.factsData??null,b.data.keyMessage??null,JSON.stringify(b.data.supportingLinks)]);await pool.query(`UPDATE issue_workflows SET workflow_status='SUBMITTED',updated_by=$1,updated_at=NOW() WHERE issue_id=$2`,[ctx.id,p.data.id]);await event(p.data.id,ctx,'RESPONSE_SUBMITTED',w.workflow_status,'SUBMITTED',null,{submissionId:rows[0].id,version:next});return reply.code(201).send({data:rows[0]});});

 app.post('/api/phase3/issues/:id/review',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params),b=reviewInput.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_REVIEW'});const ctx=request.phase3Auth!,role=actorRole(ctx);if(!canReviewPhase3(role))return reply.code(403).send({error:'FORBIDDEN'});const w=await workflow(p.data.id);if(!w)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!canTransitionPhase3(w.workflow_status,b.data.decision,role))return reply.code(409).send({error:'INVALID_WORKFLOW_TRANSITION',from:w.workflow_status,to:b.data.decision});if(b.data.decision==='REVISION_REQUIRED'&&!b.data.reason)return reply.code(400).send({error:'REVISION_REASON_REQUIRED'});const latest=(await pool.query(`SELECT * FROM issue_response_submissions WHERE issue_id=$1 AND status='SUBMITTED' ORDER BY version DESC LIMIT 1`,[p.data.id])).rows[0];if(!latest)return reply.code(409).send({error:'NO_SUBMITTED_RESPONSE'});await pool.query(`UPDATE issue_response_submissions SET status=$1,review_reason=$2,reviewed_by=$3,reviewed_at=NOW(),updated_at=NOW() WHERE id=$4`,[b.data.decision,b.data.reason??null,ctx.id,latest.id]);await pool.query(`UPDATE issue_workflows SET workflow_status=$1,approved_by=CASE WHEN $1='APPROVED' THEN $2 ELSE approved_by END,approved_at=CASE WHEN $1='APPROVED' THEN NOW() ELSE approved_at END,updated_by=$2,updated_at=NOW() WHERE issue_id=$3`,[b.data.decision,ctx.id,p.data.id]);await event(p.data.id,ctx,b.data.decision==='APPROVED'?'RESPONSE_APPROVED':'REVISION_REQUESTED',w.workflow_status,b.data.decision,b.data.reason,{submissionId:latest.id});return{data:await workflow(p.data.id)};});

 app.get('/api/phase3/issues/:id/events',{preHandler:auth},async(request,reply)=>{const p=idParam.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_ISSUE_ID'});const w=await workflow(p.data.id);if(!w)return reply.code(404).send({error:'ISSUE_WORKFLOW_NOT_FOUND'});if(!canSee(request.phase3Auth!,w))return reply.code(403).send({error:'FORBIDDEN'});return{data:(await pool.query(`SELECT e.*,u.email actor_email FROM issue_workflow_events e LEFT JOIN users u ON u.id=e.actor_user_id WHERE e.issue_id=$1 ORDER BY e.created_at DESC LIMIT 200`,[p.data.id])).rows};});
}
