import type { FastifyInstance, FastifyRequest } from 'fastify';
import type { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { hasPermission, loadAuthorizationContext, type AuthorizationContext } from './rbac.js';

declare module 'fastify' { interface FastifyRequest { phase5Auth?: AuthorizationContext } }

const paramsSchema=z.object({issueId:z.string().regex(/^\d+$/),workflowId:z.string().regex(/^\d+$/)});
const strategyFields=z.object({
 executiveSummary:z.string().trim().max(12000).nullable().optional(),
 communicationObjectives:z.array(z.any()).default([]),
 targetAudiences:z.array(z.any()).default([]),
 keyMessages:z.array(z.any()).default([]),
 talkingPoints:z.array(z.any()).default([]),
 channelStrategy:z.array(z.any()).default([]),
 timingStrategy:z.record(z.string(),z.any()).default({}),
 spokespersonStrategy:z.array(z.any()).default([]),
 contentFormats:z.array(z.any()).default([]),
 communicationRisks:z.array(z.any()).default([]),
 successKpis:z.array(z.any()).default([])
});
const reviewSchema=z.object({note:z.string().trim().max(4000).nullable().optional()});
const districtFields=z.object({
 evidenceContext:z.record(z.string(),z.any()).default({}),localAudiences:z.array(z.any()).default([]),communicationFocus:z.array(z.any()).default([]),localMessages:z.array(z.any()).default([]),talkingPoints:z.array(z.any()).default([]),localChannels:z.array(z.any()).default([]),coordinationOpds:z.array(z.any()).default([]),timingStrategy:z.record(z.string(),z.any()).default({}),successKpis:z.array(z.any()).default([]),fieldUpdateRequirements:z.array(z.any()).default([])
});
async function generateStrategyWithGemini(input:any){
 const key=process.env.GEMINI_API_KEY;if(!key)throw new Error('GEMINI_API_KEY_MISSING');
 const model=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite';
 const prompt=`Anda adalah mesin strategi komunikasi Pemerintah Kota Batam. Susun DRAFT strategi komunikasi berbasis data yang diberikan. Jangan mengarang fakta. Bedakan pesan induk Pemko dan arahan kewilayahan. Arahan kecamatan hanya untuk kecamatan yang tercantum dalam input. Pesan lokal harus konsisten dengan pesan induk. Historical learning adalah pembelajaran, bukan fakta kondisi saat ini.

Output JSON:
{"executiveSummary":"...","communicationObjectives":[],"targetAudiences":[],"keyMessages":[],"talkingPoints":[],"channelStrategy":[],"timingStrategy":{},"spokespersonStrategy":[],"contentFormats":[],"communicationRisks":[],"successKpis":[],"districtStrategies":[{"districtId":1,"evidenceContext":{},"localAudiences":[],"communicationFocus":[],"localMessages":[],"talkingPoints":[],"localChannels":[],"coordinationOpds":[],"timingStrategy":{},"successKpis":[],"fieldUpdateRequirements":[]}]}

DATA:
${JSON.stringify(input).slice(0,50000)}`;
 const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json'}})});
 if(!r.ok)throw new Error(`Gemini HTTP ${r.status}`);const payload=await r.json() as any,raw=payload.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||'').join('');if(!raw)throw new Error('GEMINI_EMPTY_RESPONSE');return JSON.parse(raw);
}

export async function registerPhase5StrategyRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(401).send({error:'USER_INACTIVE_OR_MISSING'});request.phase5Auth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const workflow=async(issueId:string,workflowId:string)=>(await pool.query(`SELECT w.*,i.title,i.description,i.risk_level,i.momentum,i.geographic_scope,o.name lead_opd_name FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id WHERE w.id=$1 AND w.issue_id=$2`,[workflowId,issueId])).rows[0]||null;
 const snapshot=async(w:any)=>{
  const [gap,response,publication,monitoring,keywords,districts]=await Promise.all([
   pool.query('SELECT * FROM issue_communication_gap_snapshots WHERE workflow_id=$1',[w.id]),
   pool.query("SELECT response_text,facts_data,key_message,supporting_links,version,approved_at FROM issue_response_submissions WHERE workflow_id=$1 AND status='APPROVED' ORDER BY version DESC LIMIT 1",[w.id]),
   pool.query('SELECT result,gap_analyzed_at,analyzed_at FROM issue_publication_analysis_snapshots WHERE workflow_id=$1',[w.id]),
   pool.query('SELECT period_number,result,evidence_summary,period_started_at,period_ended_at,analyzed_at FROM issue_monitoring_analysis_snapshots WHERE workflow_id=$1 ORDER BY period_number',[w.id]),
   pool.query("SELECT k.term,ik.keyword_role FROM issue_keywords ik JOIN keywords k ON k.id=ik.keyword_id WHERE ik.issue_id=$1 ORDER BY CASE WHEN ik.keyword_role='PRIMARY' THEN 0 ELSE 1 END,k.term",[w.issue_id]),
   pool.query(`SELECT d.id,d.name FROM issue_districts x JOIN districts d ON d.id=x.district_id WHERE x.issue_id=$1 UNION SELECT d.id,d.name FROM issue_workflow_contributors c JOIN districts d ON d.id=c.district_id WHERE c.workflow_id=$2 AND c.contributor_type='DISTRICT' ORDER BY name`,[w.issue_id,w.id])
  ]);
  const previous=(await pool.query(`SELECT pw.id workflow_id,pw.cycle_number,cs.id strategy_id,cs.version strategy_version,cs.executive_summary,pa.result publication_analysis,ma.result final_monitoring_analysis FROM issue_workflows pw LEFT JOIN LATERAL (SELECT s.* FROM communication_strategies s WHERE s.workflow_id=pw.id AND s.status IN ('APPROVED','SUPERSEDED') ORDER BY s.version DESC LIMIT 1) cs ON true LEFT JOIN issue_publication_analysis_snapshots pa ON pa.workflow_id=pw.id LEFT JOIN LATERAL (SELECT m.result FROM issue_monitoring_analysis_snapshots m WHERE m.workflow_id=pw.id ORDER BY m.period_number DESC LIMIT 1) ma ON true WHERE pw.issue_id=$1 AND pw.cycle_number<$2 AND pw.workflow_status='CLOSED' ORDER BY pw.cycle_number DESC LIMIT 1`,[w.issue_id,w.cycle_number])).rows[0]||null;
  return {capturedAt:new Date().toISOString(),previousCycleLearning:previous,issue:{id:w.issue_id,title:w.title,description:w.description,riskLevel:w.risk_level,momentum:w.momentum,geographicScope:w.geographic_scope},workflow:{id:w.id,cycleNumber:w.cycle_number,status:w.workflow_status,leadOpdId:w.lead_opd_id,leadOpdName:w.lead_opd_name},keywords:keywords.rows,districts:districts.rows,gap:gap.rows[0]||null,approvedResponse:response.rows[0]||null,publicationAnalysis:publication.rows[0]||null,monitoringAnalysis:monitoring.rows};
 };
 const requireRead=(ctx:AuthorizationContext)=>hasPermission(ctx,'strategy.read')||hasPermission(ctx,'strategy.manage');
 const requireManage=(ctx:AuthorizationContext)=>hasPermission(ctx,'strategy.manage');

 app.get('/api/phase5/strategies',{preHandler:auth},async(request,reply)=>{
  const ctx=request.phase5Auth!;if(!requireRead(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  const rows=(await pool.query(`SELECT w.id workflow_id,w.issue_id,w.cycle_number,w.workflow_status,i.title issue_title,i.risk_level,i.momentum,o.name lead_opd_name,s.id strategy_id,s.version strategy_version,s.status strategy_status,s.is_current,s.updated_at strategy_updated_at,EXISTS(SELECT 1 FROM issue_communication_gap_snapshots g WHERE g.workflow_id=w.id) gap_ready,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',d.id,'name',d.name) ORDER BY d.name) FROM issue_districts x JOIN districts d ON d.id=x.district_id WHERE x.issue_id=w.issue_id),'[]'::jsonb) districts FROM issue_workflows w JOIN issues i ON i.id=w.issue_id LEFT JOIN opd o ON o.id=w.lead_opd_id LEFT JOIN LATERAL (SELECT cs.* FROM communication_strategies cs WHERE cs.workflow_id=w.id ORDER BY CASE WHEN cs.status IN ('DRAFT','IN_REVIEW') THEN 0 WHEN cs.is_current THEN 1 ELSE 2 END,cs.version DESC LIMIT 1) s ON true WHERE w.workflow_status<>'CLOSED' OR s.id IS NOT NULL ORDER BY COALESCE(s.updated_at,w.updated_at) DESC LIMIT 200`)).rows;
  return{data:rows};
 });

 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireRead(ctx))return reply.code(403).send({error:'FORBIDDEN'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});
  const rows=(await pool.query('SELECT * FROM communication_strategies WHERE workflow_id=$1 ORDER BY version DESC',[w.id])).rows;return{data:{workflow:w,strategies:rows}};
 });
 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/districts',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_STRATEGY'});const ctx=request.phase5Auth!;if(!requireRead(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});
  const rows=(await pool.query(`SELECT d.*,x.name district_name FROM communication_strategy_districts d JOIN communication_strategies s ON s.id=d.strategy_id JOIN districts x ON x.id=d.district_id WHERE s.workflow_id=$1 AND s.issue_id=$2 AND s.version=$3 ORDER BY x.name`,[p.data.workflowId,p.data.issueId,p.data.version])).rows;return{data:rows};
 });

 app.get('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/district',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!ctx.roles.includes('district')||!ctx.districtId)return reply.code(403).send({error:'DISTRICT_ACCOUNT_REQUIRED'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});
  const involved=(await pool.query("SELECT 1 FROM issue_workflow_contributors WHERE workflow_id=$1 AND contributor_type='DISTRICT' AND district_id=$2 UNION SELECT 1 FROM issue_districts WHERE issue_id=$3 AND district_id=$2 LIMIT 1",[w.id,ctx.districtId,w.issue_id])).rows[0];if(!involved)return reply.code(403).send({error:'DISTRICT_NOT_INVOLVED'});
  const row=(await pool.query(`SELECT s.id strategy_id,s.version,s.status,s.approved_at,s.executive_summary,d.id district_strategy_id,d.district_id,d.evidence_context,d.local_audiences,d.communication_focus,d.local_messages,d.talking_points,d.local_channels,d.coordination_opds,d.timing_strategy,d.success_kpis,d.field_update_requirements FROM communication_strategies s JOIN communication_strategy_districts d ON d.strategy_id=s.id WHERE s.workflow_id=$1 AND d.district_id=$2 AND s.status='APPROVED' AND s.is_current=TRUE LIMIT 1`,[w.id,ctx.districtId])).rows[0];if(!row)return reply.code(404).send({error:'APPROVED_DISTRICT_STRATEGY_NOT_FOUND'});return{data:row};
 });

 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/draft',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});const gap=(await pool.query('SELECT 1 FROM issue_communication_gap_snapshots WHERE workflow_id=$1',[w.id])).rows[0];if(!gap)return reply.code(409).send({error:'COMMUNICATION_GAP_REQUIRED'});const open=(await pool.query("SELECT * FROM communication_strategies WHERE workflow_id=$1 AND status IN ('DRAFT','IN_REVIEW') ORDER BY version DESC LIMIT 1",[w.id])).rows[0];if(open)return reply.code(409).send({error:'OPEN_STRATEGY_EXISTS',data:open});
  const version=Number((await pool.query('SELECT COALESCE(MAX(version),0)+1 v FROM communication_strategies WHERE workflow_id=$1',[w.id])).rows[0].v),input=await snapshot(w);
  const generated=await generateStrategyWithGemini(input);
  const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query("INSERT INTO communication_strategies(workflow_id,issue_id,version,status,input_snapshot,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,success_kpis,generated_by,generated_at,created_by,updated_by) VALUES($1,$2,$3,'DRAFT',$4::jsonb,$5,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14::jsonb,$15::jsonb,$16,NOW(),$16,$16) RETURNING *",[w.id,w.issue_id,version,JSON.stringify(input),generated.executiveSummary||null,JSON.stringify(generated.communicationObjectives||[]),JSON.stringify(generated.targetAudiences||[]),JSON.stringify(generated.keyMessages||[]),JSON.stringify(generated.talkingPoints||[]),JSON.stringify(generated.channelStrategy||[]),JSON.stringify(generated.timingStrategy||{}),JSON.stringify(generated.spokespersonStrategy||[]),JSON.stringify(generated.contentFormats||[]),JSON.stringify(generated.communicationRisks||[]),JSON.stringify(generated.successKpis||[]),ctx.id])).rows[0];
  const allowed=new Set((input.districts||[]).map((d:any)=>Number(d.id)));for(const ds of (generated.districtStrategies||[])){const districtId=Number(ds.districtId);if(!allowed.has(districtId))continue;await client.query(`INSERT INTO communication_strategy_districts(strategy_id,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb,$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb)`,[row.id,w.id,districtId,JSON.stringify(ds.evidenceContext||{}),JSON.stringify(ds.localAudiences||[]),JSON.stringify(ds.communicationFocus||[]),JSON.stringify(ds.localMessages||[]),JSON.stringify(ds.talkingPoints||[]),JSON.stringify(ds.localChannels||[]),JSON.stringify(ds.coordinationOpds||[]),JSON.stringify(ds.timingStrategy||{}),JSON.stringify(ds.successKpis||[]),JSON.stringify(ds.fieldUpdateRequirements||[])]);}await client.query('COMMIT');return reply.code(201).send({data:row});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
 app.put('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params),b=strategyFields.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_STRATEGY'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});
  const v=b.data;const row=(await pool.query(`UPDATE communication_strategies SET executive_summary=$1,communication_objectives=$2::jsonb,target_audiences=$3::jsonb,key_messages=$4::jsonb,talking_points=$5::jsonb,channel_strategy=$6::jsonb,timing_strategy=$7::jsonb,spokesperson_strategy=$8::jsonb,content_formats=$9::jsonb,communication_risks=$10::jsonb,success_kpis=$11::jsonb,updated_by=$12,updated_at=NOW() WHERE workflow_id=$13 AND issue_id=$14 AND version=$15 AND status='DRAFT' RETURNING *`,[v.executiveSummary||null,JSON.stringify(v.communicationObjectives),JSON.stringify(v.targetAudiences),JSON.stringify(v.keyMessages),JSON.stringify(v.talkingPoints),JSON.stringify(v.channelStrategy),JSON.stringify(v.timingStrategy),JSON.stringify(v.spokespersonStrategy),JSON.stringify(v.contentFormats),JSON.stringify(v.communicationRisks),JSON.stringify(v.successKpis),ctx.id,p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!row)return reply.code(409).send({error:'STRATEGY_NOT_EDITABLE'});return{data:row};
 });
 app.put('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/district/:districtId',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive(),districtId:z.coerce.number().int().positive()}).safeParse(request.params),b=districtFields.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_DISTRICT_STRATEGY'});const ctx=request.phase5Auth!;if(!requireManage(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const v=b.data;
  const row=(await pool.query(`UPDATE communication_strategy_districts d SET evidence_context=$1::jsonb,local_audiences=$2::jsonb,communication_focus=$3::jsonb,local_messages=$4::jsonb,talking_points=$5::jsonb,local_channels=$6::jsonb,coordination_opds=$7::jsonb,timing_strategy=$8::jsonb,success_kpis=$9::jsonb,field_update_requirements=$10::jsonb,updated_at=NOW() FROM communication_strategies s WHERE d.strategy_id=s.id AND s.workflow_id=$11 AND s.issue_id=$12 AND s.version=$13 AND s.status='DRAFT' AND d.district_id=$14 RETURNING d.*`,[JSON.stringify(v.evidenceContext),JSON.stringify(v.localAudiences),JSON.stringify(v.communicationFocus),JSON.stringify(v.localMessages),JSON.stringify(v.talkingPoints),JSON.stringify(v.localChannels),JSON.stringify(v.coordinationOpds),JSON.stringify(v.timingStrategy),JSON.stringify(v.successKpis),JSON.stringify(v.fieldUpdateRequirements),p.data.workflowId,p.data.issueId,p.data.version,p.data.districtId])).rows[0];if(!row)return reply.code(409).send({error:'DISTRICT_STRATEGY_NOT_EDITABLE'});return{data:row};
 });

 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/review',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params),b=reviewSchema.safeParse(request.body);if(!p.success||!b.success)return reply.code(400).send({error:'INVALID_REVIEW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const row=(await pool.query("UPDATE communication_strategies SET status='IN_REVIEW',review_note=$1,reviewed_by=$2,reviewed_at=NOW(),updated_by=$2,updated_at=NOW() WHERE workflow_id=$3 AND issue_id=$4 AND version=$5 AND status='DRAFT' RETURNING *",[b.data.note||null,ctx.id,p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!row)return reply.code(409).send({error:'STRATEGY_NOT_DRAFT'});return{data:row};
 });
 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/:version/approve',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.extend({version:z.coerce.number().int().positive()}).safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_APPROVAL'});const ctx=request.phase5Auth!;if(!requireManage(ctx)||!ctx.roles.some(r=>['super_admin','humas'].includes(r)))return reply.code(403).send({error:'FORBIDDEN'});const client=await pool.connect();try{await client.query('BEGIN');const target=(await client.query("SELECT id FROM communication_strategies WHERE workflow_id=$1 AND issue_id=$2 AND version=$3 AND status='IN_REVIEW' FOR UPDATE",[p.data.workflowId,p.data.issueId,p.data.version])).rows[0];if(!target){await client.query('ROLLBACK');return reply.code(409).send({error:'STRATEGY_NOT_IN_REVIEW'});}await client.query("UPDATE communication_strategies SET status='SUPERSEDED',is_current=FALSE,updated_by=$1,updated_at=NOW() WHERE workflow_id=$2 AND status='APPROVED' AND is_current=TRUE",[ctx.id,p.data.workflowId]);const row=(await client.query("UPDATE communication_strategies SET status='APPROVED',is_current=TRUE,approved_by=$1,approved_at=NOW(),updated_by=$1,updated_at=NOW() WHERE id=$2 RETURNING *",[ctx.id,target.id])).rows[0];await client.query('COMMIT');return{data:row};}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
 app.post('/api/phase5/issues/:issueId/workflows/:workflowId/strategy/revise',{preHandler:auth},async(request,reply)=>{
  const p=paramsSchema.safeParse(request.params);if(!p.success)return reply.code(400).send({error:'INVALID_WORKFLOW'});const ctx=request.phase5Auth!;if(!requireManage(ctx))return reply.code(403).send({error:'FORBIDDEN'});const approved=(await pool.query("SELECT * FROM communication_strategies WHERE workflow_id=$1 AND issue_id=$2 AND status='APPROVED' ORDER BY version DESC LIMIT 1",[p.data.workflowId,p.data.issueId])).rows[0];if(!approved)return reply.code(409).send({error:'APPROVED_STRATEGY_REQUIRED'});const open=(await pool.query("SELECT 1 FROM communication_strategies WHERE workflow_id=$1 AND status IN ('DRAFT','IN_REVIEW') LIMIT 1",[p.data.workflowId])).rows[0];if(open)return reply.code(409).send({error:'OPEN_STRATEGY_EXISTS'});const w=await workflow(p.data.issueId,p.data.workflowId);if(!w)return reply.code(404).send({error:'WORKFLOW_NOT_FOUND'});const input=await snapshot(w),version=Number(approved.version)+1;
  const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`INSERT INTO communication_strategies(workflow_id,issue_id,version,status,input_snapshot,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,success_kpis,generated_by,generated_at,created_by,updated_by) SELECT workflow_id,issue_id,$1,'DRAFT',$2::jsonb,executive_summary,communication_objectives,target_audiences,key_messages,talking_points,channel_strategy,timing_strategy,spokesperson_strategy,content_formats,communication_risks,success_kpis,$3,NOW(),$3,$3 FROM communication_strategies WHERE id=$4 RETURNING *`,[version,JSON.stringify(input),ctx.id,approved.id])).rows[0];await client.query(`INSERT INTO communication_strategy_districts(strategy_id,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements) SELECT $1,workflow_id,district_id,evidence_context,local_audiences,communication_focus,local_messages,talking_points,local_channels,coordination_opds,timing_strategy,success_kpis,field_update_requirements FROM communication_strategy_districts WHERE strategy_id=$2`,[row.id,approved.id]);await client.query('COMMIT');return reply.code(201).send({data:row});}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}
 });
}
