import { FastifyInstance, FastifyRequest } from 'fastify';
import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { classifyIssueWithTaxonomy } from './phase2e-taxonomy.js';
import { evaluatePrintIssueLinkage } from './print-issue-linkage.js';

declare module 'fastify' { interface FastifyRequest { printAnalysisRecoveryAuth?: AuthorizationContext } }

const norm=(v:any)=>String(v||'').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim();
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const hits=(text:string,words:string[])=>words.filter(w=>text.includes(w));
const count=(text:string,term:string)=>{if(!term)return 0;let n=0,p=0;while((p=text.indexOf(term,p))!==-1){n++;p+=Math.max(1,term.length);}return n;};
const uniq=<T>(items:T[])=>[...new Set(items)];
const splitKeyword=(raw:any)=>{const source=String(raw||'');const parts=source.split(/[,;\n|]+/g).map(norm).filter(v=>v.length>=3);if(parts.length>1)return uniq(parts);const one=norm(source);return one?[one]:[];};
const OPD_STOP=new Set(['dinas','badan','bagian','kantor','kota','batam','pemerintah','pemko','sekretariat','daerah','dan','serta','bidang','upt','uptd']);
const OCR_NOISE=new Set(['halaman','page','epaper','koran','berita','headline','selasa','senin','rabu','kamis','jumat','sabtu','minggu','edisi','rubrik','kolom','foto','dok','istimewa','kompas','tribun','batampos','batam','indonesia']);
function phraseAliases(name:any,code:any){const n=norm(name),c=norm(code);const words=n.split(' ').filter(Boolean);const meaningful=words.filter(w=>!OPD_STOP.has(w)&&w.length>=3);const aliases=[n,c];if(meaningful.length>=2)aliases.push(meaningful.join(' '));const initials=meaningful.map(w=>w[0]).join('');if(initials.length>=3)aliases.push(initials);if(n.includes('komunikasi')&&n.includes('informatika'))aliases.push('kominfo','diskominfo','diskominfo batam');if(n.includes('lingkungan hidup'))aliases.push('dlh','dinas lingkungan hidup');if(n.includes('pekerjaan umum'))aliases.push('pu','pupr','dinas pu');if(n.includes('perhubungan'))aliases.push('dishub');if(n.includes('kesehatan'))aliases.push('dinkes');if(n.includes('pendidikan'))aliases.push('disdik');if(n.includes('sosial'))aliases.push('dinsos');if(n.includes('kepemudaan')&&n.includes('olahraga'))aliases.push('dispora','disporapar','dinas pemuda dan olahraga');return uniq(aliases.map(norm).filter(a=>a.length>=3));}
function keywordNoiseReason(raw:any){const v=norm(raw);if(!v)return'kosong';if(v.length<3)return'terlalu pendek';if(/^\d{6,}$/.test(v)||/^\d{6,}[a-z]+$/.test(v)||/^[a-z]+\d{6,}$/.test(v))return'pola tanggal/nomor OCR';if((v.match(/\d/g)||[]).length>=4)return'terlalu banyak angka';if(OCR_NOISE.has(v))return'kata generik hasil OCR/metadata cetak';if(/^halaman\s*\d*$/.test(v)||/^page\s*\d*$/.test(v))return'penanda halaman';return null;}
function floodCalibration(text:string){
 const weather=hits(text,['hujan deras','diguyur hujan','hujan']);
 const hazard=hits(text,['banjir','genangan','tergenang','terendam','rendam','air meluap','luapan']);
 const impact=hits(text,['jalan','simpang','akses','rumah','permukiman','kendaraan','kemacetan','macet','drainase','arus lalu lintas','lalu lintas','lalulintas','lalu lintas tersendat','lalulintas tersendat','tersendat']);
 const severe=hits(text,['akses terputus','jalan terputus','rumah terendam','evakuasi','korban','kerusakan','darurat','status darurat']);
 const contextualImpact=hazard.length>0&&impact.length>0;
 const weatherRelated=contextualImpact&&weather.length>0;
 const negativeWeight=contextualImpact?2:0;
 const baseRiskBonus=contextualImpact?28:0;
 const severeRiskBonus=contextualImpact&&severe.length?Math.min(24,12+severe.length*6):0;
 return{weather,hazard,impact,severe,contextualImpact,weatherRelated,negativeWeight,riskBonus:baseRiskBonus+severeRiskBonus};
}

export async function registerPrintAnalysisRecoveryRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.printAnalysisRecoveryAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const canAnalyze=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');
 app.post('/api/print/articles/:id/mark-analyzed-v2',{preHandler:auth},async(request,reply)=>{
  const ctx=request.printAnalysisRecoveryAuth!;if(!canAnalyze(ctx))return reply.code(403).send({error:'ANALYSIS_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});
  const current=(await pool.query(`SELECT id,title,summary,body_text,is_headline,status,opd_id,district_id,verified_by,verified_at FROM print_articles WHERE id=$1`,[id.data])).rows[0];if(!current)return reply.code(404).send({error:'NOT_FOUND'});if(String(current.status)!=='verified')return reply.code(409).send({error:'ARTICLE_MUST_BE_VERIFIED_FIRST',message:`Clipping harus berstatus Verified sebelum dianalisis. Status saat ini: ${current.status}.`});
  const safe=async<T=any>(sql:string,params:any[]=[]):Promise<T[]>=>{try{return(await pool.query(sql,params)).rows as T[];}catch(e){console.warn('Phase2E optional intelligence source skipped',String((e as any)?.message||e));return[];}};
  const [official,operator,opds,districts,villages,taxonomyMappings]=await Promise.all([safe(`SELECT k.id,k.keyword,k.opd_id,k.group_id,k.match_type,k.priority,kg.name group_name FROM keywords k LEFT JOIN keyword_groups kg ON kg.id=k.group_id WHERE k.active=true ORDER BY k.priority DESC,k.id`),safe(`SELECT keyword_text FROM print_article_keywords WHERE article_id=$1 AND source='operator' ORDER BY keyword_text`,[id.data]),safe(`SELECT id,name,code FROM opd WHERE active=true ORDER BY name`),safe(`SELECT id,name,code FROM districts WHERE active=true ORDER BY name`),safe(`SELECT id,name,district_id FROM villages WHERE active=true ORDER BY name`),safe(`SELECT k.id keyword_id,k.keyword,k.priority,tc.code taxonomy_code,tc.name taxonomy_name,kt.weight FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true WHERE k.active=true ORDER BY k.priority DESC,kt.weight DESC,k.id`)]);
  const title=norm(current.title),summary=norm(current.summary),body=norm(current.body_text),text=`${title} ${summary} ${body}`.trim();const positive=hits(text,['apresiasi','berhasil','meningkat','tumbuh','positif','penghargaan','prestasi','membaik','solusi','dukungan','optimistis','lancar']);const negative=hits(text,['keluhan','gagal','rusak','macet','banjir','sampah','protes','kritik','buruk','terlambat','masalah','konflik','penolakan','kerugian','korban']);const high=hits(text,['darurat','krisis','kecelakaan','kebakaran','korupsi','demonstrasi','unjuk rasa','pencemaran','wabah','longsor','bencana','pidana']);const critical=hits(text,['meninggal','tewas','ledakan','kerusuhan','tersangka','ditangkap','evakuasi','status darurat']);const flood=floodCalibration(text);const delta=positive.length-negative.length-high.length*2-critical.length*2-flood.negativeWeight;const sentiment=delta>=2?'positive':delta<=-2?'negative':'neutral';let risk=8+negative.length*7+high.length*15+critical.length*24+flood.riskBonus+(current.is_headline?8:0);if(sentiment==='positive')risk-=8;risk=clamp(risk);const riskLevel=risk>=80?'CRITICAL':risk>=60?'HIGH':risk>=35?'MEDIUM':'LOW';
  const officialMatches=(official as any[]).flatMap(k=>splitKeyword(k.keyword).map(term=>{const tc=count(title,term),sc=count(summary,term),bc=count(body,term),total=tc+sc+bc;if(!total)return null;return{keywordId:Number(k.id),keyword:term,keywordSet:String(k.keyword),source:'official',groupId:k.group_id==null?null:Number(k.group_id),groupName:k.group_name||null,opdId:k.opd_id==null?null:Number(k.opd_id),priority:Math.max(1,Math.min(3,Number(k.priority||2))),fields:[tc?'title':null,sc?'summary':null,bc?'body':null].filter(Boolean),occurrences:{title:tc,summary:sc,body:bc,total}};}).filter(Boolean));
  const operatorEvaluated=(operator as any[]).map(k=>{const keyword=String(k.keyword_text||'').trim(),term=norm(keyword),noiseReason=keywordNoiseReason(keyword),tc=count(title,term),sc=count(summary,term),bc=count(body,term),total=tc+sc+bc;return{keyword,source:'operator',fields:[tc?'title':null,sc?'summary':null,bc?'body':null].filter(Boolean),occurrences:{title:tc,summary:sc,body:bc,total},presentInText:total>0,noiseReason};});const operatorMatches=operatorEvaluated.filter(k=>k.presentInText&&!k.noiseReason);const operatorNoise=operatorEvaluated.filter(k=>Boolean(k.noiseReason)).map(k=>({keyword:k.keyword,reason:k.noiseReason,presentInText:k.presentInText}));const operatorNotFound=operatorEvaluated.filter(k=>!k.presentInText&&!k.noiseReason).map(k=>k.keyword);
  const classified=classifyIssueWithTaxonomy(title,summary,body,taxonomyMappings as any[],operatorMatches);const issueCategory=classified.issueCategory;const categoryEvidence=classified.categoryEvidence;
  const opdScores=new Map<number,{score:number;evidence:Set<string>}>();const addOpd=(opdId:number,score:number,evidence:string)=>{const v=opdScores.get(opdId)||{score:0,evidence:new Set<string>()};v.score+=score;v.evidence.add(evidence);opdScores.set(opdId,v);};for(const k of officialMatches as any[]){if(k.opdId!=null)addOpd(k.opdId,k.priority*3+Math.min(4,k.occurrences.total),`keyword resmi “${k.keyword}” terkait OPD`);}for(const o of opds as any[]){for(const alias of phraseAliases(o.name,o.code)){const tc=count(title,alias),sc=count(summary,alias),bc=count(body,alias),total=tc+sc+bc;if(!total)continue;const exactName=alias===norm(o.name);addOpd(Number(o.id),(tc*(exactName?9:7))+(sc*(exactName?6:4))+(bc*(exactName?4:3)),`alias OPD “${alias}” disebut ${total}x${tc?' (judul)':''}`);}}const opdRank=[...opdScores.entries()].map(([opdId,v])=>({id:opdId,name:String((opds as any[]).find(o=>Number(o.id)===opdId)?.name||`OPD #${opdId}`),score:v.score,evidence:[...v.evidence]})).sort((a,b)=>b.score-a.score);const detectedOpdObj=opdRank[0]||null;
  const districtScores=new Map<number,{score:number;evidence:Set<string>}>();const addDistrict=(districtId:number,score:number,evidence:string)=>{const v=districtScores.get(districtId)||{score:0,evidence:new Set<string>()};v.score+=score;v.evidence.add(evidence);districtScores.set(districtId,v);};for(const d of districts as any[]){const dn=norm(d.name);const aliases=uniq([dn,`kecamatan ${dn}`,norm(d.code)].filter(a=>a&&a.length>=3));for(const alias of aliases){const tc=count(title,alias),sc=count(summary,alias),bc=count(body,alias),total=tc+sc+bc;if(total)addDistrict(Number(d.id),tc*8+sc*5+bc*3,`kecamatan “${d.name}”/alias “${alias}” disebut ${total}x${tc?' (judul)':''}`);}}for(const v of villages as any[]){const vn=norm(v.name);if(vn.length<4)continue;const tc=count(title,vn),sc=count(summary,vn),bc=count(body,vn),total=tc+sc+bc;if(total)addDistrict(Number(v.district_id),tc*6+sc*4+bc*2,`kelurahan “${v.name}” disebut ${total}x`);}const districtRank=[...districtScores.entries()].map(([districtId,v])=>({id:districtId,name:String((districts as any[]).find(d=>Number(d.id)===districtId)?.name||`Kecamatan #${districtId}`),score:v.score,evidence:[...v.evidence]})).sort((a,b)=>b.score-a.score);const detectedDistrict=districtRank[0]||null;
  const selectedOpd=(opds as any[]).find(o=>Number(o.id)===Number(current.opd_id)),selectedDistrict=(districts as any[]).find(d=>Number(d.id)===Number(current.district_id));const opdMatch=current.opd_id==null?'UNSET':!detectedOpdObj?'UNDETECTED':Number(current.opd_id)===detectedOpdObj.id?'MATCH':'MISMATCH';const districtMatch=current.district_id==null?'UNSET':!detectedDistrict?'UNDETECTED':Number(current.district_id)===detectedDistrict.id?'MATCH':'MISMATCH';const validationEvidence=[...(detectedOpdObj?.evidence||[]),...(detectedDistrict?.evidence||[])];const entityValidation={selected:{opdId:current.opd_id==null?null:Number(current.opd_id),opdName:selectedOpd?.name||null,districtId:current.district_id==null?null:Number(current.district_id),districtName:selectedDistrict?.name||null},detected:{opd:detectedOpdObj,district:detectedDistrict},opdMatch,districtMatch,reviewRequired:opdMatch==='MISMATCH'||districtMatch==='MISMATCH',evidence:validationEvidence,note:'UNDETECTED berarti teks tidak memberi bukti cukup. Sistem tidak menganggap metadata manual sebagai hasil deteksi dan tidak menimpa data yang diverifikasi manusia.'};
  const officialImportance=Math.min(24,(officialMatches as any[]).reduce((s,k)=>s+(k.priority*2)+Math.min(4,k.occurrences.total)+(k.fields.includes('title')?4:0),0));const operatorImportance=Math.min(8,operatorMatches.reduce((s,k)=>s+1+Math.min(2,k.occurrences.total)+(k.fields.includes('title')?2:0),0));const importance=clamp(15+(current.is_headline?28:0)+officialImportance+operatorImportance+Math.min(20,Math.floor(text.length/500)*3)+risk*.32);const confidence=text.length>=1800&&(negative.length+high.length+critical.length+positive.length+officialMatches.length+operatorMatches.length+(flood.contextualImpact?2:0))>=3?'HIGH':text.length>=600?'MEDIUM':'LOW';const signals=[current.is_headline?'Headline/front-page indicator':null,`Kategori isu: ${issueCategory} (score ${categoryEvidence.winnerScore}; ${categoryEvidence.source})`,officialMatches.length?`Keyword resmi terdeteksi: ${(officialMatches as any[]).map(k=>k.keyword).join(', ')}`:null,operatorMatches.length?`Keyword operator valid terkonfirmasi di teks: ${operatorMatches.map(k=>k.keyword).join(', ')}`:null,operatorNoise.length?`Noise keyword diabaikan: ${operatorNoise.slice(0,8).map(k=>k.keyword).join(', ')}`:null,detectedOpdObj?`OPD terdeteksi: ${detectedOpdObj.name} (${opdMatch})`:null,detectedDistrict?`Kecamatan terdeteksi: ${detectedDistrict.name} (${districtMatch})`:null,negative.length?`Sinyal negatif: ${negative.join(', ')}`:null,high.length?`Sinyal risiko: ${high.join(', ')}`:null,critical.length?`Sinyal kritis: ${critical.join(', ')}`:null,flood.contextualImpact?`Kalibrasi banjir/genangan: dampak kontekstual terdeteksi (${uniq([...flood.hazard,...flood.impact]).join(', ')}); risk +${flood.riskBonus}`:null].filter(Boolean) as string[];
  const analysis:any={engine:'phase2e-rule-v2.9-flood-traffic-calibrated',generatedAt:new Date().toISOString(),sentiment,issueCategory,categoryEvidence,riskScore:risk,riskLevel,importanceScore:importance,confidence,officialKeywordMatches:officialMatches,operatorKeywordMatches:operatorMatches,operatorKeywordsNotFound:operatorNotFound,operatorKeywordNoise:operatorNoise,entityValidation,floodCalibration:{engine:'phase2e-flood-context-v1.1-traffic-impact',...flood},signals:signals.length?signals:['Tidak ada sinyal risiko eksplisit yang kuat pada teks terverifikasi.'],issueLinkage:{engine:'pending',candidateCount:0,linkedIssueId:null,candidates:[],degraded:true,note:'Issue linkage belum dihitung.'},note:'Phase 2E stable path v2.9: kalibrasi banjir/genangan mengenali dampak lalu lintas termasuk arus tersendat; hujan saja tidak menaikkan risiko. Taxonomy database tetap utama dan metadata manusia tetap otoritatif.'};
  const linkageClient=await pool.connect();try{await linkageClient.query(`SET statement_timeout='2500ms'`);analysis.issueLinkage=await evaluatePrintIssueLinkage(linkageClient,current,analysis);}catch(e){console.warn('Phase2E linkage skipped without blocking analysis',String((e as any)?.message||e));analysis.issueLinkage={engine:'phase2e-issue-link-v2.1-org-safe',candidateCount:0,linkedIssueId:null,candidates:[],degraded:true,note:'Issue linkage gagal/dibatasi waktu; analisis utama tetap dilanjutkan.'};}finally{try{await linkageClient.query('RESET statement_timeout');}catch{}linkageClient.release();}
  const client=await pool.connect();try{await client.query('BEGIN');await client.query(`SET LOCAL lock_timeout='2500ms'`);await client.query(`SET LOCAL statement_timeout='12000ms'`);const locked=(await client.query(`SELECT status FROM print_articles WHERE id=$1 FOR UPDATE NOWAIT`,[id.data])).rows[0];if(!locked||String(locked.status)!=='verified'){await client.query('ROLLBACK');return reply.code(409).send({error:'ARTICLE_STATUS_CHANGED',message:'Status clipping berubah sebelum analisis disimpan. Muat ulang data.'});}const row=(await client.query(`UPDATE print_articles SET status='analyzed',sentiment=$2,risk_score=$3,importance_score=$4,ai_metadata=jsonb_set(COALESCE(ai_metadata,'{}'::jsonb),'{phase2e}',$5::jsonb,true),updated_at=now() WHERE id=$1 RETURNING id,title,status,sentiment,risk_score,importance_score,ai_metadata,verified_by,verified_at,updated_at`,[id.data,sentiment,risk,importance,JSON.stringify(analysis)])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'PRINT_ARTICLE_ANALYZED_RECOVERY',$2)`,[ctx.id,{printArticleId:id.data,engine:analysis.engine,sentiment,riskScore:risk,importanceScore:importance,issueCategory,categoryScore:categoryEvidence.winnerScore,categorySource:categoryEvidence.source,confidence,opdMatch,districtMatch,operatorKeywordNoiseCount:operatorNoise.length,issueLinkageEngine:analysis.issueLinkage?.engine,issueCandidateCount:analysis.issueLinkage?.candidateCount||0,floodContextualImpact:flood.contextualImpact,floodRiskBonus:flood.riskBonus}]);await client.query('COMMIT');return{data:row,analysis};}catch(e:any){try{await client.query('ROLLBACK');}catch{}const code=String(e?.code||'');console.error('Phase2E recovery analysis failed',{articleId:id.data,code,message:e?.message});if(code==='55P03'||code==='57014')return reply.code(409).send({error:'ANALYSIS_DATABASE_BUSY',message:'Database sedang menahan lock lama pada clipping ini. Tutup modal, muat ulang halaman, lalu coba lagi setelah beberapa detik.',code});return reply.code(500).send({error:'PRINT_ANALYSIS_FAILED',message:String(e?.message||'Analisis gagal disimpan.'),code});}finally{client.release();}
 });
}