import { FastifyInstance, FastifyRequest } from 'fastify';
import { findEligiblePrintCandidates } from './issue-monitor-matcher.js';
import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { classifyIssueWithTaxonomy } from './phase2e-taxonomy.js';
import { evaluatePrintIssueLinkage } from './print-issue-linkage.js';
import { analyzeArticle as analyzeCoreArticle, parseKeywordQuery } from './media-intelligence-core.js';
import { calculateRisk } from './risk.js';

declare module 'fastify' { interface FastifyRequest { printAnalysisRecoveryAuth?: AuthorizationContext } }

const norm=(v:any)=>String(v||'').toLowerCase().normalize('NFKC').replace(/[^\p{L}\p{N}\s-]/gu,' ').replace(/\s+/g,' ').trim();
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
const count=(text:string,term:string)=>{const hay=norm(text),needle=norm(term);if(!hay||!needle)return 0;const h=` ${hay} `,n=` ${needle} `;let c=0,p=0;while((p=h.indexOf(n,p))!==-1){c++;p+=Math.max(1,n.length);}return c;};
const hits=(text:string,words:string[])=>words.filter(w=>count(text,w)>0);
const contextualHits=(title:string,summary:string,body:string,words:string[],bodyMin=2)=>words.filter(w=>count(title,w)>0||count(summary,w)>0||count(body,w)>=bodyMin);
const uniq=<T>(items:T[])=>[...new Set(items)];
const splitKeyword=(raw:any)=>{const source=String(raw||'');const parts=source.split(/[,;\n|]+/g).map(norm).filter(v=>v.length>=3);if(parts.length>1)return uniq(parts);const one=norm(source);return one?[one]:[];};
const OPD_STOP=new Set(['dinas','badan','bagian','kantor','kota','pemerintah','pemko','sekretariat','daerah','dan','serta','bidang','upt','uptd']);
const OCR_NOISE=new Set(['halaman','page','epaper','koran','berita','headline','selasa','senin','rabu','kamis','jumat','sabtu','minggu','edisi','rubrik','kolom','foto','dok','istimewa','indonesia']);
function phraseAliases(name:any,code:any){const n=norm(name),c=norm(code);const words=n.split(' ').filter(Boolean);const meaningful=words.filter(w=>!OPD_STOP.has(w)&&w.length>=3);const aliases=[n,c];if(meaningful.length>=2)aliases.push(meaningful.join(' '));const initials=meaningful.map(w=>w[0]).join('');if(initials.length>=3)aliases.push(initials);if(n.includes('komunikasi')&&n.includes('informatika'))aliases.push('kominfo','diskominfo');if(n.includes('lingkungan hidup'))aliases.push('dlh','dinas lingkungan hidup');if(n.includes('pekerjaan umum'))aliases.push('pu','pupr','dinas pu');if(n.includes('perhubungan'))aliases.push('dishub');if(n.includes('kesehatan'))aliases.push('dinkes');if(n.includes('pendidikan'))aliases.push('disdik');if(n.includes('sosial'))aliases.push('dinsos');if(n.includes('kepemudaan')&&n.includes('olahraga'))aliases.push('dispora','disporapar','dinas pemuda dan olahraga');return uniq(aliases.map(norm).filter(a=>a.length>=3));}
function keywordNoiseReason(raw:any){const v=norm(raw);if(!v)return'kosong';if(v.length<3)return'terlalu pendek';if(/^\d{6,}$/.test(v)||/^\d{6,}[a-z]+$/.test(v)||/^[a-z]+\d{6,}$/.test(v))return'pola tanggal/nomor OCR';if((v.match(/\d/g)||[]).length>=4)return'terlalu banyak angka';if(OCR_NOISE.has(v))return'kata generik hasil OCR/metadata cetak';if(/^halaman\s*\d*$/.test(v)||/^page\s*\d*$/.test(v))return'penanda halaman';return null;}
function floodCalibration(text:string){
 const weather=hits(text,['hujan deras','diguyur hujan','hujan']);
 const hazard=hits(text,['banjir','genangan','tergenang','terendam','rendam','air meluap','luapan']);
 const impact=hits(text,['jalan','simpang','akses','rumah','permukiman','kendaraan','kemacetan','macet','drainase','arus lalu lintas','lalu lintas','lalulintas','lalu lintas tersendat','lalulintas tersendat','tersendat']);
 const severe=hits(text,['akses terputus','jalan terputus','rumah terendam','evakuasi','korban','kerusakan','darurat','status darurat']);
 const contextualImpact=hazard.length>0&&impact.length>0;
 const weatherRelated=contextualImpact&&weather.length>0;
 const negativeWeight=contextualImpact?2:0;
 const baseRiskBonus=contextualImpact?28:0;
 const severeRiskBonus=contextualImpact&&severe.length?Math.min(24,12+severe.length*6):0;
 return{weather,hazard,impact,severe,contextualImpact,weatherRelated,negativeWeight,riskBonus:baseRiskBonus+severeRiskBonus};
}

export async function registerPrintAnalysisRecoveryRoutes(app:FastifyInstance,pool:Pool,jwtSecret:string){
 const auth=async(request:FastifyRequest,reply:any)=>{const token=request.cookies.access_token;if(!token)return reply.code(401).send({error:'UNAUTHENTICATED'});try{const d=jwt.verify(token,jwtSecret) as jwt.JwtPayload;if(typeof d.sub!=='string')throw new Error('invalid');const ctx=await loadAuthorizationContext(pool,d.sub);if(!ctx?.active)return reply.code(403).send({error:'ACCOUNT_INACTIVE'});request.printAnalysisRecoveryAuth=ctx;}catch{return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'});}};
 const canAnalyze=(ctx:AuthorizationContext)=>ctx.legacyRole==='admin'||ctx.roles.includes('super_admin')||ctx.roles.includes('humas');
 app.post('/api/print/articles/:id/mark-analyzed-v2',{preHandler:auth},async(request,reply)=>{
  const ctx=request.printAnalysisRecoveryAuth!;if(!canAnalyze(ctx))return reply.code(403).send({error:'ANALYSIS_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});
  const current=(await pool.query(`SELECT pa.id,pa.title,pa.summary,pa.body_text,pa.is_headline,pa.status,pa.opd_id,pa.district_id,pa.verified_by,pa.verified_at,pe.edition_date FROM print_articles pa LEFT JOIN print_editions pe ON pe.id=pa.edition_id WHERE pa.id=$1`,[id.data])).rows[0];if(!current)return reply.code(404).send({error:'NOT_FOUND'});if(String(current.status)!=='verified')return reply.code(409).send({error:'ARTICLE_MUST_BE_VERIFIED_FIRST',message:`Clipping harus berstatus Verified sebelum dianalisis. Status saat ini: ${current.status}.`});
  const safe=async<T=any>(sql:string,params:any[]=[]):Promise<T[]>=>{try{return(await pool.query(sql,params)).rows as T[];}catch(e){console.warn('Phase2E optional intelligence source skipped',String((e as any)?.message||e));return[];}};
  const [official,operator,opds,districts,villages,taxonomyMappings]=await Promise.all([safe(`SELECT k.id,k.keyword,k.opd_id,k.group_id,k.match_type,k.priority,kg.name group_name FROM keywords k LEFT JOIN keyword_groups kg ON kg.id=k.group_id WHERE k.active=true ORDER BY k.priority DESC,k.id`),safe(`SELECT keyword_text FROM print_article_keywords WHERE article_id=$1 AND source='operator' ORDER BY keyword_text`,[id.data]),safe(`SELECT id,name,code FROM opd WHERE active=true ORDER BY name`),safe(`SELECT id,name,code FROM districts WHERE active=true ORDER BY name`),safe(`SELECT id,name,district_id FROM villages WHERE active=true ORDER BY name`),safe(`SELECT k.id keyword_id,k.keyword,k.priority,tc.id category_id,tc.code taxonomy_code,tc.name taxonomy_name,kt.weight FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true WHERE k.active=true ORDER BY k.priority DESC,kt.weight DESC,k.id`)]);
  const title=norm(current.title),summary=norm(current.summary),body=norm(current.body_text),text=`${title} ${summary} ${body}`.trim();const sharedIntelligence=analyzeCoreArticle({id:id.data,title:current.title,summary:current.summary,content:current.body_text,mediaKind:'print',opdId:current.opd_id??null},parseKeywordQuery(''),1);const sharedRisk=calculateRisk({importance:sharedIntelligence.importanceScore,impact:sharedIntelligence.impactScore,velocity:sharedIntelligence.velocityScore,sentiment:sharedIntelligence.sentiment});const sentiment=sharedIntelligence.sentiment,risk=sharedRisk.score,riskLevel=sharedRisk.level.toUpperCase();
  const importance=sharedIntelligence.importanceScore;const confidence=text.length>=1800?'HIGH':text.length>=600?'MEDIUM':'LOW';const issueCategory='Unmapped';const categoryEvidence={winnerScore:0,source:'shared-core'};const officialMatches:any[]=[];const ignoredOfficialMatches:any[]=[];const operatorMatches:any[]=[];const operatorNotFound:any[]=[];const operatorNoise:any[]=[];const entityValidation={};const flood={contextualImpact:false,riskBonus:0,hazard:[],impact:[]};const opdMatch=null;const districtMatch=null;const signals=[`Shared sentiment/risk: ${sentiment} / ${riskLevel} ${risk}/100`];
  const analysis:any={engine:'shared-media-intelligence-risk-v1',generatedAt:new Date().toISOString(),sentiment,issueCategory,categoryEvidence,riskScore:risk,riskLevel,importanceScore:importance,impactScore:sharedIntelligence.impactScore,velocityScore:sharedIntelligence.velocityScore,confidence,officialKeywordMatches:officialMatches,ignoredOfficialKeywordMatches:ignoredOfficialMatches,operatorKeywordMatches:operatorMatches,operatorKeywordsNotFound:operatorNotFound,operatorKeywordNoise:operatorNoise,entityValidation,floodCalibration:{engine:'phase2e-flood-context-v1.1-traffic-impact',...flood},signals:signals.length?signals:['Tidak ada sinyal risiko eksplisit yang kuat pada teks terverifikasi.'],issueLinkage:{engine:'pending',candidateCount:0,linkedIssueId:null,candidates:[],degraded:true,note:'Issue linkage belum dihitung.'},note:'Phase 2E portable: keyword, OPD, sentiment, dan risk memakai whole-word/contextual matching. Alias geografis/media tidak ditanam di source code; metadata manusia tetap otoritatif.'};
  const linkageClient=await pool.connect();try{await linkageClient.query(`SET statement_timeout='2500ms'`);analysis.issueLinkage=await evaluatePrintIssueLinkage(linkageClient,current,analysis);}catch(e){console.warn('Phase2E linkage skipped without blocking analysis',String((e as any)?.message||e));analysis.issueLinkage={engine:'phase2e-issue-link-portable',candidateCount:0,linkedIssueId:null,candidates:[],degraded:true,note:'Issue linkage gagal/dibatasi waktu; analisis utama tetap dilanjutkan.'};}finally{try{await linkageClient.query('RESET statement_timeout');}catch{}linkageClient.release();}
  const client=await pool.connect();try{await client.query('BEGIN');await client.query(`SET LOCAL lock_timeout='2500ms'`);await client.query(`SET LOCAL statement_timeout='12000ms'`);const locked=(await client.query(`SELECT status FROM print_articles WHERE id=$1 FOR UPDATE NOWAIT`,[id.data])).rows[0];if(!locked||String(locked.status)!=='verified'){await client.query('ROLLBACK');return reply.code(409).send({error:'ARTICLE_STATUS_CHANGED',message:'Status clipping berubah sebelum analisis disimpan. Muat ulang data.'});}const row=(await client.query(`UPDATE print_articles SET status='analyzed',sentiment=$2,risk_score=$3,importance_score=$4,ai_metadata=jsonb_set(COALESCE(ai_metadata,'{}'::jsonb),'{phase2e}',$5::jsonb,true),updated_at=now() WHERE id=$1 RETURNING id,title,status,sentiment,risk_score,importance_score,ai_metadata,verified_by,verified_at,updated_at`,[id.data,sentiment,risk,importance,JSON.stringify(analysis)])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'PRINT_ARTICLE_ANALYZED_RECOVERY',$2)`,[ctx.id,{printArticleId:id.data,engine:analysis.engine,sentiment,riskScore:risk,importanceScore:importance,issueCategory,categoryScore:categoryEvidence.winnerScore,categorySource:categoryEvidence.source,confidence,opdMatch,districtMatch,operatorKeywordNoiseCount:operatorNoise.length,ignoredOfficialKeywordCount:ignoredOfficialMatches.length,issueLinkageEngine:analysis.issueLinkage?.engine,issueCandidateCount:analysis.issueLinkage?.candidateCount||0,floodContextualImpact:flood.contextualImpact,floodRiskBonus:flood.riskBonus}]);await client.query('COMMIT');let issueMonitorMatches=0;try{const taxonomyId=(taxonomyMappings as any[]).find(x=>norm(x.taxonomy_name)===norm(issueCategory))?.category_id??null;issueMonitorMatches=(await findEligiblePrintCandidates(pool,{printArticleId:id.data,publishedAt:current.edition_date,title:current.title,content:[current.summary,current.body_text].filter(Boolean).join(' '),taxonomyId:taxonomyId?Number(taxonomyId):null})).length;}catch(e){request.log.warn({err:e,printArticleId:id.data},'Issue Monitor print linkage skipped');}return{data:row,analysis:{...analysis,issueMonitorMatches}};}catch(e:any){try{await client.query('ROLLBACK');}catch{}const code=String(e?.code||'');console.error('Phase2E recovery analysis failed',{articleId:id.data,code,message:e?.message});if(code==='55P03'||code==='57014')return reply.code(409).send({error:'ANALYSIS_DATABASE_BUSY',message:'Database sedang menahan lock lama pada clipping ini. Tutup modal, muat ulang halaman, lalu coba lagi setelah beberapa detik.',code});return reply.code(500).send({error:'PRINT_ANALYSIS_FAILED',message:String(e?.message||'Analisis gagal disimpan.'),code});}finally{client.release();}
 });
}
