import { FastifyInstance, FastifyRequest } from 'fastify';
import { Pool } from 'pg';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { loadAuthorizationContext, type AuthorizationContext } from './rbac.js';
import { analyzePrintRoutingV16 } from './print-v16-adapter.js';
import { findEligiblePrintCandidates } from './issue-monitor-matcher.js';
import { analyzeArticle as analyzeCoreArticle, parseKeywordQuery } from './media-intelligence-core.js';
import { calculateRisk } from './risk.js';

declare module 'fastify' { interface FastifyRequest { printReviewAuth?: AuthorizationContext } }

export async function registerPrintReviewRoutes(app: FastifyInstance, pool: Pool, jwtSecret: string) {
  const auth = async (request: FastifyRequest, reply: any) => {
    const token = request.cookies.access_token;
    if (!token) return reply.code(401).send({ error: 'UNAUTHENTICATED' });
    try {
      const decoded = jwt.verify(token, jwtSecret) as jwt.JwtPayload;
      if (typeof decoded.sub !== 'string') throw new Error('invalid');
      const ctx = await loadAuthorizationContext(pool, decoded.sub);
      if (!ctx?.active) return reply.code(403).send({ error: 'ACCOUNT_INACTIVE' });
      request.printReviewAuth = ctx;
    } catch { return reply.code(401).send({ error: 'INVALID_ACCESS_TOKEN' }); }
  };
  const canReview = (ctx: AuthorizationContext) => ctx.legacyRole === 'admin' || ctx.roles.includes('super_admin') || ctx.roles.includes('humas');

  app.get('/api/print/review-capability', { preHandler: auth }, async (request) => ({ data: { canReviewAndVerify: canReview(request.printReviewAuth!), canAdvanceAnalysis: canReview(request.printReviewAuth!), canReopenAnalyzed: canReview(request.printReviewAuth!) } }));
  app.get('/api/print/keyword-options', { preHandler: auth }, async (request, reply) => {
    if (!canReview(request.printReviewAuth!)) return reply.code(403).send({ error: 'KEYWORD_EDIT_REQUIRES_HUMAS_OR_SUPER_ADMIN' });
    const rows = (await pool.query(`SELECT DISTINCT k.id,k.keyword,tc.id taxonomy_id,tc.name taxonomy_name,o.id opd_id,o.name opd_name FROM keywords k JOIN keyword_taxonomy kt ON kt.keyword_id=k.id AND kt.active=true JOIN taxonomy_categories tc ON tc.id=kt.category_id AND tc.active=true JOIN classification_sectors cs ON cs.id=tc.sector_id AND cs.active=true JOIN keyword_opd ko ON ko.keyword_id=k.id AND ko.active=true AND ko.routing_role='PRIMARY' JOIN opd o ON o.id=ko.opd_id AND o.active=true WHERE k.active=true AND k.organization_id IS NOT NULL AND k.opd_id IS NULL AND k.district_id IS NULL AND tc.organization_id=k.organization_id AND cs.organization_id=k.organization_id ORDER BY k.keyword,tc.name,o.name`)).rows;
    return { data: rows };
  });

  app.post('/api/print/articles/:id/review-verify', { preHandler: auth }, async (request, reply) => {
    const ctx=request.printReviewAuth!; if(!canReview(ctx)) return reply.code(403).send({error:'REVIEW_VERIFY_REQUIRES_HUMAS_OR_SUPER_ADMIN'});
    const id=z.coerce.number().int().positive().safeParse((request.params as any).id); if(!id.success)return reply.code(400).send({error:'INVALID_ID'});
    const client=await pool.connect(); try{await client.query('BEGIN');const current=(await client.query(`SELECT id,title,status FROM print_articles WHERE id=$1 FOR UPDATE`,[id.data])).rows[0];if(!current){await client.query('ROLLBACK');return reply.code(404).send({error:'NOT_FOUND'});}if(!['needs_review','verified'].includes(String(current.status))){await client.query('ROLLBACK');return reply.code(409).send({error:'INVALID_REVIEW_STATE',message:`Clipping berstatus ${current.status} tidak dapat diverifikasi dari alur review.`});}const verified=(await client.query(`UPDATE print_articles SET status='verified',verified_by=$2,verified_at=now(),updated_at=now() WHERE id=$1 RETURNING id,title,status,verified_by,verified_at,updated_at`,[id.data,ctx.id])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'PRINT_ARTICLE_REVIEW_VERIFIED',$2)`,[ctx.id,{printArticleId:id.data,previousStatus:current.status}]);await client.query('COMMIT');return{data:verified};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  });

  app.post('/api/print/articles/:id/mark-analyzed', { preHandler: auth }, async (request, reply) => {
    const ctx=request.printReviewAuth!;if(!canReview(ctx))return reply.code(403).send({error:'ANALYSIS_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_ID'});
    const current=(await pool.query(`SELECT pa.id,pa.title,pa.summary,pa.body_text,pa.status,pa.verified_by,pa.verified_at FROM print_articles pa WHERE pa.id=$1`,[id.data])).rows[0];if(!current)return reply.code(404).send({error:'NOT_FOUND'});if(String(current.status)!=='verified')return reply.code(409).send({error:'ARTICLE_MUST_BE_VERIFIED_FIRST',message:`Clipping harus berstatus Verified sebelum proses analisis. Status saat ini: ${current.status}.`});
    try{const analysis=await analyzePrintRoutingV16(pool,{title:current.title,summary:current.summary,bodyText:current.body_text});const preview={...analysis,keywordVerification:analysis.routingStatus==='ROUTED'?'PENDING':'MANUAL_REQUIRED',originalKeywordId:analysis.keywordId,originalKeyword:analysis.keyword};const keptVerified=(await pool.query(`UPDATE print_articles SET opd_id=NULL,ai_metadata=jsonb_set(COALESCE(ai_metadata,'{}'::jsonb),'{v16Routing}',$2::jsonb,true),updated_at=now() WHERE id=$1 AND status='verified' RETURNING id,title,status,opd_id,ai_metadata,verified_by,verified_at,updated_at`,[id.data,JSON.stringify(preview)])).rows[0];if(!keptVerified)return reply.code(409).send({error:'ARTICLE_STATE_CHANGED',message:'Status clipping berubah saat proses analisis. Muat ulang data dan coba lagi.'});const auditAction=analysis.routingStatus==='ROUTED'?'PRINT_ARTICLE_KEYWORD_REVIEW_PENDING':analysis.routingStatus==='AMBIGUOUS'?'PRINT_ARTICLE_ROUTING_AMBIGUOUS':'PRINT_ARTICLE_ROUTING_UNROUTED';await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,$2,$3)`,[ctx.id,auditAction,{printArticleId:id.data,engine:analysis.engine,routingStatus:analysis.routingStatus,primaryOpdId:analysis.primaryOpdId,keywordId:analysis.keywordId,keyword:analysis.keyword,taxonomyId:analysis.taxonomyId,taxonomyName:analysis.taxonomyName,evidenceSource:analysis.evidenceSource}]);return{data:keptVerified,analysis:preview,requiresKeywordVerification:true,message:analysis.routingStatus==='ROUTED'?'Analisis V16.5 selesai. Verifikasi keyword dengan Terima Keyword atau Edit Keyword sebelum data dikunci.':'Routing otomatis belum final. Pilih Master Keyword secara manual untuk menghitung ulang routing dan mengunci hasil.'};}catch(error:any){request.log.error({err:error,printArticleId:id.data},'print V16.5 routing failed');return reply.code(500).send({error:'PRINT_ANALYSIS_FAILED',message:error?.message||'Proses analisis gagal.'});}
  });

  app.post('/api/print/articles/:id/finalize-keyword', { preHandler: auth }, async (request, reply) => {
    const ctx=request.printReviewAuth!;if(!canReview(ctx))return reply.code(403).send({error:'KEYWORD_VERIFY_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).id);const body=z.object({keywordId:z.coerce.number().int().positive().optional()}).safeParse(request.body??{});if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_KEYWORD_VERIFICATION'});
    const client=await pool.connect();try{await client.query('BEGIN');const current=(await client.query(`SELECT id,title,summary,body_text,status,ai_metadata,verified_by,verified_at FROM print_articles WHERE id=$1 FOR UPDATE`,[id.data])).rows[0];if(!current){await client.query('ROLLBACK');return reply.code(404).send({error:'NOT_FOUND'});}if(String(current.status)!=='verified'){await client.query('ROLLBACK');return reply.code(409).send({error:'ARTICLE_MUST_BE_VERIFIED_FIRST'});}const preview=current.ai_metadata?.v16Routing;if(!preview||!['PENDING','MANUAL_REQUIRED'].includes(String(preview.keywordVerification))){await client.query('ROLLBACK');return reply.code(409).send({error:'NO_PENDING_KEYWORD_REVIEW',message:'Jalankan Proses Analisis terlebih dahulu.'});}
      const automatic=preview.routingStatus==='ROUTED'&&preview.keywordVerification==='PENDING';const selectedKeywordId=body.data.keywordId??(automatic?Number(preview.keywordId):NaN);if(!Number.isFinite(selectedKeywordId)){await client.query('ROLLBACK');return reply.code(400).send({error:'KEYWORD_REQUIRED',message:'Pilih Master Keyword untuk clipping yang belum terpetakan.'});}const edited=!automatic||String(selectedKeywordId)!==String(preview.keywordId);const finalAnalysis=edited?await analyzePrintRoutingV16(client as any,{title:current.title,summary:current.summary,bodyText:current.body_text,manualKeywordId:selectedKeywordId}):{...preview,keywordSource:'AUTO' as const};if(finalAnalysis.routingStatus!=='ROUTED'||!finalAnalysis.primaryOpdId||!finalAnalysis.keywordId){await client.query('ROLLBACK');return reply.code(409).send({error:'KEYWORD_HAS_NO_VALID_ROUTING',message:'Keyword pilihan tidak memiliki routing Master Classification yang valid.'});}const lockedRouting={...finalAnalysis,keywordVerification:'ACCEPTED',keywordSource:edited?'MANUAL':'AUTO',originalRoutingStatus:preview.routingStatus,originalKeywordId:preview.originalKeywordId??preview.keywordId,originalKeyword:preview.originalKeyword??preview.keyword,finalizedAt:new Date().toISOString(),finalizedBy:ctx.id};const intelligence=analyzeCoreArticle({id:id.data,title:current.title,summary:current.summary,content:current.body_text,mediaKind:'print',opdId:finalAnalysis.primaryOpdId},parseKeywordQuery(String(finalAnalysis.keyword||'')),1);const risk=calculateRisk({importance:intelligence.importanceScore,impact:intelligence.impactScore,velocity:intelligence.velocityScore,sentiment:intelligence.sentiment});const analyzed=(await client.query(`UPDATE print_articles SET status='analyzed',opd_id=$2,sentiment=$3,risk_score=$4,importance_score=$5,ai_metadata=jsonb_set(jsonb_set(COALESCE(ai_metadata,'{}'::jsonb),'{v16Routing}',$6::jsonb,true),'{intelligence}',$7::jsonb,true),updated_at=now() WHERE id=$1 RETURNING id,title,status,opd_id,sentiment,risk_score,importance_score,ai_metadata,verified_by,verified_at,updated_at`,[id.data,finalAnalysis.primaryOpdId,intelligence.sentiment,risk.score,intelligence.importanceScore,JSON.stringify(lockedRouting),JSON.stringify({...intelligence,riskLevel:risk.level,riskReasons:risk.reasons})])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'PRINT_ARTICLE_KEYWORD_FINALIZED',$2)`,[ctx.id,{printArticleId:id.data,keywordSource:edited?'MANUAL':'AUTO',originalRoutingStatus:preview.routingStatus,originalKeywordId:preview.keywordId,originalKeyword:preview.keyword,finalKeywordId:finalAnalysis.keywordId,finalKeyword:finalAnalysis.keyword,primaryOpdId:finalAnalysis.primaryOpdId,supportingOpdIds:finalAnalysis.supportingOpdIds,taxonomyId:finalAnalysis.taxonomyId,taxonomyName:finalAnalysis.taxonomyName}]);await client.query('COMMIT');
      // Issue Monitor is downstream of the authoritative print finalization.
      // Keep it non-blocking so Issue linkage can never roll back a finalized clipping.
      try{
        const edition=(await pool.query(`SELECT pe.edition_date FROM print_articles pa JOIN print_editions pe ON pe.id=pa.edition_id WHERE pa.id=$1`,[id.data])).rows[0];
        await findEligiblePrintCandidates(pool,{printArticleId:id.data,title:current.title,content:[current.summary,current.body_text].filter(Boolean).join(' '),publishedAt:edition?.edition_date??null,taxonomyId:finalAnalysis.taxonomyId==null?null:Number(finalAnalysis.taxonomyId)});
      }catch(issueMonitorError){request.log.error({err:issueMonitorError,printArticleId:id.data},'print issue monitor candidate matching failed');}
      return{data:analyzed,analysis:lockedRouting};
    }catch(error:any){await client.query('ROLLBACK');request.log.error({err:error,printArticleId:id.success?id.data:null},'print keyword finalization failed');return reply.code(500).send({error:'PRINT_KEYWORD_FINALIZATION_FAILED',message:error?.message||'Penyimpanan keyword gagal.'});}finally{client.release();}
  });

  app.post('/api/print/articles/:id/reopen', { preHandler: auth }, async (request, reply) => {const ctx=request.printReviewAuth!;if(!canReview(ctx))return reply.code(403).send({error:'REOPEN_REQUIRES_HUMAS_OR_SUPER_ADMIN'});const id=z.coerce.number().int().positive().safeParse((request.params as any).id);const body=z.object({reason:z.string().trim().min(5).max(500)}).safeParse(request.body);if(!id.success||!body.success)return reply.code(400).send({error:'INVALID_REOPEN_REQUEST'});const client=await pool.connect();try{await client.query('BEGIN');const current=(await client.query(`SELECT id,title,status,opd_id,sentiment,risk_score,importance_score,ai_metadata FROM print_articles WHERE id=$1 FOR UPDATE`,[id.data])).rows[0];if(!current){await client.query('ROLLBACK');return reply.code(404).send({error:'NOT_FOUND'});}if(String(current.status)!=='analyzed'){await client.query('ROLLBACK');return reply.code(409).send({error:'ARTICLE_NOT_ANALYZED',message:`Hanya clipping berstatus Analyzed yang dapat dibuka kembali. Status saat ini: ${current.status}.`});}const reopened=(await client.query(`UPDATE print_articles SET status='verified',opd_id=NULL,sentiment=NULL,risk_score=0,importance_score=0,ai_metadata=(COALESCE(ai_metadata,'{}'::jsonb)-'phase2e'-'v16Routing'),updated_at=now() WHERE id=$1 RETURNING id,title,status,opd_id,sentiment,risk_score,importance_score,ai_metadata,verified_by,verified_at,updated_at`,[id.data])).rows[0];await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'PRINT_ARTICLE_REOPENED',$2)`,[ctx.id,{printArticleId:id.data,previousStatus:current.status,reason:body.data.reason,previousAnalysis:{opdId:current.opd_id,sentiment:current.sentiment,riskScore:current.risk_score,importanceScore:current.importance_score,phase2e:current.ai_metadata?.phase2e??null,v16Routing:current.ai_metadata?.v16Routing??null}}]);await client.query('COMMIT');return{data:reopened};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}});
}
