import 'dotenv/config';
import Fastify, { FastifyReply, FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import argon2 from 'argon2';
import jwt from 'jsonwebtoken';
import { Pool } from 'pg';
import { randomBytes, createHash } from 'node:crypto';
import { z } from 'zod';
import { ingestEnabledSources } from './ingestion.js';
import { registerAskIntelligence } from './ask-intelligence.js';

const env = { port: Number(process.env.PORT ?? 8080), databaseUrl: process.env.DATABASE_URL ?? '', jwtSecret: process.env.JWT_SECRET ?? '', accessTtl: process.env.ACCESS_TOKEN_TTL ?? '15m', refreshDays: Number(process.env.REFRESH_TOKEN_DAYS ?? 7), corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3000', cookieSecure: process.env.COOKIE_SECURE === 'true' };
if (!env.databaseUrl || !env.jwtSecret) throw new Error('DATABASE_URL and JWT_SECRET are required');
const pool = new Pool({ connectionString: env.databaseUrl, max: 10 });
const app = Fastify({ logger: true, bodyLimit: 2 * 1024 * 1024 });
await app.register(helmet); await app.register(cors, { origin: env.corsOrigin, credentials: true }); await app.register(cookie); await app.register(rateLimit, { max: 120, timeWindow: '1 minute' });
const authSchema = z.object({ email: z.string().email(), password: z.string().min(8).max(200) });
type AuthUser = { id: string; email: string; role: 'admin'|'operator'|'viewer'; opdId: string | null };
declare module 'fastify' { interface FastifyRequest { user?: AuthUser } }
function accessToken(user: AuthUser) { return jwt.sign({ sub:user.id,email:user.email,role:user.role,opdId:user.opdId }, env.jwtSecret, { expiresIn: env.accessTtl as jwt.SignOptions['expiresIn'] }); }
function hashRefresh(token:string) { return createHash('sha256').update(token).digest('hex'); }
async function requireAuth(request:FastifyRequest, reply:FastifyReply) { const token=request.cookies.access_token; if(!token) return reply.code(401).send({error:'UNAUTHENTICATED'}); try { const decoded=jwt.verify(token,env.jwtSecret) as jwt.JwtPayload; if(typeof decoded.sub!=='string'||!['admin','operator','viewer'].includes(String(decoded.role))) throw new Error('invalid'); request.user={id:decoded.sub,email:String(decoded.email),role:decoded.role as AuthUser['role'],opdId:decoded.opdId?String(decoded.opdId):null}; } catch { return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'}); } }
function requireRole(...roles:AuthUser['role'][]) { return async (request:FastifyRequest,reply:FastifyReply)=>{ if(!request.user||!roles.includes(request.user.role)) return reply.code(403).send({error:'FORBIDDEN'}); }; }
app.get('/health', async()=>({ok:true,service:'media-intelligence-api'}));
app.post('/api/auth/login',async(request,reply)=>{ const parsed=authSchema.safeParse(request.body); if(!parsed.success) return reply.code(400).send({error:'INVALID_REQUEST'}); const row=(await pool.query(`SELECT id,email,password_hash,role,opd_id,active FROM users WHERE lower(email)=lower($1) LIMIT 1`,[parsed.data.email])).rows[0]; if(!row||!row.active||!(await argon2.verify(row.password_hash,parsed.data.password))) return reply.code(401).send({error:'INVALID_CREDENTIALS'}); const user:AuthUser={id:String(row.id),email:row.email,role:row.role,opdId:row.opd_id==null?null:String(row.opd_id)}; const refresh=randomBytes(48).toString('base64url'); await pool.query(`INSERT INTO refresh_tokens(user_id,token_hash,expires_at) VALUES($1,$2,$3)`,[user.id,hashRefresh(refresh),new Date(Date.now()+env.refreshDays*86400000)]); reply.setCookie('access_token',accessToken(user),{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/'}); reply.setCookie('refresh_token',refresh,{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/api/auth'}); return {user}; });
app.post('/api/auth/refresh',async(request,reply)=>{ const old=request.cookies.refresh_token; if(!old) return reply.code(401).send({error:'NO_REFRESH_TOKEN'}); const row=(await pool.query(`SELECT rt.id,u.id user_id,u.email,u.role,u.opd_id,rt.expires_at FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=$1 AND rt.revoked_at IS NULL AND u.active=true LIMIT 1`,[hashRefresh(old)])).rows[0]; if(!row||new Date(row.expires_at)<=new Date()) return reply.code(401).send({error:'INVALID_REFRESH_TOKEN'}); await pool.query(`UPDATE refresh_tokens SET revoked_at=NOW() WHERE id=$1`,[row.id]); const user:AuthUser={id:String(row.user_id),email:row.email,role:row.role,opdId:row.opd_id==null?null:String(row.opd_id)}; const refresh=randomBytes(48).toString('base64url'); await pool.query(`INSERT INTO refresh_tokens(user_id,token_hash,expires_at) VALUES($1,$2,$3)`,[user.id,hashRefresh(refresh),new Date(Date.now()+env.refreshDays*86400000)]); reply.setCookie('access_token',accessToken(user),{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/'}); reply.setCookie('refresh_token',refresh,{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/api/auth'}); return {ok:true}; });
app.post('/api/auth/logout',async(request,reply)=>{const token=request.cookies.refresh_token;if(token) await pool.query(`UPDATE refresh_tokens SET revoked_at=NOW() WHERE token_hash=$1 AND revoked_at IS NULL`,[hashRefresh(token)]);reply.clearCookie('access_token',{path:'/'});reply.clearCookie('refresh_token',{path:'/api/auth'});return{ok:true};});
app.get('/api/me',{preHandler:requireAuth},async request=>({user:request.user}));
app.get('/api/opd',{preHandler:requireAuth},async()=>{ const {rows}=await pool.query(`SELECT id,code,name,active FROM opd WHERE active=true ORDER BY name`); return {data:rows}; });
const filterOpd=(user:AuthUser|undefined,requested?:string)=> user?.role==='admin'?requested:(user?.opdId ?? null);
app.get('/api/articles',{preHandler:requireAuth},async(request,reply)=>{ const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),from:z.string().optional(),to:z.string().optional(),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(request.query); if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'}); const params:unknown[]=[]; const where:string[]=[]; const opdId=filterOpd(request.user,q.data.opdId); if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);} if(q.data.from){params.push(q.data.from);where.push(`a.published_at >= $${params.length}`);} if(q.data.to){params.push(q.data.to);where.push(`a.published_at < $${params.length}`);} params.push(q.data.limit); const {rows}=await pool.query(`SELECT a.id,a.title,a.url,a.published_at,a.sentiment,a.importance_score,a.impact_score,a.velocity_score,a.risk_score,a.risk_level,a.is_highlight,a.summary,ms.name source_name FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY a.importance_score DESC,a.published_at DESC NULLS LAST LIMIT $${params.length}`,params); return {data:rows}; });
app.get('/api/highlights',{preHandler:requireAuth},async(request,reply)=>{ const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),limit:z.coerce.number().int().min(1).max(50).default(10)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where=['a.is_highlight=true'];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT a.id,a.title,a.url,a.published_at,a.sentiment,a.importance_score,a.impact_score,a.velocity_score,a.risk_score,a.risk_level,a.summary,ms.name source_name FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE ${where.join(' AND ')} ORDER BY a.risk_score DESC,a.importance_score DESC,a.published_at DESC NULLS LAST LIMIT $${params.length}`,params);return{data:rows};});
app.get('/api/alerts',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),status:z.enum(['open','acknowledged','resolved']).default('open'),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[q.data.status];const where=['aa.status=$1'];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT aa.id,aa.article_id,aa.alert_type,aa.severity,aa.reason,aa.status,aa.created_at,a.title,a.url,a.published_at,a.risk_score,a.risk_level,ms.name source_name FROM article_alerts aa JOIN articles a ON a.id=aa.article_id LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE ${where.join(' AND ')} ORDER BY aa.created_at DESC LIMIT $${params.length}`,params);return{data:rows};});
app.patch('/api/alerts/:id',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({status:z.enum(['acknowledged','resolved'])}).safeParse(request.body);const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!parsed.success||!id.success)return reply.code(400).send({error:'INVALID_REQUEST'});const {rows}=await pool.query(`UPDATE article_alerts SET status=$2,acknowledged_at=CASE WHEN $2='acknowledged' THEN COALESCE(acknowledged_at,NOW()) ELSE acknowledged_at END WHERE id=$1 RETURNING id,article_id,alert_type,severity,reason,status,acknowledged_at`,[id.data,parsed.data.status]);if(!rows[0])return reply.code(404).send({error:'ALERT_NOT_FOUND'});await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ALERT_STATUS_CHANGED',$2)`,[request.user?.id,{alertId:id.data,status:parsed.data.status}]);return{data:rows[0]};});
app.get('/api/dashboard',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const opdId=filterOpd(request.user,q.data.opdId);const filter=opdId?(params.push(opdId),`WHERE opd_id=$1`):'';const {rows}=await pool.query(`SELECT COUNT(*)::int total_articles,COUNT(*) FILTER(WHERE is_highlight)::int highlights,COUNT(*) FILTER(WHERE sentiment='negative')::int negative,COUNT(*) FILTER(WHERE risk_level IN ('high','critical'))::int critical,COUNT(*) FILTER(WHERE risk_level='critical')::int critical_alerts,COALESCE(ROUND(AVG(importance_score)),0)::int momentum FROM articles ${filter}`,params);const sources=await pool.query(`SELECT COUNT(*)::int count FROM media_sources WHERE active=true`);return{metrics:{...rows[0],sources:Number(sources.rows[0].count)}};});
app.get('/api/ingestion/status',{preHandler:requireAuth},async()=>{const {rows}=await pool.query(`SELECT COUNT(*)::int sources,COUNT(*) FILTER(WHERE active=true)::int active_sources,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL)::int feed_sources,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL AND last_success_at IS NOT NULL)::int healthy_feeds,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL AND last_error IS NOT NULL)::int failed_feeds,MAX(last_success_at) last_success_at FROM media_sources`);const sources=await pool.query(`SELECT id,name,category,tier,url,active,last_checked_at,last_success_at,last_error,last_fetched_count,last_inserted_count FROM media_sources ORDER BY tier ASC,name ASC`);return{status:rows[0],sources:sources.rows};});
app.get('/api/ingestion/history',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(20)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const {rows}=await pool.query(`SELECT id,started_at,finished_at,status,source_count,successful_sources,failed_sources,fetched_count,inserted_count,details,error_message FROM ingestion_runs ORDER BY started_at DESC LIMIT $1`,[q.data.limit]);return{data:rows};});
app.post('/api/ingestion/run',{preHandler:[requireAuth,requireRole('admin','operator')]},async()=>({results:await ingestEnabledSources(pool)}));
app.post('/api/media-scan/analyze',{preHandler:requireAuth},async(request,reply)=>{const parsed=z.object({text:z.string().min(20).max(50000),filename:z.string().max(255).optional(),opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_OCR_TEXT'});const text=parsed.data.text.replace(/\s+/g,' ').trim();const negative=['gagal','korupsi','suap','kriminal','kecelakaan','banjir','macet','protes','keluhan','kritik','masalah','terlambat','lambat','kebakaran','ancaman','sengketa'];const positive=['berhasil','sukses','prestasi','penghargaan','meningkat','investasi','terobosan','apresiasi','aman','lancar','kolaborasi','pertumbuhan'];const lower=text.toLowerCase();const neg=negative.filter(k=>lower.includes(k)).length;const pos=positive.filter(k=>lower.includes(k)).length;const sentiment=neg>pos?'negative':pos>neg?'positive':'neutral';const risk=Math.min(100,20+neg*12+(text.length>1200?15:0));const risk_level=risk>=80?'critical':risk>=60?'high':risk>=35?'medium':'low';const headline=text.split(/[.!?]/)[0].slice(0,180)||parsed.data.filename||'Media cetak terdeteksi';const summary=text.slice(0,500);const recommendation=risk_level==='critical'||risk_level==='high'?'Validasi fakta segera, koordinasikan OPD terkait, tetapkan juru bicara dan siapkan holding statement.':'Monitor perkembangan dan siapkan data pendukung bila isu berkembang.';const key_message=sentiment==='negative'?'Pemko sedang melakukan verifikasi fakta dan koordinasi penanganan serta akan menyampaikan perkembangan melalui kanal resmi.':'Pemko terus menyampaikan informasi berbasis data yang dapat diverifikasi publik.';return{data:{mode:'deterministic-ocr',filename:parsed.data.filename||null,analysis:{headline,summary,sentiment,risk_score:risk,risk_level,impact_score:Math.min(100,20+Math.floor(text.length/80)),opd_name:parsed.data.opdId?'OPD terpilih':'Belum dipetakan',recommendation,key_message}}};});
app.post('/api/media-scans',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({text:z.string().min(20).max(50000),filename:z.string().max(255).optional(),opdId:z.string().regex(/^\d+$/).optional(),analysis:z.record(z.string(),z.any())}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_MEDIA_SCAN'});const opdId=filterOpd(request.user,parsed.data.opdId);const {rows}=await pool.query(`INSERT INTO media_scans(source_id,opd_id,file_name,ocr_text,analysis,status,processed_at) VALUES(NULL,$1,$2,$3,$4,'completed',NOW()) RETURNING id,opd_id,file_name,analysis,status,created_at,processed_at`,[opdId,parsed.data.filename||null,parsed.data.text,parsed.data.analysis]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'MEDIA_SCAN_SAVED',$2)`,[request.user?.id,{mediaScanId:rows[0].id,opdId}]);return{data:rows[0]};});
app.get('/api/media-scans',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({from:z.string().optional(),to:z.string().optional(),opdId:z.string().regex(/^\d+$/).optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where:string[]=[];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`m.opd_id=$${params.length}`);}if(q.data.from){params.push(q.data.from);where.push(`m.created_at >= $${params.length}`);}if(q.data.to){params.push(q.data.to);where.push(`m.created_at < $${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT m.id,m.opd_id,m.file_name,m.analysis,m.status,m.created_at,m.processed_at,o.name opd_name FROM media_scans m LEFT JOIN opd o ON o.id=m.opd_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY m.created_at DESC LIMIT $${params.length}`,params);return{data:rows};});
const incidentId=z.coerce.number().int().positive();
app.get('/api/incidents',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),status:z.enum(['MONITORING','ESCALATED','RESOLVED']).optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where:string[]=[];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`i.opd_id=$${params.length}`);}if(q.data.status){params.push(q.data.status);where.push(`i.status=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT i.*,o.name opd_name FROM incidents i LEFT JOIN opd o ON o.id=i.opd_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY i.updated_at DESC LIMIT $${params.length}`,params);return{data:rows};});
app.post('/api/incidents',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({opdId:z.string().regex(/^\d+$/).optional(),title:z.string().min(3).max(255),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).default('MEDIUM'),trigger:z.string().max(2000).optional(),commandOwnerId:z.string().regex(/^\d+$/).nullable().optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_INCIDENT'});const opdId=filterOpd(request.user,parsed.data.opdId);const owner=parsed.data.commandOwnerId===undefined?null:parsed.data.commandOwnerId;const {rows}=await pool.query(`INSERT INTO incidents(opd_id,title,severity,status,trigger,command_owner_id) VALUES($1,$2,$3,'MONITORING',$4,$5) RETURNING *`,[opdId,parsed.data.title,parsed.data.severity,parsed.data.trigger||null,owner]);await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_CREATED',$2,$3)`,[rows[0].id,{severity:rows[0].severity},request.user?.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_CREATED',$2)`,[request.user?.id,{incidentId:rows[0].id,opdId}]);return reply.code(201).send({data:rows[0]});});
app.patch('/api/incidents/:id',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const parsed=z.object({title:z.string().min(3).max(255).optional(),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).optional(),status:z.enum(['MONITORING','ESCALATED','RESOLVED']).optional(),commandOwnerId:z.string().regex(/^\d+$/).nullable().optional(),decisionRequired:z.string().max(2000).nullable().optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query(`SELECT * FROM incidents WHERE id=$1`,[id.data])).rows[0];if(!current)return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});const owner=parsed.data.commandOwnerId===undefined?current.command_owner_id:parsed.data.commandOwnerId;const values=[parsed.data.title??current.title,parsed.data.severity??current.severity,parsed.data.status??current.status,owner,parsed.data.decisionRequired===undefined?current.decision_required:parsed.data.decisionRequired,id.data];const {rows}=await pool.query(`UPDATE incidents SET title=$1,severity=$2,status=$3,command_owner_id=$4,decision_required=$5,updated_at=NOW(),resolved_at=CASE WHEN $3='RESOLVED' THEN COALESCE(resolved_at,NOW()) ELSE resolved_at END WHERE id=$6 RETURNING *`,values);await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_UPDATED',$2,$3)`,[id.data,{status:rows[0].status,severity:rows[0].severity},request.user?.id]);return{data:rows[0]};});
app.post('/api/incidents/:id/tasks',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const parsed=z.object({type:z.enum(['VERIFY','COORDINATE','MESSAGE','MONITOR']),title:z.string().min(3).max(255),ownerId:z.string().regex(/^\d+$/).nullable().optional(),dueAt:z.string().datetime().nullable().optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_TASK'});const exists=(await pool.query(`SELECT id FROM incidents WHERE id=$1 AND ($2::text IS NULL OR opd_id=$2::bigint)`,[id.data,request.user?.role==='admin'?null:request.user?.opdId])).rows[0];if(!exists)return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});const {rows}=await pool.query(`INSERT INTO incident_tasks(incident_id,type,title,status,owner_id,due_at) VALUES($1,$2,$3,'OPEN',$4,$5) RETURNING *`,[id.data,parsed.data.type,parsed.data.title,parsed.data.ownerId??null,parsed.data.dueAt??null]);return reply.code(201).send({data:rows[0]});});
app.patch('/api/incidents/:id/tasks/:taskId',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);const task=incidentId.safeParse((request.params as any).taskId);if(!id.success||!task.success)return reply.code(400).send({error:'INVALID_ID'});const parsed=z.object({status:z.enum(['OPEN','IN_PROGRESS','DONE','BLOCKED'])}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_TASK'});const scope=request.user?.role==='admin'?'':` AND i.opd_id=${Number(request.user?.opdId)||0}`;const {rows}=await pool.query(`UPDATE incident_tasks t SET status=$1,updated_at=NOW() FROM incidents i WHERE t.id=$2 AND t.incident_id=$3${scope} RETURNING t.*`,[parsed.data.status,task.data,id.data]);if(!rows[0])return reply.code(404).send({error:'TASK_NOT_FOUND'});return{data:rows[0]};});
app.get('/api/incidents/:id/events',{preHandler:requireAuth},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const scope=request.user?.role==='admin'?'':` AND i.opd_id=${Number(request.user?.opdId)||0}`;const {rows}=await pool.query(`SELECT e.* FROM incident_events e JOIN incidents i ON i.id=e.incident_id WHERE e.incident_id=$1${scope} ORDER BY e.created_at DESC LIMIT 200`,[id.data]);return{data:rows};});
app.post('/api/incidents/:id/decisions',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const parsed=z.object({decision:z.string().min(3).max(4000),status:z.enum(['DRAFT','APPROVED','REJECTED']).default('DRAFT')}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_DECISION'});const scope=request.user?.role==='admin'?'':` AND i.opd_id=${Number(request.user?.opdId)||0}`;const exists=(await pool.query(`SELECT i.id FROM incidents i WHERE i.id=$1${scope}`,[id.data])).rows[0];if(!exists)return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});const {rows}=await pool.query(`INSERT INTO incident_decisions(incident_id,decision,status,created_by) VALUES($1,$2,$3,$4) RETURNING *`,[id.data,parsed.data.decision,parsed.data.status,request.user?.id]);return reply.code(201).send({data:rows[0]});});
app.post('/api/incidents/:id/decisions/:decisionId/approve',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);const decision=incidentId.safeParse((request.params as any).decisionId);if(!id.success||!decision.success)return reply.code(400).send({error:'INVALID_ID'});const scope=request.user?.role==='admin'?'':` AND i.opd_id=${Number(request.user?.opdId)||0}`;const {rows}=await pool.query(`UPDATE incident_decisions d SET status='APPROVED',approved_by=$1,approved_at=NOW() FROM incidents i WHERE d.id=$2 AND d.incident_id=$3${scope} RETURNING d.*`,[request.user?.id,decision.data,id.data]);if(!rows[0])return reply.code(404).send({error:'DECISION_NOT_FOUND'});return{data:rows[0]};});
app.post('/api/incidents/:id/escalate',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const parsed=z.object({reason:z.string().min(3).max(1000).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const scope=request.user?.role==='admin'?'':` AND opd_id=${Number(request.user?.opdId)||0}`;const {rows}=await pool.query(`UPDATE incidents SET status='ESCALATED',updated_at=NOW() WHERE id=$1${scope} RETURNING *`,[id.data]);if(!rows[0])return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_ESCALATED',$2,$3)`,[id.data,{reason:parsed.data.reason||'Manual escalation'},request.user?.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_ESCALATED',$2)`,[request.user?.id,{incidentId:id.data,reason:parsed.data.reason||'Manual escalation'}]);return{data:rows[0]};});
await registerAskIntelligence(app,pool,env.jwtSecret);
app.setErrorHandler((error,_request,reply)=>{app.log.error(error);return reply.code(error.statusCode??500).send({error:'INTERNAL_SERVER_ERROR'});});
app.addHook('onClose',async()=>pool.end()); await app.listen({port:env.port,host:'0.0.0.0'});