import 'dotenv/config';
import Fastify, { FastifyReply, FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import argon2 from 'argon2';
import jwt from 'jsonwebtoken';
import { Pool } from 'pg';
import { randomBytes, createHash } from 'node:crypto';
import { z } from 'zod';
import { ingestEnabledSources } from './ingestion.js';
import { registerAskIntelligence } from './ask-intelligence.js';

const env = { port: Number(process.env.PORT ?? 8080), databaseUrl: process.env.DATABASE_URL ?? '', jwtSecret: process.env.JWT_SECRET ?? '', accessTtl: process.env.ACCESS_TOKEN_TTL ?? '15m', refreshDays: Number(process.env.REFRESH_TOKEN_DAYS ?? 7), corsOrigin: process.env.CORS_ORIGIN ?? 'http://localhost:3000', cookieSecure: process.env.COOKIE_SECURE === 'true' };
if (!env.databaseUrl || !env.jwtSecret) throw new Error('DATABASE_URL and JWT_SECRET are required');
const pool = new Pool({ connectionString: env.databaseUrl, max: 10 });
const app = Fastify({ logger: true, bodyLimit: 2 * 1024 * 1024 });
await app.register(helmet); await app.register(cors, { origin: env.corsOrigin, credentials: true }); await app.register(cookie); await app.register(rateLimit, { max: 120, timeWindow: '1 minute' });
const authSchema = z.object({ email: z.string().email(), password: z.string().min(8).max(200) });
type AuthUser = { id: string; email: string; role: 'admin'|'operator'|'viewer'; opdId: string | null };
declare module 'fastify' { interface FastifyRequest { user?: AuthUser } }
function accessToken(user: AuthUser) { return jwt.sign({ sub:user.id,email:user.email,role:user.role,opdId:user.opdId }, env.jwtSecret, { expiresIn: env.accessTtl as jwt.SignOptions['expiresIn'] }); }
function hashRefresh(token:string) { return createHash('sha256').update(token).digest('hex'); }
async function requireAuth(request:FastifyRequest, reply:FastifyReply) { const token=request.cookies.access_token; if(!token) return reply.code(401).send({error:'UNAUTHENTICATED'}); try { const decoded=jwt.verify(token,env.jwtSecret) as jwt.JwtPayload; if(typeof decoded.sub!=='string'||!['admin','operator','viewer'].includes(String(decoded.role))) throw new Error('invalid'); request.user={id:decoded.sub,email:String(decoded.email),role:decoded.role as AuthUser['role'],opdId:decoded.opdId?String(decoded.opdId):null}; } catch { return reply.code(401).send({error:'INVALID_ACCESS_TOKEN'}); } }
function requireRole(...roles:AuthUser['role'][]) { return async (request:FastifyRequest,reply:FastifyReply)=>{ if(!request.user||!roles.includes(request.user.role)) return reply.code(403).send({error:'FORBIDDEN'}); }; }
app.get('/health', async()=>({ok:true,service:'media-intelligence-api'}));
app.post('/api/auth/login',async(request,reply)=>{ const parsed=authSchema.safeParse(request.body); if(!parsed.success) return reply.code(400).send({error:'INVALID_REQUEST'}); const row=(await pool.query(`SELECT id,email,password_hash,role,opd_id,active FROM users WHERE lower(email)=lower($1) LIMIT 1`,[parsed.data.email])).rows[0]; if(!row||!row.active||!(await argon2.verify(row.password_hash,parsed.data.password))) return reply.code(401).send({error:'INVALID_CREDENTIALS'}); const user:AuthUser={id:String(row.id),email:row.email,role:row.role,opdId:row.opd_id==null?null:String(row.opd_id)}; const refresh=randomBytes(48).toString('base64url'); await pool.query(`INSERT INTO refresh_tokens(user_id,token_hash,expires_at) VALUES($1,$2,$3)`,[user.id,hashRefresh(refresh),new Date(Date.now()+env.refreshDays*86400000)]); reply.setCookie('access_token',accessToken(user),{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/'}); reply.setCookie('refresh_token',refresh,{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/api/auth'}); return {user}; });
app.post('/api/auth/refresh',async(request,reply)=>{ const old=request.cookies.refresh_token; if(!old) return reply.code(401).send({error:'NO_REFRESH_TOKEN'}); const row=(await pool.query(`SELECT rt.id,u.id user_id,u.email,u.role,u.opd_id,rt.expires_at FROM refresh_tokens rt JOIN users u ON u.id=rt.user_id WHERE rt.token_hash=$1 AND rt.revoked_at IS NULL AND u.active=true LIMIT 1`,[hashRefresh(old)])).rows[0]; if(!row||new Date(row.expires_at)<=new Date()) return reply.code(401).send({error:'INVALID_REFRESH_TOKEN'}); await pool.query(`UPDATE refresh_tokens SET revoked_at=NOW() WHERE id=$1`,[row.id]); const user:AuthUser={id:String(row.user_id),email:row.email,role:row.role,opdId:row.opd_id==null?null:String(row.opd_id)}; const refresh=randomBytes(48).toString('base64url'); await pool.query(`INSERT INTO refresh_tokens(user_id,token_hash,expires_at) VALUES($1,$2,$3)`,[user.id,hashRefresh(refresh),new Date(Date.now()+env.refreshDays*86400000)]); reply.setCookie('access_token',accessToken(user),{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/'}); reply.setCookie('refresh_token',refresh,{httpOnly:true,secure:env.cookieSecure,sameSite:'lax',path:'/api/auth'}); return {ok:true}; });
app.post('/api/auth/logout',async(request,reply)=>{const token=request.cookies.refresh_token;if(token) await pool.query(`UPDATE refresh_tokens SET revoked_at=NOW() WHERE token_hash=$1 AND revoked_at IS NULL`,[hashRefresh(token)]);reply.clearCookie('access_token',{path:'/'});reply.clearCookie('refresh_token',{path:'/api/auth'});return{ok:true};});
app.get('/api/me',{preHandler:requireAuth},async request=>({user:request.user}));
app.get('/api/opd',{preHandler:requireAuth},async()=>{ const {rows}=await pool.query(`SELECT id,code,name,active FROM opd WHERE active=true ORDER BY name`); return {data:rows}; });
const filterOpd=(user:AuthUser|undefined,requested?:string)=> user?.role==='admin'?requested:(user?.opdId ?? null);
app.get('/api/articles',{preHandler:requireAuth},async(request,reply)=>{ const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),from:z.string().optional(),to:z.string().optional(),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(request.query); if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'}); const params:unknown[]=[]; const where:string[]=[]; const opdId=filterOpd(request.user,q.data.opdId); if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);} if(q.data.from){params.push(q.data.from);where.push(`a.published_at >= $${params.length}`);} if(q.data.to){params.push(q.data.to);where.push(`a.published_at < $${params.length}`);} params.push(q.data.limit); const {rows}=await pool.query(`SELECT a.id,a.title,a.url,a.published_at,a.sentiment,a.importance_score,a.impact_score,a.velocity_score,a.risk_score,a.risk_level,a.is_highlight,a.summary,ms.name source_name FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY a.importance_score DESC,a.published_at DESC NULLS LAST LIMIT $${params.length}`,params); return {data:rows}; });
app.get('/api/highlights',{preHandler:requireAuth},async(request,reply)=>{ const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),limit:z.coerce.number().int().min(1).max(50).default(10)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where=['a.is_highlight=true'];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT a.id,a.title,a.url,a.published_at,a.sentiment,a.importance_score,a.impact_score,a.velocity_score,a.risk_score,a.risk_level,a.summary,ms.name source_name FROM articles a LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE ${where.join(' AND ')} ORDER BY a.risk_score DESC,a.importance_score DESC,a.published_at DESC NULLS LAST LIMIT $${params.length}`,params);return{data:rows};});
app.get('/api/alerts',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),status:z.enum(['open','acknowledged','resolved']).default('open'),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[q.data.status];const where=['aa.status=$1'];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`a.opd_id=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT aa.id,aa.article_id,aa.alert_type,aa.severity,aa.reason,aa.status,aa.created_at,a.title,a.url,a.published_at,a.risk_score,a.risk_level,ms.name source_name FROM article_alerts aa JOIN articles a ON a.id=aa.article_id LEFT JOIN media_sources ms ON ms.id=a.source_id WHERE ${where.join(' AND ')} ORDER BY aa.created_at DESC LIMIT $${params.length}`,params);return{data:rows};});
app.patch('/api/alerts/:id',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({status:z.enum(['acknowledged','resolved'])}).safeParse(request.body);const id=z.coerce.number().int().positive().safeParse((request.params as any).id);if(!parsed.success||!id.success)return reply.code(400).send({error:'INVALID_REQUEST'});const {rows}=await pool.query(`UPDATE article_alerts SET status=$2,acknowledged_at=CASE WHEN $2='acknowledged' THEN COALESCE(acknowledged_at,NOW()) ELSE acknowledged_at END WHERE id=$1 RETURNING id,article_id,alert_type,severity,reason,status,acknowledged_at`,[id.data,parsed.data.status]);if(!rows[0])return reply.code(404).send({error:'ALERT_NOT_FOUND'});await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'ALERT_STATUS_CHANGED',$2)`,[request.user?.id,{alertId:id.data,status:parsed.data.status}]);return{data:rows[0]};});
app.get('/api/dashboard',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const opdId=filterOpd(request.user,q.data.opdId);const filter=opdId?(params.push(opdId),`WHERE opd_id=$1`):'';const {rows}=await pool.query(`SELECT COUNT(*)::int total_articles,COUNT(*) FILTER(WHERE is_highlight)::int highlights,COUNT(*) FILTER(WHERE sentiment='negative')::int negative,COUNT(*) FILTER(WHERE risk_level IN ('high','critical'))::int critical,COUNT(*) FILTER(WHERE risk_level='critical')::int critical_alerts,COALESCE(ROUND(AVG(importance_score)),0)::int momentum FROM articles ${filter}`,params);const sources=await pool.query(`SELECT COUNT(*)::int count FROM media_sources WHERE active=true`);return{metrics:{...rows[0],sources:Number(sources.rows[0].count)}};});
app.get('/api/ingestion/status',{preHandler:requireAuth},async()=>{const {rows}=await pool.query(`SELECT COUNT(*)::int sources,COUNT(*) FILTER(WHERE active=true)::int active_sources,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL)::int feed_sources,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL AND last_success_at IS NOT NULL)::int healthy_feeds,COUNT(*) FILTER(WHERE active=true AND url IS NOT NULL AND last_error IS NOT NULL)::int failed_feeds,MAX(last_success_at) last_success_at FROM media_sources`);const sources=await pool.query(`SELECT id,name,category,tier,url,active,last_checked_at,last_success_at,last_error,last_fetched_count,last_inserted_count FROM media_sources ORDER BY tier ASC,name ASC`);return{status:rows[0],sources:sources.rows};});
app.get('/api/ingestion/history',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({limit:z.coerce.number().int().min(1).max(100).default(20)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const {rows}=await pool.query(`SELECT id,started_at,finished_at,status,source_count,successful_sources,failed_sources,fetched_count,inserted_count,details,error_message FROM ingestion_runs ORDER BY started_at DESC LIMIT $1`,[q.data.limit]);return{data:rows};});
app.post('/api/ingestion/run',{preHandler:[requireAuth,requireRole('admin','operator')]},async()=>({results:await ingestEnabledSources(pool)}));
app.post('/api/media-scan/analyze',{preHandler:requireAuth},async(request,reply)=>{const parsed=z.object({text:z.string().min(20).max(50000),filename:z.string().max(255).optional(),opdId:z.string().regex(/^\d+$/).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_OCR_TEXT'});const text=parsed.data.text.replace(/\s+/g,' ').trim();const negative=['gagal','korupsi','suap','kriminal','kecelakaan','banjir','macet','protes','keluhan','kritik','masalah','terlambat','lambat','kebakaran','ancaman','sengketa'];const positive=['berhasil','sukses','prestasi','penghargaan','meningkat','investasi','terobosan','apresiasi','aman','lancar','kolaborasi','pertumbuhan'];const lower=text.toLowerCase();const neg=negative.filter(k=>lower.includes(k)).length;const pos=positive.filter(k=>lower.includes(k)).length;const sentiment=neg>pos?'negative':pos>neg?'positive':'neutral';const risk=Math.min(100,20+neg*12+(text.length>1200?15:0));const risk_level=risk>=80?'critical':risk>=60?'high':risk>=35?'medium':'low';const headline=text.split(/[.!?]/)[0].slice(0,180)||parsed.data.filename||'Media cetak terdeteksi';const summary=text.slice(0,500);const recommendation=risk_level==='critical'||risk_level==='high'?'Validasi fakta segera, koordinasikan OPD terkait, tetapkan juru bicara dan siapkan holding statement.':'Monitor perkembangan dan siapkan data pendukung bila isu berkembang.';const key_message=sentiment==='negative'?'Pemko sedang melakukan verifikasi fakta dan koordinasi penanganan serta akan menyampaikan perkembangan melalui kanal resmi.':'Pemko terus menyampaikan informasi berbasis data yang dapat diverifikasi publik.';return{data:{mode:'deterministic-ocr',filename:parsed.data.filename||null,analysis:{headline,summary,sentiment,risk_score:risk,risk_level,impact_score:Math.min(100,20+Math.floor(text.length/80)),opd_name:parsed.data.opdId?'OPD terpilih':'Belum dipetakan',recommendation,key_message}}};});
app.post('/api/media-scans',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({text:z.string().min(20).max(50000),filename:z.string().max(255).optional(),opdId:z.string().regex(/^\d+$/).optional(),analysis:z.record(z.string(),z.any())}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_MEDIA_SCAN'});const opdId=filterOpd(request.user,parsed.data.opdId);const {rows}=await pool.query(`INSERT INTO media_scans(opd_id,file_name,ocr_text,analysis,status,processed_at) VALUES($1,$2,$3,$4,'completed',NOW()) RETURNING id,opd_id,file_name,analysis,status,created_at,processed_at`,[opdId,parsed.data.filename||'media-scan',parsed.data.text,parsed.data.analysis]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'MEDIA_SCAN_SAVED',$2)`,[request.user?.id,{scanId:rows[0].id,filename:parsed.data.filename||'media-scan'}]);return{data:rows[0]};});
app.get('/api/media-scans',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({from:z.string().optional(),to:z.string().optional(),opdId:z.string().regex(/^\d+$/).optional(),limit:z.coerce.number().int().min(1).max(200).default(100)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where:string[]=[];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`ms.opd_id=$${params.length}`);}if(q.data.from){params.push(q.data.from);where.push(`ms.created_at >= $${params.length}`);}if(q.data.to){params.push(q.data.to);where.push(`ms.created_at < $${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT ms.id,ms.opd_id,ms.file_name,ms.analysis,ms.status,ms.created_at,ms.processed_at,o.name opd_name FROM media_scans ms LEFT JOIN opd o ON o.id=ms.opd_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY ms.created_at DESC LIMIT $${params.length}`,params);return{data:rows};});

const incidentTaskDefaults=[['VERIFY','Validasi fakta'],['COORDINATE','Koordinasi OPD'],['MESSAGE','Siapkan pesan'],['MONITOR','Pantau eskalasi']] as const;
const incidentKey=(articleId:string|number)=>`MI-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${articleId}`;
const incidentId=z.coerce.number().int().positive();
app.get('/api/incidents',{preHandler:requireAuth},async(request,reply)=>{const q=z.object({opdId:z.string().regex(/^\d+$/).optional(),status:z.enum(['MONITORING','ESCALATED','RESOLVED']).optional(),limit:z.coerce.number().int().min(1).max(100).default(25)}).safeParse(request.query);if(!q.success)return reply.code(400).send({error:'INVALID_QUERY'});const params:unknown[]=[];const where:string[]=[];const opdId=filterOpd(request.user,q.data.opdId);if(opdId){params.push(opdId);where.push(`i.opd_id=$${params.length}`);}if(q.data.status){params.push(q.data.status);where.push(`i.status=$${params.length}`);}params.push(q.data.limit);const {rows}=await pool.query(`SELECT i.id,i.incident_key,i.opd_id,i.signal_article_id,i.severity,i.status,i.command_owner_id,i.decision_required,i.approval,i.first_detected_at,i.resolved_at,i.created_at,i.updated_at,a.title signal_title,o.name opd_name,u.email command_owner_email FROM incidents i LEFT JOIN articles a ON a.id=i.signal_article_id LEFT JOIN opd o ON o.id=i.opd_id LEFT JOIN users u ON u.id=i.command_owner_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE i.severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,i.updated_at DESC LIMIT $${params.length}`,params);return{data:rows};});
app.get('/api/incidents/:id',{preHandler:requireAuth},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const {rows}=await pool.query(`SELECT i.id,i.incident_key,i.opd_id,i.signal_article_id,i.severity,i.status,i.command_owner_id,i.decision_required,i.approval,i.first_detected_at,i.resolved_at,i.created_at,i.updated_at,a.title signal_title,a.summary signal_summary,a.url signal_url,o.name opd_name,u.email command_owner_email FROM incidents i LEFT JOIN articles a ON a.id=i.signal_article_id LEFT JOIN opd o ON o.id=i.opd_id LEFT JOIN users u ON u.id=i.command_owner_id WHERE i.id=$1 LIMIT 1`,[id.data]);if(!rows[0])return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});const incident=rows[0];if(request.user?.role!=='admin'&&request.user?.opdId&&String(incident.opd_id)!==request.user.opdId)return reply.code(403).send({error:'FORBIDDEN'});const tasks=await pool.query(`SELECT id,task_key,label,status,completed_by,completed_at,created_at FROM incident_tasks WHERE incident_id=$1 ORDER BY id`,[id.data]);const decisions=await pool.query(`SELECT id,decision,created_by,created_at FROM incident_decisions WHERE incident_id=$1 ORDER BY created_at DESC`,[id.data]);const events=await pool.query(`SELECT id,event_type,payload,created_by,created_at FROM incident_events WHERE incident_id=$1 ORDER BY created_at DESC LIMIT 100`,[id.data]);return{data:{...incident,tasks:tasks.rows,decisions:decisions.rows,events:events.rows}};});
app.post('/api/incidents',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const parsed=z.object({incidentKey:z.string().min(5).max(100).optional(),opdId:z.string().regex(/^\d+$/).optional(),signalArticleId:z.string().regex(/^\d+$/).optional(),severity:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']),status:z.enum(['MONITORING','ESCALATED','RESOLVED']).default('MONITORING'),commandOwnerId:z.string().regex(/^\d+$/).nullable().optional(),decisionRequired:z.string().max(5000).default(''),approval:z.enum(['DRAFT','REVIEW','APPROVED']).default('DRAFT')}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_INCIDENT'});const opdId=filterOpd(request.user,parsed.data.opdId);if(!opdId&&request.user?.role!=='admin')return reply.code(400).send({error:'OPD_REQUIRED'});const signal=parsed.data.signalArticleId?Number(parsed.data.signalArticleId):null;const key=parsed.data.incidentKey||(signal?incidentKey(signal):`MI-${Date.now()}`);const owner=parsed.data.commandOwnerId?Number(parsed.data.commandOwnerId):null;const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query(`INSERT INTO incidents(incident_key,opd_id,signal_article_id,severity,status,command_owner_id,decision_required,approval,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[key,opdId,signal,parsed.data.severity,parsed.data.status,owner,parsed.data.decisionRequired,parsed.data.approval,request.user?.id]);for(const [taskKey,label] of incidentTaskDefaults)await client.query(`INSERT INTO incident_tasks(incident_id,task_key,label) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[rows[0].id,taskKey,label]);await client.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_CREATED',$2,$3)`,[rows[0].id,{severity:parsed.data.severity,status:parsed.data.status},request.user?.id]);await client.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_CREATED',$2)`,[request.user?.id,{incidentId:rows[0].id,incidentKey:key}]);await client.query('COMMIT');return{data:rows[0]};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}});
app.patch('/api/incidents/:id',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);const parsed=z.object({status:z.enum(['MONITORING','ESCALATED','RESOLVED']).optional(),commandOwnerId:z.string().regex(/^\d+$/).nullable().optional(),decisionRequired:z.string().max(5000).optional(),approval:z.enum(['DRAFT','REVIEW','APPROVED']).optional()}).safeParse(request.body);if(!id.success||!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const current=(await pool.query(`SELECT id,opd_id,status,approval FROM incidents WHERE id=$1`,[id.data])).rows[0];if(!current)return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});if(request.user?.role!=='admin'&&request.user?.opdId&&String(current.opd_id)!==request.user.opdId)return reply.code(403).send({error:'FORBIDDEN'});const status=parsed.data.status??current.status;const {rows}=await pool.query(`UPDATE incidents SET status=$2,command_owner_id=CASE WHEN $3::bigint IS NULL THEN command_owner_id ELSE $3 END,decision_required=COALESCE($4,decision_required),approval=COALESCE($5,approval),resolved_at=CASE WHEN $2='RESOLVED' THEN NOW() ELSE resolved_at END,updated_at=NOW() WHERE id=$1 RETURNING *`,[id.data,status,parsed.data.commandOwnerId===undefined?null:Number(parsed.data.commandOwnerId),parsed.data.decisionRequired??null,parsed.data.approval??null]);await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_UPDATED',$2,$3)`,[id.data,{status,approval:parsed.data.approval??null},request.user?.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_UPDATED',$2)`,[request.user?.id,{incidentId:id.data,status}]);return{data:rows[0]};});
app.patch('/api/incidents/:id/tasks/:taskId',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);const taskId=incidentId.safeParse((request.params as any).taskId);const parsed=z.object({status:z.enum(['OPEN','DONE'])}).safeParse(request.body);if(!id.success||!taskId.success||!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const {rows}=await pool.query(`UPDATE incident_tasks SET status=$3,completed_by=CASE WHEN $3='DONE' THEN $4 ELSE NULL END,completed_at=CASE WHEN $3='DONE' THEN NOW() ELSE NULL END WHERE id=$2 AND incident_id=$1 RETURNING *`,[id.data,taskId.data,parsed.data.status,request.user?.id]);if(!rows[0])return reply.code(404).send({error:'TASK_NOT_FOUND'});await pool.query(`UPDATE incidents SET updated_at=NOW() WHERE id=$1`,[id.data]);await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'TASK_UPDATED',$2,$3)`,[id.data,{taskId:taskId.data,status:parsed.data.status},request.user?.id]);return{data:rows[0]};});
app.post('/api/incidents/:id/decisions',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);const parsed=z.object({decision:z.string().min(3).max(5000)}).safeParse(request.body);if(!id.success||!parsed.success)return reply.code(400).send({error:'INVALID_DECISION'});const {rows}=await pool.query(`INSERT INTO incident_decisions(incident_id,decision,created_by) VALUES($1,$2,$3) RETURNING *`,[id.data,parsed.data.decision,request.user?.id]);await pool.query(`UPDATE incidents SET decision_required=$2,updated_at=NOW() WHERE id=$1`,[id.data,parsed.data.decision]);await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'DECISION_RECORDED',$2,$3)`,[id.data,{decisionId:rows[0].id},request.user?.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_DECISION_RECORDED',$2)`,[request.user?.id,{incidentId:id.data,decisionId:rows[0].id}]);return{data:rows[0]};});
app.post('/api/incidents/:id/escalate',{preHandler:[requireAuth,requireRole('admin','operator')]},async(request,reply)=>{const id=incidentId.safeParse((request.params as any).id);if(!id.success)return reply.code(400).send({error:'INVALID_INCIDENT_ID'});const parsed=z.object({reason:z.string().min(3).max(1000).optional()}).safeParse(request.body);if(!parsed.success)return reply.code(400).send({error:'INVALID_REQUEST'});const {rows}=await pool.query(`UPDATE incidents SET status='ESCALATED',updated_at=NOW() WHERE id=$1 RETURNING *`,[id.data]);if(!rows[0])return reply.code(404).send({error:'INCIDENT_NOT_FOUND'});await pool.query(`INSERT INTO incident_events(incident_id,event_type,payload,created_by) VALUES($1,'INCIDENT_ESCALATED',$2,$3)`,[id.data,{reason:parsed.data.reason||'Manual escalation'},request.user?.id]);await pool.query(`INSERT INTO audit_logs(user_id,action,metadata) VALUES($1,'INCIDENT_ESCALATED',$2)`,[request.user?.id,{incidentId:id.data,reason:parsed.data.reason||'Manual escalation'}]);return{data:rows[0]};});
await registerAskIntelligence(app,pool,env.jwtSecret);
app.setErrorHandler((error,_request,reply)=>{app.log.error(error);return reply.code(error.statusCode??500).send({error:'INTERNAL_SERVER_ERROR'});});
app.addHook('onClose',async()=>pool.end()); await app.listen({port:env.port,host:'0.0.0.0'});