import { XMLParser } from 'fast-xml-parser';
import type { Pool } from 'pg';
import { ingestSocialBatch, type SocialCandidate } from './social-collector.js';

type WebsiteAccount = { id:string; opd_id:string|null; account_name:string; handle:string; profile_url:string|null };
const parser=new XMLParser({ignoreAttributes:false,attributeNamePrefix:'@_'});
const USER_AGENT='MediaIntelligenceBot/1.0 (+Pemko Batam media monitoring)';
const PAGE_TIMEOUT_MS=4500,FEED_TIMEOUT_MS=3500,ARTICLE_TIMEOUT_MS=3500,HTML_CRAWL_LIMIT=20;
const BACKFILL_DAYS=7,FEED_ITEM_LIMIT=100,INGEST_LIMIT=80;
const asArray=<T>(v:T|T[]|undefined):T[]=>v==null?[]:Array.isArray(v)?v:[v];
const textValue=(v:unknown):string|undefined=>{if(typeof v==='string')return v.trim()||undefined;if(v&&typeof v==='object'&&'#text' in(v as Record<string,unknown>)){const t=(v as Record<string,unknown>)['#text'];return typeof t==='string'?t.trim()||undefined:undefined}return undefined};
const firstString=(...v:unknown[])=>v.map(textValue).find(Boolean);
const decodeEntities=(v:string)=>v.replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>');
const stripHtml=(v?:string)=>v?decodeEntities(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim():undefined;
const safeDate=(v?:string)=>{if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()};
async function fetchText(url:string,timeoutMs:number){const response=await fetch(url,{headers:{'user-agent':USER_AGENT,accept:'text/html,application/xhtml+xml,application/rss+xml,application/atom+xml,application/xml;q=0.9,*/*;q=0.8','cache-control':'no-cache','pragma':'no-cache'},signal:AbortSignal.timeout(timeoutMs),redirect:'follow'});return{response,body:await response.text()}}
function discoverFeedUrl(html:string,baseUrl:string){for(const tag of html.match(/<link\b[^>]*>/gi)??[]){const rel=tag.match(/\brel=["']([^"']+)["']/i)?.[1]?.toLowerCase()??'',type=tag.match(/\btype=["']([^"']+)["']/i)?.[1]?.toLowerCase()??'',href=tag.match(/\bhref=["']([^"']+)["']/i)?.[1];if(!href||!rel.includes('alternate')||(!type.includes('rss')&&!type.includes('atom')&&!type.includes('xml')))continue;try{return new URL(href,baseUrl).toString()}catch{}}return null}
function cutoffIso(){return new Date(Date.now()-(BACKFILL_DAYS-1)*86400000).toISOString().slice(0,10)}
function withinBackfill(date:string|null){if(!date)return true;return date.slice(0,10)>=cutoffIso()}
function parseWebsiteFeed(xml:string,account:WebsiteAccount,feedUrl:string):SocialCandidate[]{const root=parser.parse(xml),items=asArray<any>(root?.rss?.channel?.item??root?.feed?.entry);return items.slice(0,FEED_ITEM_LIMIT).map((item:any)=>{const title=firstString(item.title,item.title?.['#text'],item['media:title']),canonicalUrl=firstString(item.link?.['@_href'],item.link,item.guid,item.id);if(!title||!canonicalUrl)return null;const publishedAt=safeDate(firstString(item.pubDate,item.published,item.updated,item['dc:date']));if(!withinBackfill(publishedAt))return null;const rawContent=firstString(item['content:encoded'],item.content,item.summary,item.description);return{platform:'website' as const,externalId:firstString(item.guid,item.id,canonicalUrl)??canonicalUrl,contentType:'article' as const,sourceKind:'owned' as const,ownedAccountId:Number(account.id),opdId:account.opd_id==null?null:Number(account.opd_id),authorName:account.account_name,authorHandle:account.handle,authorProfileUrl:account.profile_url,canonicalUrl,title,content:stripHtml(rawContent)?.slice(0,100000)??null,publishedAt,collector:'website-rss',rawPayload:item,metadata:{feedUrl,backfillDays:BACKFILL_DAYS}} satisfies SocialCandidate}).filter(Boolean).slice(0,INGEST_LIMIT) as SocialCandidate[]}
function metaContent(html:string,key:string){const escaped=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');for(const re of[new RegExp(`<meta[^>]+(?:property|name)=["']${escaped}["'][^>]+content=["']([^"']+)["'][^>]*>`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["']${escaped}["'][^>]*>`,'i')]){const m=html.match(re)?.[1];if(m)return decodeEntities(m.trim())}return undefined}
function canonicalFromHtml(html:string,fallbackUrl:string){const href=html.match(/<link\b[^>]*rel=["'][^"']*canonical[^"']*["'][^>]*href=["']([^"']+)["'][^>]*>/i)?.[1]??html.match(/<link\b[^>]*href=["']([^"']+)["'][^>]*rel=["'][^"']*canonical[^"']*["'][^>]*>/i)?.[1];try{return href?new URL(href,fallbackUrl).toString():fallbackUrl}catch{return fallbackUrl}}
function extractArticleLinks(html:string,baseUrl:string,limit=HTML_CRAWL_LIMIT){const base=new URL(baseUrl),seen=new Set<string>(),candidates:Array<{url:string;text:string;score:number}>=[];const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>([\s\S]*?)<\/a>/gi;let match:RegExpExecArray|null;while((match=re.exec(html))){try{const url=new URL(match[1],baseUrl);if(url.hostname!==base.hostname||!/^https?:$/.test(url.protocol))continue;url.hash='';const text=stripHtml(match[2])?.trim()??'';if(text.length<12)continue;const path=url.pathname.toLowerCase();if(path==='/'||/\/(tag|author|wp-admin|wp-content|feed)(\/|$)/.test(path)||/\.(jpg|jpeg|png|gif|webp|svg|pdf|zip|mp4|mp3)$/i.test(path))continue;const normalized=url.toString();if(seen.has(normalized))continue;seen.add(normalized);let score=0;if(/\/20\d{2}\/(0?[1-9]|1[0-2])\/(0?[1-9]|[12]\d|3[01])\//.test(path))score+=10;if(/berita|news|artikel|post/.test(path))score+=4;if(path.split('/').filter(Boolean).length>=2)score+=2;if(text.length>=30)score+=2;candidates.push({url:normalized,text,score})}catch{}}return candidates.sort((a,b)=>b.score-a.score).slice(0,limit)}
function extractArticleCandidate(html:string,url:string,linkText:string,account:WebsiteAccount):SocialCandidate|null{const title=metaContent(html,'og:title')??stripHtml(html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1])??stripHtml(html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i)?.[1])??linkText;if(!title||title.length<5)return null;const canonicalUrl=canonicalFromHtml(html,url),publishedAt=safeDate(metaContent(html,'article:published_time')??html.match(/<time\b[^>]*datetime=["']([^"']+)["']/i)?.[1]);if(!withinBackfill(publishedAt))return null;const articleHtml=html.match(/<article\b[^>]*>([\s\S]*?)<\/article>/i)?.[1]??html.match(/<main\b[^>]*>([\s\S]*?)<\/main>/i)?.[1]??'',content=stripHtml(articleHtml)??metaContent(html,'description')??metaContent(html,'og:description')??'';if(content.length<40)return null;return{platform:'website',externalId:canonicalUrl,contentType:'article',sourceKind:'owned',ownedAccountId:Number(account.id),opdId:account.opd_id==null?null:Number(account.opd_id),authorName:account.account_name,authorHandle:account.handle,authorProfileUrl:account.profile_url,canonicalUrl,title:title.slice(0,1000),content:content.slice(0,100000),publishedAt,collector:'website-html',rawPayload:{},metadata:{discoveredFrom:account.profile_url,crawlMode:'hybrid-html',backfillDays:BACKFILL_DAYS}}}
async function crawlWebsiteLinks(links:Array<{url:string;text:string}>,account:WebsiteAccount){const settled=await Promise.allSettled(links.map(async link=>{const{response,body}=await fetchText(link.url,ARTICLE_TIMEOUT_MS);if(!response.ok||!response.headers.get('content-type')?.toLowerCase().includes('text/html'))return null;return extractArticleCandidate(body,response.url||link.url,link.text,account)}));return settled.flatMap(r=>r.status==='fulfilled'&&r.value?[r.value]:[])}
function mergeCandidates(...groups:SocialCandidate[][]){const map=new Map<string,SocialCandidate>();for(const candidate of groups.flat()){const key=(candidate.canonicalUrl||candidate.externalId||`${candidate.title}|${candidate.publishedAt}`).toLowerCase();const existing=map.get(key);if(!existing||(!existing.content&&candidate.content))map.set(key,candidate)}return[...map.values()].sort((a,b)=>String(b.publishedAt??'').localeCompare(String(a.publishedAt??''))).slice(0,INGEST_LIMIT)}
async function collectHtmlCandidates(homeHtml:string,homeUrl:string,account:WebsiteAccount){const pages:[string,string][]=[[homeHtml,homeUrl]];try{const categoryUrl=new URL('/category/berita/',homeUrl).toString();if(categoryUrl!==homeUrl){const category=await fetchText(categoryUrl,PAGE_TIMEOUT_MS);if(category.response.ok&&category.response.headers.get('content-type')?.toLowerCase().includes('text/html'))pages.push([category.body,category.response.url||categoryUrl])}}catch{}
  const seen=new Map<string,{url:string;text:string}>();for(const[html,url]of pages){for(const link of extractArticleLinks(html,url,HTML_CRAWL_LIMIT)){if(!seen.has(link.url))seen.set(link.url,{url:link.url,text:link.text})}}
  return crawlWebsiteLinks([...seen.values()].slice(0,HTML_CRAWL_LIMIT),account)
}
export async function collectOwnedWebsiteAccount(pool:Pool,accountId:number){const{rows}=await pool.query<WebsiteAccount>(`SELECT id,opd_id,account_name,handle,profile_url FROM owned_social_accounts WHERE id=$1 AND platform='website' AND active=true LIMIT 1`,[accountId]);const account=rows[0];if(!account)throw new Error('WEBSITE_ACCOUNT_NOT_FOUND');if(!account.profile_url)throw new Error('WEBSITE_PROFILE_URL_MISSING');const{response,body}=await fetchText(account.profile_url,PAGE_TIMEOUT_MS);if(!response.ok)throw new Error(`Website returned HTTP ${response.status}`);const pageUrl=response.url||account.profile_url,contentType=response.headers.get('content-type')?.toLowerCase()??'',looksXml=contentType.includes('xml')||/^\s*<\?xml|^\s*<(rss|feed)\b/i.test(body);
  if(looksXml){const rss=parseWebsiteFeed(body,account,pageUrl),result=await ingestSocialBatch(pool,rss,'website-rss');return{accountId:Number(account.id),accountName:account.account_name,mode:'rss-direct',feedUrl:pageUrl,backfillDays:BACKFILL_DAYS,cutoffDate:cutoffIso(),fetched:rss.length,...result}}
  const discovered=discoverFeedUrl(body,pageUrl);let rss:SocialCandidate[]=[];let feedUrl:string|null=discovered;let rssError:string|null=null;
  if(discovered){try{const feed=await fetchText(discovered,FEED_TIMEOUT_MS),isXml=feed.response.ok&&(feed.response.headers.get('content-type')?.toLowerCase().includes('xml')||/^\s*<\?xml|^\s*<(rss|feed)\b/i.test(feed.body));if(isXml){feedUrl=feed.response.url||discovered;rss=parseWebsiteFeed(feed.body,account,feedUrl)}}catch(err:any){rssError=String(err?.message||err)}}
  let html:SocialCandidate[]=[];try{html=await collectHtmlCandidates(body,pageUrl,account)}catch{}
  const candidates=mergeCandidates(rss,html);if(!candidates.length)throw new Error('RSS/Atom dan artikel HTML 7 hari terakhir tidak dapat diekstrak');const result=await ingestSocialBatch(pool,candidates,'website-hybrid');return{accountId:Number(account.id),accountName:account.account_name,mode:'hybrid',feedUrl,backfillDays:BACKFILL_DAYS,cutoffDate:cutoffIso(),rssFetched:rss.length,htmlFetched:html.length,fetched:candidates.length,rssError,...result}}
